### ISSUE TITLE
[BUG] redirect keycloak stopped working

### ISSUE THREAD

**Issue by wolflarson** [Lissy93/dashy#1019]
### Environment

Self-Hosted (Docker)

### System

Firefox 108.0.1 (64-bit) on Manjaro (KDE)

### Version

2.1.1

### Describe the problem

While on 2.1.1 redirect to keycloak is not forced. Downgrading to 2.1.0 correctly forces login via keycloak before showing dashboard.

This is the auth block. My config is not changing between versions. Upgrade to 2.1.1 and no login needed. Downgraded and I'm forced to login via keycloak before I can interact. This might actually be a security issue because on 2.1.1 I can edit the config yaml without logging in. 

```bash
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: true
    keycloak:
      serverUrl: https://auth.example.com
      realm: example
      clientId: dashy
      legacySupport: false
 ```
 
 I reset the config file to stock and only changed this auth block to replicate the issue before opening a bug.  Full config can be found [here](https://pastebin.com/L3WwkiR6).

### Additional info

keycloak:20.0.2

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by allesauseinerhand** [comment]
Probably the same source of bug for this problem: https://github.com/Lissy93/dashy/issues/990

**Comment by ouafnico** [comment]
I actually got the same bug on 2.1.1.
I have to use 2.1.0 too.

On 2.1.1, the "disconnect" button is present, but does nothing, and I can't go to the login page.

**Comment by kieraneglin** [comment]
This _may_ have been fixed by #1026 but I have not confirmed

**Comment by wolflarson** [comment]
Should the 2.1.1 docker container include that change at this point? I can test quickly if there is a container built already .

**Comment by ouafnico** [comment]
I'm using the 2.1.1 but I still got a bug : guest access is not working, and got a continuous refresh of page.

**Comment by zell-mbc** [comment]
This one shows as closed, but it isn't for me. I was running v2.1.1 until today when I realised that my dashboard has been unprotected since December.
I would actually think this should be treated like a pretty serious/security related regression?

A downgrade to v.2.0.0 as recommended higher up, made things working again.

**Comment by jakob1379** [comment]
Same for me - 2.1.0 works as expected, 2.1.1 does not trigger any authentication/authorization

**Comment by TheRealGramdalf** [comment]
See https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 for a full explanation/semi solution

For notifications:
@jakob1379 @zell-mbc @ouafnico @wolflarson @kieraneglin @djessich @allesauseinerhand 
_Sorry if you didn't want to be pinged, but I figure you probably did - or you wouldn't have participated in the issue_

**Comment by jakob1379** [comment]
> See https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 for a full explanation/semi solution
> 
> For notifications:
> @jakob1379 @zell-mbc @ouafnico @wolflarson @kieraneglin @djessich @allesauseinerhand 
> _Sorry if you didn't want to be pinged, but I figure you probably did - or you wouldn't have participated in the issue_

My isse was a misconfiguration with keycloak.
