### ISSUE TITLE
[BUG] Missing icons

### ISSUE THREAD

**Issue by DimitriDR** [Lissy93/dashy#1042]
### Environment

Self-Hosted (Docker)

### System

Docker 20.10.3

### Version

2.1.1

### Describe the problem

When working on #1041, I found two buttons where the text was weirdly aligned.

![image](https://user-images.githubusercontent.com/56969769/211164363-79c228f2-f230-467e-8f67-2439b7e02b4e.png)

It's actually because there's an icon in each button, but they don't appear.

```
<!-- Save and cancel buttons -->
    <div class="action-buttons">
      <Button :click="saveChanges">
        <SaveIcon /> {{ $t('theme-maker.save-button') }}
      </Button>
      <Button :click="resetUnsavedColors">
        <CancelIcon /> {{ $t('theme-maker.cancel-button') }}
      </Button>
    </div>
```
^ In: src/components/Settings, lines 49 to 57.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by DimitriDR** [comment]
Still relevant.

**Comment by DimitriDR** [comment]
> Still relevant.

**Comment by Lissy93** [comment]
Hmm, yes - looks like the Save and Cancel buttons aren't loading because font-awesome not enabled.
I'll push a fix out, but in the meantime setting  `enableFontAwesome` to `true` (under [`appConfig`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#appconfig-optional)) should fix this, [re, here](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#font-awesome-icons-not-displaying).

**Comment by CrazyWolf13** [comment]
@Lissy93 Guess this could be closed, as a fix was pushed and solution provided.
😊
