### ISSUE TITLE
How to install Dashy on openshift ?

### ISSUE THREAD

**Issue by sbbagal13** [Lissy93/dashy#1052]
### Question

Hi team , I tried installing Dashy on openshift using Helm chart from this [this](https://artifacthub.io/packages/helm/krzwiatrzyk/dashy) but its not coming up as expected, Lots of error coming while starting it 
like: 

[103m[34mUnable to start Dashy's Node server[0m
 Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at doListen (node:net:1520:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}
SSL Not Enabled: Public key not present

and permission denied to /app/public/ 
Anyone tried installing it on Openshift ?

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by sbbagal13** [comment]
Hi Team, 
Anyone tried this for Openshift ?

**Comment by ThomasSchoenbeck** [comment]
I deployed my dashy instance to openshift by defining another Port using the PORT environment variable.

```yaml
- name: PORT
  value: "4000"
```

but i also had to fix a bug inside the healthcheck.js from `/app/services/healthcheck.js`. because it would not pickup the new PORT from the variable.

before:
```js
const port = process.env.PORT || !!process.env.IS_DOCKER ? 80 : 4000;
```

after:
```js
const isDocker = !!process.env.IS_DOCKER
const port = process.env.PORT || (isDocker ? 80 : 4000);
```

the fix is based on the server.js, so i took the fix from there. I have mounted the healthcheck.js as configmap, so i don't need to create a custom docker image.

**Comment by sbbagal13** [comment]
Thanks @ThomasSchoenbeck for sharing details , did you used any helm chart ? If you could able to share some details around it, that will be very helpful , Thanks again .

**Comment by sbbagal13** [comment]
Openshift not allowing image to change the permissions of some of directories and build the application with dynamic config . Is anyone tried creating HelmChart for it ? Or how to do dynamic addition of config files as URLs will get updated w.r.t. environment and need to add/delete/update them?

**Comment by ThomasSchoenbeck** [comment]
Hi, i did generate a helm chart using [kompose](https://github.com/kubernetes/kompose) based on the [docker-compose](https://github.com/Lissy93/dashy/blob/master/docker-compose.yml) file from dashy. the generated helm chart contains hardcoded values using this approach, but could be improved with minor effort. so far i am not planning to put additional work into this.
