### ISSUE TITLE
[BUG] FontAwesome API Key

### ISSUE THREAD

**Issue by RadTechDad** [Lissy93/dashy#1055]
### Environment

Self-Hosted (Docker)

### System

Unraid 6.11.5 / Docker version 20.10.21

### Version

2.1.1

### Describe the problem

I read here that Dashy supports FontAwesome 5 icons, however, they're now on FA 6 and have switched to a different format from the 10-digit key used in FA 5. In fact, I can't even find a way to go back and find a key for FA 5 through their site.

The new FA6 uses an API Token in the following format:
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

![image](https://user-images.githubusercontent.com/1923370/211522217-1deecc62-b560-4521-845e-c0c255187857.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
So it's not actually the API token you need, but just the Kit key.

![image](https://github.com/Lissy93/dashy/assets/1862727/a8ce87db-3b11-4149-8745-3766eafddfba)

It _should_ be a 10-digit alpha-numeric string. 
And you can verify it's correct, by going to: `https://fontawesome.com/kits/[kit-ID]` and you should see the setup/settings page.
