### ISSUE TITLE
[BUG] sort by `most-used` doesn't work

### ISSUE THREAD

**Issue by Zixim** [Lissy93/dashy#1056]
### Environment

Self-Hosted (Docker)

### Version

2.1.1

### Describe the problem

All of the sections on my dash have `Sort By` set to `most-used`.
In `App Config`, `Disable Smart-Sort` is unchecked.

The Edge DevTools, Application tab / Local Storage, shows 2 keys ( `lastUsed` and `mostUsed` ) changing whenever a dashboard item gets clicked.

Items do not change their order according to most used.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by hypatia1** [comment]
I also have this problem. I also don't know how/where Dashy keeps count of clicks.

**Comment by Zixim** [comment]
The stats seem to be stored locally, in the browser-cache.
From what I can see, they are very incomplete. Only 1 shortcut seems to be counted.

Whether those few stats are then used or not... I can't say, but it's obvious that sort-by most-used has zero effect.
Any input from @Lissy93 would be appreciated ?

**Comment by Zixim** [comment]
please also see https://github.com/Lissy93/dashy/issues/1033#issuecomment-1445146511

**Comment by Lissy93** [comment]
Thanks @Zixim - Have replied on https://github.com/Lissy93/dashy/issues/1033#issuecomment-1445373374
Once #1123 is merged, this should be fixed :)
