### ISSUE TITLE
[BUG] Default icons broken

### ISSUE THREAD

**Issue by ranrinc** [Lissy93/dashy#1059]
### Environment

Self-Hosted (Docker)

### System

Brave v1.46.153

### Version

2.11

### Describe the problem

The default icons suddenly broke, in my system, the broken image is influxdb, uptime-kuma, draw, and VSC. I did not change any config or edit.

Trying to restart dashy without any luck either.

![CleanShot 2023-01-11 at 13 18 16](https://user-images.githubusercontent.com/15801696/211733344-043c8b8e-2036-44da-b867-4918e6931ecf.png)

![CleanShot 2023-01-11 at 13 18 41](https://user-images.githubusercontent.com/15801696/211733416-42846707-2ea4-4c5f-884d-28b26ad9fa75.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by dbffm** [comment]
I can confirm that. 
A few days ago the "dashboard-icon" repository moved from [WalkxHub](https://github.com/WalkxHub/dashboard-icons) to [walkxcode](https://github.com/walkxcode/dashboard-icons). Maybe it is related to that?

I see that the new repository is already changed in the [docs](https://github.com/Lissy93/dashy/blob/master/docs/icons.md#home-lab-icons)

**Comment by kdruelle** [comment]
Same issue here. Also walkxcode repository mention to use cdn instead of github to fetch icons: https://cdn.jsdelivr.net/gh/walkxcode

**Comment by dbffm** [comment]
At least for me I still have problems for (some) icons. 
i.e. "hl-google-calendar" works fine; "hl-unifi-controller" is not showing an icon:
![image](https://user-images.githubusercontent.com/58473397/220276087-ed694a82-1738-4887-b413-a3c93d4ca5de.png)

**Comment by ranrinc** [comment]
This issue have never been resolve till today.

**Comment by Lissy93** [comment]
Setting icon to ` hl-unifi-controller` should be working now. Was due to an upstream change to the Walax homelab icons repo.


```yaml
- name: Example
  items:
  - title: Unifi Controller
    icon: hl-unifi-controller
```

![image](https://github.com/Lissy93/dashy/assets/1862727/4d091673-218c-4785-90c1-7ac6e6c5e351)
