### ISSUE TITLE
[QUESTION] Suddenly showing "It looks like something's gone wrong"

### ISSUE THREAD

**Issue by mfnalex** [Lissy93/dashy#1073]
<h3 dir="auto">Question</h3>
<p dir="auto">Hello :)</p>
<p dir="auto">I've been using dashy for a year or more now, and kept it updated using watchtower (it runs once every 5 minutes so I am pretty sure that I use the latest version). Since today, I always get this error message:<br>
<a target="_blank" rel="noopener noreferrer nofollow" href="https://user-images.githubusercontent.com/1122571/213356668-54c693d4-1992-4612-89a5-63af424df6cb.png"><img src="https://user-images.githubusercontent.com/1122571/213356668-54c693d4-1992-4612-89a5-63af424df6cb.png" alt="image" style="max-width: 100%;"></a></p>
<p dir="auto">However, after waiting for like 20 seconds, it shows the actual panel without errors, so I am a bit confused lol. I am not really sure on what to do or how to debug it :/</p>
<p dir="auto">Any help would be appreciated!</p>
<p dir="auto">My dashy url is <a href="https://hub.jeff-media.com" rel="nofollow">https://hub.jeff-media.com</a></p>
<h3 dir="auto">Category</h3>
<p dir="auto">Setup and Deployment</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">question hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                                <div>          <strong>                          <a href="https://hub.jeff-media.com/">Dashy</a>                      </strong>        </div>                            </blockquote>

**Comment by DanAE111** [comment]
That works for me, tried clearing browser data for the site or using a different browser? Maybe it's something simple.

**Comment by mfnalex** [comment]
Thanks, that fixed it!
