### ISSUE TITLE
[BUG] Some Font Awesome icons are not loading

### ISSUE THREAD

**Issue by SimplicityGuy** [Lissy93/dashy#1077]
### Environment

Self-Hosted (Docker)

### System

Debian 11 (Linux 5.10.0-20-amd64)

### Version

2.1.1

### Describe the problem

There is a handful of Font Awesome icons that aren't showing up, specifically ones that I'm trying to use:

- far fa-[face-grin-tongue-wink](https://fontawesome.com/icons/face-grin-tongue-wink?s=regular&f=classic)
- fas fa-[shuttle-space](https://fontawesome.com/icons/shuttle-space?s=solid&f=classic)
- fas fa-[photo-film](https://fontawesome.com/icons/photo-film?s=solid&f=classic)
- fas fa-[magnifying-glass-chart](https://fontawesome.com/icons/magnifying-glass-chart?s=solid&f=classic)
- fas fa-[hard-drive](https://fontawesome.com/icons/hard-drive?s=solid&f=classic)
- fas fa-[arrow-right-arrow-left](https://fontawesome.com/icons/arrow-right-arrow-left?s=solid&f=classic)

Per the Font Awesome website, these *should* be free. There is no error log in the console when loading these.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by SimplicityGuy** [comment]
This is still an issue.

**Comment by ThinkSalat** [comment]
Hi, same issue here. Same with material icons as well. I think they must have updated - https://fontawesome.com/v5/search these seem to work, but doing a search without specifying v5 seems to break it

**Comment by jakob1379** [comment]
it looks for me like it is an issue with all icons having more than a single dash in the name e.g `fas fa-rocket` work while `fas fa-chart-scatter-bubble` does not

**Comment by rasmuslp** [comment]
I'm having trouble with `hl-unifi-controller` not loading.

The configured path for loading these is defined here: https://github.com/Lissy93/dashy/blob/c71476d4e8f6516fd8152b331c0c67d308c1780b/src/utils/defaults.js#L215

Putting in e.g. `unifi-controller` as `{icon}` does get the correct PNG, so I'm guessing the **dash** could the general cause here.

**Comment by Lissy93** [comment]
This is because those icons are not available in [Font-Awesome V5](https://fontawesome.com/v5/search) which is what is used here.

I've opened a FR for adding V6 support in #1424
