### ISSUE TITLE
[QUESTION] How do I move objects within a section?

### ISSUE THREAD

**Issue by malordin** [Lissy93/dashy#1079]
### Question

Hello, everyone!

I have read the documentation but could not find an answer to a rudimentary question. How can I move objects within a section? That is, let's say I want to move the most recent object a little higher, that is, make it the penultimate.

To do this, edit conf.yml and rearrange objects in an array? Is it possible to do this through editing mode?

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by xiaotian1111** [comment]
在编辑配置中，拖动配置树可以改变排序

**Comment by badarotti** [comment]
From the UI, under the config menu there is a JSON editor `Edit Config`, with built-in validation, documentation and advanced options. You can use that to sort, not arrange, sections and items according to criteria like description, icon, name, id, etc...
There's also the ability to insert, append and remove, which might give you a more arranging capabilities. Yes, it's a GUI but cumbersome, honestly it's faster the use an easy to use text editor to edit the `conf.yml` file.
