### ISSUE TITLE
[QUESTION] Is there a way to disable settings menu as a whole in dashboard?

### ISSUE THREAD

**Issue by scribblepad** [Lissy93/dashy#1080]
### Question

There are appConfig boolean values like disableConfiguration which disables user from changing config. Wondering if there is a way to disable settings menu as a whole in dashboard UI. Tried hideSettings in appConfig and that doesn't work either.

Basically this would avoid changing things in UI. I wanted to keep things strictly changeable via conf.yml file.

Thanks.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hey @scribblepad - the best way to properly achieve this would be to make the conf.yml read-only. In Docker, that can be done with the `readonly` option. This would prevent any changes being able to be written.

Use that alongside `appConfig.disableConfiguration: true`, and the user won't be able to access any settings, beyond local only options (language and theme)

**Comment by GyHUN95** [comment]
We should reopen this, beacause it can not be disabled from code neither, unfortunately.
![image](https://github.com/Lissy93/dashy/assets/44195762/ed312431-cf43-405e-a490-bfec588b689f)

**Comment by Lissy93** [comment]
Should work if you set `disableConfiguration: true` under `appConfig`

**Comment by maks2199** [comment]
Hi everyone! @Lissy93, I really like this project, looks very nice and inspiring! I agree with the author of Issue, it would be helpfull to be able to disable any configuration at all, including theme, color, layout, and view settings. 

`disableConfiguration: true` allows to hide the bar and prevents from changing the sections and items, but not prevents from changing layout, view type, e.t.c.

**Comment by Trungtin1011** [comment]
Hi @Lissy93,

I agree with @maks2199 about the Settings panel. Even when I set `appConfig.disableConfiguration: true` and `appConfig.hideComponents.hideSettings: true`, other users can still go to the dashboard, toggle open the Settings Menu and edit Themes, Layout, Item Size. They can even view the content of config file in Config > Update Configuration > Click conf.yml in **Using config from /conf.yml**

![image](https://github.com/user-attachments/assets/34a8ea57-c29d-4c64-b179-544b39e450a2)

We need an option to completely disable the toggling of Setting Menu, so that user opening the page can only click into the items

**Comment by sduperret** [comment]
Hi, 
As @maks2199 and @Trungtin1011 i truely love dashy !
It may/will be amazing if we had the option directly on the app to disable editing (or protect it with a password) !
Looking forward to have new on this feature 🚀
