### ISSUE TITLE
[BUG] Incorrect configuration export

### ISSUE THREAD

**Issue by malordin** [Lissy93/dashy#1081]
### Environment

Self-Hosted (Docker)

### System

Windows 10 21H2 , Firefox 109.0 x64

### Version

2.1.1

### Describe the problem

When I go to "Update configuration":

![изображение](https://user-images.githubusercontent.com/20083687/214218014-e61d5c88-2822-45e3-a455-2bae97698bd6.png)

then "View / Export Config":

![изображение](https://user-images.githubusercontent.com/20083687/214218045-80701961-f391-47a0-8f42-1224da3d6425.png)

then click "Dlwnload as File:

![изображение](https://user-images.githubusercontent.com/20083687/214218098-6676f7ba-5d02-46e6-92ca-cd6d1d0ee034.png)

 
open the just downloaded file, copy everything there, paste into any YAML-validator (for example, [this ](https://codebeautify.org/yaml-validator)or [this](https://www.yamllint.com/)), an error occurs: 

```
Error : Unable to parse.
Line : 1 appConfig:
```

![изображение](https://user-images.githubusercontent.com/20083687/214218139-1f685520-b416-48b4-bf5b-c450775fd9b5.png)

To fix JSON data, just remove the space before "appconfig", then YAML will be correct.

![изображение](https://user-images.githubusercontent.com/20083687/214218184-89bc2158-f090-41ae-8743-2e2303c2bb26.png)

### Additional info

Accordingly, if you load the newly exported configuration into dashy, nothing will work.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Thanks @malordin :)
Fixed in #1087
