### ISSUE TITLE
[FEATURE_REQUEST] ChatGPT Widget

### ISSUE THREAD

**Issue by papampi** [Lissy93/dashy#1086]
### Describe the solution you'd like

Would be nice to have a ChatGPT widget.

Loving Dashy, Thanks for its awesomeness.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by papampi** [comment]
Here is the response from ChatGPT:
```
Sign up for an OpenAI API key. You will need this to access the GPT-3 model.

Create a HTML file for your web page and add the necessary elements, such as a text input field and a button to initiate the API call.

Add a JavaScript script to your HTML file that will handle the communication with the OpenAI API. You will need to use the Fetch API or a library like jQuery to make the API call.

In the JavaScript script, use the fetch method to make a post request to the OpenAI API, passing in your API key and the text input by the user. The API will return a response with the generated text, which you can then display on the web page.

Style the web page as desired using CSS.

To serve your webpage, you can use any web server like Apache, Nginx, etc.

Here's an example of a simple HTML file that includes a text input field and a button to initiate the API call:


```

```
<!DOCTYPE html>
<html>
<head>
    <title>ChatGPT Embedded in a Web Page</title>
</head>
<body>
    <h1>ChatGPT Embedded in a Web Page</h1>
    <form>
        <label for="input-text">Enter your text here:</label>
        <input type="text" id="input-text">
        <button type="button" id="submit-button">Generate Text</button>
    </form>
    <div id="output-text"></div>

    <script>
        // Add your JavaScript code here to handle the API call
    </script>
</body>
</html>
```

**Comment by Lissy93** [comment]
Heya @papampi 
Sorry for the delayed reply, it's been a busy couple of weeks.

What kind of stuff were you thinking the ChatGPT widget would do? Like just a chat and response field? Or something more specific?

**Comment by papampi** [comment]
No worries, 
Just a chatbox widget would do for sure.

**Comment by Lissy93** [comment]
As if right on que, OpenAI has [released](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) the firtst version of the ChatGPT API :) However, although it's reasonably priced, it is not free. Maybe just embedding the site as an iframe widget would be a better situation in your usecase?

**Comment by papampi** [comment]
That would be great

**Comment by Lissy93** [comment]
I think, for the time-being this as a widget is probably out of scope. I'd be happy to revisit in the future.

Reason being, OpenAI's API is changing pretty rapidly, as is the whole AI scene, and until more established it's going to be hard to keep this widget up-to-date. As a work-around, building your own as a simple HTML page and embedding via iframe should work. 

Happy to help if you've got any questions on this, as I've built a few apps using ChatGPT/OpenAI's API recently.

And will revisit the option for official widget, in a couple of months if there's still interest.

**Comment by rgsaura** [comment]
Would love to see this going again! I think OpenAi api compatible APIs have been establish, so this could be done without problems. Would love to be able to put my own url api + token etc... 
All the best!
