### ISSUE TITLE
[BUG] Widget for PiHole not working after PiHole update

### ISSUE THREAD

**Issue by MattW42** [Lissy93/dashy#1094]
### Environment

Self-Hosted (Docker)

### System

Rasperry Pi , Docker, Portainer v2.16.1

### Version

2.1.1

### Describe the problem

PiHole widget shows the following:
`An error occurred, see the logs for more info.
Unable to fetch data Retry`

Dashy logs:
` [15:48:01] API Key is required, please see the docs
[15:48:01] Unable to fetch data`

My config:
```

 "widgets": [
        {
          "type": "pi-hole-stats",
          "options": {
            "hostname": "http://{pihole ip}"
          },
          "id": "0_577_piholestats"
        },
        {
          "type": "pi-hole-top-queries",
          "options": {
            "hostname": "http://{pihole ip}",
            "apiKey": "{my api key}"
          },
          "id": "1_577_piholetopqueries"
        }
```

### Additional info

Issue was reported by someone else on the PiHole discourse.
`https://discourse.pi-hole.net/t/dashy-doesnt-show-all-widget-data-after-pi-hole-update/59995`

Response from PiHole support:
**Suspect it is related to "More API endpoints now require auth"** from the announcement for the most recent updates. Not used Dashy so can't be sure.

Originally published at: [Pi-hole FTL v5.20 and Web v5.18 released – Pi-hole](https://pi-hole.net/blog/2022/12/21/pi-hole-ftl-v5-20-and-web-v5-18-released/) As always, please read through the changelog before updating with pihole -up. (A new tag for docker image will arrive in due course.) Pi-hole FTL changes: This release finally ships the remaining bits of the latest dnsmasq release and updates the help text of FTL. We also update the embedded LUA engine and increase the SQLite3 cache size to get some more performance due to relying more on our internal caching comp…

Sample image of what Dashy displays
![image](https://user-images.githubusercontent.com/61036788/215932534-21b60b61-61ad-4208-af90-697301b2b60a.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by MattW42** [comment]
Adding the following to the widgets, 
retrieves 'Top Ads Blocked' and 'Top Queries'

`          "useProxy": true,`

However `pi-hole-stats` still does not work.

**Comment by albcp** [comment]
Pi-hole made some changes and now it requires the API key for the stats. It should work if you add the apiKey option. (https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#pi-hole-stats)

**Comment by MattW42** [comment]
> Pi-hole made some changes and now it requires the API key for the stats. It should work if you add the apiKey option. (https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#pi-hole-stats)
> 

Thanks @albcp 
Yes, that has resolved the issue.
I must have been reading some outdated doco.

Will mark this issue as closed.

**Comment by MattW42** [comment]
Pi-hole made some changes and now it requires the API key for the stats.
 It should work if you add the apiKey option. 
 (https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#pi-hole-stats)
 
 Thanks @albcp for the issue fix.

**Comment by MattW42** [comment]
It appears there's a typo in the documentation.
https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#public-holidays

I got this working by changing the "region" field (as shown in the example)
to "state" as defined in the options.

![image](https://user-images.githubusercontent.com/61036788/218014460-6b0de105-5672-44c5-ac2c-5f2c05ca96ca.png)
