### ISSUE TITLE
[1 click install faills] error deploying to 1 click platforms

### ISSUE THREAD

**Issue by revolverinegirl** [Lissy93/dashy#1098]
### Environment

Cloud Service (Static)

### System

Chrome

### Version

Latest

### Describe the problem

![image](https://user-images.githubusercontent.com/35229381/216903656-faa2f33c-e12a-4e27-99e9-0bb9d71901bc.png)

it fails when you want to use 1 click install

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Aerowinder** [comment]
Last I checked, Dashy wouldn't work past Node 16. Has this changed? A couple dependencies wouldn't work on newer versions, IIRC.
