### ISSUE TITLE
[QUESTION] Build from source not working

### ISSUE THREAD

**Issue by DRXAquosus** [Lissy93/dashy#1100]
Running RHEL9

When trying to build with yarn I get the following:
yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @babel/preset-env@7.18.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/helper-compilation-targets@7.18.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression@7.17.12" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.17.12" has unmet peer dependency "@babel/core@^7.13.0".
warning "@babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-class-properties@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-class-static-block@7.18.0" has unmet peer dependency "@babel/core@^7.12.0".
warning "@babel/preset-env > @babel/plugin-proposal-dynamic-import@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-export-namespace-from@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-json-strings@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-logical-assignment-operators@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-numeric-separator@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.18.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-optional-chaining@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-private-methods@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-private-property-in-object@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-class-static-block@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-dynamic-import@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-export-namespace-from@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-import-assertions@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-private-property-in-object@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-arrow-functions@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-async-to-generator@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-block-scoped-functions@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-block-scoping@7.18.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-classes@7.18.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-computed-properties@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-destructuring@7.18.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-dotall-regex@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-duplicate-keys@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-exponentiation-operator@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-for-of@7.18.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-function-name@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-literals@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-member-expression-literals@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-amd@7.18.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-commonjs@7.18.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-systemjs@7.18.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-modules-umd@7.18.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-named-capturing-groups-regex@7.17.12" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-transform-new-target@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-object-super@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-parameters@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-property-literals@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-regenerator@7.18.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-reserved-words@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-shorthand-properties@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-spread@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-sticky-regex@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-template-literals@7.18.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-typeof-symbol@7.17.12" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-unicode-escapes@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-transform-unicode-regex@7.16.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/preset-modules@0.1.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > babel-plugin-polyfill-corejs2@0.3.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > babel-plugin-polyfill-corejs3@0.5.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > babel-plugin-polyfill-regenerator@0.3.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@babel/preset-env > @babel/plugin-proposal-class-properties > @babel/helper-create-class-features-plugin@7.18.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > @babel/plugin-proposal-unicode-property-regex > @babel/helper-create-regexp-features-plugin@7.17.12" has unmet peer dependency "@babel/core@^7.0.0".
warning "@babel/preset-env > babel-plugin-polyfill-corejs2 > @babel/helper-define-polyfill-provider@0.3.1" has unmet peer dependency "@babel/core@^7.4.0-0".
warning " > @vue/cli-plugin-eslint@4.5.17" has incorrect peer dependency "eslint@>= 1.6.0 < 7.0.0".
warning "@vue/cli-plugin-eslint > eslint-loader@2.2.1" has incorrect peer dependency "eslint@>=1.6.0 <7.0.0".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > progress-bar-webpack-plugin@2.1.0" has unmet peer dependency "webpack@^1.3.0 || ^2 || ^3 || ^4 || ^5".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
Done in 66.99s.
[User@Hostname dashy]$ yarn build
yarn run v1.22.19
$ vue-cli-service build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

WARN A new version of sass-loader is available. Please upgrade for best experience.
Building Dashy [== ] 10% (0.1 seconds)Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:130:10)
at module.exports (/home/user/dashy/node_modules/webpack/lib/util/createHash.js:135:53)
at NormalModule._initBuildHash (/home/user/dashy/node_modules/webpack/lib/NormalModule.js:417:16)
at handleParseError (/home/user/dashy/node_modules/webpack/lib/NormalModule.js:471:10)
at /home/user/dashy/node_modules/webpack/lib/NormalModule.js:503:5
at /home/user/dashy/node_modules/webpack/lib/NormalModule.js:358:12
at /home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:373:3
at iterateNormalLoaders (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
at iterateNormalLoaders (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
at /home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:236:3
at runSyncOrAsync (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
at iterateNormalLoaders (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
at Array. (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
at Storage.finished (/home/user/dashy/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
at /home/user/dashy/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠏ Building for production...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
⠧ Building for production.../home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:114
throw e;
^

Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:130:10)
at module.exports (/home/user/dashy/node_modules/webpack/lib/util/createHash.js:135:53)
at NormalModule._initBuildHash (/home/user/dashy/node_modules/webpack/lib/NormalModule.js:417:16)
at handleParseError (/home/user/dashy/node_modules/webpack/lib/NormalModule.js:471:10)
at /home/user/dashy/node_modules/webpack/lib/NormalModule.js:503:5
at /home/user/dashy/node_modules/webpack/lib/NormalModule.js:358:12
at /home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:373:3
at iterateNormalLoaders (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
at iterateNormalLoaders (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
at /home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:236:3
at context.callback (/home/user/dashy/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
at /home/user/dashy/node_modules/cache-loader/dist/index.js:147:7
at /home/user/dashy/node_modules/graceful-fs/graceful-fs.js:61:14
at FSReqCallback.oncomplete (node:fs:192:23) {
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I then tried with npm and this was the result:
$ npm install
npm notice
npm notice New major version of npm available! 8.19.2 -> 9.4.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.4.2
npm notice Run npm install -g npm@9.4.2 to update!
npm notice
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @vue/cli-plugin-eslint@4.5.17
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR! dev eslint@"^7.24.0" from the root project
npm ERR! peer eslint@">= 4.12.1" from babel-eslint@10.1.0
npm ERR! node_modules/babel-eslint
npm ERR! dev babel-eslint@"^10.0.1" from the root project
npm ERR! 9 more (eslint-config-airbnb, eslint-config-airbnb-base, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.17
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR! dev @vue/cli-plugin-eslint@"^4.5.15" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.17
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR! dev @vue/cli-plugin-eslint@"^4.5.15" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See //.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR! //.npm/_logs/2023-02-09T09_34_38_698Z-debug-0.log

Any idea where I'm going wrong?

Thanks!

**Comment by DRXAquosus** [comment]
I'm pretty certain I was, overnight I wiped the VM and replaced it with RHEL 8, followed the same steps as I did before and it built successfully.
So either I wasn't previously using the correct version of Node or there was just something about RHEL 9 that wasn't jiving.

Thanks for your response!

**Comment by Aerowinder** [comment]
RHEL 9 works. I've built it on Alma 9.1 multiple times. Must have been Node :) If you post the exact commands you used (or the guide you followed), I'll take a look and see if I can spot the error.

**Comment by DRXAquosus** [comment]
Hey Aerowinder,

I couldn't find an install guide that wasn't for docker so I had to fumble around until I figured it out.
Here's what I did, keep in mind I may have forgotten to document a command or two.

1) Create user and group and open firewall TCP/4000
	sudo groupadd --system dashy
	sudo useradd --system \
		    --gid dashy \
		    --create-home \
		    --home-dir /home/dashy \
		    --shell /usr/bin/bash \
		    --comment "Dashy web server" \
		    dashy

2) Install NPM, NVM and Yarn
	sudo dnf install -y npm
	npm install --global yarn
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
	nvm use system
	nvm install 16.19
	nvm use 16
	sudo nano /home/dashy/.bashrc
		add export PATH=$PATH:/usr/local/bin/yarn to the end

3) Git Dashy
	cd /opt
	sudo git clone https://github.com/Lissy93/dashy.git
	sudo chown -R dashy:dashy dashy/
	sudo su dashy

4) Install dashy
	cd /opt/dashy
	yarn install

5) Build dashy
	yarn build

6) Verify dashy is working
	yarn start

7) Disable login for Dashy user
	sudo nano /etc/passwd
		find line that starts with dashy
		at the end of the line change dashy:/usr/bin/bash to dashy:/sbin/nologin
	
8) Create systemd service
	Still trying to figure this one out, lol

**Comment by Aerowinder** [comment]
1) Install
```
sudo tee /opt/dashy-install.sh > /dev/null << EOF
#!/bin/sh
#prereq - must use LTS version of Node (v16) as v18 is not supported by one of the dependencies.
dnf install -y curl git
curl -fsSL https://rpm.nodesource.com/setup_16.x | bash -
dnf update && dnf install -y nodejs
npm install --global yarn
 
#install
mkdir /opt/dashy
cd /opt
git clone https://github.com/Lissy93/dashy.git
cd /opt/dashy
yarn install
yarn build
 
#create user
useradd dashy -d /opt/dashy -M -r -s "/bin/bash"
chown -R dashy:dashy /opt/dashy
chmod 771 /opt/dashy
EOF
```

2) Start script
```
sudo tee /opt/dashy-start.sh > /dev/null << EOF
#!/bin/sh
cd /opt/dashy
yarn start
EOF
```

3) Update script
```
sudo tee /opt/dashy-update.sh > /dev/null << EOF
#!/bin/sh
systemctl stop dashy
cd /opt/dashy
git pull origin master
npm update
#yarn upgrade
yarn build
chown -R dashy:dashy /opt/dashy
chmod 771 /opt/dashy
systemctl start dashy
EOF
```

4) Service file
```
sudo tee /etc/systemd/system/dashy.service> /dev/null << EOF
[Unit]
Description=Dashy Daemon
After=network-online.target
 
[Service]
User=dashy
Group=dashy
Type=mixed
ExecStart=/opt/dashy-start.sh
TimeoutStopSec=30
KillMode=mixed
Restart=never
 
[Install]
WantedBy=multi-user.target
EOF
```

5) Firewall
```
sudo firewall-cmd --permanent --new-service=dashy
sudo firewall-cmd --permanent --service=dashy --set-short="Dashy"
sudo firewall-cmd --permanent --service=dashy --set-description="Dashy helps you organize your self-hosted services by making them accessible from a single place"
sudo firewall-cmd --permanent --service=dashy --add-port=4000/tcp
sudo firewall-cmd --permanent --zone=public --add-service=dashy
sudo firewall-cmd --reload
```

6) Mark scripts executable, start/enable Dashy
```
chmod +x /opt/dashy-install.sh
chmod +x /opt/dashy-start.sh
chmod +x /opt/dashy-update.sh
systemctl enable dashy
systemctl start dashy
```

**Comment by DRXAquosus** [comment]
Wow!
That is definitely above my current knowledge level but look like some great things to learn from.  Thanks for sharing and for all your help!

**Comment by DRXAquosus** [comment]
For the hell of it, I wiped my Dashy VM and reinstalled RHEL9.
Aerowinder's scripts worked absolutely flawlessly, these scripts should be part of the official documentation.

Thanks again Aerowinder!

**Comment by YR3** [comment]
**On Unix-like (Linux, macOS, Git bash, etc.) run the following command:**

`export NODE_OPTIONS=--openssl-legacy-provider`

On Node v17.9.1. That Solved it for me.

**Comment by YR3** [comment]
For Reference purposes here's the same command on Windows Systems:

**On Windows command prompt:**

`set NODE_OPTIONS=--openssl-legacy-provider`

**On PowerShell:**

`$env:NODE_OPTIONS = "--openssl-legacy-provider"`
