### ISSUE TITLE
Minimizing blank space

### ISSUE THREAD

**Issue by Kree47** [Lissy93/dashy#1103]
### Question

I love the product, I just wish I could fit more on the page.  In particular I can't figure out how to reduce the big blank vertical bars on each side.  Perhaps with custom css?

![Screenshot 2023-02-11 143843](https://user-images.githubusercontent.com/92868602/218277898-a8e65a77-4fcd-4c9e-a40a-af2e2ff77b05.jpg)

### Category

Theming & Layout

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Pazdikan** [comment]
I don't exactly know what do you mean by reducing blank vertical bars. Once you add more [sections](https://dashy.to/docs/configuring/#section) they'll fill up the empty space. You can also check out [layouts](https://dashy.to/docs/alternate-views#default), maybe the few options there will satisfy you.

**Comment by Kree47** [comment]
That was my expectation too.  The vertical empty bars do shrink a bit, but still remain on each side even while the icons get hidden.
![Screenshot 2023-02-16 092747](https://user-images.githubusercontent.com/92868602/219392153-eaff9f00-67e4-48f1-a173-3b5a7b09437b.jpg)

**Comment by Kree47** [comment]
I found the answer in https://github.com/Lissy93/dashy/discussions/148 
using Custom CSS:
.item-group-container { --col-count: 8 !important; max-width: 95% !important; }
