### ISSUE TITLE
Proxmox status not working

### ISSUE THREAD

**Issue by marktn** [Lissy93/dashy#1110]
### Question

Hi,

I have an issue with the status of proxmox. I am a new user, maybe i did something wrong... Tried different settings, but can't get it working. Also couldn't  find the error.

<img width="272" alt="afbeelding" src="https://user-images.githubusercontent.com/11601535/219327127-787a5425-7ae2-4829-afe7-f3dfaf7eb404.png">

<img width="820" alt="afbeelding" src="https://user-images.githubusercontent.com/11601535/219326982-9fb594ca-46a8-4e2a-8dd4-d09bc625e357.png">

### Category

Status Checking

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Aerowinder** [comment]
Settings are incorrect.

Set Status Check URL to https://192.186.1.25:8006
-Dashy doesn't ping the device. It contacts the HTTP/S server and waits for a response.

Set Status Check Disable SSL to False
-Proxmox uses TLS by default. Settings this option to True will break the status check of this service.

**Comment by marktn** [comment]
Hi,
Thanks for your support!


It should:
![afbeelding](https://user-images.githubusercontent.com/11601535/219382429-e083ebe0-7a5a-402f-9b30-22ad8ca7d189.png)

but after save, Status Check Disable SSL is removed.
![afbeelding](https://user-images.githubusercontent.com/11601535/219383309-994dcb8e-a3c0-42b4-9e39-b6a46ff2e963.png)

**Comment by Aerowinder** [comment]
Are you saying that the status check is still not functioning after the changes? You probably don't even need the Status Check URL, since the service URL and status check URL are the same.

**Comment by marktn** [comment]
No still not working. 
Also did a test without Status Check Url

After saving the settings, the Status Check Disable SSL is removed. So i doesn't save the settings. 
![afbeelding](https://user-images.githubusercontent.com/11601535/219393080-ee8242f7-361e-44d5-bf13-6baea405d150.png)

**Comment by DRXAquosus** [comment]
I have it working for me, here are my settings.  Hope this helps.
![image](https://user-images.githubusercontent.com/45409262/219962541-e1950691-0a3e-4bec-8903-116a8d2d37ac.png)

**Comment by Lissy93** [comment]
Heya @marktn - Could you share the contents of your browser console ([here's how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console)), as there should be some info explaining why it's not working there.

The relevant parts of your YAML might also be helpful. And just to confirm, if you visit that page directly (`https://10.2.11.80:8006`) does it return a 200?

I also recommend that if you haven't already, you take a look at [Troubleshooting → Status Checks not Working](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#status-checks-failing), as there are some more ideas there. But my guess is that it's a CORS error.

Also, have you seen #181 as it looks to be the same/ similar issue.

**Comment by marktn** [comment]
Found it! After using Firefox the save function works!
