### ISSUE TITLE
lost my dashboard configration

### ISSUE THREAD

**Issue by toxinliquid** [Lissy93/dashy#1112]
### Question

i ran docker run -p 8080:80 lissy93/dashy accidently
and now i have a brand new dashboard ! anyway to remedy this? 
thanks 

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Aerowinder** [comment]
Did you have a backup of your configuration before you nuked it? Was it located on a volume or bind mount?

If the answer is no to all questions, then I'm afraid my answer is also no.

**Comment by toxinliquid** [comment]
no to all , thank you u , lesson learnt.
