### ISSUE TITLE
Weather forecast not working even after getting plan upgrade

### ISSUE THREAD

**Issue by MrPanda011** [Lissy93/dashy#1116]
### Environment

Self-Hosted (Docker)

### System

Ubuntu Server 22.04, Docker 20.10.12, Microsoft Edge 110.0.1587.50

### Version

2.1.1

### Describe the problem

After reading documentation and understanding I need a plan which offers Forecasts, I did just that and upgraded to a "One Call by Call" plan, which gives me forecast of 8 days, tried to add the API key to my Dashy config and setup the widget, but it still gives me the "Unable to fetch data" error

### Additional info

![image](https://user-images.githubusercontent.com/37938860/220120231-b114f609-18b5-4224-b7b1-88737d5a5aec.png)
![image](https://user-images.githubusercontent.com/37938860/220120607-ba3254b7-be06-4306-bc92-498126145003.png)
![image](https://user-images.githubusercontent.com/37938860/220120371-cc1b4a82-5af1-4831-a344-1d90d714f51c.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
This is a dup of #1035
