### ISSUE TITLE
[BUG] Infinite loop with Keycloak 21.0.1

### ISSUE THREAD

**Issue by JPVenson** [Lissy93/dashy#1134]
### Environment

Self-Hosted (Docker)

### Version

2.1.0

### Describe the problem

After i was forced to recreate my container due to the whole Authentication not working with 2.1.1, i found out that with keycloak 21.0.1 and Dashy 2.1.0 the app gets in an Infinite cycle loading due to the token endpoint returning 401 after logging in.

This might be due to a misconfiguration on keycloak side but in any case the app should never just endless refresh on an Authentication error.

### Additional info

![image](https://user-images.githubusercontent.com/6794763/223234043-99e6e78e-8c92-43ea-8e30-9a7591a9c0ca.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by juantxorena** [comment]
It is still relevant

**Comment by juantxorena** [comment]
I thought I could research this bug: I updated the keycloak-js to the latest one, 21.0.2, with no success. The events in keycloak show. I attach a screenshot with the events:
![Screenshot_20230408_134209](https://user-images.githubusercontent.com/5948336/230719423-5a59e199-508a-46e5-a69c-a95fd8e84126.png)

I have other apps that login with keycloak and they work correctly. However, I don't think they implement something keycloak specific, just generic oidc stuff. This is the query to the keycloak server of one of them, [vikunja](https://vikunja.io/)

`https://auth.lan:8443/realms/zuhause/protocol/openid-connect/auth?client_id=vikunja&redirect_uri=https://projekt.lan/auth/openid/keycloak&response_type=code&scope=openid email profile&state=ysuarxd4iha`

Dashy first (successfully, 200) tries to call this: 
`https://auth.lan:8443/realms/zuhause/protocol/openid-connect/3p-cookies/step1.html`

Then this, and keycloak returns a 302:
`https://auth.lan:8443/realms/zuhause/protocol/openid-connect/auth?client_id=dashy&redirect_uri=http%3A%2F%2Fzuhause.lan%3A4000%2F&state=3eec92a5-008e-4857-8251-cab38ae69a0f&response_mode=fragment&response_type=code&scope=openid&nonce=1d96b9f0-7d64-4231-8981-08fadf1e4f90
`

Then it loads some icons and css and stuff, and dashy tries to communicate again with the keycloak server, this one getting a 401 and reloading again in an infinite loop:

`https://auth.lan:8443/realms/zuhause/protocol/openid-connect/token`

Legend:

- keycloak server: https://auth.lan:8443
- keycloak realm: zuhause
- vikunja server: https://projekte.lan
- dashy server: http://zuhause.lan:4000

**Comment by juantxorena** [comment]
Of course, it was my fault. I had set Client authentication in the config of the keycloak config. Now it's off, and working. Maybe a working config of the client would be useful for the documentation?

**Comment by thelan** [comment]
If you can post an example of a working client it would be nice.
Actually running dashy 2.1.0 + keycloak 21.0.2 and i'm facing the same problem
The client is configured with Client authentication and Standard Flow

**Comment by juantxorena** [comment]
I'll put it when I'm at home, but client authentication has to be off

**Comment by juantxorena** [comment]
Sorry for the late reply. Config, assuming that the dashy URI is dashy.example.com:

Root URL: https://dashy.example.com/
Home URL: https://dashy.example.com
Valid redirect URIs: https://dashy.example.com/*
Web origins: https://dashy.example.com

Capability config: everything off/unchecked except "Standard flow", "Direct access grants" and "Implicit flow"

I didn't touch anything else.

**Comment by thelan** [comment]
No wories.
I've tested with your settings but it's still looping on the auth.

From the keycloak side in the event logs everything is ok.

Did you add specific roles in the keycloak client config ?
