### ISSUE TITLE
[BUG] 404 Error page responds with 200 HTTP code

### ISSUE THREAD

**Issue by sambartik** [Lissy93/dashy#1136]
### Environment

Self-Hosted (Docker)

### Version

2.1.1

### Describe the problem

Hello, I have been using dashy for a while now. I have configured my own logic for 404 error pages via nginx. Today I have noticed that instead of my own logic I got shown the new native Dashy's 404 error page. 

In my configuration, the Dashy is behind a reverse proxy that handles the traffic. I have my own way of handling when Dashy would return a 404 error. However, now it fails, because Dashy returns /404 page with an HTTP 200 OK status.

Reverting back to version 2.1.0 fixed the issue.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by shellshock1953** [comment]
Same hare - can we reopen this one?

**Comment by Lissy93** [comment]
I'm actually not sure that this ever worked.

Reason being, in Vue all the routing is handled on the client side, so the server serves up the same file whatever route you visit (it's always index.html), which then renders whatever it needs (or a "not found" message if nothing matches).

That said, I can implement logic in the Node server to respond with a `404` status when the index.html itself is not found.

If this used to work for you, could it have been a change that you made in your reverse proxy config?
