### ISSUE TITLE
[FEATURE_REQUEST] Hope to be able to search in native language.

### ISSUE THREAD

**Issue by eternity1984** [Lissy93/dashy#1137]
### Is your feature request related to a problem? If so, please describe.

https://github.com/Lissy93/dashy/blob/50baed7d016471dc1614f0b4a983f0f46cb5bbae/src/utils/Search.js#L27

Currently the search function is limited to alphanumeric characters, underscores and whitespaces. However, item descriptions are usually set in the native language and it would be very attractive to be able to search in the native language.

### Describe the solution you'd like

Removing the replace method or changing the regex pattern will remedy this problem.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by Lissy93** [comment]
This has been fixed in #1351 by Deneor
