### ISSUE TITLE
[FEATURE_REQUEST] optimize search input

### ISSUE THREAD

**Issue by phmassa** [Lissy93/dashy#1145]
### Is your feature request related to a problem? If so, please describe.

Search box generate an event that search at each keystroke, but with a lot of items, it's slow.

### Describe the solution you'd like

can we add parameter to generate a search when only 3 characters are input or only when we type Enter ?

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by deneor** [comment]
Reopen, please)
