### ISSUE TITLE
[QUESTION] <title> title cannot change

### ISSUE THREAD

**Issue by rT-Troy** [Lissy93/dashy#1148]
### Question

I try 
```
pageInfo:
  title: 𝖄𝕺🌎𝕿𝕽𝕺¥
```
This title will show as the head of the page, but not on the browser tab, why? I try use normal font but still not work.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by rroethof** [comment]
Please reopen question, In the config I have set the title to 'Company name - IT links'.. but as this topic states, it keeps comming back as Dashy
