### ISSUE TITLE
[BUG] Config lost when reload OR different config paths for reading and saving 

### ISSUE THREAD

**Issue by juantxorena** [Lissy93/dashy#1160]
### Environment

Self-Hosted (Bare Metal)

### Version

2.1.1

### Describe the problem

If I modify the config via the UI, it works correctly, and it's saved in public/conf.yml (there's also a bunch of backup configs). However, if I reload the page, the original config file dist/conf.yml, so I have to manually edit the conf.yml file there

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by dropdevrahul** [comment]
@juantxorena Can you update the description its not clear what's supposed to happen and what bug is there

**Comment by juantxorena** [comment]
1. Fresh bare-metal installation
2. Modify config in the UI visual editor
3. The config file in public/conf.yml is updated with whatever changes I did
4. Hard reload page (Ctrl+F5)
5. The config file dist/conf.yml is used (as opossed to the previously updated public/conf.yml), so none of the changes done in step 2 are shown

**Comment by martin-77** [comment]
same here

**Comment by juantxorena** [comment]
It is of course still active.

**Comment by juantxorena** [comment]
This is still not fixed, but unfortunately, I think it's the project the one who's stale

**Comment by CrazyWolf13** [comment]
> This is still not fixed, but unfortunately, I think it's the project the one which is stale

Just checking, you did a rebuild right? And you have write permissions where the config is located right?

**Comment by CrazyWolf13** [comment]
Hi
This problems seems to be related to dashy not automatically rebuilding on changes, see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.
