### ISSUE TITLE
[BUG] local icons not loaded

### ISSUE THREAD

**Issue by quadcom** [Lissy93/dashy#1168]
### Environment

Self-Hosted (Docker)

### System

Unraid

### Version

2.1.1

### Describe the problem

Locally stored image assets for icons do not load when referenced in config. According to the docs, images stored in the  '/app/public/item-icons/' directory of the container are directly referenced by using the image name.

I have tested this with both png and ico files —neither works.

![image](https://user-images.githubusercontent.com/7085931/235530445-27ee38c6-e988-4a6d-bd70-48d5da51d042.png)

![image](https://user-images.githubusercontent.com/7085931/235530558-db4b6d13-96ed-4a62-b3fa-0486b26e7802.png)

![image](https://user-images.githubusercontent.com/7085931/235530753-ef1d7318-78b8-48f2-9a2c-64a064d7581f.png)

![image](https://user-images.githubusercontent.com/7085931/235530876-badeb548-aabe-49ef-b573-e1513b9b8016.png)

![image](https://user-images.githubusercontent.com/7085931/235531836-cb848645-7f53-4643-b2d3-c0b1da961f1c.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by coldshouldermedia** [comment]
> Still won't accept ico files, and the jpg/png files took multiple config saves, browser refreshes and browser cache flushing to start showing.

I am having the issue where .ico files aren't accepted.  I don't see them listed as being supported, is that the issue?
