### ISSUE TITLE
[BUG] APOD widget not working

### ISSUE THREAD

**Issue by fedepoi** [Lissy93/dashy#1172]
### Environment

Self-Hosted (Docker)

### System

proxmox, docker, debian VM

### Version

2.1.1

### Describe the problem

The apod Heroku API is currently down, making the APOD widget not work as expected

<img width="444" alt="image" src="https://user-images.githubusercontent.com/48029276/236040386-7712d1ea-e0d0-4135-8798-03358ffc4352.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/48029276/236040542-c7976629-b075-443e-8118-d2a55fd6e3d6.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/48029276/236040620-b3e345a4-ac45-4ec8-8f91-daec6114e38d.png">

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by elendil7** [comment]
+1, this is an issue.

**Comment by thezzer** [comment]
+1, hope to get fix, this is a nice feature =)

**Comment by EliasGagnef** [comment]
same issue for me

**Comment by elendil7** [comment]
Thank you very much! Works great

![image](https://github.com/Lissy93/dashy/assets/80429382/01fc072b-dee5-4722-b86b-74c67bcbe9f6)

**Comment by thezzer** [comment]
Thank you very much =)
