### ISSUE TITLE
[BUG] Deploying to Cloudflare Workers leads to error

### ISSUE THREAD

**Issue by RTBGG** [Lissy93/dashy#1174]
### Environment

Cloud Service (Static)

### System

Cloudflare Workers

### Version

latest/2.1.1 (probably)

### Describe the problem

I wanted to Deploy to Cloudflare Workers using the Button in the docs. I followed the steps provided on the Cloudflare Deploy Workers Page until the end. However the last page after few seconds of showing "initializing" showed "error". (Check first screenshot)

Then when I click on "error" it leads me to empty github actions workflows. (Check second screenshot)

Also in Cloudflare the Worker has not been created when looking for it in Cloudflares Dashboard.

In case it's relevant - I am using newest Stable Firefox version on Windows 11.

Has anyone managed to deploy to Cloudflare Workers successfully with the current version?
Thank you in advance for help.

### Additional info

[Cloudflare Deploy Workers Screenshot](https://share.rtb.gg/file/2023/05/firefox_RaXZbE24nE.png)
[Github Actions Workflows Screenshot](https://share.rtb.gg/file/2023/05/firefox_TInEUx4Wo0.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Scootter23** [comment]
I am having this exact same issue and I tried Microsoft Edge and Chrome. Here is the error in my Chrome dev window if it helps at all.

![dashy-cloudflaredeploy-error](https://user-images.githubusercontent.com/20101458/236595100-abef99b6-a1c5-402a-ab3a-1305dadbdaa3.jpg)

**Comment by Glitch3dPenguin** [comment]
CF pages deployment has been broken for quite a while. I have been checking in every now and then to see if it ever gets fixed, lol. 

https://github.com/Lissy93/dashy/issues/731

**Comment by niuhomelab** [comment]
I get the same issue in Safari
<img width="1258" alt="cloudflareerror" src="https://github.com/Lissy93/dashy/assets/127645585/9b135947-6c91-4e7a-8841-efca24b7c1ee">

**Comment by quangthe** [comment]
Have the same issue as @niuhomelab

**Comment by Glitch3dPenguin** [comment]
Cloudflare is no longer a supported version of deployment. See [merged pull request](https://github.com/Lissy93/dashy/pull/1364#event-10782299717).
