### ISSUE TITLE
[QUESTION] Add Google Widget

### ISSUE THREAD

**Issue by CrazyWolf13** [Lissy93/dashy#1177]
### Question

Hi 
I have just recently discovered Dashy and it is amazing!

But I wonder if there is any way maybe via html embed or iframe to implement a Google search widget.

It should be clickable and then you can write something and as soon as you hit enter you get redirected to a new tab with the search results from google.

I saw that there is already something like this implemented into the search thing at the left top, but I would highly prefer something centered like in the screenshot.

I anyone has an idea on how I could achieve this, I'd be very happy if you could share it.
![image](https://user-images.githubusercontent.com/96661824/236669666-a7fb3f47-4674-4c3e-83e7-dae17cdb793a.png)

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by plmi** [comment]
What about this: https://dashy.to/docs/widgets/#custom-search

**Comment by CrazyWolf13** [comment]
I have built my own using html css js

**Comment by lzsix** [comment]
> I have built my own using html css js

i would love to use that. Can you share that please?

**Comment by CrazyWolf13** [comment]
> > I have built my own using html css js
> 
> i would love to use that. Can you share that please?

Sure, happy to share it. :)

```
    {
      "name": "Google Search",
      "icon": "hl-google",
      "displayData": {
        "sortBy": "default",
        "rows": 1,
        "cols": 2,
        "collapsed": false,
        "hideForGuests": false
      },
      "widgets": [
        {
          "type": "embed",
          "options": {
            "html": "<head>\n    <style>\n        .container{\n            width: 100%;\n            min-height: 15vh;\n            padding: 5%;\n            display: flex;\n            align-items: flex-start;\n            justify-content: center;\n\n        }\n\n        .search-bar{\n            width: 70%;\n            max-width: 400px;\n            background: rgba(255,255,255,0.2);\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            border-radius: 30px;\n            padding: 10px;\n            backdrop-filter: blur(4px) saturate(180%);\n        }\n\n        .search-bar input{\n            background: transparent;\n            flex: 1;\n            border: 0;\n            outline: none;\n            padding: 10px 20px;\n            font-size: 14px;\n            color: #cac7ff;\n        }\n\n        ::placeholder{\n            color: #cac7ff;\n        }\n\n        .search-bar button img{\n            width: 20px;\n\n        }\n\n        .search-bar button{\n            border: 0;\n            border-radius: 50%;\n            width: 40px;\n            height: 40px;\n            background: #58629b;\n            cursor: pointer;\n        }\n        \n        .google-image{\n            width: 30px;\n            height: 30px;\n            margin-right: 10px;\n            order: -1;\n        }\n    </style>\n    <meta name=\"viewport\" content=\"\"width=device-width, initial-scale=\"1.0\">\n    <title> Search Bar</title>\n</head>\n<body>\n<div class=\"container\">\n    <form action=\"https://google.com/search\" method=\"get\" class=\"search-bar\">\n        <input type=\"text\" placeholder=\" \" name=\"q\">\n        <button type=\"submit\"><img src=\"icons/search.png\"></button>\n        <img src=\"icons/google.png\" alt=\"Image\" class=\"google-image\">\n    </form>\n</div>\n</body>\n"
          },
          "id": "0_1235_embed"
        },
      ],
      "filteredItems": []
    }
```

**Comment by CrazyWolf13** [comment]
Woah HTML seems to be Formated a big strange, however if you exactly copy-paste and integrate it in your existing conf.yml it should work.

**Comment by lzsix** [comment]
> > > I have built my own using html css js
> > 
> > 
> > i would love to use that. Can you share that please?
> 
> Sure, happy to share it. :)
> 
> ```
>     {
>       "name": "Google Search",
>       "icon": "hl-google",
>       "displayData": {
>         "sortBy": "default",
>         "rows": 1,
>         "cols": 2,
>         "collapsed": false,
>         "hideForGuests": false
>       },
>       "widgets": [
>         {
>           "type": "embed",
>           "options": {
>             "html": "<head>\n    <style>\n        .container{\n            width: 100%;\n            min-height: 15vh;\n            padding: 5%;\n            display: flex;\n            align-items: flex-start;\n            justify-content: center;\n\n        }\n\n        .search-bar{\n            width: 70%;\n            max-width: 400px;\n            background: rgba(255,255,255,0.2);\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            border-radius: 30px;\n            padding: 10px;\n            backdrop-filter: blur(4px) saturate(180%);\n        }\n\n        .search-bar input{\n            background: transparent;\n            flex: 1;\n            border: 0;\n            outline: none;\n            padding: 10px 20px;\n            font-size: 14px;\n            color: #cac7ff;\n        }\n\n        ::placeholder{\n            color: #cac7ff;\n        }\n\n        .search-bar button img{\n            width: 20px;\n\n        }\n\n        .search-bar button{\n            border: 0;\n            border-radius: 50%;\n            width: 40px;\n            height: 40px;\n            background: #58629b;\n            cursor: pointer;\n        }\n        \n        .google-image{\n            width: 30px;\n            height: 30px;\n            margin-right: 10px;\n            order: -1;\n        }\n    </style>\n    <meta name=\"viewport\" content=\"\"width=device-width, initial-scale=\"1.0\">\n    <title> Search Bar</title>\n</head>\n<body>\n<div class=\"container\">\n    <form action=\"https://google.com/search\" method=\"get\" class=\"search-bar\">\n        <input type=\"text\" placeholder=\" \" name=\"q\">\n        <button type=\"submit\"><img src=\"icons/search.png\"></button>\n        <img src=\"icons/google.png\" alt=\"Image\" class=\"google-image\">\n    </form>\n</div>\n</body>\n"
>           },
>           "id": "0_1235_embed"
>         },
>       ],
>       "filteredItems": []
>     }
> ```



wow thank you so much, i will try that tomorrow and report back :)

**Comment by lzsix** [comment]
> > > > I have built my own using html css js
> > > 
> > > 
> > > i would love to use that. Can you share that please?
> > 
> > 
> > Sure, happy to share it. :)
> > ```
> >     {
> >       "name": "Google Search",
> >       "icon": "hl-google",
> >       "displayData": {
> >         "sortBy": "default",
> >         "rows": 1,
> >         "cols": 2,
> >         "collapsed": false,
> >         "hideForGuests": false
> >       },
> >       "widgets": [
> >         {
> >           "type": "embed",
> >           "options": {
> >             "html": "<head>\n    <style>\n        .container{\n            width: 100%;\n            min-height: 15vh;\n            padding: 5%;\n            display: flex;\n            align-items: flex-start;\n            justify-content: center;\n\n        }\n\n        .search-bar{\n            width: 70%;\n            max-width: 400px;\n            background: rgba(255,255,255,0.2);\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            border-radius: 30px;\n            padding: 10px;\n            backdrop-filter: blur(4px) saturate(180%);\n        }\n\n        .search-bar input{\n            background: transparent;\n            flex: 1;\n            border: 0;\n            outline: none;\n            padding: 10px 20px;\n            font-size: 14px;\n            color: #cac7ff;\n        }\n\n        ::placeholder{\n            color: #cac7ff;\n        }\n\n        .search-bar button img{\n            width: 20px;\n\n        }\n\n        .search-bar button{\n            border: 0;\n            border-radius: 50%;\n            width: 40px;\n            height: 40px;\n            background: #58629b;\n            cursor: pointer;\n        }\n        \n        .google-image{\n            width: 30px;\n            height: 30px;\n            margin-right: 10px;\n            order: -1;\n        }\n    </style>\n    <meta name=\"viewport\" content=\"\"width=device-width, initial-scale=\"1.0\">\n    <title> Search Bar</title>\n</head>\n<body>\n<div class=\"container\">\n    <form action=\"https://google.com/search\" method=\"get\" class=\"search-bar\">\n        <input type=\"text\" placeholder=\" \" name=\"q\">\n        <button type=\"submit\"><img src=\"icons/search.png\"></button>\n        <img src=\"icons/google.png\" alt=\"Image\" class=\"google-image\">\n    </form>\n</div>\n</body>\n"
> >           },
> >           "id": "0_1235_embed"
> >         },
> >       ],
> >       "filteredItems": []
> >     }
> > ```
> 
> wow thank you so much, i will try that tomorrow and report back :)

Sorry to trouble you again.

I tried it today am i´m really having troubles getting it to work.
I am very new to yaml and i keep getting errors that seem to be related to formatting issues.


Could you post an example on how you integrated in your yaml? 

Thanks in advance :)

**Comment by CrazyWolf13** [comment]
> > > > > I have built my own using html css js
> > > > 
> > > > 
> > > > i would love to use that. Can you share that please?
> > > 
> > > 
> > > Sure, happy to share it. :)
> > > ```
> > >     {
> > >       "name": "Google Search",
> > >       "icon": "hl-google",
> > >       "displayData": {
> > >         "sortBy": "default",
> > >         "rows": 1,
> > >         "cols": 2,
> > >         "collapsed": false,
> > >         "hideForGuests": false
> > >       },
> > >       "widgets": [
> > >         {
> > >           "type": "embed",
> > >           "options": {
> > >             "html": "<head>\n    <style>\n        .container{\n            width: 100%;\n            min-height: 15vh;\n            padding: 5%;\n            display: flex;\n            align-items: flex-start;\n            justify-content: center;\n\n        }\n\n        .search-bar{\n            width: 70%;\n            max-width: 400px;\n            background: rgba(255,255,255,0.2);\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            border-radius: 30px;\n            padding: 10px;\n            backdrop-filter: blur(4px) saturate(180%);\n        }\n\n        .search-bar input{\n            background: transparent;\n            flex: 1;\n            border: 0;\n            outline: none;\n            padding: 10px 20px;\n            font-size: 14px;\n            color: #cac7ff;\n        }\n\n        ::placeholder{\n            color: #cac7ff;\n        }\n\n        .search-bar button img{\n            width: 20px;\n\n        }\n\n        .search-bar button{\n            border: 0;\n            border-radius: 50%;\n            width: 40px;\n            height: 40px;\n            background: #58629b;\n            cursor: pointer;\n        }\n        \n        .google-image{\n            width: 30px;\n            height: 30px;\n            margin-right: 10px;\n            order: -1;\n        }\n    </style>\n    <meta name=\"viewport\" content=\"\"width=device-width, initial-scale=\"1.0\">\n    <title> Search Bar</title>\n</head>\n<body>\n<div class=\"container\">\n    <form action=\"https://google.com/search\" method=\"get\" class=\"search-bar\">\n        <input type=\"text\" placeholder=\" \" name=\"q\">\n        <button type=\"submit\"><img src=\"icons/search.png\"></button>\n        <img src=\"icons/google.png\" alt=\"Image\" class=\"google-image\">\n    </form>\n</div>\n</body>\n"
> > >           },
> > >           "id": "0_1235_embed"
> > >         },
> > >       ],
> > >       "filteredItems": []
> > >     }
> > > ```
> > 
> > 
> > wow thank you so much, i will try that tomorrow and report back :)
> 
> Sorry to trouble you again.
> 
> I tried it today am i´m really having troubles getting it to work. I am very new to yaml and i keep getting errors that seem to be related to formatting issues.
> 
> Could you post an example on how you integrated in your yaml?
> 
> Thanks in advance :)

Sure here you go:
````
- name: Google Search
    icon: hl-google
    displayData:
      sortBy: default
      rows: 1
      cols: 2
      collapsed: false
      hideForGuests: false
    widgets:
      - type: embed
        options:
          html: |
            <head>
                <style>
                    .container{
                        width: 100%;
                        min-height: 15vh;
                        padding: 5%;
                        display: flex;
                        align-items: flex-start;
                        justify-content: center;

                    }

                    .search-bar{
                        width: 70%;
                        max-width: 400px;
                        background: rgba(255,255,255,0.2);
                        display: flex;
                        align-items: center;
                        justify-content: center;
                        border-radius: 30px;
                        padding: 10px;
                        backdrop-filter: blur(4px) saturate(180%);
                    }

                    .search-bar input{
                        background: transparent;
                        flex: 1;
                        border: 0;
                        outline: none;
                        padding: 10px 20px;
                        font-size: 14px;
                        color: #cac7ff;
                    }

                    ::placeholder{
                        color: #cac7ff;
                    }

                    .search-bar button img{
                        width: 20px;

                    }

                    .search-bar button{
                        border: 0;
                        border-radius: 50%;
                        width: 40px;
                        height: 40px;
                        background: #58629b;
                        cursor: pointer;
                    }

                    .google-image{
                        width: 30px;
                        height: 30px;
                        margin-right: 10px;
                        order: -1;
                    }
                </style>
                <meta name="viewport" content=""width=device-width, initial-scale="1.0">
                <title> Search Bar</title>
            </head>
            <body>
            <div class="container">
                <form action="https://google.com/search" method="get" class="search-bar">
                    <input type="text" placeholder=" " name="q">
                    <button type="submit"><img src="icons/search.png"></button>
                    <img src="icons/google.png" alt="Image" class="google-image">
                </form>
            </div>
            </body>
        id: 0_1235_embed
````

**Comment by lzsix** [comment]
@CrazyWolf13 thanks for the fast reply. got it running now :)

but everytime i try to type something in it it types in the dashy integrated search bar. when i copy somethin in it it works though.

**Comment by CrazyWolf13** [comment]
> @CrazyWolf13 thanks for the fast reply. got it running now :)
> 
> but everytime i try to type something in it it types in the dashy integrated search bar. when i copy somethin in it it works though.

Great!
I compledtely disabled the search bar in settings.

**Comment by lzsix** [comment]
> > @CrazyWolf13 thanks for the fast reply. got it running now :)
> > but everytime i try to type something in it it types in the dashy integrated search bar. when i copy somethin in it it works though.
> 
> Great! I compledtely disabled the search bar in settings.

that explains it. Thanks again :)

**Comment by CrazyWolf13** [comment]
> > > @CrazyWolf13 thanks for the fast reply. got it running now :)
> > > but everytime i try to type something in it it types in the dashy integrated search bar. when i copy somethin in it it works though.
> > 
> > Great! I compledtely disabled the search bar in settings.
> 
> that explains it. Thanks again :)

Sure no problem, but I forgot to mention, there is an icon you are missing

**Comment by CrazyWolf13** [comment]
![google](https://github.com/Lissy93/dashy/assets/96661824/b99f756c-7186-4b2f-9680-59124b443428)
Copy this on the icons folder next to the conf.yml

**Comment by lzsix** [comment]
> ![google](https://private-user-images.githubusercontent.com/96661824/289386127-b99f756c-7186-4b2f-9680-59124b443428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDkwODIsIm5iZiI6MTcwMjI0ODc4MiwicGF0aCI6Ii85NjY2MTgyNC8yODkzODYxMjctYjk5Zjc1NmMtNzE4Ni00YjJmLTk2ODAtNTkxMjRiNDQzNDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDIyNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYmE4YjA3OTEyY2U3ODdhN2Y4YzYzYTU3OTA0OTM3OTEzOWQwODliYmYwYzIyODg2NmI2NmYzN2NhNzZkZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.icgfD0SlrYe8pb3L9SNEgWWuGOX8-7oO8J4-R0QL1ks) Copy this on the icons folder next to the conf.yml

thanks :)
