### ISSUE TITLE
[BUG] Display issue

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#118]
Hello,

I currently have two concerns, 

1- when I click on the "Update Configuration" key, the page that appears is white, you have to choose a menu to have a display! Is it not possible to have the Configuration menu displayed directly by default?

![2021-08-04 22_38_57-Window](https://user-images.githubusercontent.com/45015615/128251771-eb5695d3-3fb5-4aa3-b30a-9d250bb9c4ad.png)

![2021-08-04 22_38_48-Window](https://user-images.githubusercontent.com/45015615/128251760-6173108d-8b29-4d8f-9fbe-dd7c9f7e7549.png)

2 - The "backup-note" does not move when you scroll, so it stays in front of the menus.

![2021-08-04 22_36_00-Window](https://user-images.githubusercontent.com/45015615/128252151-f423fffb-5a57-438e-8d30-b8b650d0fe59.png)

![2021-08-04 22_36_10-Window](https://user-images.githubusercontent.com/45015615/128252170-c7b8cab7-39e8-4209-ab31-ab099d154575.png)

I'm use Firefox, Dashy 1.5.1

Thx

**Comment by Lissy93** [comment]
Thank you- both of those do appear to be bugs. I will work on a fix for them both tomorrow evening :)
I've seen the blank page in the config menu before, but it then disappeared for me, and I have been unable to recreate it since. Did you do anything specific in order for it to be triggered?

**Comment by EVOTk** [comment]
> Did you do anything specific in order for it to be triggered?
On my installation, it is present all the time now when I open the menu (but I will not say since when).
Whether with Firefox or Chrome (up to date), and even if I have emptied my cache / history, the bug is still present.

I have a simple use of Dashy, nothing exotic: one user, some services, and healtcheck.

In the console, I have no error when I open the page, but when I leave the page I have this:
```
TypeError: e is undefined
    findIndexTab vue-material-tabs.esm.js:992
    findIndexTab vue-material-tabs.esm.js:992
    activeTabItem vue-material-tabs.esm.js:949
    disableTabItem vue-material-tabs.esm.js:961
    unRegister vue-material-tabs.esm.js:916
    beforeDestroy vue-material-tabs.esm.js:1097
    VueJS 31
    startTransitionLeave index.js:1
    close index.js:1
    toggle index.js:1
    onOverlayClick index.js:1
    click index.js:1
    VueJS 22
    startTransitionEnter index.js:1
    open index.js:1
    VueJS 9
    open index.js:1
    toggle index.js:1
    onToggle index.js:1
    VueJS 2
    show index.js:1
    show index.js:1
    showEditor ConfigContainer.vue:176
vue.runtime.esm.js:1897:12
    VueJS 34
    startTransitionLeave index.js:1
    close index.js:1
    toggle index.js:1
    onOverlayClick index.js:1
    click index.js:1
    VueJS 22
    startTransitionEnter index.js:1
    open index.js:1
    VueJS 9
    open index.js:1
    toggle index.js:1
    onToggle index.js:1
    VueJS 2
    show index.js:1
    show index.js:1
    showEditor ConfigContainer.vue:176
```

J'ai

**Comment by Lissy93** [comment]
That info was really helpful, found the issue and will merge it, along with the fix for the backup-note positioning, as part of #121 in V1.5.3 soon :)

**Comment by EVOTk** [comment]
Works great for me! Thank you
