### ISSUE TITLE
[BUG] Theme selection box text overflow

### ISSUE THREAD

**Issue by UrekD** [Lissy93/dashy#119]
Longer named themes overflow the selection box. Noticed when updated to latest version of docker image, which is a bit behind 1.4.5. 
![image](https://user-images.githubusercontent.com/38784343/128260585-7b46767c-5889-468d-a967-7a15c76a2666.png)

**Comment by Lissy93** [comment]
Thanks for raising this, I will get this fixed this evening

**Comment by Lissy93** [comment]
Thanks for raising this, fixed in d8ae1dc1a6d174e365deb047fe351d34ad01e40a which was merged as part of #121 in `Dashy V 1.5.3`. Do let me know if you come across any other issues :)
