### ISSUE TITLE
[QUESTION] Not sure how to overwrite Accept header for health checks?

### ISSUE THREAD

**Issue by masterjg** [Lissy93/dashy#1195]
### Question

Right now health checks do not pass for **Vaultwarden**

![image](https://github.com/Lissy93/dashy/assets/11464772/8a81dd28-76a0-4561-9dba-1abfdd67319c)

Tried to debug the health check via:
`curl 'https://dashy.local/status-check/?&url=https%3A%2F%2Fvaultwarden.local' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: https://dashy.local/' -H 'Cookie: dashyAuthToken=xxx' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-GPC: 1' -H 'TE: trailers'`

This resulted in the same error that was in the browser.
`{"successStatus":false,"message":"❌ Service Unavailable: vaultwarden.local resulted in ENOTFOUND (-3008)"}`

Then what I did was trying to reduce the number of headers that are sent and found out that if I change the `Accept` header from `application/json, text/plain, */*` to just `*/*` I would get to the Dashy HTML page instead of status.

Anyone used healtchchecks on Vaultwarden?

### Category

App Usage

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Technicatgor** [comment]
same issue here, I set Access-Control-Allow-Origin * problem still there
