### ISSUE TITLE
[FEATURE_REQUEST] Catppuccin theme

### ISSUE THREAD

**Issue by JMans15** [Lissy93/dashy#1199]
### Is your feature request related to a problem? If so, please describe.

I'm using the catppuccin (Mocha/Latte) theme for everything in my life and Dashy is kind of the only thing that I haven't catppuccined yet, but I'm really bad at designing things :')

### Describe the solution you'd like

It would be nice to have catppuccin themes among the default ones, I'm using Nord-frost for now so it would be even nicer to have a similar layout

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Maybe

**Comment by jasoncrevier** [comment]
Forgive me as I'm not super familiar with Github yet -- hoping a comment will re-open this.

I also want a catppuccin theme, and I can probably take a crack at it when I have some time to dig through the code.

If there's any resources for themes that someone can point me to, that would be helpful :)

**Comment by jschenke488** [comment]
I've created a request in Catppuccin's repo https://github.com/catppuccin/catppuccin/discussions/2191
