### ISSUE TITLE
[QUESTION] PiHole Widget Does not Work

### ISSUE THREAD

**Issue by marcolino7** [Lissy93/dashy#1203]
### Question

Hi,
I am runnind Dashy 2.1.1 on Docker and PiHole Pi-hole v5.17- FTL v5.23 - Web Interface v5.20.1

When I add PiHole Stats Widget I got this:
![image](https://github.com/Lissy93/dashy/assets/11460036/84117610-984b-4d8c-9663-d624015bc932)

No error in Dashy logs in Docker's container logs, perhaps logs level is not set properly.
How can I procede with Troubleshoot?

Many Thanks

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Could you pop open the browser console, and share the outut?

https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console

**Comment by marcolino7** [comment]
Hi,
it is a CORS issue, but I added in my reverse proxy Access-Control-Allow-Origin *

`Access to XMLHttpRequest at 'http://pihole.xxxxxxx.me/admin/api.php?summary&auth=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' from origin 'http://192.168.x.x:8089' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

All URL are HTTP

Thanks

**Comment by Lissy93** [comment]
So that's a CORS error, take a look here for how to solve: **[Troubleshooting - Fixing Wiget CORS Errors](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#widget-cors-errors)**

**Comment by marcolino7** [comment]
Another question,
If i click on Refresh icon of the widget, I got this error in the console logs:

`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at e.value (http://192.168.x.x:8089/js/chunk-50f31ec3.f351de1e.js:1:41997)
    at e.value (http://192.168.x.x:8089/js/chunk-50f31ec3.f351de1e.js:1:41517)
    at ResizeObserver.boundDrawFn (http://192.168.1.3:8089/js/chunk-50f31ec3.f351de1e.js:1:40370)
value @ frappe-charts.min.esm.js:1
value @ frappe-charts.min.esm.js:1
boundDrawFn @ frappe-charts.min.esm.js:1`

and graph disappear:

![image](https://github.com/Lissy93/dashy/assets/11460036/f1ab83c4-24b0-46d4-8c3c-a82ecaec0b85)

**Comment by Lissy93** [comment]
Hmm, now that one is an error. Weirdly it seems to work okay for me, but I'll look into it.
Btw you can also have widgets [continuously update](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#continuous-updates) when new data comes in, by setting like `updateInterval: 6` (although I guess you'll have the same bug here)

**Comment by marcolino7** [comment]
@Lissy93 continuously update is working fine

Marco
