### ISSUE TITLE
[FEATURE_REQUEST] Allow iframe apps to write to the clipboard.

### ISSUE THREAD

**Issue by DavidFuchs** [Lissy93/dashy#1207]
<h3 dir="auto">Is your feature request related to a problem? If so, please describe.</h3>
<p dir="auto">Some of the items I have in Dashy are little convenience tools, such as <a href="https://github.com/CorentinTh/it-tools">https://github.com/CorentinTh/it-tools</a>. IT Tools, for example, has text fields with a little copy-to-clipboard button next to them. Unfortunately, these copy buttons are prevented from working when the target app is run inside an iframe (workspace or modal).</p>
<h3 dir="auto">Describe the solution you'd like</h3>
<p dir="auto">I read that iframes require permissions such as <a href="https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard" rel="nofollow">clipboard-read and clipboard-write</a> via something called the <a href="https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API" rel="nofollow">Permissions API</a>.</p>
<p dir="auto">Unfortunately, it appears that this is considered experimental, and is not supported by all browsers (e.g. Firefox, Safari): <a href="https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility" rel="nofollow">https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API#browser_compatibility</a></p>
<p dir="auto">I tried anyway - I forked the codebase and modified <code class="notranslate">IframeModal.vue</code> so that instead of using <code class="notranslate">allow="fullscreen"</code> it used <code class="notranslate">allow="fullscreen; clipboard-write *;"</code>. While this prevented errors in the console that I previously got when attempting to copy to clipboard, the copy operation still did not succeed.</p>
<p dir="auto">It's possible this is not a solvable problem. Clipboard permissions get pretty locked down for security reasons, and it can be difficult to get around that kind of stuff. So if it's closed for that reason, that's fine, but someone smarter than me might have a solution, so I thought I'd get a feature request in either way.</p>
<h3 dir="auto">Priority</h3>
<p dir="auto">Low (Nice-to-have)</p>
<h3 dir="auto">Is this something you would be keen to implement</h3>
<p dir="auto">Maybe</p>

<blockquote>                    <img src="https://opengraph.githubassets.com/d26f05c6bd66ea66f3eb7bfffb4722f04143c8b3def6a0832806bf7a3ce1e701/CorentinTh/it-tools" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/CorentinTh/it-tools">GitHub - CorentinTh/it-tools: Collection of handy online tools for developers, with great UX.</a>                      </strong>        </div>                    <div>Collection of handy online tools for developers, with great UX.  - GitHub - CorentinTh/it-tools: Collection of handy online tools for developers, with great UX.</div>                      </blockquote><blockquote>                    <img src="https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png" width="48" align="right" />                          <div>          <strong>                          <a href="https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API">Permissions API - Web APIs | MDN</a>                      </strong>        </div>                    <div>The Permissions API provides a consistent programmatic way to query the status of API permissions attributed to the current context. For example, the Permissions API can be used to determine if permission to access a particular API has been granted or denied.</div>                      </blockquote>

**Comment by Lissy93** [comment]
Hiya David,

I've taken a look into this, and have had quite mixed results.

With updating the permissions in `allow` I was able to get a simple HTML page using the clipboard API to copy to clipboard within an iframe, using Chromium. I've submitted a PR for this in #1221

But for it-tool specifically, looks like they're [using](https://github.com/CorentinTh/it-tools/blob/main/src/composable/copy.ts)  the [vueuse `useClipboard`](https://github.com/vueuse/vueuse/blob/main/packages/core/useClipboard/index.ts), which is doing a lot of extra checks. I wasn't able to get this to work.

Also both the parent (Dashy) and the child ( in your case, it-tools) will need to be served via a valid HTTPS, as clipboard API is [only available](https://stackoverflow.com/a/71876238/979052) via secure origin

If neither of those work, then unfortunately I don't think it's going to be possible :(
