### ISSUE TITLE
[QUESTION] Cannot figure out how to add widgets, my config is in JSON, docs are in YAML

### ISSUE THREAD

**Issue by ajtatum** [Lissy93/dashy#1211]
### Question

So, I tried adding the following code below to one of my sections via the edit config feature, but it doesn't persist or work.

`      "widgets": [
        {
          "type": "weather",
          "options": {
            "apiKey": "xxxx",
            "city": "Fairfax, VA",
            "units": "imperial",
            "hideDetails": false
          },
          "updateInterval": 3600
        }
      ],`

I have that within "sections" after "items".

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by jmpinney** [comment]
I have a similar issue, but not with widgets - I've been trying to enable authentication in my config, I write the config file, it rebuilds the app, and then it doesn't persist.

Also the config file is in JSON instead of YAML, not sure what is up with that. Using the docker-compose file provided in the repo along with:

docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by CrazyWolf13** [comment]
> ### Question
> So, I tried adding the following code below to one of my sections via the edit config feature, but it doesn't persist or work.
> 
> ` "widgets": [ { "type": "weather", "options": { "apiKey": "xxxx", "city": "Fairfax, VA", "units": "imperial", "hideDetails": false }, "updateInterval": 3600 } ],`
> 
> I have that within "sections" after "items".
> 
> ### Category
> Widgets
> 
> ### Please tick the boxes
> * [x]  You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
> * [x]  You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> * [x]  You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
> * [x]  You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

I highly suggest using the yml config file or vs code server to edit the config the simply reboot the container, at best with portainer, may I ask how you set up the container?

**Comment by CrazyWolf13** [comment]
> I have a similar issue, but not with widgets - I've been trying to enable authentication in my config, I write the config file, it rebuilds the app, and then it doesn't persist.
> 
> Also the config file is in JSON instead of YAML, not sure what is up with that. Using the docker-compose file provided in the repo along with:
> 
> docker-compose version 1.27.4, build 40524192 docker-py version: 4.3.1 CPython version: 3.7.7 OpenSSL version: OpenSSL 1.1.0l 10 Sep 2019

Have you already tried editing the config through terminal? then it's plain yml and much easier, and I suggest asking either in discussions or make a separate issue, otherwise it will get a mess here.
