### ISSUE TITLE
[QUESTION] Cant get local images working

### ISSUE THREAD

**Issue by shawndamon** [Lissy93/dashy#1213]
### Question

When I was creating using docker compose I mapped conf and images to my host machine. The conf file is definitely working and it keeps updating .
![Screenshot_20230605-222907](https://github.com/Lissy93/dashy/assets/31374940/e83ebc83-e810-45f0-8245-5ff46aa3aaf4)

I have a local images directory but I can't get it to work. I even used an existing example... wondering if you could help... Ps I cleared my cache and also cntrl + f5

![Screenshot_20230605-222812](https://github.com/Lissy93/dashy/assets/31374940/77276f37-1103-48b8-ad70-e80aa615f9a6)

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Where you'd got `/app/public/item-icons/icons` it should just be `/app/public/item-icons`
Alternatively, just update the icon value to `icons/maltrail.png`

And where you've got `icon: maltrail.png` (that's YAML), in the UI you just need `maltrail.png`

**Comment by shawndamon** [comment]
thank you for your comments and wanted to confirm my understanding.

1) i should have configured my Path in Container to /app/public/item-icons if i do this then i just need to set "maltrail.png" in the ICON input field on the ui

2) Since i have already configured it to /app/public/item-icons/icons just set "icons/maltrail.png"
![image](https://github.com/Lissy93/dashy/assets/31374940/893be95d-2e4f-46b3-91d1-7f4fbea935f5)

I think i didnt map the folders the right way? because i downloaded using git and the repository has sub folders
![image](https://github.com/Lissy93/dashy/assets/31374940/93b0bf33-fa4a-4bce-be5c-ef94ec32603e)

![image](https://github.com/Lissy93/dashy/assets/31374940/fe85ebd9-99cc-4329-a6d5-6d5dc32ab533)

**Comment by Lissy93** [comment]
Yup, that should be exactly right, but let me know if you still have issues :)
