### ISSUE TITLE
[QUESTION] Additional Configuration for PWA?

### ISSUE THREAD

**Issue by Typhonragewind** [Lissy93/dashy#1215]
### Question

Hi! 

I'll start by saying this is the absolute best dashboard i've used, congrats!

I currently have it on a dedicated subdomain (using the SWAG reverse-proxy), using the latest official docker image and for some reason the "Install PWA" option in Chrome does not appear like in the demo site.
Am I doing something wrong? Does it require any special configuration?

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hmm, that's weird, let me look into that...
If you go to `[your-dashy-url]/manifest.json` - do you see the default manifest? 

Most browsers should pick it up automatically, but I'm pushing an update out in #1219 - once that's merged, try re-pulling and giving it another go

There's also some criteria your browser might enforce before an app is installable
- [Chrome PWA Install Ctrteria](https://web.dev/install-criteria/#criteria)
- [Firefox PWA Install Ctrteria](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Installable_PWAs#requirements)
- [Opera PWA Install Criteria](https://dev.opera.com/articles/installable-web-apps/)

**Comment by Typhonragewind** [comment]
I have actually been investigating more deeply. It seems that it was Authentik blocking the manifest dues to a CORS issue, which is weird by itself, since it doesn't block the manifest of Tandoor. This issue also arises with Vikunja.

For now I got around it by whitelisting the manifest url in Authentik.
