### ISSUE TITLE
[BUG] Hide settings button overlapping text

### ISSUE THREAD

**Issue by UrekD** [Lissy93/dashy#123]
The button to hide the settings overlaps with the last char in config label as pictured below. Thanks for the hard work :)
![image](https://user-images.githubusercontent.com/38784343/128431761-ac753c22-9667-48b0-b1f7-b288ba663f19.png)
![image](https://user-images.githubusercontent.com/38784343/128431843-2cb6e1f6-44a7-470d-bf87-f32cbb3e1e7d.png)

**Comment by Lissy93** [comment]
Thanks for raising this, I've fixed it in #129 :)
