### ISSUE TITLE
[BUG] pageInfo.title not working

### ISSUE THREAD

**Issue by mfnalex** [Lissy93/dashy#1234]
### Environment

Self-Hosted (Docker)

### Version

2.1.1

### Describe the problem

In the website's <title> tag (and hence in the browser's window/tab title, etc), it always says "Dashy", regardless of the setting configured in pageInfo.title.

The page itself however shows the correct title in the header.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by PoProstuWitold** [comment]
I'm also experiencing this issue running Dashy using Docker.

**Comment by guyoverhere** [comment]
I'm also experiencing this issue. Looks like this was an issue in 2.0.4 (https://github.com/Lissy93/dashy/discussions/562) but it was fixed. Now it's back, at least for me on 2.1.1 running in docker (24.02).

**Comment by alexunderboots** [comment]
can't change:
title-description

**Comment by PoProstuWitold** [comment]
Some progress fixing that?

**Comment by PoProstuWitold** [comment]
> Anybody has a workaround for this?

Unfortunately no

**Comment by CrazyWolf13** [comment]
This is a know issue, we are currently working on this, for a termporary fix, just manually trigger a rebuild 
![image](https://github.com/Lissy93/dashy/assets/96661824/0255ecb0-623d-4aab-a365-43954d4813c6)

**Comment by CrazyWolf13** [comment]
Hi
This problems seems to be related to dashy not automatically rebuilding on changes, see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.
