### ISSUE TITLE
[BUG] date.getHour inside html embed widget not working

### ISSUE THREAD

**Issue by CrazyWolf13** [Lissy93/dashy#1238]
### Environment

Self-Hosted (Docker)

### System

RaspberryPi OS 32Bit

### Version

2.1.1 (latest from docker)

### Describe the problem

using this code below creates a wonderful time widget if opened via browser, but dashy does not display any digits, my guess that the date.getHour ... don't work. 

```      <style>
         * {
            margin: 0;
            padding: 0;
            font-family: 'Poppins', sans-serif;
         }


         html, body {
            display: grid;
            height: 100%;
            place-items: center;
         }

         .wrapper {
            height: 100px;
            width: 360px;
            position: relative;
            cursor: default;
         }

         .wrapper .display,
         .wrapper span {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
         }

         .wrapper .display {
            z-index: 999;
            height: 85px;
            width: 345px;
            background: #1b1b1b77;
            border-radius: 6px;
            text-align: center;
         }

         .display #time {
            line-height: 85px;
            color: #fff;
            font-size: 50px;
            font-weight: 600;
         }
      </style>
   </head>
   <body>
      <div class="wrapper">
         <div class="display">
            <div id="time"></div>
         </div>
      </div>
      <script>
         setInterval(() => {
            const time = document.querySelector(".display #time");
            let date = new Date();
            let hours = date.getHours();
            let minutes = date.getMinutes();
            let seconds = date.getSeconds();
            if(seconds < 10){
             seconds = "0" + seconds;
           }
           if(minutes < 10){
             minutes = "0" + minutes;
           }
           if(hours < 10){
             hours = "0" + hours;
           }
            time.textContent = hours + ":" + minutes + ":" + seconds;
         });
      </script>
   </body>```

### Additional info

_No response_

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
No this is still a problem....

**Comment by Lissy93** [comment]
Heya @CrazyWolf13 

I think this is a JS issue with the code you've got.


I got it working with the below snippet.

But since the code in your ticket got cut-off, I to to (try to) re-create it:  https://jsfiddle.net/lissy93/djrcvyw8/

<br />

<img src="https://github.com/Lissy93/dashy/assets/1862727/611dcb7f-667f-4cf5-acaf-452e54b10c89" width="280" align="right" />

```yaml
sections:
- name: CrazyWolf13 Timer Section
  widgets:
  - type: iframe
    options:
      url: https://t1m3.netlify.app
```

<br />


[![Edit t1m3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/t1m3-ql8mnl?file=%2Findex.html)


Let me know if that helps :)

**Comment by CrazyWolf13** [comment]
> Heya @CrazyWolf13
> 
> I think this is a JS issue with the code you've got.
> 
> I got it working with the below snippet.
> 
> But since the code in your ticket got cut-off, I had to (try to) re-create it: https://jsfiddle.net/lissy93/djrcvyw8/
> 
> 
> <img alt="" width="280" src="https://private-user-images.githubusercontent.com/1862727/293524027-611dcb7f-667f-4cf5-acaf-452e54b10c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTA1MjIsIm5iZiI6MTcwNDExMDIyMiwicGF0aCI6Ii8xODYyNzI3LzI5MzUyNDAyNy02MTFkY2I3Zi02NjdmLTRjZjUtYWNhZi00NTJlNTRiMTBjODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTE1NzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzIzMmExM2M0ODEyMzg4YzhiNjEyODRkOGQ3ZjBkMGJlYWE5MTViMWUwMmQ3YzkwZTAxZTAwZTNmMmE5YWUzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v_AJW2dCJ5xmEMwO-ZKuT8uwtBze5htWSCBrR9Sbc7M">
> ```yaml
> sections:
> - name: CrazyWolf13 Timer Section
>   widgets:
>   - type: iframe
>     options:
>       url: https://t1m3.netlify.app
> ```
> 
> 
> [![Edit t1m3](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/p/sandbox/t1m3-ql8mnl?file=%2Findex.html)
> 
> Let me know if that helps :)

Huge thanks for this !

I think the problem was that I used html embed instead of an iframe. Because with your js code the html embed is also not working.

Got it working, huge thanks! ❤️
