### ISSUE TITLE
[BUG] Config editor "Code" mouse click inaccuracy 

### ISSUE THREAD

**Issue by UrekD** [Lissy93/dashy#124]
When trying to edit the config via web settings "Edit config" in type "Code" mouse click and the cursor position don't match 99% of the time, making it really hard to edit code fast and effectively. See GIFs below. Tested in Edge, Firefox (outdated), Brave and Chrome.

![WdkW7NmDWF](https://user-images.githubusercontent.com/38784343/128434081-6bbec5dd-3ff2-4e25-b0ad-31622a0c6b4b.gif)
![ptAaWnuq6f](https://user-images.githubusercontent.com/38784343/128434083-d20d83ca-0ad4-40aa-b044-077fffa85d7b.gif)

**Comment by Inrego** [comment]
I'm not sure if my issue is related. But for me, it's way worse. The caret is showing a few characters to the left of where it actually is. It worsens the longer the line is.

Example:
![image](https://user-images.githubusercontent.com/2242329/129148215-0008a959-42c8-4f7e-bebf-39d7733a5254.png)
This is the last position of this line. Tapping right arrow on my keyboard will move the caret to next line. Typing anything will add characters after that last comma.

I'm using Microsoft Edge. and have confirmed same issue on Chrome (both are Chromium browsers, so it makes sense)

**Comment by UrekD** [comment]
@Inrego yeah it's the same issue. It's as bad as you describe as you suggest it might be due to longer lines as in the 2nd gif at the end you can see when I double click I believe "Supermicro" you see it's offset by quite a few characters.

**Comment by Lissy93** [comment]
This is indeed an issue, although I've not been able to fix it so far. I will leave this issue open, and if either of you feel like submitting a PR for it, that would be awesome :)

**Comment by UrekD** [comment]
Should still be relevant. Thanks for the hard work :)

**Comment by UrekD** [comment]
Playing around with inspect element I think I found the issue, it seems to be the font it gets from css class html .jsoneditor * instead of the correct one from .ace-jsoneditor *, deactivating the font from .jsoneditor * fixed it, see below for refference.

![image](https://user-images.githubusercontent.com/38784343/139603164-ec093972-c2e2-446d-ba28-db4f670d65dc.png)

**Comment by Lissy93** [comment]
Thank you so much @UrekD for fixing this, nice work! 🙌🥳
PR #315 is now merged and available on DockerHub and changes visible in the dev environment: [dev.dashy.to](https://dev.dashy.to/)

There's also a new config editor, merged in #298, and released in [V 1.9.0](https://github.com/Lissy93/dashy/releases/tag/1.9.0), which doesn't require you to write JSON anymore, and may be helpful to some of you.
