### ISSUE TITLE
Issue regarding widget weather and Pi-Hole

### ISSUE THREAD

**Issue by luro611** [Lissy93/dashy#1246]
### Question

I have a problem with widgets. I use weather and it works. With the same settings weather-forecast doesn't work.
There is only a message "An error occurred, see the logs for more info. Unable to fetch data". Dashy is installed in a LXC-container in Proxmox by using docker and portainer. The log in portioner did not show anything. The same issue with Pi-hole! pi-hole-stats works and  piholestats produce the same message "An error occurred, see the logs for more info. Unable to fetch data".
Proxmox 8.0.3, LXC-container with Debian 12, Docker and Portainer current version.
I would be very happy about an idea. 

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by shad-lp** [comment]
Same problem here, I can ping the hostname used for Pi-hole recent traffic widget, and the apiKey is the right one, nothing in the logs.
