### ISSUE TITLE
[BUG] Some icons from simpleicon not working

### ISSUE THREAD

**Issue by masterchief4240** [Lissy93/dashy#1254]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 22.04.2 LTS

### Version

2.1.1

### Describe the problem

When using some of the simpleicons, icons are not loading correctly. Sorry if I am just being stupid, I did read the documentation and tried a few things.

Working example: Vodafone icon https://simpleicons.org/?q=vodafone

![image](https://github.com/Lissy93/dashy/assets/75056191/e5c2a498-0507-4edf-a1e7-a3be18979bee)

![image](https://github.com/Lissy93/dashy/assets/75056191/e4c59fdf-c694-4886-ba36-f6bb18b93998)

Code looks like this

"icon": "si-vodafone"

Non-working example (should hopefully be reproducible): Mikrotik https://simpleicons.org/?q=mikrotik

![image](https://github.com/Lissy93/dashy/assets/75056191/f87c5ae3-e90b-447a-82b8-2e71ce7eb610)

![image](https://github.com/Lissy93/dashy/assets/75056191/8ed2b6c6-3584-46e1-b5a7-15fafe2b556c)

Code looks like this

"icon": "si-mikrotik"

When placing the svg URL https://simpleicons.org/icons/mikrotik.svg in the field, it works, but it is not adjusting the color (which I guess is strange because it's working for the vodafone one).

![image](https://github.com/Lissy93/dashy/assets/75056191/32dbdee7-124d-49a2-b4a2-061095e6d731)

Many thanks!

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by KonVei82** [comment]
I am having exactly the same issue but with si-nginxproxymanager

**Comment by Fiallo** [comment]
![Screenshot 2023-08-03 130520](https://github.com/Lissy93/dashy/assets/13345085/109a519e-f0ab-4c6c-b118-bbd39add01bc)
![Screenshot 2023-08-03 130438](https://github.com/Lissy93/dashy/assets/13345085/f167a42e-99bf-4055-ae67-c7486ab8643b)
I wish I knew enough about coding to help with fixing this, but I'm also having this issue.

**Comment by Jwluker** [comment]
I'm having the same issue as well

**Comment by crumpsandmuffin** [comment]
Hello,

I am having the same issue with the following icons.

Proton Drive:
si-protondrive

Proton Calendar
si-protoncalendar

![image](https://github.com/Lissy93/dashy/assets/90122011/b299113c-5cbc-4a9b-9f07-7df0e9ca6410)

Strangely si-protonmail works. 
I did notice that on the simple Icons page the Proton Mail is titled as "ProtonMail" where as drive and calendar are "Proton Drive" and "Proton Calendar".
Perhaps the space has something to do with it but I don't know how this all works.

**Comment by wlmqpsc** [comment]
Same problem here!

I found dashy is still using old version simple-icons package. I think it is the reason which cause this problem.

in [yarn.lock row 8926](https://github.com/Lissy93/dashy/blob/master/yarn.lock#L8926C1-L8926C1) you can found it using v7.19.0

current new version is here [npmjs.com](https://www.npmjs.com/package/simple-icons/v/10.0.0?activeTab=readme) and the [repo](https://github.com/simple-icons/simple-icons)

**Comment by barndoor101** [comment]
Any updates on this? Or is there a way we can update locally? Cheers
