### ISSUE TITLE
[BUG] gl-current-cpu and gl-current-mem percentages not aligning on Safari

### ISSUE THREAD

**Issue by tmulle** [Lissy93/dashy#1255]
### Environment

Self-Hosted (Docker)

### Version

2.1.1

### Describe the problem

The percentage values displayed on both graphs are not centered when viewing on Safari on MacOS.
They appear fine when running FireFox.

Firefox
<img width="462" alt="Screenshot 2023-07-10 at 1 25 29 PM" src="https://github.com/Lissy93/dashy/assets/5183186/3a78d03d-b662-45ee-be6c-e189e515266b">

Safari
<img width="462" alt="Screenshot 2023-07-10 at 1 25 14 PM" src="https://github.com/Lissy93/dashy/assets/5183186/39244710-6909-464d-964f-0c43116bdb73">

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
@Lissy93 This can probably be closed? You commited a fix?

**Comment by Lissy93** [comment]
I _think_ I committed a fix for this, along with some other Safari bugs. But I'm not an Apple user, so testing on Safari isn't easy.

OP, if you're still seeing this issue, let me know, and I'll re-open.

**Comment by CrazyWolf13** [comment]
> Sorry for not testing myself, remembered, I had an iPad lying around. Quickly tested and sadly still not working, exactly as the screenshot above. But I think we can still keep this closed, as it i

If you need anything or testing, I'm happy to assist. :)
