### ISSUE TITLE
[QUESTION] Limit the number of items shown in Glance widgets

### ISSUE THREAD

**Issue by notthebee** [Lissy93/dashy#1256]
<h3 dir="auto">Question</h3>
<p dir="auto">I've set up Dashy on my home server, and so far, I really like it.</p>
<p dir="auto">I'm trying to build a dashboard based on your System Monitor dashboard – <a href="https://dashy.to/docs/showcase/#system-monitor" rel="nofollow">https://dashy.to/docs/showcase/#system-monitor</a> . However, since I have a bit more drives, the dashboard ends up looking like this:</p>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/30384331/252464438-7bff0863-3445-4984-a388-0032b2757574.png"><img width="399" alt="Screenshot 2023-07-10 at 21 31 49" src="https://user-images.githubusercontent.com/30384331/252464438-7bff0863-3445-4984-a388-0032b2757574.png" style="max-width: 100%;"></a>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/30384331/252464455-23df8781-1b56-4b5f-88a6-3ffa5ee6a78c.png"><img width="399" alt="Screenshot 2023-07-10 at 21 31 31" src="https://user-images.githubusercontent.com/30384331/252464455-23df8781-1b56-4b5f-88a6-3ffa5ee6a78c.png" style="max-width: 100%;"></a>
<p dir="auto">Is it possible to select which drives/mounts to display?<br>
I've looked at the documentation and the code but unfortunately couldn't find a parameter that would control the elements displayed in Dashy.</p>
<h3 dir="auto">Category</h3>
<p dir="auto">Widgets</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">question hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                                <div>          <strong>                          <a href="https://dashy.to/docs/showcase">*Dashy Showcase* 🌟 | Dashy</a>                      </strong>        </div>                    <div>| 💗 Got a sweet dashboard? Submit it to the showcase! 👉 See How |</div>                      </blockquote>

**Comment by pminiszewski** [comment]
In my case I was able to filter out unwanted devices using glances config file.
```
# cat /etc/glances/glances.conf
[fs]
hide=/dev/loop.*
```
This may not be ideal if you want to filter drives only in dashy.

**Comment by mr-f0xx** [comment]
How to fix this? It's annoying

**Comment by CrazyWolf13** [comment]
Check out #1333 for a guide on how to fix this.
