### ISSUE TITLE
[BUG] Scrolling in mobile constantly brings up edit menu on icons/items.

### ISSUE THREAD

**Issue by redge76** [Lissy93/dashy#1261]
### Environment

Self-Hosted (Docker)

### System

Docker running on an Ubuntu system

### Version

latest

### Describe the problem

When scrolling up and down in mobile view you have to put your finger on the items or icons to scroll. When you do so it bring up the context menu for that item. This is extremely annoying and makes the dashboard painful to use because then I have to click to dismiss the context menu before I click an item on my dashboard.
This is duplicate of #1135 (already closed)

### Additional info

This issue can be easly reproduced using the dev tools in chrome.
1) Open a dashy instance
2) Start dev tools
3) Switch to a mobile browser simulation with the device toolbar (ctrl + shift + M)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by redge76** [comment]
v1.9.2 running on https://live.dashy.to/ of https://demo.dashy.to/ is not impacted by this bug. 
v2.1.1 running on https://dev.dashy.to/ is impacted.

I guess it is related to the longpress detection in file LongPress.js. It seems that this code does not take in account the possibility of a "touch/drag" gesture. It only check le lenght the screen is touched without verifying if the touch location has moved.

Sorry but I have no skill with nodejs and I can't correct this myself.

**Comment by redge76** [comment]
The best workaround I found is to disable the context menu altogether.
edit mode -> edit app config -> Disable Context Menus
These context menu are not mandatory and at least dashy is usable on a mobile.

**Comment by shall0pass** [comment]
I have this same issue.  It would be nice if we could only disable the context menus on small screens that are more likely to have touch interfaces.

**Comment by redge76** [comment]
Issue is still relevant.

**Comment by mooglestiltzkin** [comment]
i solved the context issue by disabling it. like others pointed out, why not disable for small screens as a default? surely i am not the only one having scrolling issues cauzing pop ups. Sure the simple solution is to turn it off. but at least mention that in the setup guide for mobile users.

**Comment by mainTAP** [comment]
Is it possible to disable the context menus for the mobile device only ? I've tried to "save locally" but when I refresh the window it re-enables the context menus again. Thank you

**Comment by 986244073** [comment]
Issue is still relevant.

**Comment by CrazyWolf13** [comment]
still relevant

**Comment by ddenev** [comment]
@Lissy93, any chance you review and eventually merge the fix I provided?
The issue is relly annoying on a mobile device 🙂
Thank you in advance!
