### ISSUE TITLE
[QUESTION] <What am I missing/doing wrong in the Pi Hole Stats widget>

### ISSUE THREAD

**Issue by DINU03** [Lissy93/dashy#1267]
### Question
Unable to fetch the data from pi-hole

I have added useProxy: true in conf.yml still getting error 

**An error occurred, see the logs for more info.
Got success, but found no results, possible authorization error**

![pihole-dashy](https://github.com/Lissy93/dashy/assets/97852410/5e46bddc-9a73-4937-b858-6bc8002bc754)

Let me know how to resolve the issue,

Thanks,

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by DINU03** [comment]
There is no support from anyone ?

**Comment by DINU03** [comment]
?????????????????????????????? looks like this project is dead ?

**Comment by Lissy93** [comment]
Without more details, it's hard to know.
Could you share the relevant parts of your config, as well as the response from the browser console ([here's how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console), if you're unsure). There's also [a section](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#widget-errors) in the troubleshooting guide, which will show you how to get more info.

**Comment by DINU03** [comment]
- name: Pi-Hole Stats
  icon: hl-pihole
  widgets:
  - type: pi-hole-stats
    useProxy: true
  options:
    hostname: http://192.168.80.100
    apiKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Do I need to add this and where ?

Access-Control-Allow-Origin: https://url-of-dashy.local
or
Access-Control-Allow-Origin: *

**Comment by DINU03** [comment]
Pls ignore the reqeust, I had configurational issue in the code, I have reviewed and rectified.

Thanks,

**Comment by Lissy93** [comment]
Glad you got it sorted :)

**Comment by Lissy93** [comment]
If you could share your solution, it may help others who face similar issues in the future.
