### ISSUE TITLE
[FEATURE_REQUEST] Add option to forward cookies during status checks

### ISSUE THREAD

**Issue by j-waters** [Lissy93/dashy#1269]
### Is your feature request related to a problem? If so, please describe.

I have most of my services behind Authelia, so every status check results in `401 unauthorized`. It would be great if the status check endpoint forwarded the `Cookies` header when making calls to other services.

### Describe the solution you'd like

A generic solution would be to add an option like `statusCheckForwardHeaders`, which would accept a list of headers to forward from the status check request. It would be great if that option could be defined per-service or globally.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Maybe

**Comment by themedleb** [comment]
No work around other than not using Authelia?

**Comment by Lissy93** [comment]
Yeah, I can add this. Do you want the option to allow for forwarding user-defined cookies, or specific cookies from the current sesh?

**Comment by lissy93** [comment]
I know this has been a long while, apologies for the delay.
My concern with implementing this is the security - it's not good practice to be sending x-domain cookies like this, and I'm concerned about them being handled in Dashy and forwarded on.

Your best option is to use the existing `statusCheckHeaders`. And if that doesn't work for you, then set `statusCheckUrl` to something accessible from within your network or a unauthenticated health endpoint. OR handle this in your proxy, to give Dashy access to what it needs.
