### ISSUE TITLE
[BUG] Popup modal doesn't work in multipage mode

### ISSUE THREAD

**Issue by ThinkSalat** [Lissy93/dashy#1274]
### Environment

Self-Hosted (Docker)

### System

DSM 7.2-64570 Update 3, Docker version 20.10.23, build 876964a,  Chrome 114

### Version

2.1.1

### Describe the problem

In mutli page mode, after switching page, the pop up modals do not work.

1. Create multiple pages
2.  Open Dashy and switch to a different page using the navigation header
3. try to open popup modal - nothing will happen and console will show an error:

`TypeError: Cannot read properties of undefined (reading 'show')
    at o.triggerModal (Section.vue:216:1)
    at Kt (vue.runtime.esm.js:2988:30)`

### Additional info

![sidekick_VwOUU6fCmk](https://github.com/Lissy93/dashy/assets/31082405/1450977e-2211-4b95-a192-16e749c1fb91)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by cyrus104** [comment]
Is there any way we can reopen this? I have pretty much the exact same setup and modal does not work!!!

I can right click and open in any way BUT modal.
