### ISSUE TITLE
Status check doesn't work on branch firewall 

### ISSUE THREAD

**Issue by zaromarco** [Lissy93/dashy#1280]
### Environment

Self-Hosted (Docker)

### System

docker on synology nas 20.10.23

### Version

2.1.1

### Describe the problem

i added 4 fortinet firewall , one in the main site and 3 on the branch sites , the one in the main site status check works good , the other 3 reply with service error 404 not found.
i have tried to ssh into nas and run as root ping command to each of these firewall and the reply was ok 
let me know
regards 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by zaromarco** [comment]
@Lissy93 do you have any news?

**Comment by CrazyWolf13** [comment]
> @Lissy93 do you have any news?

Please do NOT ping Lissy.

Sadly neither I nor Lissy can't do much here, without having additional information. 
Firewalls can't pretty easily mess up the connection, did you check dashy's host /container can reach all those domains/ip's you configured for the firewalls?

Can you move all firewalls to the main page and test if that works?

**Comment by zaromarco** [comment]
hi , i already solved the problem when recently i changed the firewall with new model from fortinet.
from my point of view some http or https service from many device reply in different mode and dashy ping check is not able to report green light
