### ISSUE TITLE
[BUG] Icons, getting it wrong

### ISSUE THREAD

**Issue by Nivin37** [Lissy93/dashy#1288]
### Environment

Self-Hosted (Docker)

### System

CASA OS V0.4.4.1

### Version

2.2.1

### Describe the problem

When I add an icon name and I get it wrong, after saving the Item you get to see the broken icon symbol.

However when I then go back to fix the broken icon, I can never fix it.
I have tried to incert the correct name, remove all reference and save, use another correct icon name, all fail.
The only way I have found to fix this issue is to remove the item and start again.

My current build is on CASA OS, however I did have the same issue with a previous build I did on a Debian VM.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by TKinslayer** [comment]
I do have the same problem, actually. 
I would also add the fact that plenty of icons (even when I seem to get them right on the first) do not « work » - I get a broken icon. No icons from font awesome works, actually. I can make some icons work from SimpleIcon or others.

I can’t say the problems don’t come from me, though… (I mean… I’m very new to Dashy and I may do something wrong). But that bug sure looks like what I’m experiencing. 

On a side note, great, great, great app !

**Comment by PooreOne** [comment]
I also experience this. I've seen the icon work, then break, and I could then never get an icon to show again using local or hosted icons like dashboard-icons. Switching to favicon I saw the exact behavior again where notifiarr icon worked, then broke and never came back.

**Comment by Taverius** [comment]
This is absolutely still a thing that happens, and the solution is to recreate the docker image.

Looks like you're caching the remote icons locally, and so long as you're switching between valid icons it works. If you put in something which yields no icon, like a fontawesome you don't have access to, and swap back, that also works.

But if you ever end up with the broken icon icon, that never gets cleared from the cache.

What's the location in question so I can clear it, either by mounting it with a bind and wiping when needed, or with a quick rm inside the docker?
