### ISSUE TITLE
[BUG] Default instructions do not work as written

### ISSUE THREAD

**Issue by desrod** [Lissy93/dashy#1308]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 22.04, Jammy Jellyfish

### Version

git master (4786020741e11b8) 

### Describe the problem

1. `git clone https://github.com/Lissy93/dashy.git`
2. `cd dashy`
3. `yarn build` 

Fail. There is no yarn build files or configuration in the default master branch, in `dashy` or any subdirectory of the project, despite several references in the documentation that this is how it should be built. Documentation out of date? Repository missing development files?  

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Could you share the full output?

**Comment by Lissy93** [comment]
> "There is no yarn build files or configuration in the default master branch, in dashy or any subdirectory of the project, despite several references in the documentation that this is how it should be built"

Yarn doesn't need a configuration file, it's just packaging the dependencies listed in the package.json.

Are you sure you've got the per-requisites installed? And double check that this isn't a duplicate of #1

**Comment by desrod** [comment]
@Lissy93 Indeed [this](https://github.com/Lissy93/dashy/issues/1#issuecomment-841686309) was the issue completely. Ironically, I should know that, since I work for the company that produces this OS! 

I manged to push my way through with the default latest docker image and got all of the pieces working that I think I need. Now I just need to dot in all of the missing services and figure out why the columnar layout leaves large gaps. 

Thanks for the quick response!

**Comment by desrod** [comment]
Marking as closed.

**Comment by Lissy93** [comment]
Glad you got it working! :)
