### ISSUE TITLE
[BUG] Can't get weather forecast or the public holidays widgets to work

### ISSUE THREAD

**Issue by t3dium** [Lissy93/dashy#1321]
### Environment

Self-Hosted (Docker)

### System

Dietpi, docker 24.0.6, tried viewing dashy from brave & firefox

### Version

2.1.1

### Describe the problem

Pic of config file:

![image](https://github.com/Lissy93/dashy/assets/83690012/f78597d5-452d-481c-8bde-2796e2055285)

Pic of error:

![image](https://github.com/Lissy93/dashy/assets/83690012/bf7fb9ce-904d-4684-acec-fe5a8717a9bd)

Pic of console:

![image](https://github.com/Lissy93/dashy/assets/83690012/a40dd64b-a13f-41df-8f66-aaa3f4967737)

When troubleshooting i visited https://api.openweathermap.org/data/2.5/weather?q=London&appid=<my-api-key> and the page worked, so my api key is correct. Also under the editor > edit app config i ticked "use proxy for all widgets", but the issue still persists.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by sachahjkl** [comment]
bump, should I make a merge request ? this is a pretty simple fix

**Comment by Lissy93** [comment]
Do you know which endpoint it needs to use? If you're able to submit a PR, that'd be awesome - otherwise I'll try and find time to get it done this weekend
