### ISSUE TITLE
[FEATURE_REQUEST] Move conf.yml to its own folder

### ISSUE THREAD

**Issue by BlindBadgerStudios** [Lissy93/dashy#1322]
### Is your feature request related to a problem? If so, please describe.

Not related to a problem per-se, but related to the inability to map to a NFS volume (which must be a directory).  The instructions map a specific file, which is not an option when using NFS volumes in docker compose.  Moving it to a separate directory allows that directory to be mapped just for the conf file, rather than risking having to copy all the other files as well.

### Describe the solution you'd like

Code updated to look for and leverage a conf.yml file in a separate directory (Ex. /app/public/conf)

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

None

**Comment by joshbuker** [comment]
This exact problem has been frustrating with trying to use Dashy in a docker swarm setup. :sweat_smile:

**Comment by joshbuker** [comment]
Related: #693

**Comment by jordiboehme** [comment]
This issue is also preventing me from using dashy.

**Comment by Glitch3dPenguin** [comment]
I would also like to see this implemented for in-place upgrades.

**Comment by Soccerbeats** [comment]
@bajo Seems to have a solution that looks like it would be easily added.

> I opened PR #1393 to address this feature request. Feel free to test an report back any issues in the PR.

The main reason for me that this would be helpful is in docker, you can create a volume that prevents the conf.yml from being updated when I pull for and update to the app. Hence, you would not need to do a backup/restore every time you update Dashy.
This would be AWESOME! :)

**Comment by CrazyWolf13** [comment]
Hi
This should now be fixed within the new V3 release of dashy, take a look here https://github.com/Lissy93/dashy/discussions/1537 and here https://github.com/Lissy93/dashy/discussions/1529

Keep in mind V3 has breaking changes, update the volumes and the port accordingly.
