### ISSUE TITLE
[BUG] Statuscheck Time-Out

### ISSUE THREAD

**Issue by FuckingToasters** [Lissy93/dashy#1323]
### Environment

Self-Hosted (Docker)

### System

Firefox (Latest)

### Version

2.1.1

### Describe the problem

When adding Statuscheck on Domains, which are clearly online. it always result in timeout.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Bademeister9** [comment]
Kannst du mir mal deine **/app/public/conf.yml** senden?

**Comment by CrazyWolf13** [comment]
> ### Environment
> 
> Self-Hosted (Docker)
> 
> ### System
> 
> Firefox (Latest)
> 
> ### Version
> 
> 2.1.1
> 
> ### Describe the problem
> 
> When adding Statuscheck on Domains, which are clearly online. it always result in timeout.
> 
> ### Additional info
> 
> _No response_
> 
> ### Please tick the boxes
> 
> - [X] You have explained the issue clearly, and included all relevant info
> - [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
> - [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> - [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
> - [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

Hi does the problem persist?
Can you share your conf.yml?

**Comment by CrazyWolf13** [comment]
@Lissy93 Probably stale can't reproduce. 

Guess this can be closed?

**Comment by FuckingToasters** [comment]
I haven't used dashy in a while and also switched the container host, I can deploy the dashy container with the same config on my new host tomorrow and see if the issue persists and then five an update here.
