### ISSUE TITLE
Format pages and section sizes

### ISSUE THREAD

**Issue by LarryT8959** [Lissy93/dashy#1329]
### Question

Are there instructions anywhere on how to resized sections and items? Resize / reshape items? As I add more items, the built in options has the items too tight?
Thanks

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
> ### Question
> 
> Are there instructions anywhere on how to resized sections and items? Resize / reshape items? As I add more items, the built in options has the items too tight?
> Thanks
> 
> ### Category
> 
> Setup and Deployment
> 
> ### Please tick the boxes
> 
> - [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
> - [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> - [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
> - [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

I think a custom theme should do the trick, requires some CSS knowledge.

https://dashy.to/docs/theming/
