### ISSUE TITLE
gl-disk-space number of disk

### ISSUE THREAD

**Issue by LarryT8959** [Lissy93/dashy#1333]
### Question

First of all, I'm really impressed with dashy. I'm fairly new to this and building a pretty neat dashboard. One question regarding this gl-disk-space widget. Is it possible to limit the number of volumes shown? I just need the sum of them all?
<img width="502" alt="Screenshot 2023-09-27 at 7 12 56 PM" src="https://github.com/Lissy93/dashy/assets/81517389/5a7ec340-cf75-4521-b6e3-010d3881e2d4">

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Check out this: https://github.com/nicolargo/glances/issues/1429

And this: 
https://github.com/nicolargo/glances/issues/304

You can modify the config of your glances instance in glances.conf.
