### ISSUE TITLE
[BUG] Inconsistent styles and layout for emoji icons 

### ISSUE THREAD

**Issue by 4cello** [Lissy93/dashy#1340]
### Environment

Self-Hosted (Docker)

### System

Firefox 118/Chromium 117, Ubuntu 22.04

### Version

2.1.1

### Describe the problem

On my Ubuntu system, tiles that use some emoji icons are larger than tiles with other types of icons, and even other emoji icons.

As seen in the attached screenshot, `:printer:` and `:film_frames` have some extra bottom padding compared to the other emojis and hl-icons. They are also drawn in a different style.

When I copy the actual emoji into the configuration instead of using the shortcut, the emoji is displayed as expected (consistent size and style).

I haven't figured out what exactly it is that causes some emojis to behave that way, but so far all emojis I've found are from the [Unicode 7.0](https://emojipedia.org/unicode-7.0) list, but not all 7.0 emojis behave that way:
- `:monkey:` (6.0) and `:turkey:` (8.0) normal, `:chipmunk:` and `:dove_of_peace` (7.0) different
- Faces and Hands from 7.0 seem to be normal
- `:detective:` from 7.0 is weird, but `:golfer:` is normal

In Firefox, the "normal" emojis' `<i>` tag uses "Twemoji Mozilla" font, but the other ones use "Noto Sans Symbols2".

On my Android phone the emojis work as expected, but on my Windows PC (in Firefox), the emojis are displayed in the same monochrome style, but there is no extra padding at the bottom.

![2023-10-08_11-03](https://github.com/Lissy93/dashy/assets/32751308/7d9c791f-78bb-4324-aa01-be07231e41ac)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Fixed
