### ISSUE TITLE
[BUG] Search for items with cyrillic titles dosnt work

### ISSUE THREAD

**Issue by mrkhachaturov** [Lissy93/dashy#1343]
### Environment

Self-Hosted (Docker)

### System

Google chrome 117.0.5938.152,  Ubuntu 22.04.3 LTS , Docker 24.0.6

### Version

2.1.1 

### Describe the problem

After adding new items with cyrillic title, can`t search for them after. 
Seach with not cyrillic titles works normal. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
This should now be fixed, thanks Denior
