### ISSUE TITLE
Widget help please 

### ISSUE THREAD

**Issue by adm2k** [Lissy93/dashy#1348]
### Question

Just started using Dashy and seem to have an issue with the pi-hole widget. I have spent several hours researching and can't seem to resolve. I have checked and rechecked the Pi-Hole API and it is correct.

**Here is my config:**
widgets:
      - type: pi-hole-stats
        updateInterval: 60
        useProxy: true
        options:
          hostname: ip address of pi-hole servere/admin
          apiKey:  goes here...

**Error message:**
![image](https://github.com/Lissy93/dashy/assets/120423301/2a9f282e-9318-4759-bdbf-f274d51a0f88)

**From console:**
![image](https://github.com/Lissy93/dashy/assets/120423301/8b1e79f3-0a95-4969-81f1-6f68b3850425)

Any help is very much appreciated!

al...

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by adm2k** [comment]
Anyone?

**Comment by CrazyWolf13** [comment]
> Anyone?

Can you share the specific part or your full dashy config.yml?
Maybe replace things like api keys.
Which pi-hole version are you on? Not the new 6 beta right?

**Comment by adm2k** [comment]
Here is the "pi-hole" part of the config file whuch I shared originally:
widgets:
- type: pi-hole-stats
updateInterval: 60
useProxy: true
options:
hostname: xxx.xxx.xx.xx/admin
apiKey: xxxxxxxxxxxxxxxxxxxx

I have tried replacing the api key:

Pi-hole version 5.17.2

Thanks for your help!

**Comment by CrazyWolf13** [comment]
> Here is the "pi-hole" part of the config file whuch I shared originally:
> widgets:
> - type: pi-hole-stats
> updateInterval: 60
> useProxy: true
> options:
> hostname: xxx.xxx.xx.xx/admin
> apiKey: xxxxxxxxxxxxxxxxxxxx
> 
> I have tried replacing the api key:
> 
> Pi-hole version 5.17.2
> 
> Thanks for your help!

Can you test for me without proxy and then test with the hostname only being http://{ip}:{Port} without /admin, Because uncaught a could be due to the /a...

**Comment by adm2k** [comment]
I removed the /admin and still getting the same original error. Alson removing th /admin lands on the default Lightpd web page.

**Comment by adm2k** [comment]
I removed the proxy as well

also, for reference I tested in Heimdall using the same ip and api key and it works.

**Comment by CrazyWolf13** [comment]
> I removed the proxy as well
> 
> also, for reference I tested in Heimdall using the same ip and api key and it works. 

'''
- type: pi-hole-stats
        options:
          useProxy: true
          hostname: http://192.168.1.111:8080
          apiKey: xxxxxxx
        id: 0_622_piholestats
'''
For me the /admin was not neccessary.


I will look into pihole config to see if something there could cause this.

**Comment by CrazyWolf13** [comment]
> Here is the "pi-hole" part of the config file whuch I shared originally:
> widgets:
> - type: pi-hole-stats
> updateInterval: 60
> useProxy: true
> options:
> hostname: xxx.xxx.xx.xx/admin
> apiKey: xxxxxxxxxxxxxxxxxxxx
> 
> I have tried replacing the api key:
> 
> Pi-hole version 5.17.2
> 
> Thanks for your help!

Can you try exatly this hostname with http? :

http://{ip}:{port}

**Comment by adm2k** [comment]
I don't use a port to access PI-Hole. Just 192.168.86.xx/admin

**Comment by CrazyWolf13** [comment]
> I don't use a port to access PI-Hole. Just 192.168.86.xx/admin

Please share the following as files not just screenshots or pastes:
Your dashy conf.yml
and your dashy log

**Comment by Lissy93** [comment]
Because it's getting a 500 for the CORS proxy, I'm wondering if that endpoint isn't working in your instance. Have you tried manually calling the `/cors-proxy` with PostMan or something, to see if it's actually accessible? 

Depending on how you're running Dashy and Pi-Hole, you might not need to proxy the request for Pi-Hole widget (unless you've got a web server or something in front of Pi-Hole).

Can you provide details on your environment, and how are you running Dashy? (like Docker, bare metal, etc?).

Have you checked out the [Widget Errors](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#widget-errors) in the Troubleshooting guide?

And just to double-check, the API key you're using is the `WEBPASSWORD`  found in `/etc/pihole/setupVars.conf`, right?

**Comment by smetroid** [comment]
Not sure if it's the same problem I am having, but on my end the widget renders, however there is no data.  Looking at the code  I found that the `Target-URL` does not have the [summary and auth variables](https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/PiHoleStats.vue#L48).  I am not sure how they are supposed to be passed to cors-proxy.

Config:
```
 56   - name: Today
 57     icon: far fa-rocket
 58     widgets:
 59     - type: clock
 60       options:
 61         timeZone: America/********
 62         hideDate: false
 63         use12hour: true
 64     - type: pi-hole-stats
 65       updateInterval: 20
 66       useProxy: true
 67       options:
 68         hostname: http://192.168.***.***
 69         apiKey: ONE_RANDOM_TOKEN
```
![image](https://github.com/Lissy93/dashy/assets/1909699/77d6ff2f-4ede-4f58-940c-ca1fb95aaf08)

**Comment by Crayzei** [comment]
I'm having the same problem--is there a resolution for the pi-hole widgets?  Thanks.
