### ISSUE TITLE
should not have additional properties?

### ISSUE THREAD

**Issue by LarryT8959** [Lissy93/dashy#1357]
### Question

I've been adding to my dashboard for a little while now and noticed that I'm getting some errors on some of the widgets? "should not have additional properties" To get them to go away, I refresh the page. What can I do to fix this? I'm attaching several screen shots.
<img width="649" alt="Screenshot 2023-10-23 at 1 51 50 PM" src="https://github.com/Lissy93/dashy/assets/81517389/94bf0232-d5bc-4338-982c-0342eee2d7e6">
<img width="1569" alt="Screenshot 2023-10-23 at 1 44 05 PM" src="https://github.com/Lissy93/dashy/assets/81517389/303a929f-743c-4b92-bfda-5eb836e19cfe">
<img width="1676" alt="Screenshot 2023-10-23 at 1 43 46 PM" src="https://github.com/Lissy93/dashy/assets/81517389/e91c0f45-6fb2-4ff5-8997-9f5446177a80">

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrustyB** [comment]
Same issue.  I have tried deleting Filtered Properties and they just come back.

**Comment by LarryT8959** [comment]
Did you ever figure this out?

**Comment by CrazyWolf13** [comment]
Duplicate, please close this # 1361
