### ISSUE TITLE
Proposed inclusion in docs -- fixing Glances on Windows for Dashy widgets

### ISSUE THREAD

**Issue by KaiStarkk** [Lissy93/dashy#1372]
### Discussed in https://github.com/Lissy93/dashy/discussions/1371

<div type='discussions-op-text'>

<sup>Originally posted by **KaiStarkk** November  4, 2023</sup>
If running Glances on Windows, I highly recommend using the following startup options (can be set under 'arguments' in NSSM):

`--disable-plugin all --enable-plugin cpu,mem,diskio,ip,network,containers,quicklook,load,fs,alert -w`

Glances isn't extremely stable on Windows, so disabling all plugins that aren't used by Dashy widgets is a must.</div>

**Comment by CrazyWolf13** [comment]
Made a PR, Lissy will decide if she wants to add it to the docs or rather not.

https://github.com/Lissy93/dashy/pull/1456

**Comment by Lissy93** [comment]
Merged PR, closing ticket.
