### ISSUE TITLE
[BUG] Dashy new Container version "opening method" "modal" is faulty

### ISSUE THREAD

**Issue by Mimosinito** [Lissy93/dashy#1375]
![Bildschirmfoto_2023-11-08_15-16-47](https://github.com/Lissy93/dashy/assets/65483688/37f096a2-bf4c-4d7a-b3f4-0e720a493a3f)
### Environment

Self-Hosted (Docker)

### System

Firefox 119, XUbuntu 23.04, docker-ce 5:24.0.7-1~debian.11~bullseye

### Version

 Dashy Version 2.1.1  ✅ Aktuell 

### Describe the problem

Since last container update some entries with the opening method "modal" returns in the opening modal window a new dashy start screen. Some not.
Maybe the difference is, the entries have a in correct behavior don't get a complete website (html/header/body).  

You can test the behavior with https://wttr.in

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by numanair** [comment]
It seems to open several modals on top of each other. If you click to the side of them you will see.

**Comment by rokiden** [comment]
This merged pull request https://github.com/Lissy93/dashy/pull/1275 broke modals. Checked using bot's preview.

**Comment by UniqueName992** [comment]
> Pull request #1275 merged by [d2e4949](https://github.com/Lissy93/dashy/commit/d2e49494aeb5a55d20f90d73fb8c3eb3382736f9) broke modals. Checked using bot's preview.

I'm also experiencing this issue.
Manually editing the file `src/components/LinkItems/Section.vue` undoing the changes listed in the PR and rebuilding the application does workaround this issue for me, providing the expected modal behavior without opening multiple modals on top of one another.
