### ISSUE TITLE
[QUESTION] How to make healthcheck for Transmission show a green flag? 

### ISSUE THREAD

**Issue by rpgdev** [Lissy93/dashy#1380]
### Question

Currently I'm getting a red flag because the status check returns a "service error 401" I know I can add this code as an exception but is there a way to hit the real healthcheck for transmission? Everything is running locally. 

### Category

Status Checking

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by brotich** [comment]
![image](https://github.com/Lissy93/dashy/assets/23168146/3fc509ec-93fd-4b21-ae13-f10bf28a0a94)

@rpgdev set the service url to `http(s)://transmission.url` and set the status code to `401`

that way getting a 401 is considered a successful status check

**Comment by rpgdev** [comment]
@brotich I know that and put it in the issue, I wondering if there is a real healthcheck url to hit for transmission that Dashy understands.

**Comment by CrazyWolf13** [comment]
> @brotich I know that and put it in the issue, I wondering if there is a real healthcheck url to hit for transmission that Dashy understands.

That is a problem of Transmission, it needs auth, otherwise it returns 401 - unauthorized and as @brotich said you can just add 401 as an accepted code.
![image](https://github.com/Lissy93/dashy/assets/96661824/d1204de1-6c3e-4408-bf32-373ee9daa9fc)
This will then work without any problems as a real healthcheck.
