### ISSUE TITLE
[FEATURE_REQUEST] MaterialDesignIcons

### ISSUE THREAD

**Issue by ExXxtr3me** [Lissy93/dashy#139]
Would it be possible to support also MaterialDesignIcons (https://materialdesignicons.com) ?
Fontawesome is missing many icons for apps like Plex, Nginx, Jallyfin, Sonarr, Radarr aso.

**Comment by Lissy93** [comment]
Sure, this is a good idea. I was actually thinking about implementing support for [Simple Icons](https://simpleicons.org/), as they are light-weight SVGs with logos from a wide range of apps and services.

I will look into Material Design Icons, but their package is 200kb, and they don't seem to have an API, so I will have to see if there is method of implementing that won't have an impact on performance. Will take a look either this evening or tomorrow evening and get back to you here :)

**Comment by ExXxtr3me** [comment]
Awesome, thank you very much for considering it. Don´t know if it helps, but homeassistant supports them, maybe there is some way for you to look how they do it?

SimpleIcons look also nice. 👍

**Comment by Lissy93** [comment]
Hey @ExXxtr3me 
I've implemented support for your Material Design Icons in #141 - which when merged, will be released in V1.5.7, which you can pull down from DH with the `:latest` tag.

You can use it by setting `icon` to `mid-[name-of-icon]`, e.g. `icon: mdi-alien `

Enjoy :)

**Comment by Lissy93** [comment]
Merged. 
I forgot to say, that the icon package  is only loaded in if one or more of your items are using mdi icons. That's the same as font-awesome. So if you combine both FA and MDI icons, you might experience a hit in performance, so it's best to choose one or the other.
Btw, if you're enjoying the app, please consider Staring the repo. I _think_ it helps others find it :)

**Comment by ExXxtr3me** [comment]
Wow, that was fast. Thank you very much.
