### ISSUE TITLE
[BUG] should have required property 'sections '

### ISSUE THREAD

**Issue by AyaanMAG** [Lissy93/dashy#1396]
### Environment

Self-Hosted (Docker)

### System

Docker 24.0.7

### Version

2.1.1.

### Describe the problem

Can't add section, when clicking on update configuration and then edit config there is a warning sign next to config{1} and hovering over it there is written (should have required property 'sections ') in case there was an issue with docker i removed the container then the image and ran `docker run -d \
  -p 8080:80 \
  -v ~/my-conf.yml:/app/public/conf.yml \
  --name my-dashboard \
  --restart=always \
  lissy93/dashy:latest` 
again. This did not resolve it and i got the same issue again, running `docker exec -it [container-ID] yard validate-config` i see 
`yarn run v1.22.15
$ node services/config-validator

Checking config file against schema...

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Warning: 1 issue found in config file  
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1.  must be object 

Done in 0.38s.`

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
> ### Environment
> Self-Hosted (Docker)
> 
> ### System
> Docker 24.0.7
> 
> ### Version
> 2.1.1.
> 
> ### Describe the problem
> Can't add section, when clicking on update configuration and then edit config there is a warning sign next to config{1} and hovering over it there is written (should have required property 'sections ') in case there was an issue with docker i removed the container then the image and ran `docker run -d \ -p 8080:80 \ -v ~/my-conf.yml:/app/public/conf.yml \ --name my-dashboard \ --restart=always \ lissy93/dashy:latest` again. This did not resolve it and i got the same issue again, running `docker exec -it [container-ID] yard validate-config` i see `yarn run v1.22.15 $ node services/config-validator
> 
> Checking config file against schema...
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Warning: 1 issue found in config file ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> 1. must be object
> 
> Done in 0.38s.`
> 
> ### Additional info
> _No response_
> 
> ### Please tick the boxes
> * [x]  You have explained the issue clearly, and included all relevant info
> * [x]  You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
> * [x]  You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> * [x]  You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445)
> * [x]  You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

Seems like a problem with your config, why don't you share it:)

**Comment by AyaanMAG** [comment]
The issue is weird, when running the docker compose, delete the container that's made and then run the docker run command on the dashy docs website, the container made immediately and automatically after running the docker compose file is the problem, the issue does not occur in the container created with the run command
