### ISSUE TITLE
Possibility 

### ISSUE THREAD

**Issue by system-help-solution** [Lissy93/dashy#1399]
### Question

First of all, I liked the project, I'm Brazilian. I would like to know if it is possible to create a preloaded app store and add it to the PANEL. For example, let's say I wanted to use Dashy as a top installer and within it there is already a library (application store) where the user clicks and installs it, fulfilling the requirements This would be possible to create. If so, can you at least give me a glance?If so, I am willing to create a large app store contributing 100% of my time to the project, as I am a developer (amateur) it would be a commercial solution"I mean using it for my projects and sharing my knowledge and profits. My existing application ". As I'm not rich, it would be a way to help with the project in terms of knowledge, programming and financially. Thank you very much in advance, I await a response

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Can't fully understand what you mean, bu I understand You want to build some sort of Application Store and want to use dashy as the the UI.

I don't really know if that is practical for the backend, you could run a flask server for example and use http endpoints and input them into dashy, however that would get messy.

If you want to build a web-application store, I think Dashy is not ideal for this.

Dashy is a Dashboard software.

**Comment by Lissy93** [comment]
> I don't really know if that is practical for the backend, you could run a flask server for example and use http endpoints and input them into dashy, however that would get messy.
>
> If you want to build a web-application store, I think Dashy is not ideal for this.
>
> Dashy is a Dashboard software.

Agree with @CrazyWolf13 here
