### ISSUE TITLE
Dashy reaching out to google for favicons?

### ISSUE THREAD

**Issue by blaxer** [Lissy93/dashy#14]
First of all thank you for Dashy, so far I am really loving it! But...

I have been unable to get favicons to work properly for self-hosted (only locally available) sites and so in looking at the source I am seeing this for the img tag, I've replaced the domain=url for this posting...

img src="https://s2.googleusercontent.com/s2/favicons?domain=https://locallyhostedapp.mydomain.com" class="tile-icon medium "

This doesn't appear that it would function for self-hosted sites that are not avaialble externally and I would prefer that my self-hosted dashboard not reach out to google to display each icon, do I just have this wrong?

**Comment by Lissy93** [comment]
Sure, this is a really good point. Thanks for raising this, I'm very happy someone's using my project, I wasn't expecting that!

I really wasn't really comfortable using Google for favicons, but the issue I ran into is that websites often don't have their favicon reachable at example.com/favicon.ico, and there wasn't an efficient way (that I could think of) to figure out the path of their favicon.


So, currently it checks if the resource is a local IP and if so returns the local favicon if it exists (in [`ItemIcon.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/LinkItems/ItemIcon.vue#L52) L58), then uses Google's endpoint for all remote websites. I'm guessing that you've set up local domain names (?), and this is why the regex thinks it's an internet website, and tries to use Google's endpoint instead.

#### Future Fix
I've created a PR: #15 , that will fix this, by introducing a new property in the config file, letting the user set `appConfig.forceRootFavicon: true` to force favicon icons to always be fetched from the URL path, and not the Google API. However I am in two minds weather this is the neatest solution.

#### Current Workaround
In the meantime, a quick fix for you, would be to find the URL of your local services favison (something like `http://my-service.local/favicon.ico`), and paste that URL as the value for `icon`. Dashy will then fetch the icon from that web address, and there's no reason why that shouldn't work.

**Comment by blaxer** [comment]
Just me personally, I really like the idea that I would be able to set appConfig.forceRootFavicon: true and have Dashy never reach out (for anything really), but the current workaround works great for now thank you!

**Comment by Lissy93** [comment]
Heya, I've fixed this in #47
Under `appConfig` just add `faviconApi: local`, to prevent the use of any API for resolving favicons. They will instead be fetched from `https://you-domain.local/favicon.ico`. Sorry it took so long, thanks for your patience :)
