### ISSUE TITLE
[BUG] Status Check returns "EAI_again -3001" when using .local url instead of IP

### ISSUE THREAD

**Issue by bverkron** [Lissy93/dashy#1400]
### Environment

Self-Hosted (Docker)

### System

Docker (version TBD)

### Version

2.1.1

### Describe the problem

When I use the .local url for my Unraid server (http://unraid.local) the status check will briefly go grey and say "request timed out" before switching red with the error "EAI_again -3001"

Using the IP address works and I am able to access the Unraid ui via the .local url in my browser without issue. Using unraid.net (their public website) works so it seems to be something with the .local url specifically.

### Additional info

![image](https://github.com/Lissy93/dashy/assets/19174503/7f82c373-e980-4ca2-af5b-d30600d94e01)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by bverkron** [comment]
I've moved to https://github.com/gethomepage/homepage again. Much cleaner and more modern interface and much easier to modify. Dashy has just been way too buggy for me and awkward to modify. It seems to favour many methods of modification but none of them are that easy / stable.

**Comment by CrazyWolf13** [comment]
> I've moved to https://github.com/gethomepage/homepage again. Much cleaner and more modern interface and much easier to modify. Dashy has just been way too buggy for me and awkward to modify. It seems to favour many methods of modification but none of them are that easy / stable.
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/2ca03c4dd52d28c60f72b81e9fb38f3afce87d581c907fb338dff671139ea3a8/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f336165323037336166666530363136353339666236386462323664383966396662383066626132336330333239326363643363623930623937386365333261392f676574686f6d65706167652f686f6d6570616765">                                    **                          [GitHub - gethomepage/homepage: A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations.](https://github.com/gethomepage/homepage)                      **                            A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations. - GitHub - gethomepage/homepage: A highly customizable homepage (or startpage / appli...

sadly true, a total update via V3 is highly needed

**Comment by CrazyWolf13** [comment]
For me this works without problems.

However I had to set max-redirects.
![image](https://github.com/Lissy93/dashy/assets/96661824/3082ac7b-6320-48dc-afcb-6744293f54a2)

Also try with http://unraid.local

Have you set the dns server on the host?
Also make sure the host can access that url by running `nslookup unraid.local`

**Comment by rpgdev** [comment]
> For me this works without problems.
> 
> However I had to set max-redirects. ![image](https://private-user-images.githubusercontent.com/96661824/307111044-3082ac7b-6320-48dc-afcb-6744293f54a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NTE0ODksIm5iZiI6MTcyNDk1MTE4OSwicGF0aCI6Ii85NjY2MTgyNC8zMDcxMTEwNDQtMzA4MmFjN2ItNjMyMC00OGRjLWFmY2ItNjc0NDI5M2Y1NGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE3MDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1Njc1NTQ4MTExNGJkMWRlZDQ0OGIzYWE1Mjk0NjZiZmNhMDQyOWE1YmEwYTExZjg0NDFlZjNkMTlmODVkNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1raDp5txxS5i0c6aTaaMyF0ZVEGO-2OrSEScwS-aj8E)
> 
> Also try with http://unraid.local
> 
> Have you set the dns server on the host? Also make sure the host can access that url by running `nslookup unraid.local`

Worked for me too.
