### ISSUE TITLE
[BUG] Weather icons (and maybe others) missing from docker image

### ISSUE THREAD

**Issue by louisjg** [Lissy93/dashy#1401]
### Environment

Self-Hosted (Docker)

### Version

2.1.1

### Describe the problem

Am using the weather widget; all data appears fine except weather icon.  Digging around in the directories, it appears maybe some of the files didn't get rolled into the docker container?  Just a guess :-)  It could very well be something I did wrong on my end.

It also seems like the favicon isn't displaying when I load my page - may be related.

### Additional info

This is from the console of my dashy container.  Certain files from /public appear not to be in the container.

Here is the container I'm running:

<pre>
a59e0f05df579ad1c1f5a84085d0d40f2d00e0145b73b87961b3dff3c2a13a42
org.opencontainers.image.created 2023-01-01T22:08:32.916Z
org.opencontainers.image.revision 15d7e9936da4f26bd3585a9548bf92b2e502393f
</pre>

<pre>
/app # find . -name *.woff
/app # find . -name *weather*
./src/styles/weather-icons.scss
/app # find . -name *Weather*
./src/components/Widgets/WeatherForecast.vue
./src/components/Widgets/Weather.vue
/app # find . -name favicon.ico
./node_modules/@vue/cli-service/generator/template/public/favicon.ico
./node_modules/mobius1-selectr/docs/favicon.ico
/app # find . -name dashy-logo.png
/app # find . -name favicon*
./node_modules/@vue/cli-plugin-pwa/generator/template/public/img/icons/favicon-32x32.png
./node_modules/@vue/cli-plugin-pwa/generator/template/public/img/icons/favicon-16x16.png
./node_modules/@vue/cli-service/generator/template/public/favicon.ico
./node_modules/mobius1-selectr/docs/favicon.ico
/app # find . -name dashy-*
/app #
</pre>

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by TheRealGramdalf** [comment]
Did you by any chance mount `/host/path:/app/public` rather than `/host/path/to/conf.yml:/app/public/conf.yml`? This is the source of a whole bunch of weird interactions, see https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 for a full explanation

**Comment by CrazyWolf13** [comment]
> ### Environment
> Self-Hosted (Docker)
> 
> ### System
> _No response_
> 
> ### Version
> 2.1.1
> 
> ### Describe the problem
> Am using the weather widget; all data appears fine except weather icon. Digging around in the directories, it appears maybe some of the files didn't get rolled into the docker container? Just a guess :-) It could very well be something I did wrong on my end.
> 
> It also seems like the favicon isn't displaying when I load my page - may be related.
> 
> ### Additional info
> This is from the console of my dashy container. Certain files from /public appear not to be in the container.
> 
> Here is the container I'm running:
> 
> a59e0f05df579ad1c1f5a84085d0d40f2d00e0145b73b87961b3dff3c2a13a42
> org.opencontainers.image.created 2023-01-01T22:08:32.916Z
> org.opencontainers.image.revision 15d7e9936da4f26bd3585a9548bf92b2e502393f
> /app # find . -name *.woff
> /app # find . -name *weather*
> ./src/styles/weather-icons.scss
> /app # find . -name *Weather*
> ./src/components/Widgets/WeatherForecast.vue
> ./src/components/Widgets/Weather.vue
> /app # find . -name favicon.ico
> ./node_modules/@vue/cli-service/generator/template/public/favicon.ico
> ./node_modules/mobius1-selectr/docs/favicon.ico
> /app # find . -name dashy-logo.png
> /app # find . -name favicon*
> ./node_modules/@vue/cli-plugin-pwa/generator/template/public/img/icons/favicon-32x32.png
> ./node_modules/@vue/cli-plugin-pwa/generator/template/public/img/icons/favicon-16x16.png
> ./node_modules/@vue/cli-service/generator/template/public/favicon.ico
> ./node_modules/mobius1-selectr/docs/favicon.ico
> /app # find . -name dashy-*
> /app #
> ### Please tick the boxes
> * [x]  You have explained the issue clearly, and included all relevant info
> * [x]  You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
> * [x]  You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> * [x]  You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://camo.githubusercontent.com/2bc5b271f42662892ba3e33eab75759d06817af488d9599c3e8a6d08a43830d5/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445)
> * [x]  You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

You could try a recreation of the container and just insert the previously backed up config file.

**Comment by CrazyWolf13** [comment]
Have you tried a total recreation of the container and using the options like described here. 

https://dashy.to/docs/quick-start
