### ISSUE TITLE
[BUG] <title>modified config in the ui,resulting in an error in the configuration file

### ISSUE THREAD

**Issue by snbzy** [Lissy93/dashy#1403]
### Environment

Self-Hosted (Docker)

### Describe the problem

When I edit the configuration file in the UI and click Save to Profile, the configuration file will be modified to the wrong format, resulting in the inability to rebuild the application
![image](https://github.com/Lissy93/dashy/assets/45591547/500dc241-a7f0-4771-ab30-c1ef84b36180)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by snbzy** [comment]
I've fixed this, please see the image below.You only need to serialize and re-deserialize the configured objects to ensure that the configuration file is not garbled
![image](https://github.com/Lissy93/dashy/assets/45591547/3543c159-5509-4bb6-a786-3aeca83259da)

**Comment by CrazyWolf13** [comment]
Duplicate, please close this #1361

**Comment by CrazyWolf13** [comment]
Thanks for providing your screenshot and a possibly fix.
I'll look into this and if it can confirm, i'll push a fix.

Will keep you updated!

**Comment by CrazyWolf13** [comment]
Thanks, fix is pushed and approved: https://github.com/Lissy93/dashy/pull/1470
