### ISSUE TITLE
[BUG] no logs file output for broken widgets

### ISSUE THREAD

**Issue by Rob-bb** [Lissy93/dashy#1407]
### Environment

Self-Hosted (Docker)

### System

ubuntu 23.10 docker with traefik and glances

### Version

2.1.1

### Describe the problem

glances widgets fail and say 'see logs for more info' andthe logs contain nothing but this

`yarn run v1.22.15
$ node server
Checking config file against schema...
✔️ Config file is valid, no issues found
SSL Not Enabled: Public key not present
 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝
*******************************************************************************************
Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
*******************************************************************************************
Using Dashy V-2.1.1. Update Check Complete
✅ Dashy is Up-to-Date
`

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi is this still a problem?

Can you share you glances config and you dashy config?

**Comment by Lissy93** [comment]
Looks like you're looking at the wrong logs
Widgets are executed client-side, so you'll need to check your browser log (as opposed to the Docker logs).
[Here's how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) (TL;DR <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>)
