### ISSUE TITLE
[BUG] Public-IP widget doesn't load.

### ISSUE THREAD

**Issue by cyrus104** [Lissy93/dashy#1414]
### Environment

Self-Hosted (Docker)

### System

Synology DSM 7.2 Docker

### Version

2.1.1

### Describe the problem

I have a basic option of public-ip and I get the following error.

An error occurred, see the logs for more info.
Unable to fetch data
Retry
Flag (error image)

I see no errors in app info.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Can you share you conf.yml?

Does the dashy container have internet access or is behind any special firewalls?

**Comment by CrazyWolf13** [comment]
Can you share you browser console output?

https://dashy.to/docs/troubleshooting/#how-to-open-browser-console

**Comment by Lissy93** [comment]
> An error occurred, see the logs for more info.
> Unable to fetch data
> Retry
> Flag (error image)
> 
> I see no errors in app info.

That should actually be the browser logs, not the container logs. (see [here](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) for how to check it).

I've tested it out, and the widget seems to work okay, so I guess it's an issue with your config. If you want us to look into it, could you also share the relevant parts of your `conf.yml`?

IP widget is client-side, so the it shouldn't really make a difference where/how you're running Dashy, or what firewalls you have in place.
