### ISSUE TITLE
[QUESTION] <Icons began to load for a long time.>

### ISSUE THREAD

**Issue by mohapxuct** [Lissy93/dashy#1415]
### Question

The first week everything loaded quickly, then it took a long time to load, the server was not busy, the load was no more than 10%, the disk speed was 389.68 MB/sec(check by hdparm). Icons are loaded for 1-5 seconds. 90% of the icons are located locally. Restarting the container did not help.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Please share the follwoing:
Your dashy Log 
Your Hardware
Deployment type
How you installed dashy
Your config.
Thanks

**Comment by CrazyWolf13** [comment]
Can't recreate, no response from user.
