### ISSUE TITLE
[BUG] Some translate literals aren't applied

### ISSUE THREAD

**Issue by oka4shi** [Lissy93/dashy#1417]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.1</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">I found a issue, and I determined the cause of that. Could I make a pull request to fix this issue?</p>
<h2 dir="auto">Problem</h2>
<p dir="auto"><code class="notranslate">app-info.privacy-and-security-advice</code> and <code class="notranslate">app-info.privacy-and-security-advice-link</code> are not applied in App Info.</p>
<p dir="auto">This is the screenshot including the inadequacy. I marked the points with yellow lines.<br>
<a target="_blank" rel="noopener noreferrer" href="https://private-user-images.githubusercontent.com/67847553/292500785-f42369af-f608-4dce-9c96-aee40060c059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTQ1ODcsIm5iZiI6MTcwMzI1NDI4NywicGF0aCI6Ii82Nzg0NzU1My8yOTI1MDA3ODUtZjQyMzY5YWYtZjYwOC00ZGNlLTljOTYtYWVlNDAwNjBjMDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE0MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1Yjg4YzA0OTUxZWNhN2NiMzFjYTRmZjdlZGRhYTNiY2I2OTlmZjhhYWEyYzdmMjY0YTE3ZjcyNzVhZjE3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTkRI8ZCDLmo5L2km92Q6ITakW5bvF1A_X8cagO4paM"><img src="https://private-user-images.githubusercontent.com/67847553/292500785-f42369af-f608-4dce-9c96-aee40060c059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTQ1ODcsIm5iZiI6MTcwMzI1NDI4NywicGF0aCI6Ii82Nzg0NzU1My8yOTI1MDA3ODUtZjQyMzY5YWYtZjYwOC00ZGNlLTljOTYtYWVlNDAwNjBjMDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE0MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1Yjg4YzA0OTUxZWNhN2NiMzFjYTRmZjdlZGRhYTNiY2I2OTlmZjhhYWEyYzdmMjY0YTE3ZjcyNzVhZjE3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTkRI8ZCDLmo5L2km92Q6ITakW5bvF1A_X8cagO4paM" alt="Screenshot " style="max-width: 100%;"></a></p>
<h2 dir="auto">The Cause</h2>
<p dir="auto">The keys of translation files are wrong. This is a link to the incorrect part of the English translation file. The same problem also exists in the translation files for other languages.</p>
<p dir="auto"><a href="https://github.com/Lissy93/dashy/blob/40c9b41805ac67a33b27c669b48c0fa38d7f06dd/src/assets/locales/en.json#L66C14-L66C14">https://github.com/Lissy93/dashy/blob/40c9b41805ac67a33b27c669b48c0fa38d7f06dd/src/assets/locales/en.json#L66C14-L66C14</a></p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445"><img src="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445" alt="important" data-canonical-src="https://img.shields.io/badge/Important!-F6094E" style="max-width: 100%;"></a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/343078060/82f850a2-b1af-4e9f-9245-c92700d74856" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/Lissy93/dashy/blob/40c9b41805ac67a33b27c669b48c0fa38d7f06dd/src/assets/locales/en.json">dashy/src/assets/locales/en.json at 40c9b41805ac67a33b27c669b48c0fa38d7f06dd · Lissy93/dashy</a>                      </strong>        </div>                    <div>🚀 A self-hostable personal dashboard built for you. Includes status-checking, widgets, themes, icon packs, a UI editor and tons more! - Lissy93/dashy</div>                      </blockquote>

**Comment by CrazyWolf13** [comment]
> ### Environment
> Self-Hosted (Docker)
> 
> ### System
> _No response_
> 
> ### Version
> 2.1.1
> 
> ### Describe the problem
> I found a issue, and I determined the cause of that. Could I make a pull request to fix this issue?
> 
> ## Problem
> `app-info.privacy-and-security-advice` and `app-info.privacy-and-security-advice-link` are not applied in App Info.
> 
> This is the screenshot including the inadequacy. I marked the points with yellow lines. ![Screenshot ](https://private-user-images.githubusercontent.com/67847553/292500785-f42369af-f608-4dce-9c96-aee40060c059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTQ1ODcsIm5iZiI6MTcwMzI1NDI4NywicGF0aCI6Ii82Nzg0NzU1My8yOTI1MDA3ODUtZjQyMzY5YWYtZjYwOC00ZGNlLTljOTYtYWVlNDAwNjBjMDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDE0MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1Yjg4YzA0OTUxZWNhN2NiMzFjYTRmZjdlZGRhYTNiY2I2OTlmZjhhYWEyYzdmMjY0YTE3ZjcyNzVhZjE3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTkRI8ZCDLmo5L2km92Q6ITakW5bvF1A_X8cagO4paM)
> 
> ## The Cause
> The keys of translation files are wrong. This is a link to the incorrect part of the English translation file. The same problem also exists in the translation files for other languages.
> 
> https://github.com/Lissy93/dashy/blob/40c9b41805ac67a33b27c669b48c0fa38d7f06dd/src/assets/locales/en.json#L66C14-L66C14
> 
> ### Additional info
> _No response_
> 
> ### Please tick the boxes
> * You have explained the issue clearly, and included all relevant info
> * You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
> * You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> * You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445)
> * You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/343078060/82f850a2-b1af-4e9f-9245-c92700d74856">                                    **                          [dashy/src/assets/locales/en.json at 40c9b41805ac67a33b27c669b48c0fa38d7f06dd · Lissy93/dashy](https://github.com/Lissy93/dashy/blob/40c9b41805ac67a33b27c669b48c0fa38d7f06dd/src/assets/locales/en.json)                      **                            🚀 A self-hostable personal dashboard built for you. Includes status-checking, widgets, themes, icon packs, a UI editor and tons more! - Lissy93/dashy

I recommend creating a PR and Lissy93 is much more likely to see this, as she barely writes into issues in the last time as she is busy in private life.

**Comment by CrazyWolf13** [comment]
Created a PR #1471 will close this.

**Comment by CrazyWolf13** [comment]
Should be fixed now, once 2.1.2 will release the changes should take effect.

IF you want to preview it, build from source like described here:
https://github.com/Lissy93/dashy?tab=readme-ov-file#deploying-from-source-
