### ISSUE TITLE
[FEATURE_REQUEST] Auto-Fill credentials when opening a Dashy item

### ISSUE THREAD

**Issue by CenterfireXid** [Lissy93/dashy#1427]
### Is your feature request related to a problem? If so, please describe.

Because a lot of my items are self-hosted, the programs/services use the same IP address, just differentiated by the port when accessing them via web browser. Because of this, credentials can not be stored on the browser as browsers do not differentiate between services through the ports (ex: 123.123.1.123:1001 looks the same as 123.123.1.123:5005 to the browser, and thus autofills the same credentials to both).

### Describe the solution you'd like

Adding an option to pre-fill credentials on the Dashy side so that they are filled when opening the item would be useful. Having credentials filled per profile would be invaluable to security as well, but not needed. 

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by CrazyWolf13** [comment]
I cannot speak for Lissy but I guess this is way out of scope and not at all what Dashy is all about. Dashy is a Dashboard not a password manager.

 Why don't you consider using a reverse proxy? Then you could have like dashy.myserver, nas.myserver, webserver.myserver, whatever you like and there are plenty of guides on youtube.

**Comment by Lissy93** [comment]
Yeah, this wouldn't be physically possible to do from Dashy.
It'd need to be done through a browser extension - you're better of submitting a FR/PR to your password manager, adding the ability to differentiate between different hosts.

Or easier/better still as @CrazyWolf13 mentioned, setup a reverse proxy or use your DNS to configure custom local domains. That way your password manager would be able to auto-fill correctly.
