### ISSUE TITLE
[Bug] Problem with Modal when mutiple sections

### ISSUE THREAD

**Issue by insomnia417** [Lissy93/dashy#1430]
### Question

If there are multiple sections, when I use the target in modal mode and in the default view, multiple temporary pages will open at once, so I have to use workspace or minimal.

Only when there is one section, will one be opened normally,

Is this a normal phenomenon？

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi 
This seems to be a duplicate.

I will close this issue in favor of #1375

If you feel like this is no duplicate, just respond to this and I will reopen this.
