### ISSUE TITLE
Move section

### ISSUE THREAD

**Issue by jag5cof** [Lissy93/dashy#1431]
### Is your feature request related to a problem? If so, please describe.

I would like to move the section. I have tried to do this in the edit mode but my spacing gets out of place. I know an item can be moved if I'm in the edit move, the right click. The dialog box appears. This doesn't work on the section.

### Describe the solution you'd like

While in the edit mold, I would right click on on the section box.  When the move/copy dialog box open. Then select which option to use.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Maybe

**Comment by jag5cof** [comment]
Lissy,

I’m new with Dash. I will give star for your hard wok with Dash. I appreciated.

**Comment by CrazyWolf13** [comment]
Duplicate #1346

**Comment by drueppela** [comment]
https://github.com/Lissy93/dashy/issues/1346 was reopend.

@CrazyWolf13 : TNX :-)
