### ISSUE TITLE
[BUG] Emby status check does not work

### ISSUE THREAD

**Issue by yuriw** [Lissy93/dashy#1437]
### Environment

Self-Hosted (Bare Metal)

### System

Debian

### Version

12

### Describe the problem

Emby server returns -113 error on the status check when a service is up and running

### Additional info

![image](https://github.com/Lissy93/dashy/assets/3876474/9381a33d-eefe-4452-8958-0cb2787d763b)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by yuriw** [comment]
I tried different configurations, e.g http, https, local LAN and public.
All other services (proxmox, nginx, sonnar etc) work fine, except emby

**Comment by yuriw** [comment]
Emby the only service that does not report status check @Lissy93

**Comment by CrazyWolf13** [comment]
> Emby the only service that does not report status check @Lissy93

Hi
Please do NOT ping Lissy93. Or at least not for a service not being detected as online.

I quickly spun up emby and tested in dashy and it all worked fine for me.

![image](https://github.com/Lissy93/dashy/assets/96661824/1056f50c-d9f9-4f53-a3eb-8fd0b3927de2)
For the URL I used http://{ip}:8096
8096 as because it is the port that emby runs on, except you set this up differently.

This is a configuration issue on your side.

**Comment by Lissy93** [comment]
+1 to CrazyWolf's response, looks like a config error on your end. Have you seen this section of the troubleshooting  https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#status-checks-failing guide?
