### ISSUE TITLE
[QUESTION] Save to Disk failed, now Dashy won't load.

### ISSUE THREAD

**Issue by StuckInAWell** [Lissy93/dashy#1442]
### Question

The only error I get in console is "Error: Could not establish connection. Receiving end does not exist."

I changed a couple buttons to open in newtab instead of sametab, and then went to save to disk and rebuild the application, but while rebuilding, it seemed that my server completely locked up, and ever since, Dashy starts to load, and ends up at a "Possible Error, Check Logs" screen.

I can't seem to find any troubleshooting steps for this issue, and I'm not familiar enough with the configuration to troubleshoot it on my own.  I'm comfortable with resetting the config to default if that will fix it, but I'd need a quick rundown on how to do that...

Thank you!

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Have you deployed using docker?
Or how do you run dashy?

If you are on docker, you could try to recreate the container. If everything is set up correctly ans the conf.yml is mounted to a real path, if won't even reset dashy to defaults.
