### ISSUE TITLE
[QUESTION] How to set per-section/per-item config options?

### ISSUE THREAD

**Issue by bobbyl140** [Lissy93/dashy#1444]
### Question

I am noticing on the Dashy Showcase page, there are examples where some sections and/or some items are configured on a per-entity basis. The best example I can find is the "Dashy Live" example:
![10-dashy-live](https://github.com/Lissy93/dashy/assets/61990607/14a31ec0-ee20-48a1-8c00-b30c397188cb)
The sections are colored differently from each other, and some sections have small items whereas the others have medium items. 
For the coloring, I'd assume it has something to do with calling each section by class name in a custom theme, but I figured those class names are randomized. 
For the sizes of the icons, I don't know where to begin. How would I go about changing these?

### Category

Theming & Layout

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
I guess that was done using custom css and targetting sections instead of the whole page. But I can only guess.

Here is a Documentation:

https://dashy.to/docs/theming/

**Comment by Lissy93** [comment]
[Here's the config file used for that](https://gist.github.com/Lissy93/000f712a5ce98f212817d20bc16bab10#file-example-7-dashy-live-conf-yml)

I think it's `section[i].displayData` that you're looking for - [here's the docs](https://github.com/Lissy93/dashy/blob/HEAD/docs/configuring.md#sectiondisplaydata-optional) for that.

Example::

```yml
sections:
- name: Code Analysis & Monitoring
  icon: fas fa-code
  displayData:
    sortBy: default
    sectionLayout: grid
    itemCountX: 5
    cols: 2
  items:
    .....
```
