### ISSUE TITLE
[QUESTION] Question about Page

### ISSUE THREAD

**Issue by HumanG33k** [Lissy93/dashy#1448]
### Question

Can I from the docker version add page as the same way as the main page ? 
- Add page 
- Save page directly on the distant (docker) env 

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Yes, Exactly!

Here it's nocely explained.
https://github.com/Lissy93/dashy/discussions/1153

Here are some examples:
https://github.com/Lissy93/dashy/discussions/1153

**Comment by HumanG33k** [comment]
Can you show me the part about : Save page directly on the distant (docker) env 
It's not really clear for me thx.

**Comment by CrazyWolf13** [comment]
You could host some sort of web server to render that static yml file on the distant docker env, or you could make a github repo and host the file that way.

You could also make a small samba nas server and map that file inside your host to a path then bind that path to the docker container.

I suggest a quick google/youtube search depending on which way you choose. As explaining this here would be a bit out of scope.

There are plenty of good youtube tutorials
