### ISSUE TITLE
[QUESTION] Show result of curl request to TXT 

### ISSUE THREAD

**Issue by HumanG33k** [Lissy93/dashy#1449]
### Question

There is some pages (internet) that return simple raw TXT content. (for ie http://ipecho.net/plain )
There is a way to display that kind of  result ? 

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
```curl https://ipecho.net/plain``` returns the ip for me just fine.


Here I did it with js html and css, I think it would be best to create a jsfiddle account create a little widget with some html css as you like and just iframe it into dashy.

https://jsfiddle.net/CrazyWolf/qduzh524/4/

https://dashy.to/docs/widgets/#iframe-widget

Have fun :)

**Comment by HumanG33k** [comment]
Ok will try it as soon as i can.
