### ISSUE TITLE
Hi, I'm new here and I could really use some help

### ISSUE THREAD

**Issue by Mrfixitmattg** [Lissy93/dashy#1451]

**Comment by CrazyWolf13** [comment]
Hi
Welcome Here!

Have a look at the Readme for a nice summary of this awesome project.
https://github.com/Lissy93/dashy/blob/master/README.md

Here you can find all Documentations to dashy.
They are really well written. Lissy has invested great time into them and they are awesome.
https://dashy.to/docs/

Here you can find a Live Demo of the app you can play with.
https://demo.dashy.to/

Here are some examples on what beatiful dashboards others created with Dashy:
https://github.com/Lissy93/dashy/blob/master/docs/showcase.md


Have fun with Dashy!

Please close this Issue now as this is not related to an Issue at all.
