### ISSUE TITLE
[QUESTION] how to get widgets working when using nginxproxymanager

### ISSUE THREAD

**Issue by tinytempmouse** [Lissy93/dashy#1455]
### Question

Hi how do I get the widgets to work when using nginxproxymanager?
I've tried using useProxy but nothing changes

![Screenshot_20240202-195200_Cromite](https://github.com/Lissy93/dashy/assets/137355256/77058c7e-77a3-494e-9559-4bc02e815b71)

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
> ### Question
> Hi how do I get the widgets to work when using nginxproxymanager? I've tried using useProxy but nothing changes
> 
> ![Screenshot_20240202-195200_Cromite](https://private-user-images.githubusercontent.com/137355256/301956224-77058c7e-77a3-494e-9559-4bc02e815b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTEyMzksIm5iZiI6MTcwNjk1MDkzOSwicGF0aCI6Ii8xMzczNTUyNTYvMzAxOTU2MjI0LTc3MDU4YzdlLTc3YTMtNDk0ZS05NTU5LTRiYzAyZTgxNWI3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwOTAyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YmJhNzI4NDE1MjFiOTNiZGMxMTc3OTY5MTU5M2YzY2M0Y2JkNjVmMDExMWJkZGEzZmZmMmE4MmJkMTQ1NTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zByhv2looaZmk_vhlGmORjzl_-Rw-7DKqr4Q88qcVsQ)
> 
> ### Category
> Setup and Deployment
> 
> ### Please tick the boxes
> * [x]  You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
> * [x]  You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> * [x]  You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
> * [x]  You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

Hi are you using nginxproxymanager locally or with a domain?

I think if you use it with a domain, the wiget URL's also have to be publicly routable.

**Comment by tinytempmouse** [comment]
I'm using local DNS records

**Comment by CrazyWolf13** [comment]
> I'm using local DNS records 

This is most likely not a bug but I can still try to help you, however for that you need to share some more info on how you set up dashy, the easiest would be to share the. conf.yml. or the section with the not working widgets.

**Comment by CrazyWolf13** [comment]
Are you running pihole and jellyfin... Behind a reverse proxy or only dashy?

**Comment by tinytempmouse** [comment]
Sorry for the delayed response, I'm running everything behind a reverse proxy. Here is my config for dashy:
Docker-compose.yml:
`
---
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    ports:
      - 8881:80
    volumes:
      - /home/micromouse/docker/dashy/conf.yml:/app/public/conf.yml
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - dashy

networks:
  npm:
    external: true
~
`
Config.yml:
`
---
version: "3.8"
services:
appConfig:
  statusCheck: false
  theme: colorful
  fontAwesomeKey: c94dc2b452
  customCss: '.clock p.time { font-size: 3rem !important; }'
  layout: auto
  iconSize: small
  language: en
  widgetsAlwaysUseProxy: true
pageInfo:
  title: Hello, Mouse
  description: ''
  navLinks: []
  footerText: ''
  logo: ''
sections:
  - name: Global
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    widgets:
      - type: clock
        options:
          timeZone: Europe/London
          format: en-GB
          hideDate: false
        id: 0_593_clock
      - type: weather
        options:
          apiKey: *****
          city: *****
          units: metric
          hideDetails: false
        id: 1_593_weather
    items: []
    filteredItems: []
  - name: apps
    displayData:
      sortBy: default
      rows: 1
      cols: 4
      collapsed: false
      hideForGuests: false
    items:
      - &ref_0
        title: Uptime Kama
        url: https://uptime.mouse.lan/dashboard
        statusCheck: true
        id: 0_436_uptimekama
      - &ref_1
        title: Pi-hole
        url: https://dns.mouse.lan
        statusCheck: true
        id: 1_436_pihole
      - &ref_2
        title: Jellyfin
        url: https://jelly.mouse.lan
        statusCheck: true
        id: 2_436_jellyfin
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
  - name: Search
    displayData:
      sortBy: default
      rows: 1
      cols: 3
      collapsed: false
      hideForGuests: false
    widgets:
      - type: custom-search
        options:
          placeholder: I’m at your disposal. . .
          engines:
            - title: search
              url: https://searx.mouse.lan/?q=
        id: 0_598_customsearch
    items: []
    filteredItems: []
  - name: Pi-hole
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    widgets:
      - type: pi-hole-stats
        options:
          hostname: https://dns.mouse.lan
          apiKey: *****
        id: 0_654_piholestats
      - type: pi-hole-traffic
        options:
          hostname: https://dns.mouse.lan
          apiKey: ******
        id: 1_654_piholetraffic
      - type: pi-hole-top-queries
        options:
          hostname: https://dns.mouse.lan
          apiKey: *******
        id: 2_654_piholetopqueries
    items: []
    filteredItems: []
                                                 108,21        Bot
                                                 108,21        Bot








`
For example I have pihole setup so nginxproxymanager (I'll be using npm as an acronym for that here ) exposes it on port 8080 using SSL with webhooks enabled in the settings however dashy doesn't seem to like it at all.

**Comment by CrazyWolf13** [comment]
> Sorry for the delayed response, I'm running everything behind a reverse proxy. Here is my config for dashy:
> Docker-compose.yml:
> ```
> ---
> version: "3.8"
> services:
>   dashy:
>     image: lissy93/dashy
>     container_name: Dashy
>     ports:
>       - 8881:80
>     volumes:
>       - /home/micromouse/docker/dashy/conf.yml:/app/public/conf.yml
>     environment:
>       - NODE_ENV=production
>       - UID=1000
>       - GID=1000
>     restart: unless-stopped
>     healthcheck:
>       test: ['CMD', 'node', '/app/services/healthcheck']
>       interval: 1m30s
>       timeout: 10s
>       retries: 3
>       start_period: 5s
>     networks:
>       - dashy
> 
> networks:
>   npm:
>     external: true
> ~
> ```
> Config.yml:
> ```
> ---
> version: "3.8"
> services:
> appConfig:
>   statusCheck: false
>   theme: colorful
>   fontAwesomeKey: c94dc2b452
>   customCss: '.clock p.time { font-size: 3rem !important; }'
>   layout: auto
>   iconSize: small
>   language: en
>   widgetsAlwaysUseProxy: true
> pageInfo:
>   title: Hello, Mouse
>   description: ''
>   navLinks: []
>   footerText: ''
>   logo: ''
> sections:
>   - name: Global
>     displayData:
>       sortBy: default
>       rows: 1
>       cols: 1
>       collapsed: false
>       hideForGuests: false
>     widgets:
>       - type: clock
>         options:
>           timeZone: Europe/London
>           format: en-GB
>           hideDate: false
>         id: 0_593_clock
>       - type: weather
>         options:
>           apiKey: *****
>           city: *****
>           units: metric
>           hideDetails: false
>         id: 1_593_weather
>     items: []
>     filteredItems: []
>   - name: apps
>     displayData:
>       sortBy: default
>       rows: 1
>       cols: 4
>       collapsed: false
>       hideForGuests: false
>     items:
>       - &ref_0
>         title: Uptime Kama
>         url: https://uptime.mouse.lan/dashboard
>         statusCheck: true
>         id: 0_436_uptimekama
>       - &ref_1
>         title: Pi-hole
>         url: https://dns.mouse.lan
>         statusCheck: true
>         id: 1_436_pihole
>       - &ref_2
>         title: Jellyfin
>         url: https://jelly.mouse.lan
>         statusCheck: true
>         id: 2_436_jellyfin
>     filteredItems:
>       - *ref_0
>       - *ref_1
>       - *ref_2
>   - name: Search
>     displayData:
>       sortBy: default
>       rows: 1
>       cols: 3
>       collapsed: false
>       hideForGuests: false
>     widgets:
>       - type: custom-search
>         options:
>           placeholder: I’m at your disposal. . .
>           engines:
>             - title: search
>               url: https://searx.mouse.lan/?q=
>         id: 0_598_customsearch
>     items: []
>     filteredItems: []
>   - name: Pi-hole
>     displayData:
>       sortBy: default
>       rows: 1
>       cols: 1
>       collapsed: false
>       hideForGuests: false
>     widgets:
>       - type: pi-hole-stats
>         options:
>           hostname: https://dns.mouse.lan
>           apiKey: *****
>         id: 0_654_piholestats
>       - type: pi-hole-traffic
>         options:
>           hostname: https://dns.mouse.lan
>           apiKey: ******
>         id: 1_654_piholetraffic
>       - type: pi-hole-top-queries
>         options:
>           hostname: https://dns.mouse.lan
>           apiKey: *******
>         id: 2_654_piholetopqueries
>     items: []
>     filteredItems: []
> ```
> For example I have pihole setup so nginxproxymanager (I'll be using npm as an acronym for that here ) exposes it on port 8080 using SSL with webhooks enabled in the settings however dashy doesn't seem to like it at all.

Thanks for sharing.
Hmm very odd.
And if you replace the urls linking to the services via nginxproxymanager with the ip and port, then it works?

Just to eliminate network misconfigd in the first place.

Could you share a screenshot of the nginxproxymanager options you enabled of a service?

Because I have the exact same setup and it works just fine.

**Comment by tinytempmouse** [comment]
![Screenshot_20240206-120615_Cromite](https://github.com/Lissy93/dashy/assets/137355256/fd30b032-3f8a-4602-9564-28bed0c1d020)
![Uploading Screenshot_20240206-120558_Cromite.png…]()

**Comment by CrazyWolf13** [comment]
Can actually confirm this!

After further investigation I can see the that I get the exact same error. 
Even when using .com instead of .local ending.

I suspect it can be either some header thing or a problem on nginx config side.

**Comment by CrazyWolf13** [comment]
Got it working!

Adding the option "Status Checks - Max Redirects" and specifying a higher number than like 2 or 3 seems to solve the issue.

![image](https://github.com/Lissy93/dashy/assets/96661824/bf0e0496-0f98-4286-b600-4a33ff0b187e)

**Comment by CrazyWolf13** [comment]
Will add a PR to add a note into the wiki.
