### ISSUE TITLE
[FEATURE_REQUEST] Add a startpage view optimized to reduce load time

### ISSUE THREAD

**Issue by ndbrew** [Lissy93/dashy#1457]
### Is your feature request related to a problem? If so, please describe.

I'd like to use Dashy as the start-page for new tabs in my browser, I've found the page load time for that use-case a little long. The initial DOM load time for me is between 1.5 and 2.5 seconds and downloads 8MB of assets on the minimal view with a vanilla install.

### Describe the solution you'd like

Ultimately, I'd like some version of a minimal view that loads as quickly as possible. 250-500ms would probably be the sweet spot for me.

My intention is to use this view for fast app launches, web searches and low detail alert visibility. I'll use this page as a jump-off to a more full featured Dashy view where page load times are not a problem.

Primary features I'd want to use on the view:
- Item Rendering / Searching
- Item Shortcuts / HotKeys / Bangs
- Web-search

Nice to have if they fit the load time:
- Item status checks
- RSS Feed Widget

Other solutions considered:
- Use a long running instance of Dashy as my jump-off point instead of new tabs
- Use a more static site dashboard as the start-page but then I have to maintain 2 dashboards.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Maybe

**Comment by CrazyWolf13** [comment]
That is already planned, however Lissy has not yet had time to implement this, as a lot of dashy itself needs fixing and a V3 is already in the making.

https://github.com/Lissy93/dashy/discussions/405#discussion-3781535 
 
 _Lite Version
The app is served up using a Node server. Node.js is quite heavy, so a lite version (using NGINX) will be aimed at lower-spec devices, or users who don't need any of the server features (status checking and UI config editor)_
