### ISSUE TITLE
How to change --content-max-width

### ISSUE THREAD

**Issue by Outsidewall** [Lissy93/dashy#1463]
### Question

Hello, Struggling on how to change the --content-max-width from the config.yml file, would anyone please give some pointers.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi could you share a bit more?

What do you want to achieve?

Is it custom CSS?

**Comment by Outsidewall** [comment]
In default theme mode, the width of the main lists area is set to 85% (on PC browser). This wastes space, either side. I would like to  use 100% of the width. I have tried changing this via developer mode (F12 on browser) to 100%, looks good. This is where I found the variable I noted in the title. Does that help?

**Comment by Lissy93** [comment]
Sure, try this:

```yaml
appConfig:
  customCss: '.item-group-container { max-width: 100% !important; }'
```

**Comment by Outsidewall** [comment]
Thank you, works, looks much better, actually set it to 98%
