### ISSUE TITLE
[QUESTION] Custom HTML?

### ISSUE THREAD

**Issue by bobbyl140** [Lissy93/dashy#1477]
### Question

I run a Mastodon server and would like to verify back to my website, which is my Dashy homepage. However, this requires sticking a custom block of HTML on the page you link back to, with `<a rel="me" href="https://mastodon.example.com/@user">Mastodon</a>`. I can, of course, insert the link, but the `rel="me"` is the important part which I don't see a way to do. I was considering making an empty widget to do this, but I wonder if there's a better way.

### Category

Development

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Do you mean that `item` needs to have the `rel` attribute?
If so, I can add a config option to let you specify a rel value for an item.

**Comment by Lissy93** [comment]
Actually I can see how being able to set the `rel` attribute would be useful in a number of scenarios. Because currently it's just set to `noreferrer noopener` for privacy (so the links you click can't see the URL of your Dashy instance). But for links to items owned by the user, I can see why they may want or need to modify this.

I've pushed an update which let's the user optionally customoize the rel attribute of a given item. Still defaults to noreferrer noopener if not set.

Won't go live until 2.1.2 which will be merged + released in the coming days.

**Comment by bobbyl140** [comment]
> Do you mean that `item` needs to have the `rel` attribute? If so, I can add a config option to let you specify a rel value for an item.

I think so? As long as that gets set on the `<a>` element I think it should work.

> I've pushed an update which let's the user optionally customoize the rel attribute of a given item. Still defaults to noreferrer noopener if not set.

Wow, thank you! I'll test when that comes out and update.

**Comment by Lissy93** [comment]
If it's any help, [`index.html`](https://github.com/Lissy93/dashy/blob/master/public/index.html) isn't ever re-generated (it's static). If you wanted to go down that route, I'd recommend forking Dashy to keep track of your changes in your own repo, then just syncing your fork when there's a major update.

Alternativley, not sure if it'll work, but have you tried the [Embed Widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#html-embedded-widget)? That'll let you have JavaScript run on your page.
Either point `scriptSrc` to the JavaScript file, or if it's a small snippet, just include the raw JS in `script`

Can you share the link to the Mastodon docs your looking at? and I might be able to help further, because I might not be fully understanding what you're trying to do.

**Comment by bobbyl140** [comment]
I didn't realize that `index.html` was static, I might try that. 

Mastodon's help says this:
<img width="850" alt="Screenshot 2024-03-04 at 12 09 37 PM" src="https://github.com/Lissy93/dashy/assets/61990607/2d479fdf-6805-4cd2-914f-18866c7ee29f">

Basically, the crawler can't run JavaScript, so if the initial response of the page can contain the link even before executing the JS to render the page, that would fix it. I'll try the index page and see if I can get that to work, since it seems like this is out of the scope of this issue, and I'll update.

**Comment by Lissy93** [comment]
Ah I see what you mean now.
That wouldn't work as an item in Dashy, because they require JavaScript.
But it would work fine if you put it in the index.html :)

**Comment by bobbyl140** [comment]
Alright yeah, thank you. I'll see what I can do with that file.

I did think about having that kind of page, but I was hoping to link to the homepage itself just for cleanliness and since that's the page I actually use as my homepage. I thought about linking back from a `mastodon.html` but it's just not as good of an experience. 

Thank you for the help!

**Comment by bobbyl140** [comment]
That did end up working. Thank you again!

**Comment by bobbyl140** [comment]
@Lissy93 I'm sorry to comment on this again, but I have a question about your advice on editing `index.html` inside the Docker container. I don't really know how to set up a repo with automatic Docker container builds, and while I do want to figure that out, for now I just was hoping to change the file inside the container. But obviously taking down the container causes those changes to be reset. I copied my (working) `index.html` from the container to my host and made it a volume in Docker just to persist the changes, but that breaks Dashy altogether. From the [management docs](https://github.com/Lissy93/dashy/blob/master/docs/management.md#providing-assets), I figured I could do this as some other static assets in that folder are listed, but something doesn't seem to be working. the Dashy container logs seem normal as far as I can tell, and the breakage comes when loading the page:
<img width="1352" alt="Screenshot 2024-03-05 at 6 20 48 PM" src="https://github.com/Lissy93/dashy/assets/61990607/3a9190a0-0c27-4572-a453-ae01dc9f729a">
Do you have any ideas, or is this not a possibility? Thank you again.

**Comment by Lissy93** [comment]
I think you've made a small syntax error somewhere in the `index.html`

Or there's something missing somewhere. What does the browser console say? ([heres how to see](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console))

---

And in answer to your second question, best way to manage an edited index page would be:
**Option 1)** This file doesn't change often, so you could just create a copy locally and mount it as a file in your Docker container, like you've done (but valid html)
**Option 2)** Alternatively, fork Dashy, make your desired edits, and run your own fork. GitHub has an option for syncing forks from their upstream origins, so you can still stay up-to-date with the latest changes. It will however mean you need to publish your own Docker image to some registry (if you use Docker).


Another option, I know you said having an /mastodon.html page wasn't ideal, but you could create such a page (named anything, located anywhere) which includes the required verification, then automatically redirects to your dashboard.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="refresh" content="0; url=https://bobbyl140.com/" />
  <link rel="canonical" href="https://bobbyl140.com/" />
  <link rel="icon" type="image/png" href="/favicon.ico" />
  <title>bobbyl140's Dashy</title>
</head>
<body>
  <a rel="me" href="https://mastodon.bobbyl140.com/@bobbyl140">Mastodon</a>
</body>
```

**Comment by Lissy93** [comment]
Beyond that, I'm not really sure what other solutions there are

**Comment by bobbyl140** [comment]
> I think you've made a small syntax error somewhere in the `index.html`

You're entirely right, my fault. I was editing the file on my phone and I made a typo 😅. But I fixed that and it does work now, so I'm sorry I bothered you about this. Next time I'll be more careful :)

**Comment by bobbyl140** [comment]
> Another option, I know you said having an /mastodon.html page wasn't ideal, but you could create such a page (named anything, located anywhere) which includes the required verification, then automatically redirects to your dashboard.
> 
> 
> 
> ```html
> 
> <!DOCTYPE html>
> 
> <html lang="en">
> 
> <head>
> 
>   <meta http-equiv="refresh" content="0; url=https://bobbyl140.com/" />
> 
>   <link rel="canonical" href="https://bobbyl140.com/" />
> 
>   <link rel="icon" type="image/png" href="/favicon.ico" />
> 
>   <title>bobbyl140's Dashy</title>
> 
> </head>
> 
> <body>
> 
>   <a rel="me" href="https://mastodon.bobbyl140.com/@bobbyl140">Mastodon</a>
> 
> </body>
> 
> ```


I thought there was a way to do that but I couldn't think of what it was. I tried hacking together an Apache if statement that looked at user-agent strings to determine a redirect, which didn't work. Thank you for this though!
