### ISSUE TITLE
[BUG] Dashy crashlooping after last upgrade to 2.1.2

### ISSUE THREAD

**Issue by Matsched** [Lissy93/dashy#1494]
### Environment

Self-Hosted (Docker)

### System

Docker 25.0.3 build 4debf41

### Version

Dashy V-2.1.2

### Describe the problem

After upgrading to last docker-image, dashy crashes after few seconds. Im able to open the dashy dashboard (like normal), then reload and i get "Not found".
I didnt changed anything in my config-files.
Im using docker-compose with Watchtower for Dashy.

### Additional info

```
dashy  | ✔️ Config file is valid, no issues found
dashy  |
dashy  | SSL Not Enabled: Public key not present
dashy  |
dashy  |
dashy  |  ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
dashy  |  ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
dashy  |  ██║  ██║███████║███████╗███████║ ╚████╔╝
dashy  |  ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
dashy  |  ██████╔╝██║  ██║███████║██║  ██║   ██║
dashy  |  ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝
dashy  |
dashy  | *******************************************************************************************
dashy  | Welcome to Dashy! 🚀
dashy  | Your new dashboard is now up and running with Docker
dashy  | *******************************************************************************************
dashy  |
dashy  |
dashy  | Using Dashy V-2.1.2. Update Check Complete
dashy  | ✅ Dashy is Up-to-Date
dashy  |
dashy  |
dashy  | -  Building for production...
dashy  |  WARN  A new version of sass-loader is available. Please upgrade for best experience.
dashy  | Error: ENOENT: no such file or directory, stat '/app/dist/index.html'
dashy  | error Command failed with signal "SIGKILL".
dashy  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dashy  | ERROR: "build-watch" exited with 1.
dashy  | error Command failed with exit code 1.
dashy  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
dashy exited with code 0
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by ulrik-vj** [comment]
Also having this issue. I can run the container as root (2.1.2/latest) no problems. But running as user: XXXX:XXXX, gives constant crashing. 
Just pulled and Tested on 2.1.1, there i can run as user no crashing. Here is something from logs running latest image: 
![dashy](https://github.com/Lissy93/dashy/assets/108303827/a7a3b9a8-08b5-4218-995f-1f08acc5bc9b)

**Comment by CrazyWolf13** [comment]
> Hmm, that's not good. I did push an update a few hours ago, was this before or after that update? Could you try re-pulling that latest image / tag?

Actually getting the same error :/

**Comment by p6002** [comment]
It stops working, how I can check what is a reason and share here?

**Comment by CrazyWolf13** [comment]
> It stops working, how I can check what is a reason and share here?

Lissy has already identified the issue and is currently testing a fix.

Huge claps to her 👏

**Comment by Matsched** [comment]
I have tested a bit:
If i `docker` compose up dashy` and immediately open the dashboard in browser i get 
```
dashy  | Error: ENOENT: no such file or directory, stat '/app/dist/index.html'
```
And Dashy exit with errorcode.

After disabling resource-limits in docker-compose.yml and waiting for dashy to fully start up, dashy is working. I can repeat F5 without any issue.

If i open Dashy on unlimited resources before it fully starts up, i get again "ENOENT: no such file..." like above and dashy hang up.

Now i see in: https://dashy.to/docs/deployment/ Dashy needs 1GB. It runs all the time on 256MB flawlessly (lol)

**Comment by Lissy93** [comment]
> Now i see in: https://dashy.to/docs/deployment/ Dashy needs 1GB. It runs all the time on 256MB flawlessly (lol)

Nothing changed there, those were just the recommended specs for the Node base image, but it very very very rarley gets anywhere near 1GB

**Comment by Lissy93** [comment]
Merging #1496 now....
Will be available on DockerHub shortly
I'm hoping this will fix the issue, so 🤞
Let me know if that works out for you

**Comment by Lissy93** [comment]
Okay, updated version live on DockerHub and GHCR. Try re-pulling `:latest` or `:2.1.2` tag.
It's working for me and @CrazyWolf13 - but OP give it a shot and let us know how you get on.

And sorry for the trouble this has caused, I'll do smaller and more frequent updates going forward, to hopefully mitigate things breaking.

**Comment by p6002** [comment]
Thanks it works now!
`sudo docker pull lissy93/dashy:latest`
