### ISSUE TITLE
[QUESTION] Build from Source not working anymore 2.1.2?

### ISSUE THREAD

**Issue by nicedevil007** [Lissy93/dashy#1495]
### Question

Heya guys,

I have my installation on an AlmaLinux 9.3 and I was running NPM 16.x before. I used the deployment guide from here https://dashy.to/docs/deployment#build-from-source.

Now the eror is looking like this:
![image](https://github.com/Lissy93/dashy/assets/17103076/d3308fd2-6f1e-4743-9800-f916b0b7c9ee)

If I use version 17 I get the errors with the dependencies. (See question 1)

If I use a newer version than 17 for NPM I get this error
![image](https://github.com/Lissy93/dashy/assets/17103076/7cca93b5-b7ff-4f2a-8b28-9d48fcdb09a1)

So questions are:

1) How to get rid of these errors?
```bash
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning Workspaces can only be enabled in private projects.
```

2) Is there any plan to update everything to any newer versions of NPM in the future?

I already tried useing npm (https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#yarn-error) instead of yarn, same thing here.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
That currently a know problem where github actions fails to build the image to docker when node is higher than 18 LTS, so we temporarly set BUILD_ENV down to 18 LTS but kept normal node when running the image at 20 LTS. 

For a temporary fix you could use node 17 LTS.

**Comment by Lissy93** [comment]
For the `The engine "node" is incompatible with this module` error specifically, try running with the `--ignore-engines`

E.g.  `yarn install --ignore-engines` should fix this. And that will work with Node LTS (21.11.1) or later.

@CrazyWolf13 - I think since the GH actions & Docker thing, is a bug with the Alpine + Node base container, whereas OP is building from source, so shouldn't run into that issue.  Ahh, the joys of Node.js 😆

**Comment by nicedevil007** [comment]
> For the `The engine "node" is incompatible with this module` error specifically, try running with the `--ignore-engines`
> 
> E.g. `yarn install --ignore-engines` should fix this. And that will work with Node LTS (21.11.1) or later.
> 
> @CrazyWolf13 - I think since the GH actions & Docker thing, is a bug with the Alpine + Node base container, whereas OP is building from source, so shouldn't run into that issue. Ahh, the joys of Node.js 😆

confirmed, works like a charm with that :)
so should we close this here or do you want to track the fix in general with this issue?

**Comment by CrazyWolf13** [comment]
Hi
I think we can close this issue, the argument `--ignore-engines` is only needed on older versions, so there's not really much to do there and for the other issue when building for GH-Actions we are waiting for a upstream fix.
