### ISSUE TITLE
[QUESTION] Alpine 3.15 LXC unmet peer dependency warnings?

### ISSUE THREAD

**Issue by homelabd** [Lissy93/dashy#1504]
### Question

Pretty much getting the same error as #1495, but I don't quite understand why I am getting this error for my particular instance.

For some context, I am attempting to run this on an alpine 3.15 LXC. The problem might have to do with the yarn / nodejs version. Crazywolf13 recommends to use node 17 LTS as a temporary fix, but wouldn't using a v16.20.2 work as well? 

I would just like to understand why I am getting these errors?

![image](https://github.com/Lissy93/dashy/assets/118637783/c20575a7-6832-4052-ad8b-b43a1cd47ffa)

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

yarn / node versions
```shell
dashy:~/dashy# yarn -v
1.22.17
dashy:~/dashy# node -v
v16.20.2
```

**Comment by CrazyWolf13** [comment]
I think the option '--openssl-legacy-provider' is not needed on node 16 LTS, however the issue you linked gets fixed when running 'yarn --ignore-engines, so you should be able to use any newer version of node like 20LTS when running 'yarn --ignore-engines '.
