### ISSUE TITLE
[QUESTION] Trying to set it to a Domain Name

### ISSUE THREAD

**Issue by RedPrismOwner** [Lissy93/dashy#1516]
### Question

i’m using the quick setup docker line and i’m trying to have it point to my domain, how do i do that?

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi,

That really depends on you network layout, whether you selfhost or in the cloud, if you have a public IP or use something like CLoudflare Tunnels etc

However a really general first step is to get going with a reverse proxy, here is an example tutorial with nginxproxymanager, however you can use bare bone nginx, traefik, caddy, .....

https://www.youtube.com/watch?v=qlcVx-k-02E

Here is also a good general article about this topic.

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Publishing_your_website?retiredLocale=de

**Comment by RedPrismOwner** [comment]
Hi, yea. i am using a VPS to host it. i have a public IP and i ufw allow 8080 and 80 both

**Comment by CrazyWolf13** [comment]
Great!

Here is a nice guide on how to setup nginxproxymanager, however the setup depends on where you bought your domain.

https://www.youtube.com/watch?v=P3imFC7GSr0

Also there is not only one solution, mine is really just a suggestion, there are a thousand ways to do this.

**Comment by CrazyWolf13** [comment]
Will close this due to no response.

If you got anymore questions feel free to reply back to this and I'll reopen this :)

Have a nice day!
