### ISSUE TITLE
[BUG] vercel don't build

### ISSUE THREAD

**Issue by bpshou** [Lissy93/dashy#1520]
### Environment

Cloud Service (Static)

### System

Chrome, mac, cloud

### Version

2.1.2

### Describe the problem

auto build error ! it's not work

error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 \|\| 10 \|\| 12 \|\| 14 \|\| 16 \|\| 17". Got "18.19.1"
--
11:55:09.120 | error Found incompatible module.

Error: Command "yarn install" exited with 1

### Additional info

![image](https://github.com/Lissy93/dashy/assets/22309240/5ad6624f-25cf-41b3-9e1a-c32e3b0c4794)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Look here for a fix.
https://github.com/Lissy93/dashy/issues/1499#issuecomment-1981014703

**Comment by bpshou** [comment]
very nice, thinks~
