### ISSUE TITLE
Auth with admin can`t save anything

### ISSUE THREAD

**Issue by Nexow91** [Lissy93/dashy#1523]
### Environment

Self-Hosted (Docker)

### System

Debian 12 Bookworm

### Version

2.1.1

### Describe the problem

Hello, Im Using Unraid before I moved dashy to a proxmox LXC because the authentication worked and I could also save config using WebUI from Dashy. After the move and the transfer of the config I could not update the config.yml -> see screenshot. I have also tried to enter only the parameters "user" "hash" "type: admin" in the configuration but without success. That's why I'm now turning to the community via github. Unfortunately I don't know which version I had on Unraid. I used the script from tteck (https://github.com/tteck/Proxmox/) to deploy the LXC with Dashy, but unfortunately version 2.1.1 is also installed here, which apparently often causes problems with authentication. 2.1.2 is apparently not possible because it would break the Docker on the LXC. Maybe someone can help. Sry I have now opened a post because I did not know if this is right.

Edit: attempts with "appConfig.auth.enableGuestAccess: true" or "yarn build" have also failed. 

Translated with DeepL.com (free version)

### Additional info

> Config with Authentification 

![Config](https://github.com/Lissy93/dashy/assets/73191540/22c82eb3-83c9-4ee9-8245-c0933619b490)

> Rebuild Config WebUI

![image](https://github.com/Lissy93/dashy/assets/73191540/3cc0f3a8-f4b0-4901-8871-423aa7a373c6)

> Show Login

![image](https://github.com/Lissy93/dashy/assets/73191540/d9089b46-41fb-4574-bfbe-2b485cc897b4)

- [ ] 

- [ ] 

> Clean Config

![image](https://github.com/Lissy93/dashy/assets/73191540/0b356172-4fae-4d56-a9cb-2f647d82e2b3)

> Rebuild Application with clean install without authentification 
![image](https://github.com/Lissy93/dashy/assets/73191540/3d27c70d-a929-4caf-9158-9dce04b79b8f)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi

First of all, you've done all right!

The tteck helper script is not affiliated with dashy, so we can't really change much there however auth not working seems more like a dashy thing.

If you are editing the conf through the UI to enable auth, reload the page. Then if you use the same url/ip as of before moving to the lxc you may have to clear the cookies especially the auth cookie.

**Comment by CrazyWolf13** [comment]
Hi
A lot of things have changed since 2.1.1, I suggest you to update to v3.0. and then report back to here..
As you are on tteck's helper scrips that process should be fully automated.
