### ISSUE TITLE
[NGINX 404 Not Found] <Deployed Dashy via Helm>

### ISSUE THREAD

**Issue by abhinavthula** [Lissy93/dashy#1526]
### Question

I deployed dashy via Helm in the AKS cluster. helm install dashy2 selfhosted-helmcharts/dashy --values values.yaml

I enabled the ingress and added the path /airflow & /airflow/flower as paths in the values.yaml however, when I access the ingress LB IP over browser it says 404 Nginx Not Found. Need to know what other things are missing in my setup.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Could you share the chart and nginx config that you used, as I can't see what might be wrong or try and recreate anything without those details.
