### ISSUE TITLE
[BUG] Cant install dashy from Lissy93/portainer-templates in portainer

### ISSUE THREAD

**Issue by NAVARRA** [Lissy93/dashy#1535]
### Environment

Self-Hosted (Docker)

### Describe the problem

Hello Lissy93 and thank you so much for your amazing work.

I do have a couple of instances of dashy running in my homelab but it always has been a hassle to set them up.
So i thougt i will use the Lissy93/portainer-templates in portainer to make the install easier.

i used this instruction https://github.com/Lissy93/portainer-templates to setup the templates with below url

https://raw.githubusercontent.com/Lissy93/portainer-templates/main/templates.json

when i hit deploy stack i always receive this error message:

failed to deploy a stack: Network dashy_default Creating Network dashy_default Created Container Dashy Creating Container Dashy Created Container Dashy Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/portainer/Files/AppData/Config/Dashy/conf.yml" to rootfs at "/app/public/conf.yml": mount /portainer/Files/AppData/Config/Dashy/conf.yml:/app/public/conf.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expect

what is configured wrong?
help would be highly appriciated since i absolutly love dashy

thank you so much navarra

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
Not sure what's giving you such a headache, but installing dashy is very very simple and straightforward, imagine having to install manually from source...

Here is a command you can enter into your shell:

````
docker run -d \
  -p 8080:80 \
  -v ~/my-conf.yml:/app/public/conf.yml \
  --name my-dashboard \
  --restart=always \
  lissy93/dashy:latest
````

This will expose the latest dashy instance on your host's ip on port 8080, you can freely choose it.

--name is the container name, you can also freely name it.
-v ~/my-conf.yml has to be the path on the host to your working dashy conf file, you can also take the default one from the github here located in /app/public

That's it.

If you encounter any error feel free to report back, thanks!

**Comment by CrazyWolf13** [comment]
Keep in mind dashy will soon upgrade to v3 where the path inside the container for mounting will change a bit, but we'll let everyone know once it releases

**Comment by CrazyWolf13** [comment]
Dashy has updated to V3, look here for the docker commands:

https://dashy.to/docs/deployment

**Comment by nmincone** [comment]
Use this docker-compose in Portainer to get started;
`services:

  dashy:
    image: lissy93/dashy    
    container_name: dashy
    ports:
      - 4000:8080
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - YOUR_LOCATION_HERE/docker/dashy/user-data:/app/user-data
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s`
