### ISSUE TITLE
[QUESTION] How to Update to 3.0 with baremetal now?

### ISSUE THREAD

**Issue by nicedevil007** [Lissy93/dashy#1540]
### Question

As the title says, I try to update my old 2.x version to 3.0 and this is not working as I did before anymore.
The page just keeps blank.

This here were the steps that worked for me in the past:

```python
systemctl stop dashy
cd /opt/dashy
git merge
git pull origin master
npm install --ignore-engines
npm run build
systemctl start dashy
```

My dashy service file looks like this:

```python
[Unit]
Description=dashy

[Service]
Type=simple
WorkingDirectory=/opt/dashy
ExecStart=/usr/bin/npm start
[Install]
WantedBy=multi-user.target
```

The service always tells me that there is still version 3.0 available as update and dashy keeps running as version 2.1.2.

```python
Apr 21 08:17:44 dashy npm[554]: 
Apr 21 08:17:44 dashy npm[554]: ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
Apr 21 08:17:44 dashy npm[554]: ┃ Welcome to Dashy! 🚀                                                       ┃
Apr 21 08:17:44 dashy npm[554]: ┃ Your new dashboard is now up and running at http://127.0.1.1:4000         ┃
Apr 21 08:17:44 dashy npm[554]: ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
Apr 21 08:17:44 dashy npm[554]: 
Apr 21 08:17:44 dashy npm[554]: Using Dashy V-2.1.2. Update Check Complete
Apr 21 08:17:44 dashy npm[554]: ━━━━━━━━━━━━━━━━━━━━━━━━━━━
Apr 21 08:17:44 dashy npm[554]: ⚠️ Update Available: 3.0.0 
Apr 21 08:17:44 dashy npm[554]: ━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

I want to mention that here are some warning during the update process:

```python
root@dashy:/opt/dashy# systemctl stop dashy
root@dashy:/opt/dashy# git pull origin master
remote: Enumerating objects: 2035, done.
remote: Counting objects: 100% (1952/1952), done.
remote: Compressing objects: 100% (1643/1643), done.
remote: Total 2035 (delta 350), reused 1890 (delta 307), pack-reused 83
Receiving objects: 100% (2035/2035), 88.66 MiB | 5.67 MiB/s, done.
Resolving deltas: 100% (370/370), completed with 67 local objects.
From https://github.com/Lissy93/dashy
 * branch              master     -> FETCH_HEAD
   129c6d71..382f8f3e  master     -> origin/master
Updating 129c6d71..382f8f3e
error: Your local changes to the following files would be overwritten by merge:
        public/conf.yml
        yarn.lock
Please commit your changes or stash them before you merge.
Aborting
root@dashy:/opt/dashy# npm install --ignore-engines
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'dashy@2.1.2',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <21.6.2' },
npm WARN EBADENGINE   current: { node: 'v21.7.1', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v21.7.1', npm: '10.5.0' }
npm WARN EBADENGINE }

up to date, audited 1599 packages in 8s

155 packages are looking for funding
  run `npm fund` for details

79 vulnerabilities (1 low, 50 moderate, 23 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
error: Your local changes to the following files would be overwritten by merge:
        public/conf.yml
        yarn.lock
Please commit your changes or stash them before you merge.
Aborting

This suggests that changes to the file conf.yml and yarn lock are not made because they are different on your system than on the git repo.

Please make a copy of conf.yml (and possibly other assets like images that you saved inside dashy) and remove the whole dashy folder and clone the repo again.
That is probably the easiest.
Otherwise save a copy of conf.yml and assets and run 'git reset --hard'

**Comment by nicedevil007** [comment]
> ```
> error: Your local changes to the following files would be overwritten by merge:
>         public/conf.yml
>         yarn.lock
> Please commit your changes or stash them before you merge.
> Aborting
> ```
> 
> This suggests that changes to the file conf.yml and yarn.lock are not made because they are different on your system than on the git repo.
> 
> But yarn.lock needs to be changes as there were changes in dependencies and upgrading them.
> 
> Please make a copy of conf.yml (and possibly other assets like images that you saved inside dashy) and remove the whole dashy folder and clone the repo again. That is probably the easiest. Otherwise save a copy of conf.yml and assets and run 'git reset --hard'

oh sry maybe I had to be more clear, I meant the warnings, not the errors :) Last ones are absolutly clear.

this part here:
```python
root@dashy:/opt/dashy# npm install --ignore-engines
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'dashy@2.1.2',
npm WARN EBADENGINE   required: { node: '>=16.0.0 <21.6.2' },
npm WARN EBADENGINE   current: { node: 'v21.7.1', npm: '10.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.2',
npm WARN EBADENGINE   required: { node: '8 || 10 || 12 || 14 || 16 || 17' },
npm WARN EBADENGINE   current: { node: 'v21.7.1', npm: '10.5.0' }
npm WARN EBADENGINE }
```

oh... with the `git reset --hard` did the trick, thank you!

**Comment by CrazyWolf13** [comment]
Great to see it's working for you!
As you can see, you are using a little bit to new version of node, I think in the docs it's even written that dashy needs the latest LTS version which is currently 20.x.x, but as you can see it even works with newer version, just with that note.

I think --ignore-engines was introduced to fix some dependency issue when upgrading some of them to more up-to date versions, but not entirely sure on that.
