### ISSUE TITLE
Dashy Latest 3.00 Does not Work

### ISSUE THREAD

**Issue by awptechnologies** [Lissy93/dashy#1541]
### Environment

Self-Hosted (Docker)

### System

Docker on Debian

### Version

3.0.0

### Describe the problem

Dashy does not come up at all container starts everything seems to be okay but i have no connecting through my reverse proxy or directly from ip and port. Tried the latest and auto image no luck.

### Additional info

After trying both of the new images i went back to 2.1.2 and everything worked right away.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
![image](https://github.com/Lissy93/dashy/assets/96661824/dcdec364-34c2-4c8a-8a1d-d7566ada11a6)

![image](https://github.com/Lissy93/dashy/assets/96661824/3ad50874-0890-448e-aa04-fad67ca1b75a)

https://github.com/Lissy93/dashy/discussions/1529

https://github.com/Lissy93/dashy/discussions/1537
