### ISSUE TITLE
[BUG] Outdated Docs

### ISSUE THREAD

**Issue by vaughngx4** [Lissy93/dashy#1545]
### Environment

Self-Hosted (Docker)

### System

Alma Linux 8

### Version

3.0.0

### Describe the problem

After updating I was greeted with the default dashboard. Took me a bit to figure it out but the user config and icons path have changed (not sure since which version) and have not been updated in the Dashy docs. I found this by using docker exec to get a terminal and reading the docker yaml contained in the docker image.

Configuration Path:
Old Path: /app/public/conf.yml
New Path: /app/user-data/conf.yml

Local Icons Path:
Old Path: /app/public/item-icons
New Path: /app/user-data/item-icons/

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi,
Look here for the detailed docs.

https://github.com/Lissy93/dashy/issues/1541#issuecomment-2068105504

The docs on the main page update slower that the ones on github, there even is a note, for the latest documentation view the ones on github.

But you are right, for such breaking changes they should probably be updated quicker, thanks for the feedback.

**Comment by Lissy93** [comment]
Apologies @vaughngx4 looks like the website was slower to update. It should be refreshed now.
