### ISSUE TITLE
[FEATURE_REQUEST] Hide Settings from Guests and Specific users

### ISSUE THREAD

**Issue by G-S322** [Lissy93/dashy#1552]
### Is your feature request related to a problem? If so, please describe.

I don't like how users and guests have access to the menu can download the config file from the settings menu, which also contains the hashed password...

### Describe the solution you'd like

I would like to have the option to disable the settings menu for guests and/or specific users completely so that this just acts as a dashboard/ Landing page for links.

I was thinking something like
hideSettingsForGuests: true
and
hideMenu: true
for users under the auth section.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None

**Comment by rxunique** [comment]
+1

**Comment by Lissy93** [comment]
Actually, this sounds like something which should be implemented by default.
If basic auth is enabled, and the user is not logged in, they shouldn't be able to write any changes.

Thoughts?

**Comment by rxunique** [comment]
>  should be implemented by default

Do you mean there is already implementation? Or thinking its a good idea to be default?

>If basic auth is enabled, and the user is not logged in

In my mind, I was hoping add an option  to `appConfig.hideComponents` . currently `hideSettings` only collapsed the setting

maybe an option `disableSettings` to globally stop non-admin to edit and basically view only

**Comment by Lissy93** [comment]
> maybe an option disableSettings to globally stop non-admin to edit and basically view only

Thanks @rxunique - Done!

I figured, if you've setup basic auth, and have guest access enabled- you wouldn't want guests to be able to edit configuration (otherwise there's not much point to the auth, beyond roles).

So instead of adding an extra option to disable edits from guests, it's now (since V 3.0.1) disabled by default. And so logging in is required to make changes, if auth is enabled.

If you need anything else modifying around this, let me know below, and I'll reopen.

**Comment by electrofloat** [comment]
> If you need anything else modifying around this, let me know below, and I'll reopen.

I would still like to have a setting to completely remove the settings from the page for specific users (all the settings not just disabling the ability to read/write the config, but do not show the theme chooser, layout, item size, config, logout menu/buttons).

**Comment by KnPk11** [comment]
What the OP also might have meant is that the config is conveniently exposed as a download link for any visitor (guest) to download.

<img width="480" height="812" alt="Image" src="https://github.com/user-attachments/assets/b0a29fd6-3f4c-49ca-acf9-59f1e9a12453" />

Is there a way to hide this download link? I'd like the guest access to be turned on for public showcase of my homelab, but it makes me anxious that the config file can be downloaded along with:

1. My admin credentials (hashed password)
2. My widget credentials (such as Glances auth)
3. Any links to widgets that are not meant to be visible to guests

Settings such as `appConfig.disableConfiguration` don't seem to help. I also thought maybe secrets could be moved out of `config.yml` to some other file (similar to how Docker secrets work), but it doesn't seem possible?

If you like I could open a new issue?
