### ISSUE TITLE
[BUG] Sharing Keycloak setup, not exactly a bug but certainly felt like one

### ISSUE THREAD

**Issue by rxunique** [Lissy93/dashy#1554]
### Environment

Self-Hosted (Docker)

### System

Docker 25

### Version

3.0

### Describe the problem

It wasn't very smooth for me to get Dashy 3.0 and KC 24.0.3 working together, but I kinda got there, so sharing my settings that may help others. Also there's a bit bug like behavior, not sure which side it originate from, or just need a documentation update

Most of Dashy doc are good, here are some crucial details

**In TC clients,** 
"Client authentication" must be switched off, otherwise it gets into a redirect loop, or at least that's how it looks like to me.

**In TC clients -> Advanced -> OpenID Connect Compatibility Modes,** 
"Exclude Issuer From Authentication Response " must be switched on. Otherwise it redirects to "https://dashy.my.domain/#iss=https://keycloak.my.domain/realms/my-realm"

You can still login to dashy, but refresh, logout will generate in TC error="invalid_redirect_uri"

**In TC clients -> Access settings,** if you are using multiple dashy pages, you need

- Root URL   https://dashy.my.domain/   (with/wo trailing / doesn't matter)
- Valid redirect URIs must be    /*

Otherwise other pages will generate in TC error="invalid_redirect_uri"

With above steps, I got KC working ok, but show/hide based on group/role still doesn't work, raised here https://github.com/Lissy93/dashy/issues/1550

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by spacecake** [comment]
Hello all,
For anybody using Dashy authentication, please read the following posts:  

- [https://subract.dev/posts/dashy/](url)
- https://github.com/Lissy93/dashy/issues/668#issuecomment-2024390223

Read carefully before using Dashy exposed to the internet.

**Comment by CrazyWolf13** [comment]
Hi 
I created a PR for this: https://github.com/Lissy93/dashy/pull/1581.

Once it gets merged i'll close this here.

Regarding the Post by subtract, view the recent post by lissy: https://github.com/Lissy93/dashy/discussions/1579
