### ISSUE TITLE
[QUESTION] How to upgrade vom 2.x.x to 3.x.x?

### ISSUE THREAD

**Issue by haruzept** [Lissy93/dashy#1556]
### Question

Hello,

thanks for your great work ;)

But how can I upgrade from 2.x.x to 3.x.x?
I'm created dashy with a simple command like docker run -p 8080:8080 lissy93/dashy (but for the old version).
I'm not realy confirm with docker so I don't know how to upgrade.

I copied my files to the new directory from /home/haruzept/dashy/public to /home/haruzept/dashy/user-data/ and then I tried to run "docker start dashy". But I get an error, that docker can't find the files under /home/haruzept/dashy/public.

Than I tried the command docker run -p 8080:8080 lissy93/dashy, but my cpu and ram usage are directly to 100%, so that I have to restart my lxc.

I also tried the update command from the troubleshooting guide docker start dashy -V ./my-local-conf.yml:/dashy/user-data/conf.yml but I get unknown shorthand flag: 'v' in -v.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
Here you go:

```
sudo docker run -d \
  -p 8080:8080 \
  -v /home/haruzept/dashy/user-data:/app/user-data \
  --name my-dashboard \
  --restart=always \
  lissy93/dashy:latest

```

That command is copied from 
https://dashy.to/docs/deployment
Where I added your folder.

**Comment by haruzept** [comment]
Thank you, but I guess it doesn't work.

Now I see on the website building...
And the cpu/ram has a 100% usage.
After 10 minutes of waiting still building.

**Comment by CrazyWolf13** [comment]
> Thank you, but I guess it doesn't work.
> 
> Now I see on the website building...
> And the cpu/ram has a 100% usage.
> After 10 minutes of waiting still building.

Hi what are your resources that you assigned to dashy?

Like ram and cpu cores?

**Comment by haruzept** [comment]
2 CPU Cores from an Intel i5 6500T and 1GB RAM.
After fixing my spelling issue on the path I get this error:
Possible Error, Check Logs

If I run docker logs dashy I get:
Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
*******************************************************************************************


Using Dashy V-3.0.0. Update Check Complete
✅ Dashy is Up-to-Date


-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.

**Comment by CrazyWolf13** [comment]
What happens if you wait another two minutes the refresh the page after possible error appears?

On low end hardware that may pop up if dashy hasn't yet finished to build.

**Comment by haruzept** [comment]
Still the same error.
If I run docker logs dashy I get:
Using Dashy V-3.0.0. Update Check Complete
✅ Dashy is Up-to-Date


-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.

**Comment by haruzept** [comment]
I deleted the docker "docker rm dashy", I moved my folder away and I run docker run -p 8080:8080 lissy93/dashy.
Still the same.

**Comment by CrazyWolf13** [comment]
> Still the same error.
> If I run docker logs dashy I get:
> Using Dashy V-3.0.0. Update Check Complete
> ✅ Dashy is Up-to-Date
> 
> 
> -  Building for production...
>  WARN  A new version of sass-loader is available. Please upgrade for best experience.
> 

Hmm that looks to me like it did not finish building correctly.

What os are you running?
How long did you wait ?
Is you system up to date?

**Comment by haruzept** [comment]
I use ubuntu 22.04 with latest updates.
I waited ~10 Minutes

**Comment by CrazyWolf13** [comment]
> I deleted the docker "docker rm dashy", I moved my folder away and I run docker run -p 8080:8080 lissy93/dashy.
> Still the same.

If not even the basic command without any volumes is working, there seriously seems to be an issue!

Can you assign more ressources?

**Comment by haruzept** [comment]
After migrate to my powerfull host and assign 10 Cores (i9 12900HK) and 4GB of RAM its build in a few moments.
So the problem is/was that dashy 3.0 needs a lot of ressources for building.

**Comment by CrazyWolf13** [comment]
Awesome!
Good that you got it working!

Seems a bit odd, mine was running fine on a raspberry pi with 2 gb ram.

But now at least it only needs a rebuild on start and not anymore on each config change.

I'll close this but will keep the high resource usage problem in mind.
