### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by alaya233** [Lissy93/dashy#1557]
### Environment

Self-Hosted (Docker)

### Version

3.0.0

### Describe the problem

When dashy saves the configuration and then overwrites the configuration file,there no backup of the configuration file is created.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Did you mount the config directly or mount the folder user-data?

**Comment by alaya233** [comment]
> Did you mount the config directly or mount the folder user-data?

Thanks.I change it to mount the folder user-data,it works.

**Comment by CrazyWolf13** [comment]
Awesome 😎!
