### ISSUE TITLE
[BUG] user-defined-themes.scss broken in 3.0.1

### ISSUE THREAD

**Issue by rtm516** [Lissy93/dashy#1559]
### Environment

Self-Hosted (Docker)

### System

Chrome 124, Debian 11, Docker 24.0.2

### Version

3.0.1

### Describe the problem

When upgrading to 3.0.1 with a mounted `user-defined-themes.scss` file due to the change in startup it doesn't get built therefor meaning custom themes don't work.

Changed in https://github.com/Lissy93/dashy/commit/1bbb91b3fef501b8e23bc8942c6cf59df3db36a5

Reverting back to 3.0.0 fixes this problem and so does reverting the changes in commit by altering the start command

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi,
You're right!

I have created and merged a PR to revert the recent changes.

Can you test the new image, by re-pulling the :latest tag from docker-hub?

**Comment by rtm516** [comment]
Looks to be fixed in registry, thanks.
