### ISSUE TITLE
[FEATURE_REQUEST] Push image to GHCR in addition to Dockerhub

### ISSUE THREAD

**Issue by onedr0p** [Lissy93/dashy#156]
**Is your feature request related to a problem? If so, please describe.**

👋🏼 Dockerhub rate limits are a major pain in the butt, it would be cool if you could push this image to the Github Container Registry as well

**Comment by Lissy93** [comment]
Sure, good idea. I'll try and get this done either tonight or sometime tomorrow :)
Not published anything to GH packages before, so I figure I need to write an action to build and publish the container, which I am just looking into now. If you have any suggestions for implementation, do let me know

**Comment by onedr0p** [comment]
It's pretty simple. You are using the right tools already in your workflows. THe one catch is after the image is pushed you need to manually set the image to public from your Github packages.

Could I also suggest that the docker tags follow semver? (e.g. 1.5.0 instead of release-1.5.0)? Thanks!

**Comment by Lissy93** [comment]
Thanks for the reply, should now be done and [live](https://github.com/Lissy93/dashy/pkgs/container/dashy) on GHCR :)
Feel free to submit a PR if you'd like to improve upon it

I will try and add an action to publish fixed versions everytime there is a release. Stable releases usually happen every 2 weeks, and the version number ends in a `.0` - so next one should be tomorrow evening

**Comment by onedr0p** [comment]
Thanks! Glad you figured it out. I am peeved dockerhub pulled that bait and switch, it used to be sooo good. After they established themselves as the defacto image registry for open source projects they pivoted and started charging people 😠

**Comment by Lissy93** [comment]
Yeah, DH has gone down hill a lot recently- they also started charging $5 per month for integrations which used to be free, meaning a lot of people's builds just stopped working until they paid up. I'd never used the GH registry before today, but it it seems pretty awesome so far, hopefully it'll stay free - thanks for introducing me to it :)
