### ISSUE TITLE
[BUG] instructions for docker container on docker hub are incorrect

### ISSUE THREAD

**Issue by ulrichwisser** [Lissy93/dashy#1566]
### Environment

Self-Hosted (Docker)

### System

Synology

### Version

latest

### Describe the problem

Instructions on github say
```-v /root/my-local-conf.yml:/app/user-data/conf.yml \```
whereas docker hub says
```-v /root/my-local-conf.yml:/app/public/conf.yml \```
That made all my conf disappear when my container was updated.
Seems that the instructions on github are correct.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Thank you for the notice, 
You are right the ones on dockerhub are outdated, let me check that :)

**Comment by Lissy93** [comment]
Hey @ulrichwisser 
Sorry about that. DockerHub disabled the API endpoint I was using to keep the README synced up. In the meantime, I've manually updated it, to just link the user to the website/github.
