### ISSUE TITLE
[FEATURE_REQUEST] Multi-architecture Docker images

### ISSUE THREAD

**Issue by onedr0p** [Lissy93/dashy#158]
**Is your feature request related to a problem? If so, please describe.**

Please build multi-architecture docker images. I see that you are tagging docker images by arch. Instead, `docker buildx` can be used to make one tag that supports multiple architectures. The base image for node that you are using already supports multiple architectures as well, see the drop down here for what architectures you could pass thru to the build: https://hub.docker.com/layers/node/library/node/lts-alpine3.14/images/sha256-2fd3c3bf9fbc4ac390b3625e3ae6fedf65233d40ac7515d4af036bba2448d2b8?context=explore

Please checkout my project's workflow here for an example on using `docker buildx`

https://github.com/onedr0p/exportarr/blob/master/.github/workflows/release.yml

**Comment by onedr0p** [comment]
and thanks for this project, it's coming along great!

**Comment by Lissy93** [comment]
Awesome, your new Dockerfile is working great! 
Thanks so much for doing that, I'm still quite new to Dockerizing apps, so this was really helpful :)

**Comment by onedr0p** [comment]
@Lissy93 I don't think the workflows were ever set up to build multi arch images, I left a link above on how you could do it.
