### ISSUE TITLE
[BUG] Unauthorized user can access /conf.yml

### ISSUE THREAD

**Issue by Towerism** [Lissy93/dashy#1586]
### Environment

Self-Hosted (Docker)

### System

Chrome 124.0.6367.201, Debian GNU/Linux 12 (bookworm), Docker 20.10.24+dfsg1 build 297e128

### Version

3.1.0

### Describe the problem

First of all, thanks for creating this product. It's a beautiful, easy to configure, easy to use dashboard that has made it a pleasure to organize my home network.

Now onto to the bug.

With the following settings:
```
appConfig.disableConfigurationForNonAdmin: true
appConfig.auth.enableGuestAccess: false
```

an unauthorized user can access /conf.yml and view the entire config. This seems like a security flaw. Unauthorized users should be denied access to /conf.yml.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Closed as duplicate of https://github.com/Lissy93/dashy/issues/668

Please look into the docs before creating a new issue; https://dashy.to/docs/authentication

It's explained here.
Also you can find a resolution, for example by adding http basic auth.

Also look at this:
https://github.com/Lissy93/dashy/discussions/1579#discussion-6644336
