### ISSUE TITLE
[BUG] Glances Issue

### ISSUE THREAD

**Issue by Eviljubs** [Lissy93/dashy#1594]
### Environment

Self-Hosted (Docker)

### Describe the problem

I had Glances widgets working fine but recently it updated and it hasn't been working. I thought it might be something in my config file but everything there looks fine as far as I can tell. However, I did a bit of digging in my logs and found that the url being referenced by dashy's glances widget is http://192.168.1.2:61208/api/3/mem. I tried navigating to the page in my browser but it doesn't give any data: {"detail":"Not Found"} . 

I then found out that glances has a 4th version of the api (guess that's recent?) -- so if I replace replace the 3 with a 4 like this: http://192.168.1.2:61208/api/4/mem. I get what looks to be data output:  {"total":33538297856,"available":22703775744,"percent":32.3,"used":10834522112,"free":22703775744,"active":6034456576,"inactive":24548749312,"buffers":135168,"cached":23524229120,"shared":753487872}

I would update the appended url string "/api/3/mem/" myself however, I'm not sure where Dashy actually stores that. Any chance the code could be updated relatively quickly? Seems like it could be an easy find/replace job.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
I just tested with the new api v4 version and it seems like most of the things work.

What threw an error:

-   - type: gl-ip-address:
``` 
⚠️ Warning ⚠️ The IP plugin is not supported in this instance of Glances This is likely not an issue with Dashy, but rather your configuration.If you think it is a bug, please open a ticket on GitHub: https://git.io/JukXk
```

 - - type: gl-network-traffic:
 ```
 110Error: <path> attribute d: Unexpected end of attribute. Expected number, "M".
110Error: <path> attribute d: Expected number, "Mundefined,NaNLLu…".
frappe-charts.min.esm.js:1 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at e.value (http://172.17.104.102:4000/js/chunk-50f31ec3.5ad55dde.js:1:42229)
    at e.value (http://172.17.104.102:4000/js/chunk-50f31ec3.5ad55dde.js:1:41749)
    at ResizeObserver.boundDrawFn (http://172.17.104.102:4000/js/chunk-50f31ec3.5ad55dde.js:1:40602)
    
![image](https://github.com/Lissy93/dashy/assets/96661824/1a08e475-2ddc-4004-a162-ecbfb6df89b4)
 ```
 
-   - type: gl-cpu-temp:

```
Shows nothing on the dashboard, shows no erros, but seems broken.
![image](https://github.com/Lissy93/dashy/assets/96661824/0cf632e5-efd9-42cc-a5fa-81bc2a1c37cf)
```
Glances CPU temp could also be due to testing inside WSL but I enabled the sensors plugin.

@Lissy93 I'll get a PR ready to update to V4, but could you take a look at the above three widgets?

**Comment by mr-f0xx** [comment]
Same issue with latest version, it stopped working. I had to go to the previous version.

**Comment by CrazyWolf13** [comment]
> Same issue with latest version, it stopped working. I had to go to the previous version.

A fix has been release, just re-pull the :latest tag of the docker container and rebuild, then it should work again. :)

**Comment by mr-f0xx** [comment]
> > Same issue with latest version, it stopped working. I had to go to the previous version.
> 
> A fix has been release, just re-pull the :latest tag of the docker container and rebuild, then it should work again. :)

Weird...There's no change

**Comment by CrazyWolf13** [comment]
> > > Same issue with latest version, it stopped working. I had to go to the previous version.
> > 
> > A fix has been release, just re-pull the :latest tag of the docker container and rebuild, then it should work again. :)
> 
> Weird...There's no change

Can you share your browser console?
This can be found by right clicking anywhere in the browser and selecting the last entry, called develop, developer tools or similar.

Then you can seitch to the console tab on the rights side, please send a screenshot or copy +paste here

And also your dashy log?

**Comment by Eviljubs** [comment]
Here is my console log:

![image](https://github.com/Lissy93/dashy/assets/128203322/abbbda5b-f9eb-4431-88ee-1eada2ed72df)

It looks like the update is in place, and if I copy and paste the address (http://192.168.1.45:61208/api/4/mem) from there I can access the data feed directly in my browser.   However, it looks like it's not allowing it to talk to Dashy directly for some reason.  Unsure why this would be, unless something updated or changed on the Glances side of things, a few weeks ago all of this was working perfectly.

**Comment by CrazyWolf13** [comment]
@mr-f0xx  and @Eviljubs 

Those are CORS-Errors: 
https://dashy.to/docs/widgets#troubleshooting-widget-errors

You can just add `useProxy: true` to each item.

**Comment by Eviljubs** [comment]
Perfect, that worked, thanks!

**Comment by portalzine** [comment]
For those using Nginx Proxy Manager
1. Create custom location / , apply default IP + Port
2. Press Gear Icon and set CORS header
`add_header 'Access-Control-Allow-Origin' *;`
