### ISSUE TITLE
own config not loaded after upgrade to 3.1 <title>

### ISSUE THREAD

**Issue by quinti123** [Lissy93/dashy#1598]
### Question

hi there,
ive upgraded from 2.1.2 to 3.1.0
Port is changed to 8080
this was my volume config before:
    volumes:
      - /var/lib/docker/volumes/dashy/my-config.yml:/app/public/conf.yml
      - /var/lib/docker/volumes/dashy/meters.yml:/app/public/meters.yml
      - /var/lib/docker/volumes/dashy/haus.yml:/app/public/haus.yml
      - /var/lib/docker/volumes/dashy/buero.yml:/app/public/buero.yml
      - /var/lib/docker/volumes/dashy/grafana.yml:/app/public/grafana.yml
      - /var/lib/docker/volumes/dashy/icons:/app/public/item-icons/icons

ive changed to 
    volumes:
      - /var/lib/docker/volumes/dashy/:/app/public/

but now i have only the default page

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by defmondo** [comment]
I've had to change 

- /volumes/dashy/my-config.yml:/app/**user-data**/conf.yml

I also had to change the IP port mapping to 4000:8080 instead of 4000:80, not if I mist another update in the meantime.

Tony

**Comment by twsouthwick** [comment]
These are both breaking changes for v3: https://github.com/Lissy93/dashy/discussions/1529

**Comment by CrazyWolf13** [comment]
Hi Tony

Yes you are right, dashy V3 introduced a new to load the config so no more rebuilds are required, and also a lot of other nice things.

The breaking changes were a switch from port 80 to port 8080.

The switch of all configs (not icons or item-icons) to user-data folder.

Do you still experience any problems or does everything work after changing those things?
