### ISSUE TITLE
[QUESTION] Issue running docker command

### ISSUE THREAD

**Issue by dmkw01** [Lissy93/dashy#1599]
### Question

When I run the docker command:-

docker run -d   -p 4000:8080   -v /home/pi/docker/dashy/my-conf.yml:/app/user-data/conf.yml   --name dashy   --restart=always   lissy93/dashy:latest

I get the error:-

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/pi/docker/dashy/my-conf.yml" to rootfs at "/app/user-data/conf.yml": mount /home/pi/docker/dashy/my-conf.yml:/app/user-data/conf.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

The path /home/pi/docker already exists.

What should the correct syntax be?

Thank you.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
Is this path existing?
`/home/pi/docker/dashy/my-conf.yml`

So is the config file already created?
If not please do so by copying the one from github, located in user-data folder.

You could also try the following:
`/home/pi/docker/dashy:/app/user-data`

Let me know if this solves your problem.

**Comment by CrazyWolf13** [comment]
Awesome!
