### ISSUE TITLE
[QUESTION] Cookies or Session states cleared/reset when link clicked?

### ISSUE THREAD

**Issue by hvisage** [Lissy93/dashy#1606]
### Question

I'm using ProxMox, and everytime a link, via Dashy is opened, that link requires a new login session, even though I might have (or had) a logged in session running (that *USUALLY* works in Brave/Firefox when I opened a 2nd/3rd session or re-open a tab/window for with the site URL)

Is it a setting I need to check on Dashy side that would "preserve" the previous sessions?

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
There definitely is no setting for that.

I think dashy just links to proxmox, about the same, like manually entering the link.

Although proxmox is quite aggressive with its session releasing, I've noticed a similar behaviour, possibly they lowered the number in proxmox v8, but couldn't find any post about this.


Here an explanation from Proxmox Staff.
https://forum.proxmox.com/threads/proxmox-gui-session-timeout.46583/post-318462



If there is an active session, within an open tab, and you get to proxmox via dashy, is it asking for login or continues the session?

**Comment by hvisage** [comment]
Here is the problem,
1) Click on the PVE link on my Dashy board
2) I login, 
3) go back to my Dashy board, and click again (new tab)
4) need to log in again

BUT I then copy paste the PVE link(s) in the same browser in a different tab, I'm "in" without needing to login.

THAT is why I asked and wondered about Dashy's work flow that might be triggering it.

**Comment by CrazyWolf13** [comment]
Yeah that definitely shouldn't be the case, can you send your conf.yml

**Comment by hvisage** [comment]
Anonimized version: [dash.conf.yml](https://github.com/user-attachments/files/15521143/dash.conf.txt)

**Comment by CrazyWolf13** [comment]
I've just tested this, and for me opening a new tab of proxmox normally, through the url, proxmox asks me again for login credentials, this is really not something that's related to dashy, dashy is basically just linking you to the url, you provided, there's no way, dashy could manipulate, disable or enabled cookies on you proxmox website.

If there's nothing else, I think this can be closed, as this is an external problem with Proxmox

**Comment by hvisage** [comment]
No,  I've just tested on Brave, macOS, the following:

Dashy -> PVE new tab -> asks login -> login -> go to dashy -> PVE new tab -> asks login -> login (rinse repeat)
copy URL from PVE above
Alt-T (New tab) -> paste -> PVE without login -> Alt-T(New Tab) -> paste -> PVE without login (rinse repeat) -> Dashy -> PVE new tab -> asks for login -> don't login -> Alt Tab (new Tab) -> paste -> PVE asks login -> login -> Alt-T(new tab) -> paste -> PVE doesn't ask login

Thus EVERY TIME I use Dashy to go to a PVE, that environment gets a clearing of sorts, and thus I need to login. 
If I DON'T open via Dashy, but new tab and paste the URL, then (if I recently logged in) the session doesn't require logins.

Thus, Dashy does something, in some way, that does trigger the clearing, and THAT is what I'd like to know what could be the reason.

I don't say it's a bug, but knowing the reason, would make it have the win to understand and (re)design my work flows around it,

**Comment by hvisage** [comment]
> edit: I noticed, when directly accessing proxmox without reverse proxy, the session seems to be kept alive, maybe you need to provide the direct ip inside dashy.

hmm... I am directly accessing them, how/where do you believe I reverse proxy?

**Comment by CrazyWolf13** [comment]
I thought due to domains names being used in the config it was a reverse proxy, but just seen the port numbers, so probably only dns names.

Also seen, that your config still hast some weird quirks of dashy's past:
```
    filteredItems:
      - *ref_0
      - *ref_1
      - *ref_2
      - *ref_3
      - *ref_4
      - *ref_5
```
That leads me to believe, you're running a heavily outdated instance of dashy?

**Comment by hvisage** [comment]
> That leads me to believe, you're running a heavily outdated instance of dashy?

I followed the Netlify instructions

**Comment by Lissy93** [comment]
Only thing I could possibly think of is if you're using mixed protocols (like Dashy on https but your service on http, or visa versa). Or if Dashy is sending over some reffer data that conflicts with what the service is expecting. If that's the reason, I've added the no-refer meta tag (in https://github.com/Lissy93/dashy/commit/768d746cbfcf365c58ad1194c5ccc74c14f3ed3a), so you can try again with the latest version?

But beyond that, there wouldn't be any reason why session or cookie states shouldn't be preserved when visiting from Dashy. Dashy can only ever set, modify or delete session data from it's own domain, and so it wouldn't ever affect other apps.

You could debug this further by looking at the target app under the Storage tab in the dev tools, and checking if the required data is there in either session or normal cookies.
