### ISSUE TITLE
error 404 all of a sudden

### ISSUE THREAD

**Issue by LarryT8959** [Lissy93/dashy#1609]
### Question

All of a sudden, all of my widgets are failing an I've tried everything I know to resolve it. Everything was fine, not sure what caused this.
Fail to load resource: Origin http:// 192.168.10.10:4000 is not allowed by access control allow orgin. Status code 404.
What is this telling me?

<img width="695" alt="Screenshot 2024-06-03 at 12 55 35 PM" src="https://github.com/Lissy93/dashy/assets/81517389/443a1789-a9a0-4138-97f8-f8e77f39f4f7">

<img width="636" alt="Screenshot 2024-06-03 at 12 56 19 PM" src="https://github.com/Lissy93/dashy/assets/81517389/0b3d2fcf-036e-4100-927f-f935be2ef01f">

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi 
Look here for widget troubleshooting:
https://dashy.to/docs/widgets#troubleshooting-widget-errors

In your specific case you can add the following, and the widgets should work again.

```
useProxy: true
```

**Comment by LarryT8959** [comment]
Very strange that this is happening, everything was fine. I’ve been through this before, and inserted “use proxy: true” and finally got it working. Now when I look at the config, I don’t see the line in the widget? All of them are missing? Last update may have changed? Added them back and still have the issue.

name: CPU Usage
    icon: fas fa-tachometer
    widgets:
      - type: gl-current-cpu
        useProxy: true
        label: Imac Docker cpu
        options:
          hostname: http://192.168.50.4:7300 <http://192.168.50.4:7300/>

Any thoughts?

**Comment by CrazyWolf13** [comment]
Hi @LarryT8959 

To be honest, I can't fully understand what you mean.

Does it work after adding the useProxy ?

Please share your full config and describe clearly what your problem is, what you've tried and some exact steps, so I can reproduce the issue.

**Comment by CrazyWolf13** [comment]
Yeah that's correct, as there were changes to glances, they migrated to api v4.

After updating to the latest version and adding useProxy: true everything works again fine, tested with mutiple systems and different users.

Rebuild your container through docker, make sure the tag is set to latest and re-pull the image.

**Comment by LarryT8959** [comment]
Well that didn’t work for me. I deleted the container, reinstalled, and added proxy comment and that didn’t solve the issue. I have to move on from Dashy. This doesn’t make sense.
Thanks

**Comment by CrazyWolf13** [comment]
Yeah you're right!
That's really weird, that shouldn't be happening, can you send the browser logs again, after enabling the proxy?

**Comment by LarryT8959** [comment]
Different errors now.

￼

**Comment by LarryT8959** [comment]
￼

**Comment by CrazyWolf13** [comment]
@LarryT8959 Could you reupload your uploaded images from github?

For me they are not rendered correctly and don't display.

**Comment by LarryT8959** [comment]
<img width="1034" alt="Screenshot 2024-06-03 at 5 25 00 PM" src="https://github.com/Lissy93/dashy/assets/81517389/e767e216-7d00-409a-bcdc-f4dcaa94459e">

<img width="843" alt="Screenshot 2024-06-03 at 4 42 17 PM" src="https://github.com/Lissy93/dashy/assets/81517389/a4fbd4c2-7b0b-444f-b3e3-ff787ae8ec1d">

**Comment by LarryT8959** [comment]
<img width="535" alt="Screenshot 2024-06-03 at 5 21 52 PM" src="https://github.com/Lissy93/dashy/assets/81517389/b8ab73ec-730b-4bb7-b2c3-e9385b9d0b86">

**Comment by CrazyWolf13** [comment]
Hmm, this looks like the Glances server is not correctly set up, are you running the latest version?

Plase share your version number of the installed glances.

**Comment by LarryT8959** [comment]
Looks like 3.4.3.3

**Comment by LarryT8959** [comment]
This has something to do with the glances version. I updated glances on my nas and those widgets are working now. I’ll work on the others now.
Thanks

**Comment by CrazyWolf13** [comment]
Yeah, most likely what happened here, glances updated to apiv4, dashy adapted to apiv4 ant therefore broke apiv3 support, and your specific instance has not yet updated to the new glances version, simply updating the python package on you mac should work.

**Comment by LarryT8959** [comment]
No matter what I do, the PI3 won't work with the widgets. I setup the same way as I did the PI4 I have which is working great.

**Comment by CrazyWolf13** [comment]
Can you verify that the apiv4 works on the server you want to use for the widgets?

For example something like this, please execute oth of those commands, replace the ip and port with your own and show the results here.

```
curl http://192.168.0.10:61208/api/3/pluginslist
```

```
curl http://192.168.0.10:61208/api/4/pluginslist
```

**Comment by LarryT8959** [comment]
Got what looks like a normal response from 3 but an error on 4.
<img width="813" alt="Screenshot 2024-06-12 at 12 39 33 PM" src="https://github.com/Lissy93/dashy/assets/81517389/aff194b8-692c-49b5-85b4-83d09d0b364b">

**Comment by CrazyWolf13** [comment]
Yeah that means, you are still on an old version of glances.

Would you mind sharing, how you installed glances on that machine, so I can try to help you to update glances?

**Comment by LarryT8959** [comment]
I believe I used this stack;
# Docker Compose file version
version: "3"

# Define services to run
services:
  # Service name: glances
  glances:
    # Name of the container
    container_name: glances

    # Docker image to use
    image: nicolargo/glances:3.4.0.3-full

    # Port mapping between host and container
    ports:
      - 7300:61208

    # Environment variables
    environment:
      - TZ=$ America/New_York # Timezone
      - GLANCES_OPT=-w # Glances option to run as a web server

    # Use the host's PID namespace
    pid: host

    # Container restart policy
    restart: unless-stopped

    # Volumes to mount into the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket for monitoring

Don't understand because I used same method on other PI and have no issues. I did try to edit stack to change version but it wouldn't allow it.??

**Comment by LarryT8959** [comment]
I got it! I edited the stack to this! It would't work the other day for whatever reason. Thanks so much, I appreciate the help.
# Docker Compose file version
version: "3"

# Define services to run
services:
  # Service name: glances
  glances:
    # Name of the container
    container_name: glances

    # Docker image to use
    image: nicolargo/glances:latest-full

    # Port mapping between host and container
    ports:
      - 61208:61208

    # Environment variables
    environment:
      - TZ=$ America/New_York # Timezone
      - GLANCES_OPT=-w # Glances option to run as a web server

    # Use the host's PID namespace
    pid: host

    # Container restart policy
    restart: unless-stopped

    # Volumes to mount into the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket for monitoring

**Comment by CrazyWolf13** [comment]
Yeah that's correct, yes updating the tag make docker automatically use tha latest or whatever tag specified on rebuild.

Great to hear, that you got it working.

**Comment by LarryT8959** [comment]
One last thing, I had two instances of glances running on an old iMac I turned into a server. one running in docker desktop (port 7300), and the other running on the macOS (port 61208). I was able to monitor resources on both. Any ideas of why I can't get the one on the Mac to connect to dashy? I have verified they both are version four.
Thanks

**Comment by CrazyWolf13** [comment]
Please share some more info about the macOS instance and the browser conosle logs of dashy.

**Comment by LarryT8959** [comment]
Must be the same issue because I'm getting error on api 4 but not 3 even though it said I'm running version 4 of glances.

**Comment by LarryT8959** [comment]
Same error
![Screen Shot 2024-06-12 at 4 39 53 PM](https://github.com/Lissy93/dashy/assets/81517389/e825aa2f-6290-48be-9451-48e4e479cf94)

**Comment by LarryT8959** [comment]
Other instance. I just can figure out how to install the new version on macOS. I used home-brew to install if I can remember correctly. When I run "brew upgrade glances" is says glances is not installed? But it is an I can reach it.
![Screen Shot 2024-06-12 at 4 41 22 PM](https://github.com/Lissy93/dashy/assets/81517389/f08350a9-9ec5-4fc2-b5c6-67f9b93b201b)

**Comment by CrazyWolf13** [comment]
Hi you can try the following, if you installed glances using brew: 

```
brew update
brew upgrade glances
glances -v
```

If you installed using ports:
```
sudo port selfupdate
sudo port upgrade glances
glances -v
```

Otherwise you can try to loon into taskmanager or something like that, to find the process and how it's started.

**Comment by LarryT8959** [comment]
I can't get past this message. Disable home-brew no install cleanup? I need to figure this out. I get this when I try to reinstall glances.

@Larrys-iMac ~ % brew reinstall glances   
==> Downloading https://ghcr.io/v2/homebrew/core/glances/manifests/4.0.8
Already downloaded: /Users/larrythompson/Library/Caches/Homebrew/downloads/2775a675706dd8cef14632c4790f39a275e3c12b59dfb686b70eb30791e4f261--glances-4.0.8.bottle_manifest.json
==> Fetching glances
==> Downloading https://ghcr.io/v2/homebrew/core/glances/blobs/sha256:480cb774a7
Already downloaded: /Users/larrythompson/Library/Caches/Homebrew/downloads/688e4c408f0a3e4515ffac30a9180cd0bad44fc46b81a98c3d08c6e24e84f693--glances--4.0.8.monterey.bottle.tar.gz
==> Reinstalling glances 
==> Pouring glances--4.0.8.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/glances/4.0.8: 288 files, 4MB
==> Running `brew cleanup glances`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

**Comment by LarryT8959** [comment]
Removed glances and reinstalled using ports.
This is the error  I'm getting;
FastAPI import error. Glances cannot start in web server mode

**Comment by CrazyWolf13** [comment]
Hi to be honest I also don't know this, as I don't own a mac and never use brew.

As the dashy side is working I suggest creating an issue on their github, I'm sure they are able to help you.

**Comment by LarryT8959** [comment]
Thank you. I ended up getting it but don't completely understand what and why? The first thing I did was to delete the docker instance of glances, removed pip and brew then started over. Once I got that instance going, I added the docker instance.
