### ISSUE TITLE
SEVERE bug in Dashy - looping reinstall after adding basic auth to conf.yml

### ISSUE THREAD

**Issue by don-ferris** [Lissy93/dashy#1614]
### Environment

Self-Hosted (Docker)

### System

Mint 21.3

### Version

3.1.1

### Describe the problem

I put the finishing touches on Dashy while I was at work today. Had _everything_ right where I wanted it including customizing the colors on Material Dark theme. A couple hours and I went back to it, expecting to be logged out. At that point, I realized there _was no_ login. So I went to the docs and realized this is not a default feature in Dashy. So I added basic auth as per the instructions in the docs. Logged in and logged out a couple times - great! 

I came back to it an hour or so later and I couldn’t get to it. I mean it was just down. So I came home and accessed it locally. I got a screen saying Dashy was ”Initializing”…
![IMG_1159](https://github.com/Lissy93/dashy/assets/109878120/182ad820-c22c-4491-af39-e3b7c57e326d)
And when it finished, I got all my groups - but they were empty; no items. When I logged in, one of my groups (the one I setup a couple days ago) had items in it but none of the groups I’ve created/populated since then.

So I restarted the container, hoping for the best. When it came up, I got the “ Initializing”. When it finished and I logged in, same result - all my groups empty except for the one I setup a couple days ago. Now I was curious, so I restarted the container again. “ Initializing” screen AGAIN.

Everything worked great ‘til I added the basic auth.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hmm that kinda sounds like a caching issue, could you try clearing cache and cookies?

**Comment by don-ferris** [comment]
Done. Same result.

**Comment by CrazyWolf13** [comment]
Could you post your conf.yml, and your log?

**Comment by don-ferris** [comment]
I'm unclear on "log". Is that the name of the file? Can you tell me where exactly to find it?
conf.yml:
pageInfo:
  title: Mission Control
  description: Donnie Ferris's Homelab
  navLinks:
    - title: Bookmarks
      path: https://bookmarks.donferris.me
      target: newtab
    - title: GitHub
      path: https://github.com/donferris
      target: newtab
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
appConfig:
  theme: material-dark
  layout: horizontal
  iconSize: small
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: true
  statusCheckInterval: 60
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    users:
      - user: admin
        hash: 14656ad68233df29c17dd8e462f063c22fb1318
        type: admin
      - user: guest
        hash: 8be0b5445fca6eb16d14c6f4eaff1cf1d1a3362
    enableGuestAccess: true
    enableOidc: false
    oidc: {}
    enableHeaderAuth: false
    headerAuth:
      userHeader: REMOTE_USER
      proxyWhitelist: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
sections:
  - name: Management
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: true
    items:
      - title: Lab Docs
        icon: fas fa-file
        url: https://labdocs.donferris.me
        id: 0_1021_labdocs
      - title: Yacht
        icon: fas fa-ship
        url: https://yacht.donferris.me
        id: 1_1021_yacht
      - title: Portainer
        icon: fas fa-anchor
        url: https://portainer.donferris.me
        target: newtab
        id: 2_1021_portainer
    icon: fas fa-wrench
  - name: Services
    icon: fas fa-bolt
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
  - name: Websites
    icon: fas fa-atom
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
  - name: Media
    icon: fas fa-film fas fa-music
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items: []
  - name: Dashy
    icon: fas fa-rocket
    items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
        id: 0_505_dashylive
      - title: GitHub
        description: Source Code, Issues and Pull Requests
        url: https://github.com/lissy93/dashy
        icon: favicon
        id: 1_505_github
      - title: Docs
        description: Configuring & Usage Documentation
        provider: Dashy.to
        icon: far fa-book
        url: https://dashy.to/docs
        id: 2_505_docs
      - title: Showcase
        description: See how others are using Dashy
        url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
        icon: far fa-grin-hearts
        id: 3_505_showcase
      - title: Config Guide
        description: See full list of configuration options
        url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
        icon: fas fa-wrench
        id: 4_505_configguide
      - title: Support
        description: Get help with Dashy, raise a bug, or get in contact
        url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
        icon: far fa-hands-helping
        id: 5_505_support
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: true
      hideForGuests: false
`
That was a little difficult. I got it through a shell executed from Portainer and I had to copy and paste it 25 lines at a time. So I left out the custom colors section which I assume you don't really need.

**Comment by Lissy93** [comment]
If you role back your most recent change, does everything work again?
If clearing browser data didn't help, killing and restarting the container should fix it.

Rest assured, your config data should be fine, and unaffected. Dashy won't write anything to that file without you saving changes, and backups are always made in the user-data dir.
