### ISSUE TITLE
[SHOWCASE] <A Simple Dash>

### ISSUE THREAD

**Issue by rahul-sha** [Lissy93/dashy#1616]
### Title

A Minimal Dash for a basic Plex Server

### Screenshot

![image](https://github.com/Lissy93/dashy/assets/17428129/15d99884-bde3-4a33-b84f-743406f0fb57)

### Would you like your name/ username included?

Yes

### Description (Optional)

Finally settled on a minimalistic dash for my very first NAS experience. Tried to go with more widgets.. but didn't like the clutter and instead use Grafana for overall monitoring.

**Comment by k8seren** [comment]
Hello! Looks awesome. I'm new to Dashy - can I ask how you got the Status indicator for Plex to work/how you have that item configured? My other self-hosted app Status indicators are working properly, but I'm stuck on Plex. thanks for any help!

**Comment by rahul-sha** [comment]
> Hello! Looks awesome. I'm new to Dashy - can I ask how you got the Status indicator for Plex to work/how you have that item configured? My other self-hosted app Status indicators are working properly, but I'm stuck on Plex. thanks for any help!

Here you go:
![image](https://github.com/Lissy93/dashy/assets/17428129/c85ae363-d994-49a8-b636-8baf0282ce09)

It's a round about way of checking it. So if Plex is offline (in my case, the docker container) neither of these codes(401, 403) will post. Seems to do the job.
