### ISSUE TITLE
[QUESTION] <Dose it fit for Rack mate T1 mini chassies ?>

### ISSUE THREAD

**Issue by yoyojacky** [Lissy93/dashy#1621]
### Question

I have build my own cluster and want to use this repository to build my own dashboard , does it support on rack mate T1 mini chassis by 52Pi ? here is the product url: [h](https://deskpi.com/collections/deskpi-rack-mate)

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi,

Not sure what you mean, but dashy has nothing to do with a rack mount.

Here you can see a list of how to deploy dashy:
https://dashy.to/docs/deployment

**Comment by yoyojacky** [comment]
> Hi,
> 
> Not sure what you mean, but dashy has nothing to do with a rack mount.
> 
> Here you can see a list of how to deploy dashy: https://dashy.to/docs/deployment

Oh, let me see, I mean, I want to monitor my rack mount cluster by using the dashy on my raspberry Pi.

**Comment by CrazyWolf13** [comment]
Oh that makes a lot more sense.

You can monitor using the build it widgets, or using glances:

https://dashy.to/docs/widgets

Or you could even do things like setting up any monitoring system and then creating an iframe over it, for example Telegraf+InfluxDB + Grafan and then iframe Grafana to Dashy.

**Comment by yoyojacky** [comment]
> n creating an iframe over it, for example Telegraf+InfluxDB + Grafan
Oh, I see, thank for your tips, that help me a lot ,thanks bro! have a nice day!

**Comment by CrazyWolf13** [comment]
Sure, no problem, if you have further questions, don't hesitate to write again here.

But if there are no more questions, I'll close this issue for now.
