### ISSUE TITLE
[BUG] Favicon not loading, console errors

### ISSUE THREAD

**Issue by evroon** [Lissy93/dashy#163]
The Favicon is not loading for me on Firefox, which did work a while ago.
Also, 

It returns 404s for: 
* `<domain>/img/icons/apple-touch-icon-152x152.png`
* `<domain>/img/icons/favicon-16x16.png`

Also, Firefox says the mime type of a stylesheet is incorrect:
`The stylesheet https://<domain>/# was not loaded because its MIME type, “text/html”, is not “text/css”.`

Chrome does not give the error above, but another error:
`InitServiceWorker.js:82 Error during service worker registration: TypeError: Failed to register a ServiceWorker for scope ('https://<domain>/') with script ('https://<domain>/service-worker.js'): ServiceWorker script evaluation failed`

I run Dashy 1.5.9 using the arm32v7 Docker image on a Raspberry pi.

**Comment by MilesTEG1** [comment]
Hello,
I don't have the dashy favicon too but only with Firefox, it's present with MS Edge...
Is there a way to have it in firefox ?

**Comment by DrAg0n141** [comment]
I have the Problem too with the "generative" Icons.

**Comment by jhelmink** [comment]
The `generative` icons API/Server has gone down. This should be removed from the docs.

favicons are coded in lots of different ways for different apps and sites, suggest you specify a manual URL for the ico/png, or use `icon: si-firefox`

https://github.com/Lissy93/dashy/blob/master/docs/icons.md

**Comment by Lissy93** [comment]
Thank you @jhelmink for the heads up about the Generative Icons no longer working. 

Have made an update in #261 for V-`1.8.5` to point it to a new API, so this should now be working again :)

<p align="center"><img width="385" src="https://i.ibb.co/b2pC2CL/generative-icons-2.png" /></p>

**Comment by evroon** [comment]
> 
> 
> The `generative` icons API/Server has gone down. This should be removed from the docs.
> 
> favicons are coded in lots of different ways for different apps and sites, suggest you specify a manual URL for the ico/png, or use `icon: si-firefox`
> 
> https://github.com/Lissy93/dashy/blob/master/docs/icons.md

I'm a bit confused by this. I think you are talking about fetching favicons of services that are displayed in Dashy. I was talking about the favicon of Dashy itself, which is part of this repository and is (AFAIK) not fetched from an external source.

**Comment by evroon** [comment]
In the html, there are two favicons that return 404s:
```html
<link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png">
<link rel="apple-touch-icon" href="/img/icons/apple-touch-icon-152x152.png">
```

**Comment by Lissy93** [comment]
Yup, you are right - I was just replying to drag0n141 and Josh, who mentioned that generative icons were not working. Separate issue, I know.
