### ISSUE TITLE
[BUG] Failed to deploy: out of memory

### ISSUE THREAD

**Issue by FortiterInRe** [Lissy93/dashy#1634]
### Environment

Self-Hosted (Docker)

### System

18.09.1

### Version

3.1.1

### Describe the problem

When I tried to initialize my dashy, errors happened:
```
<--- Last few GCs --->

[60:0x7f7eca94e650]    94304 ms: Scavenge 615.7 (631.7) -> 614.6 (636.2) MB, 40.61 / 0.00 ms  (average mu = 0.386, current mu = 0.333) allocation failure; 
[60:0x7f7eca94e650]    95952 ms: Mark-Compact (reduce) 618.3 (636.5) -> 616.5 (631.7) MB, 973.16 / 0.02 ms  (+ 296.0 ms in 55 steps since start of marking, biggest step 20.8 ms, walltime since start of marking 1574 ms) (average mu = 0.374, current mu = 0.

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 
Then I used htop to figure out the cause: vue-cli-service took up too much memory and led to crash. I had found that another issue reported the same problem: [https://github.com/nodejs/node/issues/37150](url). Could you please modify the configuration of vue or use any alternate to fix it? Thanks!

### Additional info

It happened during build-time.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi 
That means dashy is out of memory, how much ram do you have/ how much is available and how much is available for dashy ?

**Comment by CrazyWolf13** [comment]
Hi 
Okay I see.

How much ram do you have on your system?

Please share some general information about your hardware.

**Comment by FortiterInRe** [comment]
> Hi Okay I see.
> 
> How much ram do you have on your system?
> 
> Please share some general information about your hardware.

Debian 10 64 Bit, 1.25GB ram and 1GB swap, 1 cpu core

**Comment by CrazyWolf13** [comment]
I core and just 1.25gb ram seems really really little, could you extend it, to say to 2gb ram and 2 core, if It's a VPS?

**Comment by FortiterInRe** [comment]
> I core and just 1.25gb ram seems really really little, could you extend it, to say to 2gb ram and 2 core, if It's a VPS?

Yeah, it is. Since it is simply because of low memory volume, I will close it and try another way. Besides, could you please add a tip of lowest requirement to your README, in order to warn people like me?

**Comment by CrazyWolf13** [comment]
Hi

Since upgrading to V3 more problems with low amounts of ram/cpu have appeared, but since neither I nor lissy are able to reproduce, we are always happy to get some debug infos and try to investigate further into this.

Here is already an open issue about your request, where we will keep track of this issue, and either lift the min. Requirements or fix an issue, so I'll close yours as a duplicate.
 https://github.com/Lissy93/dashy/issues/1585
