### ISSUE TITLE
[BUG] Dashy crash on startup if IPv6 used

### ISSUE THREAD

**Issue by demetrius2003** [Lissy93/dashy#1642]
### Environment

Self-Hosted (Bare Metal)

### System

win10

### Version

Using Dashy V-3.1.1.

### Describe the problem

Please replase banner to this:
```
    // Prepare message for users running app on bare metal
    msg = `${chars.GREEN}┏${line(83)}┓${chars.BR}`
      + `┃ ${chars.CYAN}Welcome to Dashy! 🚀${blanks(60)}${chars.GREEN}┃${chars.BR}`
      + `┃ ${chars.CYAN}Your new dashboard is now up and running at ${chars.BRIGHT}`
      + `http://${ip}:${port}${chars.RESET}${blanks(26 - ip.length)}${chars.GREEN}┃${chars.BR}`
      + `┗${line(83)}┛${chars.BR}${chars.BR}${chars.RESET}`;

```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi

Currently IPv6 is not really supported / only alpha, you can check out this for a explanation and a possible workaround.

https://github.com/Lissy93/dashy/issues/979

So I will close this as a duplicate.
