### ISSUE TITLE
[BUG] crash while trying to install

### ISSUE THREAD

**Issue by kittenvr** [Lissy93/dashy#1645]
### Environment

Self-Hosted (Docker)

### System

debian

### Version

latest i think

### Describe the problem

when i run the command from the website i get an error

### Additional info

 sudo docker run -d   -p 8080:8080   -v ~/my-conf.yml:/app/user-data/conf.yml   --name my-dashboard   --restart=always   lissy93/dashy:latest
docker: Error response from daemon: Conflict. The container name "/my-dashboard" is already in use by container "a1ed5f996baf74e1b1875e7f2838376009c3d5fcf718a9fc50d1a3e3a95ed8ad". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi seems like you already have a container named my-dashboard, try a different name or delete the old if not used anymore.

Then the command should work fine :)

**Comment by kittenvr** [comment]
what command to delete it

**Comment by CrazyWolf13** [comment]
I suggest you familiarize yourself first with docker a bit, here are some basic tutorials:
https://youtu.be/eGz9DS-aIeY
https://youtu.be/94VQvRpjfO8

**Comment by CrazyWolf13** [comment]
@kittenvr  Could you resolve the issue?

**Comment by kittenvr** [comment]
I think so

**Comment by highfillgoods** [comment]
even after removing the container it was still around. had to do a prune.

docker system prune
docker system prune -a --volumes
