### ISSUE TITLE
[BUG] Update from 2.1.2 to 3.1.1 Get refused connect.

### ISSUE THREAD

**Issue by nickm324** [Lissy93/dashy#1653]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 21.04 

### Version

2.1.2

### Describe the problem

When updating docker container from 2.1.2 to 3.1.1 version of dashy after install log shows dashy is running and config file is fine but when you try and access it you get "Refused to Connect".
Rolling back to version 2.1.2 allows dashy to once again to be accessible.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
In regular update versioning a update in the first number, e.g. from 2-3 there are breaking changes, look here on what changes and has to be adapted:


https://github.com/Lissy93/dashy/discussions/1529

**Comment by nickm324** [comment]
> In regular update versioning a update in the first number, e.g. from 2-3 there are breaking changes, look here on what changes and has to be adapted:
> 
> #1529

Thanks for pointing me to this discussion. This info should probably be in the troubleshooting or more obvious on the read me.

**Comment by CrazyWolf13** [comment]
It's on the very top of the readme, was announced multiple times in releases and multiple times in discussions, so I guess that's enough.
