### ISSUE TITLE
[QUESTION] How should I share a working authentik OIDC configuration?

### ISSUE THREAD

**Issue by dasunsrule32** [Lissy93/dashy#1664]
### Question

I'm opening this up because I worked on getting `authentik` working with Dashy last night. I'm authenticating successfully and it's picking up groups successfully. I can hide pages/sections, etc based on `authentik` group membership.

The only thing I haven't figured out is how to differentiate admins and users. I am looking for information on that if you could share how I can do that in Dashy. Maybe assigning an OIDC group to a `type: admin`. Not sure if that is implemented or not.

How would you like this information shared with the community? I can open a PR against the docs and add it there if you'd like. Thank you in advance.

### Category

Authentication

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
Thanks!

Yeah the best will probably be to add this to the authentication docs on the oidc section in a subsection examples -> authentik.

Feel free to clone make the changes, push and open a PR.

For the differation from admin and user I allow myself to ping @twsouthwick as he was so kind and made this PR.

Thanks!

**Comment by dasunsrule32** [comment]
Thank you. I hope there is a way differentiate. I'll open a PR with the documentation changes.

**Comment by CrazyWolf13** [comment]
As the PR got merged, I'll close this.
Thanks again! ✨

**Comment by CrazyWolf13** [comment]
Oh apologies, overlooked that it's also an issue, due to the nature of this thread and it being tagged as question, I'd rather create a new one, and directly tag [twsouthwick](https://github.com/twsouthwick)

**Comment by dasunsrule32** [comment]
Done. https://github.com/Lissy93/dashy/issues/1675
