### ISSUE TITLE
[BUG] The attempt to rmdir the dist folder prevents cache the dist on an NFS share

### ISSUE THREAD

**Issue by chevdor** [Lissy93/dashy#1666]
### Environment

Self-Hosted (Docker)

### System

K8S

### Version

3.1.1

### Describe the problem

Dashy builds in `/app/dist` and unlike `user-data` that is customizable via ENV, `/app/dist` seems to be hardcoded (please tell me if this is not the case).

I was thrilled to read:
<img width="688" alt="image" src="https://github.com/user-attachments/assets/e67519c4-8091-42d7-bfa5-f59f30e75c3a">
and it looks like it is not very close to be true for most scenarii... but not yet for all :)

<img width="615" alt="image" src="https://github.com/user-attachments/assets/168fc460-4cf9-4380-a380-b2122e508042">

Dashy itself does not need much resources, and since my K8S limits are low, I alos run into a:
<img width="655" alt="image" src="https://github.com/user-attachments/assets/82855083-ad58-48cf-ab14-45c6ba5b7f95">
which should be read as "it is ok, it just takes longer than expected".

Since the build takes a while, to avoid a new build, I considered mounting a volume for `/app/dist`.
This however fails when using a NFS share since, during the build, dashy attempts to `rmdir /app/dist` and the root of a NFS share cannot be removed.

I understand that wiping the dist folder is easier when an upgrade is required.
I hope it triggers only on upgrades btw :)

This NFS issue is not typical to dashy (people often run into it when using NFS shares, k8s and databases for instance). The Solution is known and simple: let the user define the `/app/dist` location with an ENV. This would allow telling dashy to work in say `/app/dist/subdist` (`subdist` is an example, it could be `foobar`, the key point is that it is a folder under the `/app/dist` mounting point).

The NFS share is then still mounted as `/app/dist` but using a sub folder, allows to let the build script to control the `subdist` folder (and remove it). It is not possible and won't be possible for the build script (or anything else for that matter) to rm/chmod/chown the root of the NFS share, in this example `/app/dist`. 

```
Using Dashy V-3.1.1. Update Check Complete
✅ Dashy is Up-to-Date
-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
 ERROR  Error: EBUSY: resource busy or locked, rmdir '/app/dist'
Error: EBUSY: resource busy or locked, rmdir '/app/dist'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi

This has been discussed before: https://github.com/Lissy93/dashy/issues/1570

Dashy's config loading is fully dynamic, however smaller things like adding files (icons), changing default view, auth.... still require a rebuild, and as lissy was a bit busy, we tried without the rebuild on the container reboot, however this lead to quite some issues and we hotfix/reverted this back to the `yarn build-and-start` command.

I will close this issue as a duplicate.
