### ISSUE TITLE
[FEATURE_REQUEST] Route widget traffic through backend instead of (client)

### ISSUE THREAD

**Issue by B4T3S** [Lissy93/dashy#1670]
### Is your feature request related to a problem? If so, please describe.

I would like to monitor my server hardware using dashy, which only shows up when logged in. This itself works fine, but I would prefer not exposing glances to the public.

I currently have glances running in an internal docker-network that dashy can access, but which is not accessible from the outside.

### Describe the solution you'd like

Preferably, this would be a config flag you can set for each glances widget, which - if enabled - simply routes all requests to the glances instance through dashy first.

So for example the config for the `current-cpu` widget could look like this:
```yml
- type: gl-current-cpu
  label: CPU
  options:
    hostname: http://glances:61208
    dashy_proxy: true
```

Routing *any* request through dashy could of course open up some attack vectors, so we should be able to limit the domains that can be proxied through a config entry. Something like this:
```yml
- allowed_proxy_domains:
  - glances
  - google.com
  - some.internal.url
```

Any domain that is not on this list should return an error message.

The proxy itself could be a simple endpoint for dashy itself, like
```
https://my.dashy.app/proxy/<URL-To-Request>
```
### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Yes!

**Comment by B4T3S** [comment]
(Also github auto-assigned you @CrazyWolf13 I don't know if that is supposed to happen, but sorry for the ping either way ^^")

**Comment by CrazyWolf13** [comment]
Hi @B4T3S  

Yeah I occasionally help on the Dashy project, and help managing it.

I agree this would be a really good feature, and could be extended to any widget, to route the traffic through the backend, instead of client.

**Comment by B4T3S** [comment]
I'm not an expert web-dev. But I could take a crack at implementing this feature myself when I get off of work. 
I recon the basic implementation should be pretty straightforward ^^

**Comment by CrazyWolf13** [comment]
That's awesome! 🚀✨

Yeah currently there are quite some things to do on dashy, so contributions and PR's are always welcomed! 🫶

**Comment by B4T3S** [comment]
After poking around the code (and the docs after that) I found out that the option `corsProxy` does basically exactly what I described in the original issue, minus the domain sanity checks. So I suppose this is good case of RTFM 😅

I'm gonna go ahead and close the issue for now, feel free to re-open if it would make more sense to implement a second version of this that doesn't mess with the CORS headers! Although I don't think that should matter for most applications ^^
