### ISSUE TITLE
[QUESTION] How can I restore dashy_conf.yml  ?

### ISSUE THREAD

**Issue by AndKe** [Lissy93/dashy#1671]
### Question

so I did backup using a dashy_conf.yml , but how(where in the UI) do I restore it?

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi
This depends on how you backed up dashy, did you use cloud backup?
Then you need the ID and Password which were showed during the backup.

Otherwise, they should be located in /app/user-data/config-backups, mostly you should have user-data folder mapped to a folder on your host through a docker volume.

**Comment by AndKe** [comment]
I backed up using the view(Export config:
![image](https://github.com/user-attachments/assets/c2fab2f8-b7ae-44f4-88a7-397b50cd67fd)
then "download as a file"

And I would guess that there is/should be a GUI place to import a exported config (or not?)
How can I insert that data again?

**Comment by AndKe** [comment]
thank you, it worked fine.
