### ISSUE TITLE
[BUG] Linkding Widget Broken

### ISSUE THREAD

**Issue by GitGramm** [Lissy93/dashy#1679]
### Environment

Self-Hosted (Docker)

### Describe the problem

The linkding widget seems to be broken.
Nothing is displayed on my dashboard.
Tested with both selfhosted linkding instance and the demo https://demo.linkding.link
useproxy is set to "true"

Console error message:
Linkding.vue:59 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')

cc: @m42e

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by GitGramm** [comment]
I did some further testing and was able to get the widget diplaying my bookmarks

The following needs to be done:
in dashy-conf.yml
set "tags:"  this is not optional as described in the docs

on linkding
Bookmarks from linkding need to have set a title (which is optional there) to be displayed in the dashy-widget.

**Comment by Wikid82** [comment]
I was coming to report the same thing but was worried it was just me and my inexperience. If you got it working, am I setting it up incorrectly?

![Screenshot from 2024-08-28 13-04-16](https://github.com/user-attachments/assets/345c84ca-c307-4683-b9d3-7d81c0b6cbf9)
![Screenshot from 2024-08-28 13-05-02](https://github.com/user-attachments/assets/680dda3a-e276-48a3-8460-fdafa2f8f140)
![Screenshot from 2024-08-28 13-09-34](https://github.com/user-attachments/assets/6bd86c71-be07-4efa-8ccd-52fcd39dfe6a)

**Comment by GitGramm** [comment]
`My list of tags looks slightly different and i also use the _useProxy:true_ setting.

- type: linkding
  updateInterval: 30
  options:
    host: https://lingding.somedomain.com
    apiKey: my-very-secret-api-key
    useProxy: true
    tags: 
      - MyTag1
      - MyTag2
```

**Comment by Wikid82** [comment]
If you got yours working than I'm sure it's just me. I changed my tag to list format and still nothing. It's more than likely my yml spacing so I'll just keep messing with it until I get it right. I didn't use Linkding before this so it's not going to make or break anything. I'll just use it as an excuse to play with code.
