### ISSUE TITLE
[BUG] Dashy no longer builds from source on a clean install.

### ISSUE THREAD

**Issue by ZanzyTHEbar** [Lissy93/dashy#1684]
### Environment

Other (Specify below)

### System

Debian 12

### Version

3.1.1

### Describe the problem

1. clone
2. `yarn install` <-- install deps, yarn build doesnt even run without this, yet this isnt in the docs. I only knew to do this since i am a developer
3. `yarn build` <-- fails 

### Additional info

```bash
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
⠏  Building for production...

 ERROR  Failed to compile with 1 error                                                                                      9:38:25 AM

 error  in ./src/main.js

Syntax Error: Error: [BABEL] /root/dashy/src/main.js: @babel/preset-env: The plugins/built-ins 'es.array.iterator, es.promise, es.object.assign, es.promise.finally' passed to the 'exclude' option are not
    valid. Please check data/[plugin-features|built-in-features].js in babel-preset-env (While processing: "/root/dashy/node_modules/.pnpm/@vue+babel-preset-app@4.5.19_@babel+core@7.25.2_vue@2.7.16/node_modules/@vue/babel-preset-app/index.js.overrides[0]$0")
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)
    at cachedFunction.next (<anonymous>)
    at loadPresetDescriptor.next (<anonymous>)
    at recursePresetDescriptors.next (<anonymous>)
    at recursePresetDescriptors.next (<anonymous>)
    at Generator.next (<anonymous>)
    at loadFullConfig.next (<anonymous>)
    at transform.next (<anonymous>)


 @ multi ./src/main.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by CrazyWolf13** [comment]
Hi 

What version of node are you running?

Can you test the following?

```bash
git clone https://github.com/lissy93/dashy
yarn --ignore-engines
yarn build-and-start
```
