### ISSUE TITLE
[QUESTION] context for french translation

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#169]
Hello,

In order to update the fr json file
Can you tell me (screen?),  When (context?) the following mesages are displayed?

thank you so much

```
    "proceed-to-dashboard": "Proceed to Dashboard",
    "proceed-guest-button": "Proceed as Guest"
```

**Comment by Lissy93** [comment]
Ah yes, good question - this is for guest mode.

When guest mode is enabled, and the user navigates to the login page, there is a button that lets them skip login and have read-only guest access the dashboard, like this:

![image](https://user-images.githubusercontent.com/1862727/130284761-a19c0694-96a2-4147-9555-94af66c00509.png)

The second bit of text probably isn't needed, it's for when the user is already logged in, and they manually navigate to the login page, it looks like this:

![image](https://user-images.githubusercontent.com/1862727/130284916-da7c8cf9-a366-48c2-80eb-412cc6125f55.png)

**Comment by EVOTk** [comment]
Thx for your reply :)
#170
