### ISSUE TITLE
Configuration frame stucked

### ISSUE THREAD

**Issue by shadowking001** [Lissy93/dashy#17]
Hello (again),

When I'm cliking on the wrench, I end up on the config menu but I can't navigate between tabs in the upper part of the frame.
Plus, of the six buttons on the landing config page only download config and reset local settings are effective.

I tried with Chrome and Firefox, normal and private mode. Same behaviour.
Using a reverse proxy to access dashy URL, I'll use an IP to see if it behaves differently.

**Comment by Lissy93** [comment]
Hmm that's weird, not come across that before - sorry about that. Would you mind opening up the dev tools (usually F12), going to the console tab, and copy pasting the error message? That should show what's causing the issue.

**Comment by shadowking001** [comment]
There are errors indeed :

![dashy_config_1](https://user-images.githubusercontent.com/43928955/121089289-383fa500-c7e7-11eb-832f-3ce159667538.PNG)

**Comment by shadowking001** [comment]
I can confirm that it's not related to the reverse proxy setup.
I can also confirm that it is not related to false-positive adblocking.

**Comment by shadowking001** [comment]
Another problem, when I open the config tab, I can't find a way to close it without reloading the page ?
I don't see any closing cross nor escape on keyboard or closing cross.

**Comment by Lissy93** [comment]
Really sorry about that- was my mistake. I've fixed it now with [this](https://github.com/Lissy93/dashy/pull/18) PR. The updated Docker image should be pushed in a few minutes

**Comment by Lissy93** [comment]
Okay the new image is now live on docker hub, so a fresh pull of `:latest` should fix this. That PR should also have fixed the issue with closing the popup too. To close the modal, just click anywhere outside of it, or press Esc. I will add a dedicated close button in a future PR, as I think that will be more intuitive. But let me know if that, or anything else is still not working

Thank you very much for all your feedback - I'm working on some unit tests at the moment, and that should prevent any regression bugs sneaking into future releases :)

**Comment by shadowking001** [comment]
Works perfectly, thank you.
I'm really enthousiast about your work, if I can help I'll do, I wish I were a developer and could directly write up push requests.
