### ISSUE TITLE
[BUG] Granular access not consistent across Minimal & Workspace views.

### ISSUE THREAD

**Issue by lue30499** [Lissy93/dashy#172]
### Environment

Self-Hosted (Docker)

### Version

V1.6.4

### Describe the problem

Hi,

Thanks for implementing the granular access 😀.

I've noticed that the restrictions of:
hideForUsers
showForUsers

(Maybe hideForGuests but I haven't tested)

Doesn't apply to the Minimal & Workspace views. It does work in the Default view.

Regards,
Lue-

### Please tick the boxes

- [X] You are using the latest, or recent version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Ah you're right, sorry about that, looks like I wrote the checking code in the wrong place 🤦 - that's quite a big bug. 
I will this that this afternoon, thanks for reporting :)
