### ISSUE TITLE
[BUG] error "should be object" on auth propertie

### ISSUE THREAD

**Issue by MilesTEG1** [Lissy93/dashy#176]
### Environment

Self-Hosted (Docker)

### Version

1.6.5

### Describe the problem

When I edit the configuration in the UI, I see a warning icon ⚠️  (see screenshot) saying : 
> contains invalid properties

This is the `auth` on witch there is a problem : 
> should be object

### Additional info

![image](https://user-images.githubusercontent.com/29298312/130355548-4addeaa8-0b12-4841-9276-765a29359481.png)

The yml config file is like this : 
![image](https://user-images.githubusercontent.com/29298312/130355738-533ebd3b-d4b9-4a63-a05e-7c14b576ee25.png)
It's like your example auth config : https://github.com/Lissy93/dashy/blob/master/docs/authentication.md#setting-up-authentication

### Please tick the boxes

- [X] You are using the latest, or recent version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Take a look at the [Authentication Docs](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md)

**Comment by Lissy93** [comment]
If you open up the console you should see a message, basically #174 involved some changes to the auth object to allow for more advanced authentication methods. The previous structure will continue to work just fine, but you'll see a validation warning, and a message informing you how to fix it in the console. There is a note about this in the [Troubleshooting Guide](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#auth-validation-error-should-be-object), and you can see more info about authentication in the [Authentication Docs](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md) 

But basically you need to replace:

```yaml
auth:
- user: xxx
  hash: xxx
```

with

```yaml
appConfig:
  auth:
    users:
    - user: xxx
      hash: xxx
```
Hope that helps :)

**Comment by MilesTEG1** [comment]
@Lissy93 
Oh !!! I swear I read the doc... but my eyes didn't see then the differences I see now... :sweat_smile:
Thank you for bringing me the solution.
Next time, I'll read more carefully the doc :innocent:
