### ISSUE TITLE
[BUG] Simple Icons not being loaded

### ISSUE THREAD

**Issue by frybin** [Lissy93/dashy#188]
### Environment

Self-Hosted (Docker)

### Version

1.6.8

### Describe the problem

Setup section items to use sa-[icon_name] and they are failing to load.

### Additional info

![Screenshot_2021-08-29-121533](https://user-images.githubusercontent.com/17693407/131257498-b0dc36c2-fe16-4780-89ad-fa7d70326553.png)
![Screenshot_2021-08-29-121424](https://user-images.githubusercontent.com/17693407/131257500-9f089bd0-6fae-4d1b-b8d6-f2ce0bc8ff7f.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hey @frybin - Thanks for your issue.
Looks like you've got a typo in your icon name. SimpleIcon icons need to be prefixed with `si-` (not `sa-`). Try updating your config, and this should work. You can reference the [Icon Docs](https://github.com/Lissy93/dashy/blob/master/docs/icons.md#simple-icons) to learn more.
