### ISSUE TITLE
[BUG] Can't serve SVG files

### ISSUE THREAD

**Issue by IzeQube** [Lissy93/dashy#199]
### Environment

Self-Hosted (Docker)

### Version

1.7.0

### Describe the problem

I put a few PNG und SVG files in my icons-folder. The PNG files work without problems, the SVG files don't work.
The embedded webserver just returns a 404

If I serve the same SVG from a different server everything works.

### Additional info

Error Message in Dev-Tools
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /home-assistant.svg</pre>
</body>
</html>
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Thanks for raising, this is fixed in 412c179 of PR #201 released in V 1.7.1
