### ISSUE TITLE
some error message when I build the docker image

### ISSUE THREAD

**Issue by cerealconyogurt** [Lissy93/dashy#2]
Hi there!

I am receiving some error message when I tried to build the docker image. I am following the instruction `docker build -t lissy93/dashy .`

```
Step 7/13 : RUN yarn install
 ---> Running in bd7dc922e3d6
yarn install v1.22.5
warning package.json: No license field
warning panel@0.1.0: No license field
```
```
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue-js-modal@2.0.0-rc.6" has incorrect peer dependency "vue@2.6.11".
warning " > @vue/cli-plugin-eslint@4.5.12" has incorrect peer dependency "eslint@>= 1.6.0 < 7.0.0".
warning "@vue/cli-plugin-eslint > eslint-loader@2.2.1" has incorrect peer dependency "eslint@>=1.6.0 <7.0.0".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.2.1" has unmet peer dependency "eslint-plugin-import@^2.22.1".
warning " > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
```

I am still able to run the container with the following instruction: `docker run -it -p 8080:80 --rm --name my-dashboard lissy93/dashy` but those messages might be a problem.

**Comment by Lissy93** [comment]
Hi, thanks for raising this. Those are just warnings (rather than errors), and it's fairly common for yarn to output all of this when in verbose mode. I will add the license field into the package.json though, and that will clear it all up. 
Was there anything that was not working?

**Comment by cerealconyogurt** [comment]
Hello!, it works as should be after building the container regardless of the warning messages. I am having other docker related issues that I am pretty sure is not related to those warning messages

**Comment by Lissy93** [comment]
@cerealconyogurt - Just to check, are you still having issues?
I've built a new Docker container (which is now on [Docker Hub](https://hub.docker.com/r/lissy93/dashy)), which is more efficient and should fix your issues.
