### ISSUE TITLE
[BUG] Tooltip Design Makes Words Hard to Read

### ISSUE THREAD

**Issue by shimizurei** [Lissy93/dashy#205]
### Environment

Self-Hosted (Docker)

### Version

1.7.2

### Describe the problem

Hovering over the settings menu: the tooltips used to have a style applied so that you could see the text, but now the words kind of mingle with the text they overlay.

(I am using Play With Docker)

### Additional info

![tooltip](https://user-images.githubusercontent.com/3500094/132216505-f3ca7f8a-b7c2-4328-b58a-a065e20b0c18.jpg)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Ah yeah, that is definitely a bug. I made some recent changes to the tooltip, and didn't notice that it had broken the stylings for it elsewhere. Thanks for raising, I'll try and get this fixed this evening

**Comment by Lissy93** [comment]
Fixed and merged in #207 :)
