### ISSUE TITLE
[FEEDBACK] locale json for spanish

### ISSUE THREAD

**Issue by lu4t** [Lissy93/dashy#216]
Hey Alicia,
I installed your app and it's great. I realized there's no spanish translation and I thought it would be a good idea to give something back. I am not confident doing pull request, and I read you would accept the json file and pull it yourself.
Should you want me to adjust the translation, and reduce (maybe) the number of words I used, just let me know.
Keep on with the good job you're doing. Best regards!!
[es.zip](https://github.com/Lissy93/dashy/files/7145353/es.zip)

**Comment by Lissy93** [comment]
Hey @lu4t - Thanks so much :)
This looks awesome, I really appreciate your time with this. I will implement it into the app this evening, and update you here once it's done.
Ps- sorry for my misbehaving bot! ;)

**Comment by Lissy93** [comment]
Thanks again for this, I've merged it in #222 released in V 1.7.4.
It should be available on Docker in half an hour or so :)

**Comment by lu4t** [comment]
Thanks for this great App!!, I will pull the new image over the weekend 😜
