### ISSUE TITLE
[FEATURE_REQUEST] Have online code editor yml instead of JSON

### ISSUE THREAD

**Issue by gabevenberg** [Lissy93/dashy#243]
### Is your feature request related to a problem? If so, please describe.

It can be confusing when the documentation talks about yml (and indeed the file on the server is yml), but when you edit the configuration in the website, it takes the form of JSON.

### Describe the solution you'd like

It would be nice if the on-disk config and the site code editor used the same config format.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Heya, thanks for your request :)
It's a good point, and I do agree that it's confusing having the two formats. Reason behind it is that, from a technical standpoint it's not easy to work with YAML in the UI, but users (generally) prefer YAML configs over JSON.  But I am actually going to completely scrap the JSON editor, and am working on building a more intuitive UI editor at the moment, which should (hopefully) be much nicer :)

In the meantime, check out this [JSON to YAML](https://www.json2yaml.com/) tool, and the [YAML to JSON](https://www.json2yaml.com/convert-yaml-to-json) version for the reverse. Not totally ideal, I know, but it's half-way there.

I will update you here, on this issue when the new editor is released - should be V 1.9, aiming for 2 weeks from now 🤞

**Comment by Lissy93** [comment]
Going to close as I already have an open ticket for the new config editor on the project board, but your feedback has been taken on board, and I will update you once the UI-based config editor is implemented.
Feel free to reach out again if you have any questions, bugs, feedback, etc :)
