### ISSUE TITLE
[QUESTION] Secure auth method that still has guest acess?

### ISSUE THREAD

**Issue by gabevenberg** [Lissy93/dashy#247]
Reading the [authentication docs](https://github.com/Lissy93/dashy/wiki/authentication#keycloak), It seems like guest access is only possible if using the 'insecure' password method. Is it possible to add support for a more secure authentication system while still giving guests access to the site? (obv still keeping them from changing config or viewing sections that guests are disallowed viewing.)

**Comment by Lissy93** [comment]
So this would be something that you configure in Keycloak, rather than with Dashy. 
Basically kc sits in-front of Dashy, and any non-authenticated user is rejected server side. Modifying that would not be possible, as it'd open up the exact same issues that an adversary could use against the basic auth (cracking the hash) 

I'll have a read though the kc docs and get back to you tomorrow with instructions, if it is actually possible. How are you running keycloak- with Docker, right?

**Comment by Lissy93** [comment]
Generally I do not have much control over the features offered by third-party authentication providers. If there's a feature you want from one of these services, your best bet is going to raise this issue/ submit a PR / create a bounty with their repo.

So here are your options:
- Switch to Authelia, which has a [similar feature set](https://www.authelia.com/docs/features/) but more login options
- Keep your current KC setup, and create guest account(s) on the Keycloak admin interface for each of your friends/ family/ whoever
- Use a [KC extension](https://www.keycloak.org/extensions.html) to provide social login for your guests
- Write a KC extension to provide all of your desired functionality (I think you'll find it easier than it sounds, looks like you have Java experience)
- Use basic auth, but choose a strong password (that can't be reasonably cracked using it's hash), and preferably don't expose your dashboard publicly to the internet. Guest functionality is available out of the box
- Fork the repo and add in whatever functionality you need, and then run your version of Dashy

At this moment in time, I don't plan on adding many new features to the auth system. I don't have much spare time, and added complexity makes testing and securing harder, and there are other authentication providers which manage user control much better than I ever could, and I am focusing on the new UI editor + widget support over the next couple of weeks.

**Comment by Lissy93** [comment]
Heya @gabevenberg - Just checking that these work arounds solve you issue?

**Comment by gabevenberg** [comment]
Thanks. For now Im just using built in auth. There isnt anything really sensitive on there. (anything sensitive has its own auth, as well.)
