### ISSUE TITLE
How can i set a base_url?

### ISSUE THREAD

**Issue by polhaghverdian** [Lissy93/dashy#249]
Hi,

First of all great job on this project. Its the best dashboard i have used.

I want to put dashy behind a reverse-proxy (nginx). However its not possible to do that when i have multiple services running on different paths. All of my services provide a way of adding a base_url in order to have it mapped easily against a reverse-proxy url path.

**Comment by Lissy93** [comment]
Heya, thanks for your kind words :)

So you should just be able to set `BASE_URL` to your sub-URL, as an environmental variable. There's a bit more detail under the web server config section of the [Management Docs](https://github.com/Lissy93/dashy/blob/master/docs/management.md#web-server-configuration).

See also #31 and #193

Hope that helps :) But feel free to reopen the issue if your still having trouble with this

**Comment by polhaghverdian** [comment]
Hi @Lissy93 

Unfortunately the Management Docs does not provide information for docker.

**Comment by UrekD** [comment]
Hey @polhaghverdian 

What about just passing it along to the IP and exposed port of your docker host? 
I for example use NPM (Nginx Proxy Manager) and have dash.domain.com proxy to http://192.168.1.160:4000

**Comment by polhaghverdian** [comment]
@UrekD  Yes you are right that would work. However i like to specify paths for each app. 

for example: 
 - mydomain.com/gitea
 - mydomain.com/jellyfin
