### ISSUE TITLE
[BUG] statusCheck on specific URL returns ENOTFOUND error

### ISSUE THREAD

**Issue by jhelmink** [Lissy93/dashy#251]
### Environment

Self-Hosted (Docker)

### Version

1.8.3

### Describe the problem

`statusCheckUrl: http://homeassistant.local:4357/` 
returns 
`Service Unavailable: homeassistant.local resulted in ENOTFOUND (-3008)`

I was unable to manually check the ping command using my local dashy instance
`http://192.168.1.190:8080/ping?url=https%3A%2F%2Fgoogle.com`
returns
`Cannot GET /ping`

Not sure if it's not parsing my URL correctly and/or I'm not manually testing the ping command properly to see the problem.

### Additional info

![image](https://user-images.githubusercontent.com/4581673/134848536-0661353a-c73e-4904-a92a-2a67e7df0c7a.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Heya, 

So part of this is my fault, I just realized that there's an error I made in the docs (fixed it now in 8d8a362b41ec93e66502f79695b06303fbcb5be1) - I recently renamed the `/ping` endpoint to `/status-check`. 

Do you think you could try manually checking the status again, and share the output for a known online site (like Google), and then the local site your testing, e.g:
`http://192.168.1.190:8080/?&url=https%3A%2F%2Fgoogle.com`
`http://localhost:4000/status-check/?&url=http%3A%2F%2Fhomeassistant.local%3A4357%2F`

Is it only this one app that's not working, or everything? Do you have any custom authentication service sitting in front of your Home Assistant? And is it a self-signed certificate, or non-SSL?

**Comment by jhelmink** [comment]
Hey Lissy,

`http://192.168.1.190:8080/status-check/?&url=https%3A%2F%2Fgoogle.com`
returns
`{"statusCode":200,"statusText":"OK","serverName":"www.google.com","successStatus":true,"timeTaken":751,"message":"âœ… www.google.com responded with 200 - OK. \nâ±ï¸Took 751 ms"}`
Looks like some encoding issues in the response, but it works :)
Status checks for my other services are fine.

Side note: Weird to me that you need to have `...status-check/?&url=...` in the URL after the status check for this to work.
Why couldn't it just be `...status-check?url=...` for the single parameter?

Anyway pinging the HA Observer;
`http://192.168.1.190:8080/status-check/?&url=http%3A%2F%2Fhomeassistant.local%3A4357`
returns
`{"successStatus":false,"message":"âŒ Service Unavailable: homeassistant.local resulted in ENOTFOUND (-3008)"}`
So that is what I'm seeing in the dashy UI.

Check the network status for the request it is parsing the parameter correctly;
![image](https://user-images.githubusercontent.com/4581673/135735083-244e3a4c-7498-4b9e-a944-f8facf824050.png)

I have no authentication in front of the homeassistant instance, and no SSL.
I tried the HA UI endpoint too `/lovelace/` but that produces the same error.

The error message `ENOTFOUND` looks like a Node.js URL parsing failure from what I can tell.

**Comment by Lissy93** [comment]
Possibly try adding a trailing slash? Browsers are pretty good at resolving websites in any format, but Node.js is less so.

I've tried everything to recreate this on my home assistant service, but with no luck. If the endpoint is working with Postman, then it's not an issue with the server, and most likely something in your config. So I'm not sure that there's much more I can do to help with this.

**Comment by jhelmink** [comment]
`homeassistant.local` was returning an IP6 address when pinging, so I think it's due to that.
I just switched to the IP4 IP address instead and it's working fine :)

**Comment by House079** [comment]
I have the same problem. I put direct address in status check url, but it is the same error
