### ISSUE TITLE
[FEATURE_REQUEST] Workspace view item launch in new tab

### ISSUE THREAD

**Issue by jhelmink** [Lissy93/dashy#254]
### Is your feature request related to a problem? If so, please describe.

When in Workspace view the per item `target: newtab` option is ignored and dashy will try to load the target URL into the workspace view. I think this should be honored because usually this is applied to things that don't/won't work in iFrames.

### Describe the solution you'd like

If `target: newtab` is set it should be used even when in workspace view.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Good point, will do this at the same time as #255 :)
