### ISSUE TITLE
[BUG] overflow issue with no-icon setup

### ISSUE THREAD

**Issue by kimpenhaus** [Lissy93/dashy#278]
### Environment

Self-Hosted (Docker)

### Version

1.8.7 / docker:latest

### Describe the problem

Hi Lissy,

me is running dashy with an "no-icon" setup and after updating to the latest version my titles are not displayed any more 😄 I've tried to drill down the problem and found a solution but as I am not an frontend developer it's quite hard to say if that is a good and a proper solution.

My current theme is `Nord-Frost` and item-size is `medium` and it looks like:

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/575109/137604851-4a00ac34-02e3-4f2f-b531-0b1e169a57e2.png">

Same behavior on desktop and mobile

My 2 solutions could be:

1. reduce the min-height of icon.wrapper-medium when running in no-icon mode:

```
.item-icon.wrapper-medium {
    min-height: 2.5rem;
}
```

2. to remove the `item-icon` node when running with no icon

I guess first solution would be needed to be applied to different item sizes.
I've made a screencast to better show the problem I've got and how my `fixes` apply.

Thanks for your time!

### Additional info

![dashy](https://user-images.githubusercontent.com/575109/137604801-14b30252-7e8c-49f7-b0bb-dcb05df807dc.gif)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Heya, yeah that's definitely a bug.
Sorry about that - I made a lot of changes on the previous PR, and looks like I broke this.
I've fixed it now in #280 which will be merged shorty :)
