### ISSUE TITLE
[BUG] Item titles squeeze issue when hovering over them

### ISSUE THREAD

**Issue by EnCz** [Lissy93/dashy#283]
### Environment

Self-Hosted (Docker)

### Version

1.8.7

### Describe the problem

Hey,
we have some weird flickering behaviour when hovering over some items (I guess when the title reaches a certain length):

https://user-images.githubusercontent.com/7642122/137855883-3fded648-2b4a-4c4b-a998-3765e69efe42.mp4

Please let me know if you need more information, happy to help!

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by EnCz** [comment]
@Lissy93 idk exactly why this got auto-closed, please have a look and tell me if you need any more information :) Happy to help out if questions arise.

**Comment by Lissy93** [comment]
Sorry about that, yeah that definitely sounds like a bug, I'll look into it this evening, and hopefully get a fix pushed out :)

**Comment by EnCz** [comment]
> I've fixed this in #284 which should be merged shortly :) Let me know if you have any other issues, or if this doesn't fully fix this one.

Yeah, thank you very much :) Will have a look as soon as the release is up!

**Comment by Lissy93** [comment]
Hey @EnCz - You might have noticed this issue re-appear, I had to revert the change as it caused some items to overlap when using the Material theme. 
✅ Both issues are now fixed, and merged in #285 and should be released via Docker shortly :)
Thank you for your patience, and sorry for that mess-up. Feel free to reach out if you need anything else :)
