### ISSUE TITLE
[QUESTION] How to update using docker-compose?

### ISSUE THREAD

**Issue by mfnalex** [Lissy93/dashy#294]
Hi :)

Thanks for this awesome software! I've been looking for something like this for weeks! Now, to my question :D

How can I update from 1.8.7 to 1.8.8 using docker-compose? I did `docker-compose stop` and then `docker-compose up -d` and thought it will now use the newest version, but it doesn't. I'm not really familiar with docker, so any help would be appreciated :)

**Comment by nate872711** [comment]
CD (into the directory of the compose file)

docker compose down

docker compose pull

docker compose up -d
