### ISSUE TITLE
[FEATURE_REQUEST] CSS font change

### ISSUE THREAD

**Issue by Hakker** [Lissy93/dashy#296]
### Is your feature request related to a problem? If so, please describe.

CSS theming doesn't support font changing.

Also if possible allow local machine fonts to be used. Like Arial, Cambria if the font isn't there you always revert to the default font to begin with.

The second one would be a bonus if not present by default however changing the font would be nice. Now I changed Bee theme since it's mostly what I'd like anyway but I do nor like the font of it and that can only be changed in the js file.

### Describe the solution you'd like

a font option in the css editor.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Forgot to mention, but following your request, have implemented the option to change the font directly through the theme confiscator.

This was merged in #319 and released in V 1.9.1. 

Hope that's helpful, and Happy Christmas :)

<img src="https://user-images.githubusercontent.com/1862727/147394967-98c3b2a6-a38a-4f9b-a0ac-1560ee54ffeb.png" width="300">
