### ISSUE TITLE
[DOCS] Ticket for grammatical updates to the README.md

### ISSUE THREAD

**Issue by royshreyaaa** [Lissy93/dashy#304]
Hello,

There are a few minor grammatical errors in the README.md that I'd like to update. Please assign this to me.

Referencing #303

**Comment by Lissy93** [comment]
Sure, that would be awesome if you could- thank you very much! If you submit a PR, I can approve it :)

**Comment by Lissy93** [comment]
Thank you :)
Merged in f489a92e2898ef58ded981e1f63215c27bcc94a4
