### ISSUE TITLE
Is setting BASE_URL supported?

### ISSUE THREAD

**Issue by MoriTanosuke** [Lissy93/dashy#31]
I want to run _dashy_ on a subpath on my domain (and also behind a reverse proxy) but I can't figure out how to set the vue `BASE_URL` or `publicPath`. I want to deploy the production build to a nginx server.

Does _dashy_ support running from a subpath instead of `/`?

**Comment by Lissy93** [comment]
Yeah, it should be. As you mentioned, Vue uses an environmental variable called `BASE_URL`, and that's what I'm using to include web assets. I just tested it out by setting `BASE_URL=/hello` and then placing the contents of the `dist` directory into `website/hello`, where NGINX is serving up `website`, and then visited `website/hello` and it was working. 

So are you just serving the built app up directly with NGINX, or using Docker, or the Node.js server? Another option, is if `example.com/dashy` isn't easy to get working, you could try `dashy.example.com`.

**Comment by MoriTanosuke** [comment]
I tried to create a multi-stage `Dockerfile` and set the variable, but it did not work for me. Maybe I failed to pass the env var to yarn+vue, I don't know much about those build tools. Here's my Dockerfile:

````
FROM node:lts-alpine

# Define some ENV Vars
ENV PORT 80
ENV DIRECTORY /app
ENV IS_DOCKER true

# Create and set the working directory
WORKDIR ${DIRECTORY}

# Copy over both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# Install project dependencies
RUN yarn

# Copy over all project files and folders to the working directory
COPY . .

# Build initial app for production
ARG BASE_URL=/hello
RUN yarn build

FROM nginx

COPY --from=0 /app/dist /usr/share/nginx/html/hello
````

Nevertheless, I set the [publicPath](https://cli.vuejs.org/config/#publicpath) in `vue.config.js` and that worked for my setup. I need to rebuild the image anyway for _arm64_ because I want to run on my k8s raspberry cluster, so I can keep this change in a local branch.

**Comment by shadowking001** [comment]
Can't you just rewrite the path in your nginx conf file for dashy ?

```
location /dashy {
    return 301 $scheme://$host/dashy/;
}

location ^~ /dashy/ {
    include /config/nginx/proxy.conf; # Include usual proxy settings
    set $upstream_app dashy;
    set $upstream_port 4000;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    rewrite /dashy(.*) $1 break;
}
```
You can poke an eye on how SWAG handles reverse proxy : [https://github.com/linuxserver/reverse-proxy-confs](url)

**Comment by Lissy93** [comment]
Hey @MoriTanosuke - Are you still having trouble with this?

**Comment by MoriTanosuke** [comment]
I solved my issue in my local infrastructure. Thanks a lot for your help.
