### ISSUE TITLE
[FEEDBACK] Add Authelia as an eventual security frontend to Dashy

### ISSUE THREAD

**Issue by shadowking001** [Lissy93/dashy#33]
Hello @Lissy93 

I just stumbled upon your authentication implementation, nice work !
You also mention some alternatives,  I could not enough recommend you to give a word about [Authelia](https://github.com/authelia/authelia).
It allows access-control based on IP, path, users, etc... with a better fine-grained set of rules than base Nginx (it comes on top of Nginx, HAProxy or Caddy afaik).
You can set 2FA, simple password access or bypass policies for your domains.
Runs in Docker and is free.

Great alternative to mention imho. VPN access is quite too much restrictive sometimes (e.g. I can't use VPN at work).

**Comment by Lissy93** [comment]
I just took a look at Authelia - it looks awesome, wish I had come across it sooner! Thanks for the recommendation, I will definitely add it in there :)

**Comment by Lissy93** [comment]
Heya, 
Sorry it took me so long to reply to this. So I guess that setting this up would be something done on the users side, so I've added some [docs](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md#authelia) on doing this. I've also added native support for Keycloak in V 1.6.5 / PR #174.
Alicia :)
