### ISSUE TITLE
[BUG] Warning "should be boolean" on a boolean value for statusCheckAllowInsecure propertie

### ISSUE THREAD

**Issue by MilesTEG1** [Lissy93/dashy#336]
### Environment

Self-Hosted (Docker)

### Version

1.9.2

### Describe the problem

Hello,
I have a warning on a boolean value witch "should be boolean" :
![image](https://user-images.githubusercontent.com/29298312/141779819-0e94e685-556e-4f78-af7e-2b6c7b9756de.png)
![image](https://user-images.githubusercontent.com/29298312/141779849-0f4bb5d5-7178-4bee-83aa-5d77ff9c999c.png)
But it seems it's already a boolean, no ?
What do you think ?

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by EVOTk** [comment]
Hello,
on the beginning of the line change for Auto ?
![2021-11-15 14_42_09-Window](https://user-images.githubusercontent.com/45015615/141791913-021b9894-207f-496d-b6ae-e8b6c96b6c8e.png)
![2021-11-15 14_42_21-Window](https://user-images.githubusercontent.com/45015615/141791915-43c3011d-f0fd-41d4-b826-d05311e7ea85.png)

**Comment by MilesTEG1** [comment]
@EVOTk Yes !!
Thanks :)
I always forget that there is some action I can do on the left of each line :D
