### ISSUE TITLE
[BUG] keycloak blackscreen

### ISSUE THREAD

**Issue by TheUdK** [Lissy93/dashy#341]
### Environment

Self-Hosted (Docker)

### Version

latest + tested 1.9.1 and 1.9.0

### Describe the problem

Blackscreen after config build when keycloak enabled with all parameters.

Tried:
- v1.9.0 / 1.9.1 / 1.9.2
- locally hosted keycloak and dashy
- k8s hosted keycloak and dashy
- adding config params via yaml
- adding config params via editor
- keycloak valid redirect URIs and web origins with full URIs and also just wildcard

I am not getting any errors on the config build. All i get is just a black screen after the build and no log entries in either the keycloak or dashy containers that would point to any issues.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya, thanks for the question.
I've not come across this issue before. Would you mind sharing the console output of your browser, (press F12) - there will probably be an error message, which will help me debug this. A redacted version of your config and any validation warnings (`yarn validate-config`) would also be helpful. Can you also confirm that your KC is setup with an user, realm and application?
