### ISSUE TITLE
[BUG] statusCheckAllowInsecure is added as String rather than Boolean

### ISSUE THREAD

**Issue by olearycrew** [Lissy93/dashy#344]
### Environment

Self-Hosted (Docker)

### Version

1.9.2

### Describe the problem

When adding the `statusCheckAllowInsecure` option from the UI, it is added as a string of `'true'` rather than a boolean of `true`

Steps to reproduce:
1. Edit an item
2. Under "More fields" click "+ Status Check Disable SSL"
3. Select "True"
4. Open the "Edit Configuration" and observe invalid configuration based on the string type

<img width="485" alt="image" src="https://user-images.githubusercontent.com/6044920/143807899-06380f9f-4c5d-4690-9038-bb7c9505df1c.png">

Of note, the field `statusCheck` IS handled correctly.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by olearycrew** [comment]
I think this fixes it: https://github.com/Lissy93/dashy/pull/345

**Comment by Lissy93** [comment]
Good spot, and thanks for the fix - merged :)
