### ISSUE TITLE
[QUESTION] Use Tailscale VPN

### ISSUE THREAD

**Issue by seba5496** [Lissy93/dashy#348]
### Question

Hey there, 
I was wondering if there is a way to use Tailscale VPN to access the services with their alternative IP addresses, since Tailscale it's based in WireGuard as far as I know.
Thanks in advance
Best regards

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya @seba5496 Thanks for your question, but I'm not sure I fully understand. What part of the app isn't working through Tailscale? I'm just using plain old WireGuard + ZeroTeir on my setup, and hadn't noticed any issues. So if you could share some more details about your config and explain the question further, that'd be helpful :)

**Comment by EVOTk** [comment]
Tailscale is an intermediary, the Wireguard server is not at your place, but at Tailscale. Not sure it works.

**Comment by seba5496** [comment]
I'm trying to connect to my services from outside my home, but through Dashy, so I was wondering if there is a relatively simple way to use those IPs (Tailscale's) when I'm connected to Dashy through Tailscale VPN, or if there is a way to add secondary/alternative IPs for all my services without exposing them directly to the internet, so I can access them directly from Dashy.
I don't if I expressed myself correctly haha

**Comment by Lissy93** [comment]
Thanks for explaining, I _think_ I understand now.
I could in the future add an option for secondary URLs, although I'm not sure how you'd switch between primary and secondary links intuitively, or if it's something that would be useful to many users. 
In your instance, would a better approach be to keep your dashboard behind the VPN too, then all service IPs will be the same and nice n secure behind your firewall, or would that not work in your situation?

**Comment by seba5496** [comment]
> Thanks for explaining, I _think_ I understand now.
> I could in the future add an option for secondary URLs, although I'm not sure how you'd switch between primary and secondary links intuitively, or if it's something that would be useful to many users.
> In your instance, would a better approach be to keep your dashboard behind the VPN too, then all service IPs will be the same and nice n secure behind your firewall, or would that not work in your situation?

The issue with that would be, that it would always need an internet connection to work, and there are times at home that I lose access to the internet and that would mean that all links are unavailable. Perhaps this feature could be integrated with the check if a given service is online or not, letting me choose the link (?) or using the first link that is available.
I’m pretty sure that there is a simple solution I’m not seeing, maybe with another tool to use in conjunction with Dashy. I’ll keep exploring for now.
 Thanks again

**Comment by Lissy93** [comment]
Ah thanks for explaining, that makes sense now. And I now see how it could be very useful to use a secondary URL when the primary one is unavailable. I'll add it to the todo list, but right now am working on widget support, so it this likely won't be implemented for a while. In the meantime, if you find a service that solves that problem, do let me know here, as I would also be interested in this :)

**Comment by Lissy93** [comment]
Looking into this further, and I think you could actually do this just with NGINX (presuming you're already using it as a reverse proxy). One option could e  by creating a `@fallback` to that will resolve to the secondary service when the primary endpoint is unavailable. If you're using NGINX Proxy Manager, then this can also be incorporated into it with a [custom config](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations). Possibly something like:

```
server {
    location / {
        proxy_pass http://primary-instance;
        error_page 404 500 502 503 504 = @fallback;
    }

    location @fallback {
        proxy_pass http://secondary-instance;
    }
}
```

I think this can also be done better with [`proxy_next_upstream`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream), where you assign different `weight`s to each endpoint (primary, secondary or even tertiary if needed), and NGINX will use the first **available** service with the highest weight.

I'm not too strong with NGINX, so if someone knows a better method, that would be awesome. Or maybe there's an entirely different approach, for non-NGINX setups.

**Comment by Lissy93** [comment]
Am closing this issue for now, since the best approach is going be to implement it server-side, independently of Dashy.
But I have added the option for secondary/ backup URLs to the backlog, and I will update you here if/ when implemented.
In the meantime, feel free to update this ticket if you have any more ideas around this topic.
Thanks :)

**Comment by dacagi** [comment]
I know this is very old and I don't have a solution but maybe my workaround helps someone. I also use Tailscale and need to access services with a different IP when outside than on my home LAN.

I ended spinning up a second docker container with the same config, except in this one I swapped the IPs/hostnames accordingly for Tailscale's. Now when I'm at home I use one, when outside I reach the other. Lastly, I can sync the config files to always have the same settings but sed the urls which are the only changes.

It also works with another page inside a single Dashy instance, but if you don't mind the extra RAM usage I think it's best for security to have two separate. You may want to only allow certain services from TS or arrange them differently to ease access from a phone, like my case.
