### ISSUE TITLE
[BUG] Docker Error (RPI OS arm64)

### ISSUE THREAD

**Issue by walkxcode** [Lissy93/dashy#356]
### Environment

Self-Hosted (Docker)

### Version

latest (arm64v8)

### Describe the problem

I've installed dashy on many raspberry pi's before, but today I got an error while running the docker command:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/AppData/Config/Dashy/config.yml" to rootfs at "/app/public/conf.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

I have tried multiple things, but I just can't get it to work.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Heya @walkxcode,
This looks like you're either passing in a directory instead of a file for the config file location, or that the path your specifying doesn't exist. Could either of these be the case? If you remove the --volume flag, does the app then work?

**Comment by walkxcode** [comment]
It works if i remove the volume flag, but how will I be able to edit the config than?

**Comment by Lissy93** [comment]
Okay, so if it is working without the volume flag, then this is definitely a miss-typed path. Make sure that:
- The file your passing is a file, with an extension and not a directory
- The path is correct and an absolute location
- The file has the correct access rights to be read by the container 

Let me know if you're still having trouble after trying that, and if you could supply some more info about your Docker setup, then I can look into it further :)

**Comment by walkxcode** [comment]
I've already done all of that, still doesn't;t work :(

**Comment by Lissy93** [comment]
And the cat command works from anywhere?

**Comment by walkxcode** [comment]
Yes.

**Comment by Lissy93** [comment]
Okay, mind sharing your Docker compose, or the Docker run command you're using?

It should look something like this:
`docker run -p 8080:80 -v "/c/AppData/Config/Dashy/config.yml":/app/public/conf.yml lissy93/dashy`

```
docker run -d \
  -p 8080:80 \
  -v "/c/AppData/Config/Dashy/config.yml":/app/public/conf.yml \
  --name my-dashboard \
  --restart=always \
  lissy93/dashy:latest
```

Or for Docker compose, [like this](https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#using-docker-compose)

**Comment by Lissy93** [comment]
> Unrelated question, but was the "Adventure" theme inspired by my homer theme? 👀

Ha ha, yeah I think it might have been!

**Comment by walkxcode** [comment]
I am using 
```
docker run -d \
  -p 8001:80 \
  -v "/AppData/config/dashy/conf.yml:/app/public/conf.yml \
  --name dashy \
  --restart=unless-stopped \
  lissy93/dashy:arm64v8

**Comment by Lissy93** [comment]
So on Windows, I think you need to specify the drive letter, and you also have a missing quote

**Comment by walkxcode** [comment]
I am on a Raspberry pi.

**Comment by Lissy93** [comment]
Ah sorry, saw the app data and just thought Win

Okay, what user is Docker running under, and which user owns the config file?

Are you sure that AppData is on the root of your FS, that doesn't sound right for Linux?

**Comment by walkxcode** [comment]
Docker is running under the pi user, it has all permissions needed. Yes, AppData is at the root of my FS.
The config file is owned by the pi user, but docker has all permissions to read it (I tested this by giving another docker container the file and it was able to read). 

It might be something with the OS I'm on, as I am on the RPI OS Lite arm64 "beta" image.
```
       _,met$$$$$gg.          pi@rpi-srv
    ,g$$$$$$$$$$$$$$$P.       ----------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64
 ,$$P'              `$$$.     Host: Raspberry Pi 4 Model B Rev 1.4
',$$P       ,ggs.     `$$b:   Kernel: 5.10.63-v8+
`d$$'     ,$P"'   .    $$$    Uptime: 21 mins
 $$P      d$'     ,    $$P    Packages: 556 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/0
 Y$$.    `.`"Y$$$$P"'         CPU: BCM2835 (4) @ 1.800GHz
 `$$b      "-.__              Memory: 852MiB / 7812MiB
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**Comment by Lissy93** [comment]
I can dust out my Pi when I get home, and try installing the beta channel and see if I can recreate the issue

**Comment by walkxcode** [comment]
Alright, thanks! 🤍

**Comment by Lissy93** [comment]
After some research, I'd suggest trying the following:
- Put your config in a subdir within the user space, that's where it should be, then you can reference it with `~`
- Run `docker version` and ensure that the client and daemon version are **in sync**, and **both up-to-date**
- Again, ensure the chmod is correct, and check the permissions with `ls -la ~/AppData/Config/Dashy/config.yml`
- Try running Docker in debug mode, and see if you get additional info. Run `systemctl stop docker`, `dockerd --debug` then retry the run command.
- Ensure you've not got any conflicting mounts
- Restart your system

For more info, check these links:
- https://github.com/docker/cli/issues/297
- https://github.com/docker/compose-cli/issues/1795

**Comment by Lissy93** [comment]
I've tried this out on a Pi 3, and it worked fine with passing the YAML file in to the Docker container.
Am fairly sure that this is an issue with either the file your passing in or your setup, and not a problem with Dashy itself.

That last part of your error message I think is quite descriptive; you're trying to mount a local file or directory from your host (/AppData/Config/Dashy/config.yml) into the container. However, the path on your host cannot be found, or is a directory.

> `mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

Closing ticket, as not an issue with Dashy, and without more info not possible to resolve.

**Comment by vapzombi** [comment]
I had this same issue on windows11 and ubuntu 20.4
i used docker-compose and my volumes are like this (ubuntu)
volumes:
  - /home/myusername/appdata/dashy/conf.yml:/app/public/conf.yml
  - /home/myusername/appdata/dashy/icons:/app/public/items-icons
 windows 11
volumes:
      - /c/appdata/dashy/conf.yml:/app/public/conf.yml
      - /c/appdata/dashy/icons:/app/public/items-icons
both give this error when building container
mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

i looked in the appdata folder and noticed the conf.yml was made as a folder not a file so i deleted it then made a conf.yml file instead of the folder the container made and this fixed the problem on both windows and ubuntu for me 

not sure why it made a folder for me in the first place lol but it did it no both systems so hopefully this may help

**Comment by thewriteway** [comment]
On Raspberry PI with Portainer/docker:

I had to fix this by:
1) manually creating a named directory in /var/local 
2) manually creating a conf.yml with the example content from https://dashy.to/docs/configuring
3) Updating the run string to only list the folder locations on the host and inside the container as below:

sudo docker run -d -p 4000:80 -v /var/local/dashy:/app/public/ --name dashy --restart=always lissy93/dashy:latest

It then worked perfectly after this.

**Comment by BlackspearZero** [comment]
Was running into this issue myself trying to deploy in Portainer inside a Docker install on a LXC container running Debian 12 using Lissy's godsend of a template library: https://portainer-templates.as93.net/

I was finding that when it goes to deploy it cold, it creates `conf.yml` as a directory, which it then cant edit. If you go in and delete it, then `touch conf.yml `just to have a placeholder file, then go back and run it again it will work.

Hope this helps others running into this issue, might be specific to certain environments.
