### ISSUE TITLE
Pull Data from APIs for display on Dashy Cards

### ISSUE THREAD

**Issue by bmcgonag** [Lissy93/dashy#360]
### Describe the solution you'd like

As a Dashy user, I would like to see some stats made available through APIs of my various self-hosted applications listed on Dashy.  

Ideas:
 - Expandable cards indicating there is more information when clicked in certain place.
 - Special section in UI to show Stats separate from cards

If this feature exists, and I missed it, just smack me, and let me know. 

BTW - Love this project!

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Heya @bmcgonag 
I'm working on this at the moment, see the [FEATURE/basic-widget-support](https://github.com/Lissy93/dashy/tree/FEATURE/basic-widget-support) branch. But it's a big task, so will probably take a while to complete.
P.s, if you're enjoying the project, consider staring the repo, it helps new users find it :)

**Comment by Lissy93** [comment]
Hi @bmcgonag 
Sorry, totally forgot to keep you updated on this. I've implemented this feature in #382.

I made a couple of pre-configured cards for displaying useful info and stats from commonly self-hosted services, can find usage instructions in the [Widget Docs](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md).

Let me know what you think, and Happy new year :)
