### ISSUE TITLE
[BRAVE] Brave rewards no longer verified? 

### ISSUE THREAD

**Issue by walkxcode** [Lissy93/dashy#364]
### Question

Since today Dashy doesn't seem to be verified on Brave rewards anymore. I wanted to tip you some BAT, but it says ur unverified (also on other devices). Maybe look into it, as I really want to donate.

### Category

Development

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Thanks so my @walkxcode 💖
I'll update the DNS records and let you know when they're populated :)

**Comment by Lissy93** [comment]
Account updated :)
