### ISSUE TITLE
[FEEDBACK] Remove Preview and Production Environments

### ISSUE THREAD

**Issue by walkxcode** [Lissy93/dashy#365]
Hey,

Maybe consider removing the [Preview](https://github.com/Lissy93/dashy/deployments/activity_log?environment=Preview) and [Production](https://github.com/Lissy93/dashy/deployments/activity_log?environment=Production) Environments. They both seem to be inactive and outdated, and it will clean up this repository a bit.

**_Yes I have issues with making repositories as clean as possible. I contribute to every repo I see that can be "cleaned". 😅_**

**Comment by Lissy93** [comment]
Agreed, it's annoying. But not sure if GH allows you to remove environment deploys. If it does, I've not seen how.
Maybe it's possible to do via the GH API, so I will look into that...

**Comment by Lissy93** [comment]
Figured this out using the following script, based on [this answer on StackOverflow](https://stackoverflow.com/a/61272173/979052)

```bash
env=Preview
token=xxxx
repo=dashy
user=lissy93

for id in $(curl -u $user:$token https://api.github.com/repos/$user/$repo/deployments\?environment\=$env | jq ".[].id"); do
    curl -X POST -u $user:$token -d '{"state":"inactive"}' -H 'accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/$user/$repo/deployments/$id/statuses
    curl -X DELETE -u $user:$token https://api.github.com/repos/$user/$repo/deployments/$id
done
```

I'm leaving the GitHub pages env there, since I'm using that for deploying the [dashy.to](https://dashy.to/) docs website. But the other stale environment has now been removed.
