### ISSUE TITLE
[BUG] Tile Move Bug

### ISSUE THREAD

**Issue by rramchar** [Lissy93/dashy#366]
### Environment

Self-Hosted (Docker)

### Version

 1.9.3

### Describe the problem

Moving tiles doesn't work and result in a duplicate tile.  See video attached.

https://user-images.githubusercontent.com/45997492/145626543-39192884-a55e-4507-aac9-4d638cdefbec.mp4

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
✅ Fixed in #388 :)
