### ISSUE TITLE
🐛 [BUG] Text overlapping in public demo

### ISSUE THREAD

**Issue by walkxcode** [Lissy93/dashy#367]
<h3 dir="auto">Environment</h3>
<p dir="auto">Cloud Service (Static)</p>
<h3 dir="auto">Version</h3>
<p dir="auto">Public Demo</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">On <a href="https://demo.dashy.to/" rel="nofollow">https://demo.dashy.to/</a>, the text seems to be overlapping.<br>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/71191962/145821604-5d78001d-b762-46cb-ab8d-e90b3166722d.png"><img src="https://user-images.githubusercontent.com/71191962/145821604-5d78001d-b762-46cb-ab8d-e90b3166722d.png" alt="image" style="max-width: 100%;"></a></p>
<h3 dir="auto">Additional info</h3>
<p dir="auto">Issue happening on <code>Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit)</code>. Haven't tested on other browsers yet.</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                                <div>          <strong>                          <a href="https://demo.dashy.to/">Dashy</a>                      </strong>        </div>                            </blockquote>

**Comment by Lissy93** [comment]
Thanks for the info :) Will get this fixed this weekend

**Comment by walkxcode** [comment]
👍

**Comment by walkxcode** [comment]
Any updates on when this will be fixed?

**Comment by Lissy93** [comment]
Have got several other things on at the moment, and some higher priority tasks up next, but should get this fixed within the next week.

I think I just need to remove this line from the [`conf.yml`](https://gitlab.com/Lissy93/dashy/-/blob/master/public/conf.yml#L31), and update the demo to the latest version of Dashy.

**Comment by walkxcode** [comment]
Still relevant :)

**Comment by walkxcode** [comment]
Still relevant :)

**Comment by Lissy93** [comment]
I'm going to close this in favor of #855 (outlining same issue)
