### ISSUE TITLE
[BUG] StatusCheck not working/recognized

### ISSUE THREAD

**Issue by GhostTheSlayer** [Lissy93/dashy#37]
When I try to use the statuscheck in the config I get error saying "should NOT have additional property: statusCheck".

I'm running this on a fresh VM on Photon OS in VMware Workstation/ESXi. I tried cloning via git clone and manual dl and ftp.  I'm using docker-compose to build it ,  I have tried running the default config and editing it. I tried importing my config into docker playground and it worked there.

![brave_rnyidfxiCz](https://user-images.githubusercontent.com/38784343/122318918-26b17800-cf20-11eb-898b-19686e3f0b6e.png)

Also the clone command in the instructions doesn't  work.
![cmd_JPuYh6zojG](https://user-images.githubusercontent.com/38784343/122319146-8019a700-cf20-11eb-8bde-fb6d32cedd4f.png)

**Comment by Lissy93** [comment]
> When I try to use the statuscheck in the config I get error saying "should NOT have additional property: statusCheck".

You've not got the latest version of code. Status indicators were added in #34, and that attribute is defined in [the schema](https://github.com/Lissy93/dashy/blob/master/src/utils/ConfigSchema.json#L98). Try [updating](https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#updating) to the latest version, and you should be good to go :)

<details>
    <summary>Example Output</summary>
    <p>
I just did a fresh run on <a href="http://ip172-18-0-37-c35i987qf8u000e40fog-4000.direct.labs.play-with-docker.com/#/">PWD</a>, and it seems to be working
<img src="https://user-images.githubusercontent.com/1862727/122380455-cb06df00-cf5f-11eb-94d0-a73623cd7c8a.png" /></p>
</details>

---

> Also the clone command in the instructions doesn't work.

That error message is informing you that you are not authenticated. You can log in with git, by adding your SSH key to the keychain ([this tutorial](https://www.gitkraken.com/learn/git/tutorials/how-git-ssh-works) might help you). Alternatively, just clone via https, by running: `git clonehttps://github.com/Lissy93/dashy.git`

Hope that helps, feel free to update this issue if your still having trouble

**Comment by GhostTheSlayer** [comment]
Thanks for the help.  I got it running after updating it via ` docker pull lissy93/dashy:latest`.  Is it normal that git clone doesn't pull the latest version, since I had to update even though I just cloned it for the first time after all.

**Comment by Lissy93** [comment]
Nope, git clone will always pull down the latest code, but it won't keep it updated, for that you need to run `git pull origin master` to fetch the latest. Here's a quick guide on [keeping Dashy updated](https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#updating).
