### ISSUE TITLE
Config not updating on Synology

### ISSUE THREAD

**Issue by montrealwest** [Lissy93/dashy#373]
### Question

Installed dashy via docker compose and am trying to get the config to update in the yml file on my host. The main page changes but for some reason I cannot get the conf.yml to update on my host. I am getting inconsistent results across various browsers so I am not sure where exactly the container is deriving it's config file from.

I am using this mount:
- /volume1/docker/dashy/my-conf.yml:/app/public/conf.yml \
As a test, when I rename my-conf.yml on the nas volume the container will not start so that tells me the mapping is ok.
I try to console into the container to check for the existence of conf.yml and portainer fails to allow the login.

I have tried different machines and private browsing to access the page.
I make a change to a section title (v1->v2), save and then save to disk. refresh the browser and the change reverts to the previous edit (v1). I then go to a different browser and the change eventually (but not always) shows up after several refreshes. I did a rebuild and my latest edits appeared. If I do a subsequent edit (v3), go to other browsers and v2 may appear.

My initial config was using - PUID=1000 (matches my user/group) and - GUID=1000, I remarked these out and restarted the container and no change.
I changed to PUID=1000 and - GUID=1000 and restarted the container and the config page went back to default, without my changes.

I am trying Save locally, Save to Disk (which shows a successful message).

I tried a reset followed by a rebuild

I ssh into the nas and ran ls -li and the dates of the config files are not changed from days ago and the inodes remain unchanged.

I am completely stumped as to what I have done wrong here, any suggestions would be greatly appreciated. Thanks

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by montrealwest** [comment]
This is not spam, how do I reopen this case?

**Comment by Lissy93** [comment]
In Dashy, go to the Config Menu, and click Reset Local Settings. It sounds like your browser is just caching the previous data.
For more info, you can see the [Troubleshooting Guide](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#config-not-updating)

Let me know if that doesn't work, and I'll try and help further

**Comment by montrealwest** [comment]
Thank you, yes, I have Reset Local Settings a few times.
You are correct, it appears that changes take some time (15-60 seconds to propagate).
That said, I can still not see any changes getting stored in the host file on the nas (my-conf.yml). The file has not been changed since I place the original one in the directory. Any way I can test the updates to the nas files?
