### ISSUE TITLE
[BUG] Config saving but not loading correctly

### ISSUE THREAD

**Issue by JohnFawkes** [Lissy93/dashy#374]
### Environment

Self-Hosted (Docker)

### Version

1.9.3

### Describe the problem

So after making edits in the interactive config and saving and the refreshing the page, those edit disappear. restarting the container does not brin them back. However when checking my yml conf, the edits are still present.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by JohnFawkes** [comment]
so i was able to fix by using ctrl f5. sorry for that. thanks for the awesome software!

**Comment by JohnFawkes** [comment]
actually, its a little more bugged than i thought. using ctrl f5 does work, however if i just normal refresh or restart container then the edits disappear again

**Comment by JohnFawkes** [comment]
so it seems this is likely related to just my browser somehow because if i login on a different device then all my edits show with no issues

**Comment by Lissy93** [comment]
So you can go to the Config Menu, then hit "Reset Local Settings", that will clear the cache, and should fix your issue. Worth also noting, that on low powered devices, after a config change the rebuild can take up to a minute to propagate. That should be fixed in the future, but just worth keeping in mind :)
