### ISSUE TITLE
[BUG] Using Docker Compose not working

### ISSUE THREAD

**Issue by Asteliks** [Lissy93/dashy#386]
### Environment

Self-Hosted (Docker)

### Describe the problem

Not able to use docker compose with the given instructions here 
https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#using-docker-compose 

![image](https://user-images.githubusercontent.com/62251475/147657191-98777db0-ffd2-467f-b257-7e4b0cdce37f.png)

According to the instructions I should create a `docker-compose.yml` file and run it with `docker compose up -d` but I get this:
![image](https://user-images.githubusercontent.com/62251475/147657289-21e65a8e-02ad-49e6-b6e2-94f05260a01e.png)

I've also tried `docker-compose up -d` but that didn't move me forward:
![image](https://user-images.githubusercontent.com/62251475/147657424-fcc1a6e3-83eb-4b5a-b7e1-bb36a0143bc5.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Asteliks** [comment]
I'm not so sure if this is a duplicate of that issue

**Comment by Lissy93** [comment]
The error message is saying that the [version of Docker-Compose](https://docs.docker.com/compose/compose-file/compose-versioning/) specified, isn't installed on your system. You need to either update your docker / docker-compose installation, or downgrade the version in the compose file.

**Comment by Asteliks** [comment]
Welp my mistake. Thank you for hour help. TBH I was really surprised to see that my docker was outdated. I thought that apt-get updata and apt-get upgrade takes care of everything but apparently not. Guess I’m still a noob

**Comment by Lissy93** [comment]
No problem, glad you've got it working :)
