### ISSUE TITLE
[BUG] Not all Simple Icons are working

### ISSUE THREAD

**Issue by lordfiSh** [Lissy93/dashy#387]
### Environment

Self-Hosted (Docker)

### Version

1.9.4

### Describe the problem

Hi, 
not all Simple Icons seem to be working. AdGuard, Portainer and Unraid are not found. It seem the simple-icons package is not up2date (5.23.0 - 6.4.0). Could you update that? 

![image](https://user-images.githubusercontent.com/389680/147679129-b3e975b9-b17b-4649-a22c-5aac2a4e4873.png)

Thanks for your time for this Tool :

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hi @lordfiSh

Thanks for your issue, but I don't think this is a bug, all icons are working correctly. Could you be miss-typing them?
Please refer to the [Icon Docs](https://github.com/Lissy93/dashy/blob/master/docs/icons.md) for usage instructions. In the future, it makes things easy to diagnose if you can provide more info, such as the relevant parts of the config file and console output.

If it helps, here's a working usage example

```yaml
items:
  - title: AdGuard
    icon: si-adguard
    target: newtab
    url: https://adguard.local
  - title: Portainer
    icon: si-portainer
  - title: Unraid
    icon: si-unraid
```

<img width="300" src="https://i.ibb.co/rwfy43Y/simple-icons-screenshot.png" />

**Comment by lordfiSh** [comment]
hm it even said no Icon found via console, but after clearing the cached it worked. Probably wrong icon names... 
![image](https://user-images.githubusercontent.com/389680/147689957-a77c06fb-88c0-4d9b-9576-1b219ac667d2.png)
