### ISSUE TITLE
[BUG] Home & Source buttons appear when not specified in config

### ISSUE THREAD

**Issue by KierenConnell** [Lissy93/dashy#389]
### Environment

Self-Hosted (Docker)

### Version

1.9.5

### Describe the problem

'Home' and 'Source' buttons appear in top left - Not present in config

### Additional info

My config file doesn't contain the 'Home' or 'Source' buttons for the top left corner, but once I run the container, they appear.
![image](https://user-images.githubusercontent.com/46445781/147712787-a31382c0-1384-4b17-8f3a-4cc9ef90ddba.png)

Taken from my local config file
```
    "pageInfo": {
        "title": "Dashboard",  
        "description": "Kieren Connell",  
        "footerText": ""  
      },
```

Taken from the config file within Dashy's config editor
```
    "pageInfo": {
    "title": "Dashboard",
    "description": "Kieren Connell",
    "navLinks": [
      {
        "title": "Home",
        "path": "/"
      },
      {
        "title": "Source",
        "path": "https://github.com/Lissy93/dashy"
      }
    ],
    "footerText": ""
  },
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by KierenConnell** [comment]
Not spam

**Comment by Lissy93** [comment]
Heya, I'll look into this in the morning, but in the meantime just set `hideNav` (under `appConfig.hideComponents `) to `true`

**Comment by KierenConnell** [comment]
Have set `hideNav` and the buttons still appear
![image](https://user-images.githubusercontent.com/46445781/147759101-f321f905-9929-436c-9a23-d68ab6ad8024.png)
