### ISSUE TITLE
How to add new app?

### ISSUE THREAD

**Issue by connected201** [Lissy93/dashy#390]
### Question

hi, i newbie, i deployed container, open interface, but i don't know how to add new app icons.
![image](https://user-images.githubusercontent.com/20506433/147755468-84a20978-8b32-4bc2-a359-6ecb336cff8c.png)
Button "Add new item" not appear on my "Test category"

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Can confirm, this is a bug. Introduced in #382. 
Very sorry about that, my mistake. Thanks for raising, I will get it fixed this evening.
In the meantime, under the Config menu, you can add a first item in the JSON editor.

**Comment by lordfiSh** [comment]
Workaround: Create a Item in another Category and then move it (right-click), after that you can add Items in the new Category.
