### ISSUE TITLE
[SHOWCASE] The Private Dashboard

### ISSUE THREAD

**Issue by DylanBeMe** [Lissy93/dashy#419]
### Title

The Private Dashboard

### Screenshot

![dashy](https://user-images.githubusercontent.com/41838333/149346355-a6351328-eda5-4931-bc7d-52b63f8a1a78.png)

### Would you like your name/ username included?

Yes

### Description (Optional)

There's so many things on my dashboard that I can't even fit it all in the screenshot. I use it every day and it works great! It holds my links for quick and easy access, check if my servers are up and looks neat while doing so!

**Comment by DylanBeMe** [comment]
Ay, I figured you'd like it when you said that I have some great apps there. I really like Dashy and your privacy checklist a lot. I have donated a little before and might do it some more in the future, you do some great stuff with the power of caffeine!

**Comment by Lissy93** [comment]
Thank you Dylan 💖
 Your dashboard is added in ce4acc1
Feel free to reach out if you need anything :)

**Comment by thorrrr** [comment]
> ### Title
> The Private Dashboard
> 
> ### Screenshot
> ![dashy](https://user-images.githubusercontent.com/41838333/149346355-a6351328-eda5-4931-bc7d-52b63f8a1a78.png)
> 
> ### Would you like your name/ username included?
> Yes
> 
> ### Link to your Website/ Profile/ Twitter (optional)
> _No response_
> 
> ### Description (Optional)
> There's so many things on my dashboard that I can't even fit it all in the screenshot. I use it every day and it works great! It holds my links for quick and easy access, check if my servers are up and looks neat while doing so!

HI 
Love the Dashboard would be happy to share your conf.yml file  (redacted if needed)  with me?
I would love to see have you have structured it 
Cheers
