### ISSUE TITLE
[BUG] troublesome bottom copyright 

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#42]
Hello,

On mobile, the bar at the bottom with the copyright prevents re-opening a menu that has been closed.
Troublesome bottom copyright because it overlaps with other elements.

If I try to click on "Gestions Fichiers" to open it, instead, I go to the site https://aliciasykes.com/.

<img src="https://user-images.githubusercontent.com/45015615/122754734-4f28d180-d294-11eb-99a3-8c3af8a184dd.jpeg"  width="50%" height="50%">

<img src="https://user-images.githubusercontent.com/45015615/122754746-55b74900-d294-11eb-9e7b-6e5a28a8c2f7.jpeg"  width="50%" height="50%">

Thx you.

**Comment by Lissy93** [comment]
Thanks for raising this 🙌 
I've made a fix for it in PR #44, and will merge it once all the checks pass :)

**Comment by Lissy93** [comment]
Also, if you like, then you can add you're own content to the footer, by setting [`pageInfo.footer`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#pageinfo), it supports both plain-text and HTML :)

**Comment by EVOTk** [comment]
Thank-you for your prompt fix 💯
