### ISSUE TITLE
[BUG] Empty Space in Mobile Layout

### ISSUE THREAD

**Issue by ratty222** [Lissy93/dashy#432]
### Environment

Self-Hosted (Docker)

### Version

1.9.9

### Describe the problem

Update to 1.9.9 created empty space in mobile browser (iOS brave/safari). Adjusting layout type and item size don’t correct the issue. See screenshots.

### Additional info

![A58EE0CB-E191-47F1-B79C-D110CD9B094D](https://user-images.githubusercontent.com/92832598/150691815-ce9f02d3-5df7-4dfa-9a74-9dd08f73e67d.jpeg)
![F1D1A736-A2A7-4EBB-88BB-E458DB8AC720](https://user-images.githubusercontent.com/92832598/150691816-676566f8-e13c-48df-8353-5c30d16c8fbd.jpeg)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Thanks for raising, I did make some changes to sections recently and looks like I didn't test it properly on mobile devices. I will fix it this week.

In the meantime, you can fix this by setting the `cutToHeight` option, under `section.displayData`

```yaml
sections:
- name: Today
  icon: far fa-calendar-alt
  displayData:
    cutToHeight: true
  items:
    ....
```

:)

**Comment by ratty222** [comment]
Awesome. Thanks for the quick reply and the temp fix.  Looks good now. I really appreciate the time you spend documenting things. You write your docs like a patient teacher.  Hope you have a great week :))
