### ISSUE TITLE
[BUG] PiHole widget not working

### ISSUE THREAD

**Issue by Szymek887** [Lissy93/dashy#436]
### Environment

Self-Hosted (Docker)

### Version

1.9.9

### Describe the problem

I am trying to use PiHole Dashboard, but when I try to put hostname with http it is blocking it and when I try to put hostname with https it says that request has been blocked with the CORS policy. I have my apps behind NGINX Reverse Proxy using wildcart certs.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
This sounds like a CORS error, see [the docs](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#troubleshooting-widget-errors) for a guide on fixing.
Basically you need to either set the correct headers (e.g. `Access-Control-Allow-Origin: *`) or proxy your request (with `useProxy: true`).

_In the future, please check the [Docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) + [Troubleshooting Guide](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md) before opening an issue, and include the relevant info like browser console output and config._
