### ISSUE TITLE
[BUG] Columns height on Safari 12

### ISSUE THREAD

**Issue by samuelhalle** [Lissy93/dashy#439]
### Environment

Self-Hosted (Docker)

### Version

1.9

### Describe the problem

The height of the columns are taking the whole viewport on Safari (it's been like this for while).

The visual editor seems to have the same issue.

Here are screenshots :

![capture 1](https://user-images.githubusercontent.com/199032/150830279-fd161635-7eb5-4245-b670-ff57cb120149.jpg)

![capture 2](https://user-images.githubusercontent.com/199032/150830277-0b819d6e-1b4f-4d7d-9f4f-6d57a78f82cc.png)
 

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Does setting the `cutToHeight` option (under [`section.displayData`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#sectiondisplaydata-optional)) fix this?

I'm not an Apple user, so is really hard to test this, but I think it's probably a duplicate of #432

**Comment by Lissy93** [comment]
To be honest, I didn't actually know that anyone still used Safari. I can try and push a fix out based on the screenshot, but will have no idea if it will work or not. I think the only solution here is going to be to drop support for Safari, since short of buying an Apple,  I have no way of maintaining a version for it :(

That said, if this is something you want to take on, then feel welcome :)

**Comment by samuelhalle** [comment]
Wow that was quick. 

It fixed the editor (see capture)!

I'll have a look to see if I can fix the columns height and send a PR later if that work :)

Thanks for your hard work, I love it!

![capture 5](https://user-images.githubusercontent.com/199032/150845495-1efc02c7-c36d-4c3a-b70d-4562ba4681f2.png)

**Comment by Lissy93** [comment]
Yay, I'm glad that worked! And sick dashboard you've got!
Feel free to reach out if there's anything else you need :)
