### ISSUE TITLE
Nord-Frost Theme: container height broken on Safari 15

### ISSUE THREAD

**Issue by kimpenhaus** [Lissy93/dashy#442]
### Environment

Self-Hosted (Docker)

### Version

1.9.9 (latest)

### Describe the problem

It looks like the container height is too large. this only happens to be on Safari 15 (OSX 12.1) - as far as I can tell. Firefox and Edge looks good. I am running the Nord-Frost theme in horizontal layout

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/575109/150930438-4f550a65-3fa1-4036-bee8-e711bf9bbe2a.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/575109/150930829-04f8048d-f40c-42e3-9659-53be84c88a83.png">

I've tried to reset the config and of course shift+reload. None of them worked.

Thanks for investigating!

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by kimpenhaus** [comment]
gnaaa 🙈  - seems to be a duplicate to #432

**Comment by Lissy93** [comment]
Did the `cutToHeight` option help you here? 
I don't have an Apple device, so it's really hard to test for Safari 😕

**Comment by kimpenhaus** [comment]
yap - that worked well - thanks for the quick answer! set it on first container while not on second...

<img width="525" alt="image" src="https://user-images.githubusercontent.com/575109/150978401-544ce8de-abad-46bc-a410-3ef4f2cf79d7.png">

**Comment by Lissy93** [comment]
Awesome. I will add a media query so that the [offending CSS](https://github.com/Lissy93/dashy/blob/master/src/components/LinkItems/Collapsable.vue#L257) is not applied in Safari browsers :)

**Comment by kimpenhaus** [comment]
Can confirm it's working with the latest docker version - thanks for the quick fix!
