### ISSUE TITLE
[BUG] Section still visible while searching, even when no results 

### ISSUE THREAD

**Issue by Lissy93** [Lissy93/dashy#447]
### Raised by @kimpenhaus  in https://github.com/Lissy93/dashy/discussions/444

<div type='discussions-op-text'>

<sup>Originally posted by **kimpenhaus** January 25, 2022</sup>
Hi,

there seems to be a change lately which shows a 'no items to show yet' label in  empty, expanded container with no elements. Before those container were hidden - is there any config prop to enable the old behavior again?

Thanks,
m.

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/575109/150966288-4a1c3566-6abf-4605-b58d-9b694b1a73d0.png">
</div>

### Probably Cause

The `no-results` class is being correctly applied

https://github.com/Lissy93/dashy/blob/5f8a83fd4782ce72b86fc6354eb7beee2521f594/src/views/Home.vue#L45-L46

But the CSS that hides the section doesn't seem to have any effect:

https://github.com/Lissy93/dashy/blob/5f8a83fd4782ce72b86fc6354eb7beee2521f594/src/views/Home.vue#L262-L263

**Comment by kimpenhaus** [comment]
Thank you!

**Comment by kimpenhaus** [comment]
Looks to be good with the latest version! Thanks for the quick fix!
