### ISSUE TITLE
[FEATURE_REQUEST] An new widget showing CPU temperature

### ISSUE THREAD

**Issue by henkiewie** [Lissy93/dashy#452]
### Describe the solution you'd like

Hi Lissy,
I'm interested in a widget that shows me the current temperature of the CPU of my Raspberry PI 4.
My Glances docker container shows it under sensors as cpu_temp1. It can have the same look as gl-current-cpu and gl-current-mem.
I'm very happy with the dashboard. Got netdata up and running also. That dives very deep into all possible parameters you can think of. I wish I had that tool available in my working days as datacenter system engineer :smiley:
regards
Henk

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

Yes!

**Comment by henkiewie** [comment]
The new widget is working (ofcourse 😄 ), but it doesn't seem to accept the interval parameter? If I look at the (F12) console api/3/mem and cpu are constantly updating. but api/3/sensors only if you refresh by hand. Maybe a crazy idea. But wouldn't it be nicer (I mean less resource intensive) if you could make these kind of requests (xhr?) depended on the parameter if the widget is collapsed or not? My poor PI 4 is having a hard time 😢 .
I am already an advocate of dashy on discord and reddit whenever I can 😃 .
Using this as a template is still a bridge too far for me 😄 .

**Comment by Lissy93** [comment]
Glad it's working :) And thank you for sharing Dashy, that means a lot :D 
That's a good idea, I can make requests be paused when the widget is collapsed.

The continuous updates seems to be working. If you open up the browser tools, under the networking tab, select XHR and you should see the updates coming through. It might be that the actual Glances sensors plugin isn't showing changes as regularly as your updating.

```diff
  - type: gl-cpu-temp
+   updateInterval: 20
    options:
      hostname: http://dns-device.local:61208
```

Also in terms of performance, it seems that enabling Glance's sensors plugin is known to [cause a hit in performance](https://github.com/nicolargo/glances/issues/1664#issuecomment-632063558) on some systems. Increasing the time between updates (higher update interval) should help with this.

Hope that helps :)

**Comment by henkiewie** [comment]
Oh I'm sorry, you are right. I put the updateInterval in the wrong widget. That's the dashboard I wanted.
![Screenshot 2022-02-15 at 15 46 38](https://user-images.githubusercontent.com/74558874/154086116-b07b8332-1f7a-40de-b705-c6a68bbd5967.png)
