### ISSUE TITLE
[BUG] Widget gl-alerts showing wrong values

### ISSUE THREAD

**Issue by henkiewie** [Lissy93/dashy#454]
### Environment

Self-Hosted (Docker)

### Version

1.9.9

### Describe the problem

The value in glances is rounded, but not in the widget.

Usage alerts

Fri, Jan 28, 22 at 11:39:40 AM
LOAD - 1.2482725321888415%
I dont know what percentages makes this warning
![Screenshot 2022-01-28 at 18 16 25](https://user-images.githubusercontent.com/74558874/151592919-2c3e4861-a514-4c1f-b23d-3356d5e568dc.png)
.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Sure, I can round these values, I will push an update sometime this weekend :)

**Comment by Lissy93** [comment]
Sorry for the delay, busy couple of weeks.
This is now fixed in #488 / V2.0.3 :)
