### ISSUE TITLE
[FEATURE_REGUEST] Allow custom status codes for status checking

### ISSUE THREAD

**Issue by Lissy93** [Lissy93/dashy#456]
### Discussed in https://github.com/Lissy93/dashy/discussions/448

<div type='discussions-op-text'>

<sup>Originally posted by **louisonsarlinmagnus** January 27, 2022</sup>
In my Homelab I'm using Authelia as SSO.
Problem is that the `statusCheck` I get a red dot because of 401 return.
![image](https://user-images.githubusercontent.com/70757160/151366962-b6385455-d738-433d-981a-ea51dab21853.png)

Is there a way to add a "rule" saying 401=>Green ?</div>

---

### Implementation

Most of these changes would need to be implemented in the backend, in [`status-check.js`](https://github.com/Lissy93/dashy/blob/master/services/status-check.js).

In the main export, add a line to get the accepted status codes, then pass it as a param to `makeRequest(...)`

```javascript
const acceptCodes = decodeURIComponent(params.get('acceptCodes'));
...
makeRequest(url, headers, enableInsecure, acceptCodes, render);
```

In the `catch` block of `makeRequest(...)`, check the status code, and if it's in the accepted range, then return the success message

```javascript
if (validCodes && String(validCodes).includes(returnCode)) { // Success overridden by user
        const results = {
          successStatus: getResponseType(returnCode, validCodes),
          statusCode: returnCode,
          statusText: response.statusText,
          timeTaken: (new Date() - startTime),
        };
        results.message = makeMessageText(results);
        return results;
      }
```

In `getResponseType()`, add a param for `validCodes`, then check if actual code is found in expected codes

```javascript
const getResponseType = (code, validCodes) => {
  if (validCodes && String(validCodes).includes(String(code))) return true;
  const numericCode = parseInt(code, 10);
  return (numericCode >= 200 && numericCode <= 302);
};
```

Then, in [`Item.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/LinkItems/Item.vue), get the option from prop, convert to URL parameter and add it to the endpoint

```javascript
const acceptCodes = statusCheckAcceptCodes ? `&acceptCodes=${statusCheckAcceptCodes}` : '';
...
return `${baseUrl}${serviceEndpoints.statusCheck}/${urlToCheck}`
        + `${headers}${enableInsecure}${acceptCodes}`;
```

And in [`Section.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/LinkItems/Section.vue), pass the prop to the item

```javascript
:statusCheckAcceptCodes="item.statusCheckAcceptCodes"
```

**Comment by masterwishx** [comment]
How to set Dashy if i got answer from auth.mysite.com becose Authelia but i need like photo.mysite.com ?

**Comment by Lissy93** [comment]
So it's not super clear what you're asking. But if you mean how to set accepted status codes, then you can do this with something like: `statusCheckAcceptCodes: '403,418'`, see: **[Docs --> Status Checking --> Allowing Alternative Status Codes](https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md#allowing-alternative-status-codes)**.

Or if you meant something else, then is probably covered in the [troubleshooting section](https://github.com/Lissy93/dashy/blob/master/docs/status-indicators.md#troubleshooting-failing-status-checks=) - there are lots of options you can set, so status checks to nearly all services should work.

It's been discussed before, but ping-only status checks are not supported directly in Dashy, see: #233
So for that, you'd need to write your own service (it's very simple, don't worry),  to accept a GET request, ping what you need, then respond with 200.

**Comment by masterwishx** [comment]
> So for that, you'd need to write your own service (it's very simple, don't worry), to accept a GET request, ping what you need, then respond with 200.

can you explain ?
