### ISSUE TITLE
cutToHeight does not work

### ISSUE THREAD

**Issue by MihataBG** [Lissy93/dashy#461]
### Environment

Self-Hosted (Docker)

### Version

2.0.0

### Describe the problem

When we set cutToHeight: true, it does not work also go to error in configuration editor:
![cutToHeight](https://user-images.githubusercontent.com/43669254/151760828-65e95105-67c4-4be2-b777-28ccb0c05d69.JPG)

### Additional info

Theme is "Colorful"

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Your right, looks like I forgot to add this to [`ConfigSchema.json`] (https://github.com/Lissy93/dashy/blob/master/src/utils/ConfigSchema.json).

I'll get that fixed this evening

**Comment by MihataBG** [comment]
Its so good, but this does not resolve the problem with "colorful" theme.

**Comment by Lissy93** [comment]
Ah yeah, that seems to be caused by this line within the `colourful` theme block.
https://github.com/Lissy93/dashy/blob/e1a78db85320bd3def159c9e82261ae725294129/src/styles/color-themes.scss#L356-L358

I'll add that to the fix too :)
