### ISSUE TITLE
Memory consumption seems high

### ISSUE THREAD

**Issue by DennisGaida** [Lissy93/dashy#470]
### Environment

Self-Hosted (Docker)

### Version

2.0.1

### Describe the problem

Checking my docker stack, dashy is almost the highest consumer of RAM/memory with currently **255MB** assigned to it. I'm just wondering whether this is "normal"? Dashy ultimately is a static HTML page being served and I believe that is a bit much RAM for a HTML page...

Am I missing some caching mechanism I haven't activated? I haven't restarted the container no, so maybe I'm experiencing a memory leak?

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Heya @DennisGaida,
I think it's the Node server consuming memory, but it should only happen when the container rebuilds. Node.js is notoriously heavy, but there is a lite version planned (see [roadmap](https://github.com/Lissy93/dashy/discussions/405)).

In the meantime, you can serve up the static files yourself with NGINX or similar web server (here's an example: [Dockerfile](https://github.com/Lissy93/dashy/blob/master/docker/Dockerfile-lite)). Only downside is that the server-side endpoints (update config, status check, and proxy widget results) will not work, and you currently won't be able to modify config.

Going to close this as a duplicate, but if you've got a mem dump, or more info that shows there's a bug, or if the memory has massively spiked between versions, then this would be a bug, so feel free to reopen.

**Comment by DennisGaida** [comment]
Thank you for answering this @Lissy93! I'm sure it is node, I just thought that maybe there was something to make it leaner.

Looking forward to the lite version - I'll keep running the current version w/o nginx since 250MB isn't too bad, but I was still wondering where all that memory goes.

**Comment by Hakker** [comment]
Well lite version should happen soon then because in recent versions it has been growing to roughly 465 MB.
