### ISSUE TITLE
Allow disabling local config saving (one source of truth)

### ISSUE THREAD

**Issue by epheterson** [Lissy93/dashy#485]
It's surprisingly difficult and frustrating trying to set this up in the UI and preserving all changes. Each change requires being saved first locally, then separately going back in and saving remotely. Then you must clear the cache to confirm it's saved, which often for some reason it isn't.

For users who don't care for a separate local/permanent config, this dance is very unnecessary. Please allow having a single source of truth, which would simplify updating the config file.

**Comment by krswin** [comment]
Why this issue is closed, yes its very annoying to have save 2 times.

**Comment by hppyworld** [comment]
why this issue is closed? can we reopen it?

**Comment by Lissy93** [comment]
Yeah, feel free to submit a PR

**Comment by epheterson** [comment]
This is great, thanks! Just updated it and happy to see the "Save Locally" button disabled. Ironically, it did take a few saves and resetting local settings to stick, but now all good!

Also noticed a little typo on the settings:
>If set to true, no users will not be able to save config changes to disk through the UI

> If set to true, no users will not be able to save config changes to the browser's local storage

You either need "no users" or "will not" but currently it's a double-negative.

**Comment by epheterson** [comment]
It's looking like if I don't "Reset Local Settings" then I can never locally apply updates from the config file. Is that by design?

Example –
1. Disable local config by enabling "Prevent saving config to local storage."
2. Reset local settings, reload, verify local save button is disabled.
3. Enable "Widgets always use proxy"
4. Save
5. Reload browser (Shift + Reload on Firefox)
6. Notice no change, try "Reset Local Settings"
7. Changes are applied / config file is re-read from server

**Comment by Lissy93** [comment]
So that's not actually local storage, just the backend taking a minute to recompile the frontend. You can check the dev tools, specifically local storage (not saved), network request (xhr to save to disk) and console (status is logged there)

**Comment by epheterson** [comment]
Thanks for explaining, though is there anything that can be done to speed it up? Dashy is great except for the editing flow which leaves you waiting to see your changes, sometimes leaving you wondering if they saved at all.

**Comment by Lissy93** [comment]
It's VueCLU which is slow. These architectural changes would need to be made:
- Have changes read from file on the fly (not compiled)
- Rewrite backend in Go, instead of Node.js

**Comment by epheterson** [comment]
Agree Dashy is great, looking forward to trying it again when the new method comes out! Thanks for all your hard work on it @Lissy93!
