### ISSUE TITLE
[FEEDBACK] Allow useProxy: true to be a global widget setting

### ISSUE THREAD

**Issue by epheterson** [Lissy93/dashy#486]
I'm getting into widgets now, and they had an issue connecting when on my reverse proxy, but worked fine when directly going to the port. I saw in troubleshooting this can be solved with `useProxy: true`, which did resolve my issue. I'm now copy/pasting it to all of my widgets which pull from self-hosted services.

It'd be nice if `useProxy: true` could be a global widget setting so I don't need to copy it on each widget, since my configuration seems to require it on all.

I guess external widgets may not require it, not sure if there's fallout of this being set on those as well?

**Comment by Lissy93** [comment]
Sure, you should be able to do this with [YAML Anchors](https://dev.to/paulasantamaria/introduction-to-yaml-125f#distinctive-features), to define a property / set of properties once, then reuse them across as many items as you like. 

Worth noting that a better solution would be to set the correct headers in your reverse proxy, to accept requests coming from the URL where you're hosting Dashy. Obviously that won't work for managed services, so for those you'll have to use the `useProxy` option.

In the meantime, I can add this option in to the global `appConfig`, although not sure if it's the best approach.

If you're running a fork of Dashy, and want to add in any more options to the config, then [here is a guide](https://github.com/Lissy93/dashy/blob/master/docs/development-guides.md#adding-a-new-option-in-the-config-file) on how to do so :)

**Comment by epheterson** [comment]
Thanks for all the info! Looking forward to the patch, it's probably the path I'll take.

**Comment by Lissy93** [comment]
Implemented in #488 (released in V2.0.3) :)

**Comment by epheterson** [comment]
Works great, thanks!
