### ISSUE TITLE
[FEATURE_REQUEST] Widget for AdguardHome

### ISSUE THREAD

**Issue by JohnFawkes** [Lissy93/dashy#493]
### Describe the solution you'd like

A widget made for selfhosted adguardhome

### Priority

Medium (Would be very useful)

**Comment by Lissy93** [comment]
Hey John, would this be something you'd be able to work on?

**Comment by JohnFawkes** [comment]
maybe. i dont know vue or yarn though. i thought about just forking the pihole one and making changes where needed for adguard

**Comment by Lissy93** [comment]
Actually I remember looking into this a [few weeks back](https://github.com/Lissy93/dashy/discussions/370#discussioncomment-1855268), and it doesn't appear that AdGuard Home has an API that exposes any info, meaning it's not possible to build a widget for :(
[Here's a list of what's needed](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#requesting-a-widget) in order for it to be possible to build a widget.

**Comment by JohnFawkes** [comment]
https://github.com/AdguardTeam/AdGuardHome/tree/master/openapi

**Comment by Lissy93** [comment]
Awesome, then it will be possible then :)

At the moment I don't personally have time to build this myself, as I have a lot on atm. And [this](https://github.com/Lissy93/dashy/discussions/405) is what I'm going to be working on next, plus some media widgets. I can try and come back to AdGuard in the future.

I have written a guide on [how to build a widget](https://github.com/Lissy93/dashy/blob/master/docs/development-guides.md#building-a-widget), it's pretty straigtforward, and you can use on the [existing ones](https://github.com/Lissy93/dashy/tree/master/src/components/Widgets) as a template.

**Comment by JohnFawkes** [comment]
sounds good. ill look at the templates and the guide and see if I can come up with something. If I can ill open a PR and maybe even try to work on some other widgets

**Comment by Lissy93** [comment]
Awesome, let me know if you have any questions, or need any help :)

**Comment by projectdv** [comment]
Was about to suggest this same thing, not sure if this is still being worked on? :)

**Comment by Lissy93** [comment]
It is on my todo list :)
But I've still got a bunch of other improvements, features and stuff that is above this on the list. If only there were more hours in the day...

**Comment by projectdv** [comment]
> It is on my todo list :) But I've still got a bunch of other improvements, features and stuff that is above this on the list. If only there were more hours in the day...

No worries, was just checking and wondering as the item was closed :)
Keep up the good work! If I ever learn a bit how to do these things myself I'd be more than happy to contribute

**Comment by Lissy93** [comment]
What sort of data would you like to see in an AdGuard widget?

I'm a Pi-Hole user, so this is new to me. I've spun up a fresh instance of AdGuard to build this, but since it doesn't have any real data, it's hard to visualize what's important to you guys, as AdGuard users. 

Based on the API endpoints available, these are my ideas:

- **1: AdGuard Stats**
  - DNS query category pie chart 
  - stats (query count, categories, etc)

- **2: AdGuard DHCP Status**
  - View status
  - V4 and V6 IP private IP addresses
  - List of leases

- **3: AdGuard Safety, view status of and toggle** (possibly)
  - Parental Controls (view, enable, disable)
  - Safe Search (view, enable, disable)
  - Safe Browsing (view, enable, disable)

That sound okay?

For reference, you can see the AdGuard docs, by pasting [this](https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/openapi/openapi.yaml) into [here](https://editor.swagger.io/)

**Comment by ServoAtya** [comment]
I'm really glad if this widget arrive, because the AdGuard Home is the best solution for Encrypted DNS Server (DOT, DOH)+LetsEncrypt for using outside of my network, without VPN.

**Comment by projectdv** [comment]
> 

For me personally the main goal is to have query stats as in your first example as that's my main usage for Adguard.
The other suggestions are also useful though, I may look into those when I start configuring it further

**Comment by Lissy93** [comment]
Thanks guys :)

Am working on this now! But need a small favor, my instance doesn't enough real data to properly test what I've done so far.

If one of you could share the output of the following URLs, that would be really helpful. If you redact anything, be sure the format remains the same.
`https://[adguard-hostname]/control/stats`
`https://[adguard-hostname]/control/filtering/status`
`https://[adguard-hostname]/control//dns_info`

**Comment by projectdv** [comment]
> 

Any way I can send you that data directly? As I'm unsure if there's any personal data in there that I don't want on a public page here 😄

**Comment by Lissy93** [comment]
Yeah, you can email it to alicia.sykes@protonmail.com
Thanks so much!

**Comment by projectdv** [comment]
> > It looks like this issue isn't in English - not a problem, here's the translation! 🇬🇧
> 
> Yeah, you can email it to [alicia.sykes@protonmail.com](mailto:alicia.sykes@protonmail.com) Thanks so much!

Sent! :)

**Comment by Lissy93** [comment]
Will get it merged either this evening or tomorrow evening...

Here's a preview:

<p align="center">
<img width="400" src="https://i.ibb.co/qgkcxsN/adguard-block-percent-2.png" />
<img width="400" src="https://i.ibb.co/WsJkf5g/adguard-filters-list.png" />
<img width="400" src="https://i.ibb.co/G0JngBb/adguard-dns-info.png" />
<img width="400" src="https://i.ibb.co/qRhYYTk/adguard-top-domains.png" />
</p>

**Comment by ServoAtya** [comment]
One ting about this preview: We are able to specify multiple DNS Servers for upstream, like with the bootstrap servers
![image](https://user-images.githubusercontent.com/94781687/171004122-e1bffbdd-5632-42df-ae5a-c183af355dea.jpeg)

Just to avoid design issues
