### ISSUE TITLE
[FEATURE_REQUEST] Limit Redirect in Status Check

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#494]
### Is your feature request related to a problem? If so, please describe.

Hello,
I use the StatusCheck to check the availability of my services.
But for some of these services, when it is not available, my reverse proxy automatically redirects visitors to my status page ( uptime kuma ). Because of this, even if the service is offline, Dashy does not detect it!

### Describe the solution you'd like

Would it be possible to add an option to configure the maximum number of redirects before considering the service as offline?

Thank you

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Yes, this is possible, and a good idea :)
Note to self: In Axios has a [config](https://github.com/axios/axios#request-config) item called `maxRedirects` which will do this.
