### ISSUE TITLE
[FEEDBACK] About the contributing

### ISSUE THREAD

**Issue by Singebob** [Lissy93/dashy#497]
Hello, 
First of all, thank you for this great project 👍 
In the development part you talk about NVM and Gitpod, but in the repo there is no config file for these two tools, which in my opinion is not practical. 
Nvm allows contributors to have the same versions of Node and Yarn that you use. ( I couldn't find the exact versions 😢 )
Gitpod allows the contributor to have a development environment very quickly to help you with the configuration you want
Would it be possible to add these two configuration files to facilitate the contribution to your project? 

Disclaimer: Sorry for my english 😭

**Comment by Lissy93** [comment]
Hey @Singebob,
Absolutely, I can add configuration files for those platforms, it's a good idea :)

In the meantime, you can find the GitPod, and CodeSpaces links in the readme,  and the node version in the package.json 

[![Open Project in VS Code](https://img.shields.io/badge/Open_in-VS_Code-863cfc?style=flat-square&logo=visualstudiocode)](https://open.vscode.dev/Lissy93/Dashy) [![Open in GitPod](https://img.shields.io/badge/Open_in-GitPod-ffae33?style=flat-square&logo=gitpod)](https://gitpod.io/#github.com/lissy93/dashy.git) [![Open in GitHub Code Spaces](https://img.shields.io/badge/Open_in-Code%20Spaces-131313?style=flat-square&logo=github)](https://github.dev/Lissy93/dashy)

https://github.com/Lissy93/dashy/blob/2e63da041ab8a8ddb18a8ef219b4830214654a07/package.json#L67-L69

**Comment by Lissy93** [comment]
Hiya @Singebob,
I've added a [`.gitpod.yml`](https://github.com/Lissy93/dashy/blob/master/.gitpod.yml) in #557 / V 2.0.6
Let me know how you get on with that :)
