### ISSUE TITLE
[BUG] basic login page not display correctly on the Material-dark theme

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#50]
Hello,
I'm use Material-dark theme and I just configured a user.

the login page has a problem, the color of the text in the login fields is the same as the background! So the text is not visible (unless it is highlighted with the cursor).

![2021-06-21 22_22_02-Window](https://user-images.githubusercontent.com/45015615/122823300-7789ed80-d2df-11eb-9e3c-eaf55cbb25b7.png)

In Login I wrote "ilovedashy" but it is not visible, only "dashy" that I have highlighted

The writing in the button is also invisible.

Thx

**Comment by Lissy93** [comment]
Thank you :)
Fixed in be4621d76f299cf77b151c5a5b157acc2593e3fd of #52, will merge soon
