### ISSUE TITLE
[FEATURE_REQUEST] Public IP widget - Allow choosing ipv4/ipv6

### ISSUE THREAD

**Issue by hugalafutro** [Lissy93/dashy#500]
### Describe the solution you'd like

The vm on which dashy runs uses mullvad vpn, using public ip widget I get the ipv6 address displayed (which also gets cut off if only 1 column is configured), I would like an option for the widget to instead show the ipv4 address.

I use just the default 1 line to make the widget:
```
    widgets:
      - type: public-ip
```

![image](https://user-images.githubusercontent.com/30209689/154839007-fd249283-d199-4d64-94f8-90c7e4526142.png)

Otherwise let me just say thanks for dashboard of my dreams ❤️

### Priority

Low (Nice-to-have)

**Comment by Lissy93** [comment]
Just looking into this now, there are [three different providers](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#public-ip) supported for getting IP address. But after looking through their docs, (correct me if I'm wrong) I don't think any of them let you specify IPv4 / IPv6 address type to display.

We could use some CSS to either reduce the text size or allow it to break onto the next line? Alternativley, if you're running Glances, you could try the [`gl-ip-address`](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#ip-address) widget.

On another note, I also use Mullvad, and I think it's fairly popular, so I am thinking of making a Mullvad widget. They have a a small REST API: [`https://am.i.mullvad.net/json`](https://am.i.mullvad.net/json), which displays IP address, server or ISP location and Mullvad status. Doesn't fix the long IPv6 address issue tho.

**Comment by hugalafutro** [comment]
I couldn't find a way to choose the protocol at provider lvl either. Alternatively a widget option to not show the ip, just the flag and isp? As long as I see it's not my real isp I know I'm good (why I wanted ipv4 address is because I remember if it's 8x. i'm off vpn and if it's 1xx. I'm on vpn). 

Mullvad specific widget would be very nice, I switched to them few months back from pia and I'm quite happy.

I am looking into Glances, for now I just made the network section 2 columns wide.

**Comment by Lissy93** [comment]
I think adding an option to hide the IP address, from the IP address widget, might not be the most practical.

So how about you instead do this just on your instance, with CSS. Under the config menu, go to custom styles, and paste something like: `p.ip-address { display: none; }`. Or put it under  `appConfig.customCss` in your config.

**Comment by hugalafutro** [comment]
Fantastic, the CSS line works just as how I wanted it, even better than showing the ip, many thanks!
