### ISSUE TITLE
[BUG] interactive editor - no save modifications 

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#503]
### Environment

Self-Hosted (Docker)

### Version

2.0.3

### Describe the problem

Hello,
I think the last update of Dashy broke something, because it is no possible to save the modifications via the interactive editor whereas it worked 2 days ago.

![2022-02-20 18_09_30-Window](https://user-images.githubusercontent.com/45015615/154855053-875a1c62-0f42-42a1-a4fe-37a1fd51b846.png)

![2022-02-20 18_09_36-Window](https://user-images.githubusercontent.com/45015615/154855055-dfcddb69-1d4c-4c6a-a9e5-2d8d98e47336.png)

### Additional info

```
id evo-dashy
uid=1000(evo-dashy) gid=1000(evo-dashy) groupes=1000(evo-dashy)`
```

```
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
     - ./conf.yml:/app/public/conf.yml
     - ./item-icons:/app/public/item-icons
    ports:
     - 4000:80
    environment:
     - NODE_ENV=production
     - UID=1000
     - GID=1000
    restart: unless-stopped
```

Docker logs: 

```
node:events:368
      throw er; // Unhandled 'error' event
      ^
 WAIT  Compiling...5:08:04 PM
 DONE  Build complete. Watching for changes...
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.end (node:_http_outgoing:846:15)
    at module.exports (/app/services/save-config.js:51:9)
    at /app/server.js:88:47
Emitted 'error' event on ServerResponse instance at:
    at emitErrorNt (node:_http_outgoing:726:9)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start" exited with 1.
yarn run v1.22.15
$ npm-run-all --parallel build-watch start
$ vue-cli-service build --watch --mode production
$ node server
Checking config file against schema...
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by EVOTk** [comment]
Hello,
I just went back to 2.0.2 and it works, so there is something wrong with 2.0.3 :(

**Comment by DennisGaida** [comment]
Unrelated, but related - I also had to revert to 2.0.2 using docker-compose. In my case the node server doesn't even spin up:

Unable to start Dashy's Node server
 Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (node:net:1317:21)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)

Sorry - don't want to steal this ticket for anything, just wanting to agree that something is wrong with 2.0.3.

**Comment by EVOTk** [comment]
It's visibly linked and obviously, there have already been things done to correct this: https://github.com/Lissy93/dashy/discussions/498
