### ISSUE TITLE
Docker run fails

### ISSUE THREAD

**Issue by GogoFC** [Lissy93/dashy#509]
### Environment

Self-Hosted (Docker)

### Version

latest 

### Describe the problem

Hello

Just gonna put this here. 

Docker compose runs fine.

Docker run gives following error. 

```sh
ubuntu@openvpn:~$ sudo docker run -d \
>   -p 8080:80 \
>   -v ~/my-conf.yml:/app/public/conf.yml \
>   --name my-dashboard \
>   --restart=always \
>   lissy93/dashy:latest
Unable to find image 'lissy93/dashy:latest' locally
latest: Pulling from lissy93/dashy
59bf1c3509f3: Pull complete
b616ac4a64bf: Pull complete
3b9e1e8ab9ce: Pull complete
3507ddbf3909: Pull complete
d9fe68e859ca: Pull complete
3151f21357d2: Pull complete
e3e28f5bd0a2: Pull complete
Digest: sha256:c8f4c2ee83b9e0c618c099cb9bb765f16023ebc2b182717bd1aff16075af9343
Status: Downloaded newer image for lissy93/dashy:latest
723c3bd5d593ebe551f4c62607ffc71a401019a8b922996d66c622972633c7c8
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/ubuntu/my-conf.yml" to rootfs at "/app/public/conf.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by GogoFC** [comment]
Hey so
I'm a noob at Docker

Now I'm tried  mounting a volume to `/app/public` but it gets overwritten by the empty directory on the host, and dashy doesn't start.  Mounting a file with `-bind` also gave the same error.
 
How do you guys do it to keep the conf file.  I guess I don't need it I can just download it from the UI after I edit it. Should I even try mounting volumes for this?  All I can think of is copy all the files from `/app/public` to the host and then mount the folder. 

Another thing, I followed the instructions for self singed SSL, to mount a volume to `/etc/ssl/certs/dashy-priv.key` , but there is no `/etc` directory just `/app` , where should the directory be mounted to? This will be on LAN, can't have public access so my other option is to use nginx proxy and have SSL there, but I wanted to make my life easier but made it harder.

**Comment by Lissy93** [comment]
Looks like it's being mounted as a directory, when a file is expected

**Comment by GogoFC** [comment]
Yeah because the file already exists inside.

Hey you're the creator, awesome app thanks :)
