### ISSUE TITLE
[QUESTION] Admin user does not have permission to write changes to Config File

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#51]
Hello,
I configured a user admin using https://github.com/Lissy93/dashy/blob/master/docs/authentication.md 

Admin user does not have permission to write changes to Config File
If, I cancel the implementation of authentication, then this function is usable again.
<img src="https://user-images.githubusercontent.com/45015615/122827945-55936980-d2e5-11eb-83ab-db559b21891e.png"  width="50%" height="50%">

Is it normal to lose this functionality when configuring an administrator user yet?

Thx.
Your favorite pumpkin. :)

**Comment by Lissy93** [comment]
Heya :)
Thank you for raising this. I don't seem to be able to recreate this one through. I see the problem from your screenshot, and that does indeed looks like a bug. But I can't seem to find the bug on any of my instances of the app. Was there anything else you did before you found the bug? Do you maybe you have `allowConfigEdit` set to `false` in your config?

**Comment by EVOTk** [comment]
Dashy was updated last night by watchtower, and I can't reproduce the bug. Maybe a problem with my browser?
If I manage to reproduce it, I will re-open an issue with as much information as possible to reproduce it.

Thx
