### ISSUE TITLE
[QUESTION] SSL Configuration

### ISSUE THREAD

**Issue by qcgilbert** [Lissy93/dashy#514]
### Question

First, your project is awesome, thank you! I am using docker compose and can't seem to configure SSL for dashy. I dug through the docs and can't seem to figure it out. Thank you in advance.

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hey @qcgilbert, thank you, glad you're enjoying it :)
 
There's several ways to setup SSL, and the method you choose depends on how the rest of your homelab is setup.
I've written a more detailed guide in the [management](https://github.com/Lissy93/dashy/blob/master/docs/management.md) docs, see: **[Securing Dashy with SSL](https://github.com/Lissy93/dashy/blob/master/docs/management.md#ssl-certificates)**

But in short, the easiest method is to use a proxy, like [Traefik](https://traefik.io/traefik/) or [NGINX](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) + [NGINX Proxy Manager](https://nginxproxymanager.com/). That way you can setup auto-SSL (signed or self-signed) for all your self-hosted service through a nice web interface, and they will auto-renew.

Alternatively, you can generate your own self-signed certificates and pass them to Dashy. The path that Dashy will look for certificates in is `/etc/ssl/certs/dashy-pub.pem` and `/etc/ssl/certs/dashy-priv.key`, but can be changed by setting the `SSL_PUB_KEY_PATH` and `SSL_PRIV_KEY_PATH` environmental variables respectively. If you're using Docker, you can then pass your certs in using the `--volume` option. Then change the port binding to XX:443 for Docker, or open 4001 on bare metal, again this can be changed with the `SSL_PORT` env var. If you go with this method, I would recommend the [Valian/docker-nginx-auto-ssl](https://github.com/Valian/docker-nginx-auto-ssl) docker image, to handle renewing certificates automatically.

Hope that helps :)

**Comment by qcgilbert** [comment]
Thank you!  I don't know how I missed that.  I was digging through the website, not github.  Thank you again.

**Comment by Lissy93** [comment]
No problem :)
I've been meaning to build some searching functionality into the website, it would make navigating it much quicker...
