### ISSUE TITLE
[FEATURE_REQUEST] allow toggle fullscreen for iframes in workspace view

### ISSUE THREAD

**Issue by Byolock** [Lissy93/dashy#524]
### Is your feature request related to a problem? If so, please describe.

Toggle fullscreen buttons currently don't work in workspace view because iframes need to have 
`<iframe allow="fullscreen"></iframe>` set. 

### Describe the solution you'd like

Set `allow="fullscreen"` globally for dashy, or if there are any drawbacks that im not aware of providing it as an optional setting would be great

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Sure, good idea - will look into this and hopefully get a PR submitted this week :)

And thank you so much for the sponsorship 💖

**Comment by Lissy93** [comment]
Apologies again for the delay, have had a lot on. This has now been implemented in #557 :)
