### ISSUE TITLE
[QUESTION] Icon on the left of the services

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#53]
Hello,
it's me, again !

![2021-06-22 22_27_20-Window](https://user-images.githubusercontent.com/45015615/122994943-3cec8780-d3a9-11eb-99c4-6fc05bb6b153.png)

Can you tell me what that represents? Is this customizable?

Thx

**Comment by Lissy93** [comment]
Yeah, that is supposed to show the opening method (`newtab`, `sametab`, `iframe`, etc). It uses font-awesome for the icons, so it looks to me like it's not getting loaded. Try setting `enableFontAwesome: true` under `appConfig`, and let me know if that doesn't fix it :)

![item-hover](https://i.ibb.co/0XFG73t/material-dark-icons-hover.gif)

**Comment by EVOTk** [comment]
Adding `enableFontAwesome: true` under `appConfig `actually solved the problem, thank you.
![2021-06-23 07_58_11-Window](https://user-images.githubusercontent.com/45015615/123043718-02124000-d3f9-11eb-8d17-5a72cb3b7563.png)
