### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by GogoFC** [Lissy93/dashy#537]
### Environment

Self-Hosted (Docker)

### Version

 V-2.0.4.

### Describe the problem

`docker exec -it Dashy yarn build` fails in V 2.0.4.
image: lissy93/dashy

/app/src dir is mostly empty

```sh
 ERROR  Failed to compile with 1 error                                                                                9:00:02 AM
This relative module was not found:

* ./src/main.js in multi ./src/main.js
 ```

### Additional info

![Screenshot 2022-03-07 100044](https://user-images.githubusercontent.com/9360410/157000978-150bd779-7c93-445d-86bc-fabd06e9991a.png)
![Screenshot 2022-03-07 093942](https://user-images.githubusercontent.com/9360410/157000984-84160c39-ffff-4e64-a288-3b909828b0be.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Ateroz** [comment]
The app no longer needs to be built in 2.0.4. It ships prebuilt and no longer requires a build to update the config.

**Comment by GogoFC** [comment]
OH wow nice :) 
I though so because the Welcome message in logs was changed :)

**Comment by GogoFC** [comment]
This is like much quicker now hmm, isn't it, like alot?

**Comment by Lissy93** [comment]
Yup, so much better. Big thanks to Ateroz for that :)

**Comment by GogoFC** [comment]
Yeah I kept refreshing it, I couldn't believe :)
