### ISSUE TITLE
[BUG] BASE_URL broken on 2.0.4

### ISSUE THREAD

**Issue by vypxl** [Lissy93/dashy#543]
### Environment

Self-Hosted (Bare Metal)

### Version

2.0.4

### Describe the problem

Dashy does not honor the BASE_URL environment variable. I tried setting it in docker-compose, via docker run --env, and also via cloning the repo and running `env BASE_URL=/dashy yarn start`. I also tried `dashy`, `/dashy/` and `./dashy`. None are respected, if I connect to `<host>/dashy`, I get '404: cannot get /dashy`.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Ateroz** [comment]
Did this work before 2.0.4? The server bundled with Dashy doesn't really have anything to do with `BASE_URL` as it only serves dashy and not any other web app, so it only serves at your ip and port combo with no subpath. `BASE_URL` is used if you're using a static host that needs particular configuration.

Are you trying to serve the application behind a reverse proxy under a subpath?

**Comment by Lissy93** [comment]
For reference, this can be fixed using:

```
location / 
{
    rewrite conf.yml https://mycustomdomain.net/dashboard/conf.yml redirect;
}
```

As shared by am93 in [#600](https://github.com/Lissy93/dashy/issues/600#issuecomment-1100131674)
