### ISSUE TITLE
[BUG] local icons do not display

### ISSUE THREAD

**Issue by Rickerdo** [Lissy93/dashy#545]
### Environment

Self-Hosted (Docker)

### Version

2.0.4

### Describe the problem

Local icons do not display.

### Additional info

Config:
```
      - title: Woocommerce Admin
        description: Shopping cart test
        icon: 'icon: woocommerce.png'
        url: http://wordpress/wp-admin
        id: 4_934_woocommerceadmin

      - title: Mautic
        description: Campaign Marketing
        icon: 'icon: mautic.png'
        url: http://mautic
        id: 3_934_mautic
```

Container:
```
docker exec -it dashy sh
/app # ls -l /app/public/item-icons
total 148
-rw-r--r--    1 node     node         24128 Mar  8 14:09 mautic.png
-rw-r--r--    1 node     node         18328 Mar  8 14:09 opencart.png
drwxr-xr-x    2 node     node         16384 Mar  8 14:16 self-hosted
-rw-r--r--    1 node     node         87734 Mar  8 14:09 woocommerce.png
```

Screenshot:
![image](https://user-images.githubusercontent.com/6199259/157274320-e32cb81a-85f7-403f-b53e-488195e330fe.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Looks like an error in your config file, you've got: `icon: 'icon: mautic.png'` - should just be `icon: mautic.png`

**Comment by Lissy93** [comment]
If you visit `[location-of-dashy]/item-icons/mautic.png` you should see your icon. If not, then [browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) and have a look at the path that it is requesting under the Networking tab --> img.

Tested local icons on current version (2.0.4) and things seem to be working okay, so likely just the typo causing this, so going to close this ticket for now.

**Comment by Rickerdo** [comment]
> Looks like an error in your config file, you've got: `icon: 'icon: mautic.png'` - should just be `icon: mautic.png`

The problem clearly lies between the chair and keyboard. I completely misread the docs - https://dashy.to/docs/icons#local-icons

**Comment by Lissy93** [comment]
Ha ha, easily done! 
Feel free to reach out if you need anything else :)
