### ISSUE TITLE
[BUG] Favicon not present

### ISSUE THREAD

**Issue by MuadDibVV** [Lissy93/dashy#55]
Hello,

  I use the docker version : the favicon does not appear (on chrome and edge). Is it a problem from my side ?

**Comment by Lissy93** [comment]
Heya, thanks for raising this :)
I've implemented a fix in 74c3ee058cb5c98bd7d5cc009821bac7a94623e7 part of PR #57 which I will merge this evening, and I'll update this thread once the new image is deployed

**Comment by MuadDibVV** [comment]
Thank you !

**Comment by MuadDibVV** [comment]
Work fine, thanks a lot
