### ISSUE TITLE
[FEATURE_REQUEST] Docker integration

### ISSUE THREAD

**Issue by KaktusXY** [Lissy93/dashy#550]
<h3 dir="auto">Is your feature request related to a problem? If so, please describe.</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Describe the solution you'd like</h3>
<p dir="auto">A docker integration that connects to the docker socket to retrieve data like running containers, exposed ports, container name, etc... which then are automatically added to the dashboard with their corresponding link. And maybe configuration for those dashboard-entries/container through docker lables e.g. enable(if it should automatically add it or not), port(if multiple are exposed), ...</p>
<p dir="auto">Inspiration from:<br>
<a href="https://github.com/pawelmalak/flame">https://github.com/pawelmalak/flame</a><br>
<a href="https://github.com/plugsy/core">https://github.com/plugsy/core</a></p>
<h3 dir="auto">Priority</h3>
<p dir="auto">Low (Nice-to-have)</p>
<h3 dir="auto">Is this something you would be keen to implement</h3>
<p dir="auto"><em>No response</em></p>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/365565715/41e1c378-2d4a-4350-b432-b59abbc67c9f" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/pawelmalak/flame">GitHub - pawelmalak/flame: Flame is self-hosted startpage for your server. Easily manage your apps and bookmarks with built-in editors.</a>                      </strong>        </div>                    <div>Flame is self-hosted startpage for your server. Easily manage your apps and bookmarks with built-in editors. - GitHub - pawelmalak/flame: Flame is self-hosted startpage for your server. Easily mana...</div>                      </blockquote><blockquote>                    <img src="https://opengraph.githubassets.com/49d8e22b29c1e4a44ddf7ef02bb7dad16317deb92407f5c22232ae086f6c409a/plugsy/core" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/plugsy/core">GitHub - plugsy/core: A simple, pluggable dashboard and status page</a>                      </strong>        </div>                    <div>A simple, pluggable dashboard and status page. Contribute to plugsy/core development by creating an account on GitHub.</div>                      </blockquote>

**Comment by Lissy93** [comment]
I think it's a bit out of scope for what dashy is, and exposing the sock comes with some serious security pitfalls.

But you could create a separate service that aggregates and exposes the data you need, then make a widget to display the data.

**Comment by Balmain38** [comment]
Currently, glances aggregates and exposes the data on /api/3/docker.
Considering glances api call are already done, maybe it's easier to implement today ?
Monitoring container cpu & mem usage could be very interesting in dashy !
