### ISSUE TITLE
[QUESTION] Having trouble with connecting to external css file?

### ISSUE THREAD

**Issue by shimizurei** [Lissy93/dashy#551]
### Question

For some reason my CSS file isn't loading and I'm not sure what do with this type of error. There is a reference to the stylesheet once the app is built: `<link rel="stylesheet" href="/assets/dashycsstweaks.css">`, but when I click it, there is the following error message: `Cannot GET /assets/dashycsstweaks.css`. It looks like it's returning a 404, but my background in the same folder shows up fine. I tried the solutions in this [SO link](https://webcache.googleusercontent.com/search?q=cache:Re-7tTnTIIUJ:https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type+&cd=1&hl=en&ct=clnk&gl=us) (that I understood) to no avail (note: link is a cache link as SO is currently down for maintenance).

```
CoolConsole.js:6 
Dashy  V2.0.4 🚀
192.168.0.104/:1 Refused to apply style from 'http://192.168.0.104:4000/assets/dashycsstweaks.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
192.168.0.104/:1 Uncaught (in promise) EventisTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0path: (5) [link, head, html, document, Window]returnValue: truesrcElement: linktarget: linktimeStamp: 3239.600000023842type: "error"[[Prototype]]: Event
192.168.0.104/:1 Refused to apply style from 'http://192.168.0.104:4000/assets/dashycsstweaks.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Response Headers

```
HTTP/1.1 404 Not Found
X-Powered-By: Express
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 164
Date: Sat, 12 Mar 2022 20:14:35 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

### Category

Setup and Deployment

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by attzonko** [comment]
I have the same issue.  I am running Dashy using the latest Docker image: `ghcr.io/lissy93/dashy`

I did not find anywhere in the container filesystem a file called `dashycsstweaks.css`

**Comment by shimizurei** [comment]
> dashycsstweaks.css

That's my user-defined CSS file.

**Comment by Lissy93** [comment]
In the meantime, you can put your CSS file in `/public` (or a sub dir within), and that should work.

**Comment by shimizurei** [comment]
Oh ok. Weird. It used to work when I had `/volume1/docker/dashy/assets/dashycsstweaks.css:/app/src/styles/user-defined-themes.scss`, but the error goes away with `/volume1/docker/dashy/assets/dashycsstweaks.css:/app/public/assets/dashycsstweaks.css`. Thanks!

**Comment by Lissy93** [comment]
Ah yeah this would have been caused by the changes in how the config is loaded in the past version, since the app source was removed from the Docker image. This is being added back in, in #559 - so once merged, that should fix your issue
