### ISSUE TITLE
[BUG] When using local icons, if you open a section the icons are broken

### ISSUE THREAD

**Issue by jcbromstad** [Lissy93/dashy#570]
### Environment

Self-Hosted (Docker)

### Version

2.0.5

### Describe the problem

When using local icons, if you open a section the icons are broken.

The console indicates that Dashy is attempting to retrieve `http[:]//server/home/items-icons/icon.png` instead of `http[:]//server/items-icons/icon.png`
![errors](https://user-images.githubusercontent.com/72997757/159562059-e804f7ea-d7b6-49b7-9e60-abc382ae1104.png)

On main page
![mainpage](https://user-images.githubusercontent.com/72997757/159561566-5fbff6c7-8ac6-42ed-8ba8-41cc1ad9ca66.png)

On Section Page

![sectionpage](https://user-images.githubusercontent.com/72997757/159561637-de059b8f-811d-4026-a14e-be868423a6da.png)

Related to this, the "Back to All" link at the top of the screen shot takes you back to `http[:]//server/home` instead of the original location (in my case `http[:]server`) injecting the home sub location when it doesn't exist.

It's not noticeable at first until you refresh the page at which point it you get a "`Cannot GET /home`" error

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Thanks for the detailed ticket.
Seems I was using relative path instead of absolute 🤦
Fixed in #557 / V 2.0.6
Feel free to reach out if you need anything else :)
