### ISSUE TITLE
[QUESTION] There a way to open local links?

### ISSUE THREAD

**Issue by FormBurden** [Lissy93/dashy#574]
### Question

Hi, 

got to say this is a fun project, really helps out on learning and being more proficient with code. Plus putting my projects and content all together in one place. Anyway, while looking through the docs, I couldn't find anything along the lines to be able to open local links from on your computer. 

You know in markdown how you can open links from your local computer, such as using `file:///url-here-to-file/program` or even other types of syntax of other kinds of languages  (different than markdown). Is there a way to do that here? Or is this something that hasn't been implemented yet? 

I use Linux as my main OS and sync three different computers using SyncThing so the file locations are pretty much the same. So that's why I would like to have something like this.

I guess this is a question and an idea if it's not implemented yet. 

### Category

Search & Shortcuts

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
I've not tried this out, but in HTML it is the same as your example (like file://), so just putting that as the item's URL _should_ work.

My todo list is very long at the moment, but when I get a moment, I will look into this further, and update you here.

**Comment by Lissy93** [comment]
Hey @FormBurden 
I've looked into this, and the TDLR is that it's not going to be possible because browser security policies will block access to `file://`. If you try, you'll see this CORS error: `Not allowed to load local resource: <URL>` in the console.

A much better solution, would be to have a little web server that serves up your SyncThing files, then use the URL to a given file via that server. If this is just within your LAN it should be pretty simple to setup, and you could also use something like NextCloud or a NAS app to manage this.

Hope that helps. Going to close issue, as nothing to do on my end

**Comment by FormBurden** [comment]
Hey I appreciate it. No worries, like I said, was just trying to have central location where I could access pretty much everything in one place. Such as Dashy. I'll look into the web server you're talking about. You wouldn't happen to have something in mind for this solution? I use NextCloud as well, plus I have an entire Proxmox server, so nothing is out of my reach haha. 

Thanks again! I really enjoy Dashy, so I'll be continuing to use it. You wouldn't happen to have a time-window possibly of when we would see Multi-Page Support? Currently I have about 4 instances running, due to being an organized fellow haha, so one page for specific things is my go-to. Regardless, thanks for your time!

**Comment by Lissy93** [comment]
The very simplest thing you could do is to just start a web server that points to the root of your SyncThing directory :- here are some basic examples of [one-line web servers](https://notes.aliciasykes.com/32456/one-line-web-server).

A more practical solution would be to use either NGINX + [NPM](https://nginxproxymanager.com/) or [Traefik](https://traefik.io/traefik/), either of those solutions will let you spin up a web server that exposes a directory of files that you can then access anywhere within your LAN.

If you want a nice UI, you could also use a web-based directory lister/ file manager, like [DirectoryLister](https://www.directorylister.com/) or [FileGator](https://filegator.io/), which will give you easy GUI-based read-only access to your files. But both are PHP-based, so needs PHP installed.

**Comment by Lissy93** [comment]
Multi-page support is coming very soon, I think it's the most requested feature!!
I'm working on bug fixes at the moment, then finishing sub-items, after that it will be multi-page support.
Thanks for your patience, I know it can be frustrating having to run multiple instances.
