### ISSUE TITLE
[QUESTION] Widget w/ API: Unable to fetch data

### ISSUE THREAD

**Issue by vanillanesquik** [Lissy93/dashy#578]
### Question

Hello,

I am having trouble with the weather widget, I was able to go through the configuration and setup all of my links and sections but I am trying to experiment with the widgets.

I was able to confirm that the basic widgets works (no API), for example the Crypto ones in the sample config.

I signed up for openweather.org and setup the widget in my config. I have tried several different city codes and switched to US just for troubleshooting.

I have tried with both the proxy (useProxy: true) and internal CORS (no proxy). I don't know how to access the logs to find out what the problem is. I only saw references to using the browser console which I do not have much experience with in troubleshooting.

Any idea where I may be able to find the logs, or how to resolve this?

I am running on Docker in Unraid. I have Pihole running on unraid and use PFsense on my router. Openweather.org and api.openweather.org are both pingable from inside the container.

![image](https://user-images.githubusercontent.com/79759690/160200898-2c2c54e9-d84d-41cb-97ff-0583f867c101.png)

- name: Today
    displayData:
      rows: 5
      sortBy: default
      cols: 5
      collapsed: false
      hideForGuests: false
    widgets:
      - type: weather
        useProxy: true
        options: null
        apiKey: efdbade728b37086877a5e83442004db
        city: US
        units: imperial
        hideDetails: false
        id: 0_513_weather
        

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Answered [here](https://github.com/Lissy93/dashy/issues/577#issuecomment-1079732488) in #577.
