### ISSUE TITLE
[FEATURE_REQUEST] Multi-Page Support

### ISSUE THREAD

**Issue by gdepountis** [Lissy93/dashy#584]
### Is your feature request related to a problem? If so, please describe.

When tou have a lot items is a confution to have all in a page. 

### Describe the solution you'd like

The solution of the problem is to have muti pages support in order to create category per page.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
P.s thank you so much for your sponsorship, it's super kind of you 💖
I'll bump this request to the top of my todo list, and hopefully get it pushed out in the next few weeks :)

**Comment by Lissy93** [comment]
Just to keep you updated, am working on this right now. Got some spare time over next couple of days, so should get it done within the week 🤞

**Comment by gdepountis** [comment]
Not a problem. Also I am very busy but I would like to help you with Greek translation if you want.

**Comment by compgeniuses** [comment]
i think this issue should be closed, since the feature is released, to clean up the issues

**Comment by Lissy93** [comment]
Oh yeah, thanks

Closing as (finally!) implemented in #617
For usage, update to [2.0.8](https://github.com/Lissy93/dashy/releases/tag/2.0.8), then see the [Pages docs](https://github.com/Lissy93/dashy/blob/master/docs/pages-and-sections.md)
