### ISSUE TITLE
[BUG] Config file and Path creation issue

### ISSUE THREAD

**Issue by nickm324** [Lissy93/dashy#592]
### Environment

Self-Hosted (Docker)

### Version

2.0.6

### Describe the problem

in the compose file the path and config file as given in the example it does not create a config file, but creates a folder named my-config.yml which causes an exception.

### Additional info

Error received when trying to deploy the container

Creating Dashy ... 
 ERROR: for Dashy Cannot start service dashy:
 failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/home/nickm/dashy/my-config.yml" to rootfs at "/app/public/conf.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type ERROR: for dashy Cannot start service dashy: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/home/nickm/dashy/my-config.yml" to rootfs at "/app/public/conf.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type Encountered errors while bringing up the project. : exit status 1

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by santochen** [comment]
Hey @nickm324 , I think you need to comment that out if you don't have any existing config on the host.

Sample from the docker-compose has the config yml mapping commented out

**Comment by Lissy93** [comment]
Hi @nickm324 , as mentioned in your previous ticket, please be sure to check the troubleshooting guide and docs before opening a ticket. This question is covered [here](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#docker-directory).
