### ISSUE TITLE
[BUG] using conf.yml outside of docker causes getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by Wit4r7** [Lissy93/dashy#593]
### Environment

Self-Hosted (Docker)

### Version

2.0.6

### Describe the problem

First off I saw this application a few days on reddit and I thought directly I need this. 

My problem. I'm running Docker on my Synology NAS. So if I run the container without an external volume, everything is fine. When I link the /app/public/conf.yml to the conf.yml stored on my NAS the container won't start and I got this error message 
`Error: getaddrinfo ENOTFOUND Dashy 
 at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
 hostname: 'Dashy'
}`

As content of the yml I put in the get-started.yml from github. 
Also I provided the UID and GID to the docker account. The stored yml in my NAS is owned by the docker /app/public/conf.yml is linked to /dock/dashy/config.yml

Any ideas, what causes this problem? 

Best regards and thanks for the awesome work. 

### Additional info

Synology Version: DSM 7.0.1-42218 Update 3
Docker Version: 20.10.3-1239

### Please tick the boxes

- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Wit4r7** [comment]
Ok. For some reason, if I try to create the docker via the GUI I get the error mentioned above. 
As I used the documentation from dashy.to where the Synology is missing, this was my way to go. 

I've just double checked the documentation here on github which is more up to date and if I deploy the container via the Synology Tasks its working. 

So Issue can be closed and sorry for the circumstances.

**Comment by bepstein111** [comment]
Similar issue after switching from bridge to host networking mode as explained in #445:

`Checking config file against schema...
✔️ Config file is valid, no issues found
SSL Not Enabled: Public key not present
Using Dashy V-2.1.1. Update Check Complete
✅ Dashy is Up-to-Date
-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
Error: getaddrinfo EAI_AGAIN dashy
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dashy'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Any ideas on how to fix? I've tried recreating the container already

**Comment by ChowRex** [comment]
> ### Environment
> Self-Hosted (Docker)
> 
> ### Version
> 2.0.6
> 
> ### Describe the problem
> First off I saw this application a few days on reddit and I thought directly I need this.
> 
> My problem. I'm running Docker on my Synology NAS. So if I run the container without an external volume, everything is fine. When I link the /app/public/conf.yml to the conf.yml stored on my NAS the container won't start and I got this error message `Error: getaddrinfo ENOTFOUND Dashy at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) { errno: -3008, code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'Dashy' }`
> 
> As content of the yml I put in the get-started.yml from github. Also I provided the UID and GID to the docker account. The stored yml in my NAS is owned by the docker /app/public/conf.yml is linked to /dock/dashy/config.yml
> 
> Any ideas, what causes this problem?
> 
> Best regards and thanks for the awesome work.
> 
> ### Additional info
> Synology Version: DSM 7.0.1-42218 Update 3 Docker Version: 20.10.3-1239
> 
> ### Please tick the boxes
> * [x]  You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
> * [x]  You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
> * [x]  You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
> * [x]  You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

As I had ever tried, there is a workround for `Linux` platform, see below:

```bash
NEW_HOSTNAME="a.b.com"

hostnamectl set-hostname $NEW_HOSTNAME
```

This error is cause by [Fully qualified domain name - Wikipedia](https://en.wikipedia.org/wiki/Fully_qualified_domain_name), you need to change the hostname of your machine, and meet the requirement of FQDN, but I didn't have a thorough understanding, and  I didn't read the source code of this project, so I can't post more detail about what happened and why the error raised, sorry for that. Hope this may help you to troubleshooting.
