### ISSUE TITLE
[BUG] Route not found only for loading conf.yml

### ISSUE THREAD

**Issue by am93** [Lissy93/dashy#600]
### Environment

Self-Hosted (Docker)

### Version

2.0.7

### Describe the problem

I am trying to use Dashy on custom domain under URL path "/dashboard". Complete URL is https://mycustomdomain.net/dashboard".

I made following changes to configuration:
- defined the BASE_URL environmental variable using docker-compose 
- assigned appConfig.routingMode value "hash" (I believe this is "ignored" as the frontend can't load the file from the server due to wrong request).

After setup is completed and I try to visit the URL I can see from chrome dev tools, that BASE_URL should be working, because resources are being fetched from the server. 

![image](https://user-images.githubusercontent.com/9057292/163563293-6e45c9aa-009b-4051-922a-57bd8cbef3b8.png)

But when the requests come to conf.yml I get redirected to route 404 and I can see an exception in console:

![image](https://user-images.githubusercontent.com/9057292/163563449-956f04c7-a83e-4148-9624-9a560e60f40c.png)

### Additional info

See attached screenshots above.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by am93** [comment]
@Lissy93 - I think the bot made a mistake 😄 Can you please check this issue ?

**Comment by Lissy93** [comment]
I'm actually not sure, I remember getting this working a while back in NIGINX, unsure how. So unless you know of a method in Vue to get this working natively, then only serving from base domain is supported.

**Comment by am93** [comment]
Hey, thanks for the response.

I will try to look into it. further Currently I suspect that there is something wrong with passing BASE_URL to Vue ( https://github.com/Lissy93/dashy/blob/a784a2fe308508ee23062c8a974dd679a16cd0a0/vue.config.js#L17), but I am not sure what, as it follows Vue guidelines (https://cli.vuejs.org/config/#baseurl).

If you get any idea on how this was resolved, please let me know.

**Comment by am93** [comment]
Solved the issue with Vue and NGINX. Apart from what I have already written above I have added following configuration to my NGINX:

```
location / 
{
    rewrite conf.yml https://mycustomdomain.net/dashboard/conf.yml redirect;
}
```

**Comment by Lissy93** [comment]
That's awesome, nice one! And thanks for sharing the solution :)
I will add this to the docs to help anyone else looking for this...

**Comment by RyougiTale** [comment]
I found that you can change url to relative in store.js and InitServiceWorker.js like 'yaml.load((await axios.get('./conf.yml')).data'
