### ISSUE TITLE
[BUG] Wrong docker compose template in documentation

### ISSUE THREAD

**Issue by am93** [Lissy93/dashy#601]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.0.7</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">If you follow default README on the main page of this git repository and click on the link for the Docker compose setup, you are redirected to the Deployment documentation page, which has an incorrect volume path in sample docker-compose.yml inside markdown (docker-compose.yml inside code repository is OK) :)</p>
<p dir="auto">Link to documentation: <a href="https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#using-docker-compose">https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#using-docker-compose</a></p>
<p dir="auto"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/9057292/163576313-8886c56a-bc09-41db-981c-f5399010b6d7.png"><img src="https://user-images.githubusercontent.com/9057292/163576313-8886c56a-bc09-41db-981c-f5399010b6d7.png" alt="image" style="max-width: 100%;"></a></p>
<h3 dir="auto">Additional info</h3>
<p dir="auto">See above.</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/343078060/82f850a2-b1af-4e9f-9245-c92700d74856" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/Lissy93/dashy">dashy/deployment.md at master · Lissy93/dashy</a>                      </strong>        </div>                    <div>🚀 A self-hosted startpage for your server. Easy to use visual editor, status checking, widgets, themes and tons more! - dashy/deployment.md at master · Lissy93/dashy</div>                      </blockquote>

**Comment by Lissy93** [comment]
Thanks
Actually not sure why this was removed in https://github.com/Lissy93/dashy/commit/40a56ceb583712418c541e3ef838f0de2de99882 by StevKast 🤔
But you are correct, full path is required, so I'll add it back in
