### ISSUE TITLE
[BUG] 2.0.7 Opening method not honored, always newtab regardless of setting.

### ISSUE THREAD

**Issue by hugalafutro** [Lissy93/dashy#602]
### Environment

Self-Hosted (Docker)

### Version

2.0.7

### Describe the problem

After update to 2.0.7 I noticed all the buttons I have set to modal open as newtab. Mouseovering all buttons revels they all show the openming mode icon as newtab. Checking the config of the modal buttons confirms they have modal selected as opening method. I tried removing the opening method field, rebuilding, adding it back to no avail.

Opening modal via right click (which now works in Android - many thanks!) works correctly.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by hugalafutro** [comment]
unrelated, but every time I post issue I get email like this:
![image](https://user-images.githubusercontent.com/30209689/163578432-993c17c9-a0bf-4f60-9964-8a134b87bd11.png)

**Comment by Lissy93** [comment]
Heya @hugalafutro 
Thanks for raising, I've pushed a hot fix out in a784a2fe308508ee23062c8a974dd679a16cd0a0 :)
I've also disabled that action, until I can get a fix for it
