### ISSUE TITLE
[BUG] didn#t save 

### ISSUE THREAD

**Issue by robbyatbln** [Lissy93/dashy#603]
### Environment

Self-Hosted (Bare Metal)

### Version

Dashy version 2.0.7

### Describe the problem

Hello if i save the config to disk and reload the page all ist gone lokal save works but so i cant see it on other browser.
by robby

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by robbyatbln** [comment]
hy liss-bot  thats not helpfull, is there any tutorial how can i fix it looks like the conf.yml goes always back to the start conf.yml

**Comment by Lissy93** [comment]
There's some info about config troubleshooting in the [Troubleshooting Guide](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md).

But your question isn't very clear, do you have an error message, console output, etc?

**Comment by robbyatbln** [comment]
https://1drv.ms/v/s!AtKm83CUlTGflbwGV3ivnSZhkBp44g
here is a Little try to explain thanks for helping

**Comment by Lissy93** [comment]
Thanks

Here's a couple of things to try:
- Check if the conf.yml file on disk has been updated
- Check the [console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) for error messages
- Try rebuilding the app (Config --> Rebuild)
- Try clearing local data / using incognito (Config --> Clear data)

In the meantime, you can go to the export menu, and copy the changes to disk manually (Config --> Export). Or just use Docker, as I know this works in Docker.

**Comment by scumola** [comment]
I'm having this same issue.  Using as a proxmox container and from the latest git release.  I just installed the Ubuntu 22.04 container image, git pull'd the source, did npm run build and npm run.

I have the same exact issue.  The config file gets saved (old one gets backed up), but when I hit the reload button in the browser, I get the original config values.  Going back into the config file after the refresh happens, I see the original config values..  Prior to hitting the refresh button, I can see the new config values in the config file on the server-side.  Doing a re-build does not fix the issue because on my machine - even with 4 cores and 4GB of ram allocated to the container, the rebuild takes so long that it fails.  To me this sounds like a weird caching thing somewhere maybe?

**Comment by Lissy93** [comment]
Lemme reopen...

**Comment by scumola** [comment]
So @Lissy93 I found that in the docker container, it happens too, but only immediately.  I guess it's re-building behind the scenes?  After a while, the docker container retains the new changes, but if Dashy is loaded into a new browser window right away after saving changes, I get the old version of the config for 30-ish seconds, and then the new changes show up.

In the proxmox container, the new changes don't take effect unless a manual build is triggered, then the changes are permanent.

**Comment by ghzgod** [comment]
This is happening for me too.  It takes quite some time to take the new changes after saving to disk.  Sometimes it doesn't change at all, other times it makes a change 30-60 seconds after I hit save.

**Comment by Lissy93** [comment]
Still relevant...
will be addressed in #799

**Comment by CrazyWolf13** [comment]
Hi
This problems seems to be related to dashy not automatically rebuilding on changes, see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.
