### ISSUE TITLE
 [BUG] Redirect loop when keycloak auth is enabled

### ISSUE THREAD

**Issue by kafeinnet** [Lissy93/dashy#605]
### Environment

Self-Hosted (Docker)

### Version

2.0.7

### Describe the problem

Hi,

Dashy cause a redirect loop when keycloak auth is enable and I'm not sure how I can debug that.

The app keeps redirecting to my keycloak server (`/auth/realms/myrealm/protocol/openid-connect/auth?client_id=...` and all the auth workflow).
Then keycloak redirect to the app callback `https://fqdn/#state=...`.
Then there is a POST request on /auth/realms/myrealm/protocol/openid-connect/token and keycloak returns a JSON objet which seems to be a valid bearer token.
And then the app refresh itself and everything starts again.

The keycloak session is OK, the returned token is OK, some other apps are using this keycloak instance without problem and dashy is working OK if I don't enable keycloak auth. Is there any way to be sure this a a dashy bug or to find out what is happening ?

And message to liss-bot, please pretty please don't close it ! I starred the project now !!

\fab

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Closing, as I reopened #604
See [here](https://github.com/Lissy93/dashy/issues/604#issuecomment-1102613682) for my reply :)
