### ISSUE TITLE
[BUG] Losing prior changes on subsequent change

### ISSUE THREAD

**Issue by ethereal-engineer** [Lissy93/dashy#607]
### Environment

Self-Hosted (Docker)

### Version

2.0.6 (via Docker)

### Describe the problem

I use the interactive editor to make changes to groups (adding items, changing things). Usually I try to make sure I have the latest copy of the config loaded in whatever browser and computer I am using (I move between about 3 computers daily), but if it happens to be the case that the one I am using last has an old copy of the config, then my new changes are stored and the last set of changes are lost. This is why I TRUST git so much (for code changes). Is there a way you could force a refresh of the client browser's config BEFORE they make or commit changes?

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
> Is there a way you could force a refresh of the client browser's config BEFORE they make or commit changes?

Not really, since you'd obviously lose whatever changes you were making. 
Could  you not just refresh your page before making changes?
