### ISSUE TITLE
[BUG] Could not activate guest access

### ISSUE THREAD

**Issue by DragoSpiro98** [Lissy93/dashy#608]
### Environment

Self-Hosted (Docker)

### Version

2.0.7

### Describe the problem

When I add enableGuestAccess: true in conf.yml an error is returned 

". appConfig should NOT have additional property:"

The only properties of appConfig that I currently have entered are:
auth, theme, layout, iconSize, language.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by DragoSpiro98** [comment]
I read the documentation and just following the documentation this error is returned...
The documentation says: You can enable guest access, by setting `appConfig.enableGuestAccess: true`
But it doesn't work

**Comment by Lissy93** [comment]
That's because `enableGuestAccess` goes under `appConfig.auth`
You can check the [Configuring Docs --> `appConfig` --> `auth`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#appconfigauth-optional) for more info.

**Comment by DragoSpiro98** [comment]
> That's because `enableGuestAccess` goes under `appConfig.auth` You can check the [Configuring Docs --> `appConfig` --> `auth`](https://github.com/Lissy93/dashy/blob/master/docs/configuring.md#appconfigauth-optional) for more info.

Then the [documentation](https://dashy.to/docs/authentication/#enabling-guest-access) is wrong, since it clearly says:
You can enable guest access, by setting `appConfig.enableGuestAccess: true`
And not `appConfig.auth.enableGuestAccess: true`

**Comment by Lissy93** [comment]
Use the docs in the repo, don't think the site us up-to-date..

**Comment by DragoSpiro98** [comment]
> Use the docs in the repo, don't think the site us up-to-date..

It's the same [here](https://github.com/Lissy93/dashy/wiki/authentication#enabling-guest-access)

**Comment by Lissy93** [comment]
Thanks for spotting, I'll update that.

You can also run `yarn validate-config` if you're ever unsure if what you've got is right.
