### ISSUE TITLE
[BUG] Ugly Line Breaking in top left search-label when using CJK Locale

### ISSUE THREAD

**Issue by moemoeq** [Lissy93/dashy#611]
### Environment

Self-Hosted (Docker)

### Version

2.0.7 (Master)

### Describe the problem

Hello, first of all, thank you for your awesome project!

I'm adding a Korean translation. so I'm repeating the build and preview to make sure the translation is correct, and I saw the ugly line breaking in the search label.

to make sure, I checked other languages and just found this problem only happens when using CJK (Chinese, Japanese, Korean) languages.
(when using cjk, such as those problems are common issues) 
Please refer to the attached picture.

### Additional info

<img width="945" alt="image" src="https://user-images.githubusercontent.com/1808434/164847618-c6d08b76-ee1a-446f-aace-1837947e3cf4.png">

I did a simple debugging and found a solution.
There are two ways to solve this problem.

The first method is to put the `word-break: keep-all;` into the label tag that uses search-label. 
The second method is to remove the `width:100%` from the search-wrap class.

but, the second method is not a visually significant difference, but I think it will cause unexpected problems. (Do you have a good idea?)

I am currently writing a PR to correct this issue.
This issue was created for reference and sharing.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hey @moemoeq 
Thanks for raising, and very well presented issue :)
I am not super familiar with CJK locals, so my apologies for the issues. Your fix (`word-break: keep-all;`) doesn't seem to break anything else, so should be all good to add it.

**Comment by moemoeq** [comment]
https://github.com/Lissy93/dashy/pull/612

**Comment by Lissy93** [comment]
Thanks @moemoeq - Your PR is merged :)
