### ISSUE TITLE
[FEATURE_REQUEST] Google Search Ability

### ISSUE THREAD

**Issue by MayhemBill** [Lissy93/dashy#614]
### Describe the solution you'd like

The Ability to start a search (preferably google) through the dashboard, it was a feature I liked from Heimdall I would like to see on Dashy

### Priority

Medium (Would be very useful)

**Comment by Lissy93** [comment]
Have you seen the [Searching Docs](https://github.com/Lissy93/dashy/blob/master/docs/searching.md#web-search), specifically the web search section. 
It is quite basic at the moment, but you can set the search engine to Google.

**Comment by MayhemBill** [comment]
Ah I was unaware of that, it was around last time I used Dashy (I think)
