### ISSUE TITLE
[FEATURE_REQUEST] Uptime-Kuma service

### ISSUE THREAD

**Issue by DraneLixX** [Lissy93/dashy#616]
### Describe the solution you'd like

I would like to see [Uptime-Kuma](https://github.com/louislam/uptime-kuma) get its own card like Statping, Pi-Hole and others.

Uptime-Kuma has APIs for the status pages:

- /api/status-page/incident
- /api/status-page/monitor-list
- /api/status-page/heartbeat

Which returns the data that makes up the status page. We should be able to pull the overall status of All Systems Operational/Partially down from these APIs.

### Priority

Medium (Would be very useful)

**Comment by Lissy93** [comment]
Do you have a link to the API docs?

**Comment by Lissy93** [comment]
Closing, as Uptime Kuma does not seem to have an official API (was also [discussed here](https://github.com/Lissy93/dashy/discussions/370#discussioncomment-1855400)).

In future, please read [Requesting a Widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#requesting-a-widget) before opening a ticket, to ensure all required info is provided

You're very welcome to try to implement this yourself, but without a stable and accessible API, it's likely going to be more work than it's worth.

**Comment by Lissy93** [comment]
Nothings impossible :)

But without a proper API to interact with it, it wouldn't be easy to implement, nor would any temporary solution be stable. But I'm open to ideas, if you're more familiar with Uptime-Kuma than me.

**Comment by masterwishx** [comment]
Don't have a lot of experience with Kuma only basics, but checked and they working on API
or getting to start work :)

**Comment by Lissy93** [comment]
They've been "working on an API" for the past year, so I wouldn't get your hopes up too much
