### ISSUE TITLE
[BUG] Docker deployment failing

### ISSUE THREAD

**Issue by MateoPeri** [Lissy93/dashy#624]
### Environment

Self-Hosted (Docker)

### Version

2.0.7

### Describe the problem

Tried running Dashy on `docker-compose` with the provided config, but it failed with error:
```
Using Dashy V-2.0.7. Update Check Complete
✅ Dashy is Up-to-Date


-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGKILL".
ERROR: "build-watch" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It is not a compose issue, I can reproduce the issue just by running `docker run -p 8080:80 lissy93/dashy` (the simplest docker example provided in the docs).

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [x] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
I've not seen this before, and don't think it's an issue with Dashy.
The only think I can think of, is that you've not assigned enough memory. But without more info, it's not possible to help any further.

**Comment by MateoPeri** [comment]
I allocated more memory and that seemed to do the trick. Thanks!
