### ISSUE TITLE
[QUESTION] RSS widget improvement

### ISSUE THREAD

**Issue by wtld** [Lissy93/dashy#632]
### Question

I am working on adding two options to RSS widget (I plan a PR):

1. Optionally don't display item descriptions (only titles)
2. The ability to display the both date and time, not just the date

But my question is:

Should I change the following fragment in the original widget code:

```
axios.get(this.endpoint)
  .then((response) => {
    this.processData(response.data);
  })
  .catch((error) => {
    this.error('Unable to RSS feed', error);
  })
  .finally(() => {
    this.finishLoading();
  });
```

to this one:

```
this.makeRequest(this.endpoint).then(this.processData);
```

Seems much cleaner for me :) I am new to Dashy, maybe makeRequest method was added after RSS Widget was created?

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Yeah, you're right, it should be that :)
I added `makeRequest` after I'd already created several of the widgets, and it looks like I forgot to refactor that

**Comment by Zovix** [comment]
> I am working on adding two options to RSS widget (I plan a PR):
> 
> 1. Optionally don't display item descriptions (only titles)

Was this added as a feature? I was looking for the option in the docs and didn't see it.
