### ISSUE TITLE
[FEATURE_REQUEST] support Compose labels to automatically add services to Dashy

### ISSUE THREAD

**Issue by zilexa** [Lissy93/dashy#639]
<h3 dir="auto">Is your feature request related to a problem? If so, please describe.</h3>
<p dir="auto">Currently, Docker services need to be added manually to Dashy. Either via the UI or via yaml file directly.<br>
However if one is already using Docker Compose to run its services, including Dashy, the compose.yml file already contains basic configuration of each service.</p>
<h3 dir="auto">Describe the solution you'd like</h3>
<p dir="auto">By adding support for Docker Compose Labels, the Dashy dashboard can automatically add services, when one runs <code class="notranslate">docker-compose up -d</code>.<br>
Just 4 labels: a label for a name, category and icon, optionally a URL if it has a webUI would be enough.</p>
<p dir="auto">These need to be added by the user to each service in their Compose file that they want to add to Dashy.</p>
<p dir="auto">Dashy would need Docker API support.</p>
<p dir="auto">I think this would be <em>very</em> useful but can imagine if others see it as nice to have.</p>
<p dir="auto">For example, look at Plugsy, it does this exactly and does it pretty well (but it seems to have been abandoned and has a nasty bug, preventing users from proxying Plugsy):<br>
<a href="https://github.com/plugsy/core">https://github.com/plugsy/core</a></p>
<h3 dir="auto">Priority</h3>
<p dir="auto">Medium (Would be very useful)</p>
<h3 dir="auto">Is this something you would be keen to implement</h3>
<p dir="auto">No</p>

<blockquote>                    <img src="https://opengraph.githubassets.com/967f8564c514935dbaa0a25b979875d3961a3a7b7ae2a2ca3a9b31cff1112ab9/plugsy/core" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/plugsy/core">GitHub - plugsy/core: A simple, pluggable dashboard and status page</a>                      </strong>        </div>                    <div>A simple, pluggable dashboard and status page. Contribute to plugsy/core development by creating an account on GitHub.</div>                      </blockquote>

**Comment by Lissy93** [comment]
Possibly similar to: #496 and #429 and #550 ?

**Comment by Lissy93** [comment]
> Dashy would need Docker API support, but it probably already has since it can check its health checks and status etc.

It actually doesn't, as the status checking is just done through web requests. Since exposing the docker.sock obviously comes with some serious security concerns.

---

Maybe you should add this feature in your own fork of Dashy? Or use another dashboard app, [here are some alternatives](https://github.com/lissy93/dashy#alternatives-).

Btw that Plugsy error, would likely just be a mis-matched certificate, rather than an actual error, so there might still be hope ;)

**Comment by Lissy93** [comment]
Maybe I could make a separate service, that interacts with the Docker sock, then securley exposes the required info through an API, to be used by apps like Dashy, without the need for Dashy to have full and direct access to Docker.

I agree that it would be very useful for a lot of people. I will consider it for a future update, and when / if complete, I'll let you know here :)

**Comment by zilexa** [comment]
In my case I don't even expose a dashboard online.
 As a selfhoster/user with a homeserver, I only expose services that really need to be exposed: Firefox Sync Server, Vaultwarden password manager and FileRun, a file manager. The rest is only accessible through Wireguard VPN. 
Exposing Docker stuff therefore doesn't really matter to me, once I'm on VPN, I can access everything anyway :) 

I'd say don't overcomplicate. But I like that you care about security.

**Comment by mbjurstrom** [comment]
Sorry to bump this old issue. But I just started using Dashy the other day and love it this far. Great work. 

I am also missing this feature though, and would love to have it implemented. 

> Maybe I could make a separate service, that interacts with the Docker sock, then securley exposes the required info through an API, to be used by apps like Dashy, without the need for Dashy to have full and direct access to Docker.
> 
> I agree that it would be very useful for a lot of people. I will consider it for a future update, and when / if complete, I'll let you know here :)

For my containers that require access to the docker socket I use this https://github.com/fluencelabs/docker-socket-proxy to minimize the security risk.  I run multiple instances with the various combinations of APIs enabled and pass in the one with the most minium amount enabled for each container.  It is a bit messy though and require the user to understand which api each container need. 

If there is no interest to implement this in the official repo I might try to implement something for my self.

**Comment by NikitaMikhailov** [comment]
@lissy93 back in 2022 you mentioned a separate service that reads Docker and hands Dashy the config, so Dashy itself never needs docker.sock access. That's basically what I ended up building. dashsync runs standalone, reads dashsync.* labels, and writes Dashy's conf.yml directly. Dashy stays exactly as isolated from Docker as it is today.

https://github.com/NikitaMikhailov/dashsync
