### ISSUE TITLE
[QUESTION] Unable to delete all navigation links

### ISSUE THREAD

**Issue by Pheggas** [Lissy93/dashy#642]
### Question

How could i delete all the navigation links from my dashy instance? I tried it through interactive editor and also by editing configuration file (deleting whole part with navigation links, and also only deleting the two links to docs and github page). Tried rebuilding the app right after so the changes would apply.

Nothing of mentioned helped. After reloading the page, those navigation links appears again. 

PS: Also tried saving it locally but also on disk.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hmm, that maybe sounds like a bug. Let me look into it....
