### ISSUE TITLE
[BUG] system-info widget does not show data

### ISSUE THREAD

**Issue by gergles** [Lissy93/dashy#643]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.0.8</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">On my system, the <code class="notranslate">system-info</code> widget does not properly show data and shows an error message of "An error occurred, see the logs for more info. Error generating backend data".</p>
<p dir="auto">However, it is correctly pulling at least some data (the uname kernel version, uptime, and load average visible in the screenshot are correct, but the hostname is wrong). Clicking retry doesn't make the error go away.</p>
<p dir="auto">Here is the relevant config snippet:</p>
<div class="snippet-clipboard-content position-relative overflow-auto" data-snippet-clipboard-copy-content="  - name: System Info
    widgets:
      - type: system-info"><pre class="notranslate"><code class="notranslate">  - name: System Info
    widgets:
      - type: system-info
</code></pre></div>
<p dir="auto">I am launching dashy from compose but passing no options other than the port mapping and mapping in the config file and item-icons directory as volumes.</p>
<p dir="auto">[As a total aside, while looking in the logs, I did see that every page load fires off API requests to everything with widgets, even if the widget isn't currently visible because the section it is in is collapsed. Is there an option to lazy-load widgets in this case I missed in the docs? Just want to be a good steward of the relevant APIs.]</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto">The JS console shows:<br>
Error generating backend data This is likely not an issue with Dashy, but rather your configuration. If you think it is a bug, please open a ticket on GitHub: <a href="https://git.io/JukXk" rel="nofollow">https://git.io/JukXk</a></p>
<p dir="auto">Nothing unusual appears in the container logs or build log.</p>
<p dir="auto">Screen shot:<br>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/2148340/167544290-bef36162-5b6f-40ea-985c-eef9fab719c6.png"><img width="467" alt="Screen Shot" src="https://user-images.githubusercontent.com/2148340/167544290-bef36162-5b6f-40ea-985c-eef9fab719c6.png" style="max-width: 100%;"></a></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/">Build software better, together</a>                      </strong>        </div>                    <div>GitHub is where people build software. More than 83 million people use GitHub to discover, fork, and contribute to over 200 million projects.</div>                      </blockquote>

**Comment by Lissy93** [comment]
> As a total aside, while looking in the logs, I did see that every page load fires off API requests to everything with widgets, even if the widget isn't currently visible because the section it is in is collapsed. Is there an option to lazy-load widgets in this case I missed in the docs? Just want to be a good steward of the relevant APIs

That's a very good point. And should be easy enough to implement, so I'll add it to my todo list :)
