### ISSUE TITLE
[BUG] Password is incorrect no matter what

### ISSUE THREAD

**Issue by Farsuperslime** [Lissy93/dashy#649]
### Environment

Self-Hosted (Docker)

### Version

2.0.8

### Describe the problem

When I go to configure users and then try to the test them it says the password is incorrect and I know I'm typing it correctly

### Please tick the boxes

- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
That's weird, are you sure you're hashing the passwords correctly?

It needs to be SHA-256, there's a guide under: [Docs → Auth → Hash Password](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md#hash-password)

Maybe the tool you're using to make the hash is adding a trailing space or something. Try using [this one](https://passwordsgenerator.net/sha256-hash-generator/), as it deffo works.

**Comment by Farsuperslime** [comment]
So if I am configuring this through the gui need to create a hash and then type that into the the password spot in the gui config? That makes more sense.

**Comment by Farsuperslime** [comment]
This was the issue, I was just misreading the wiki, thank you!

**Comment by Lissy93** [comment]
Ah yeah, maybe I could make that clearer. Or even handle the hashing on the frontend, and make that input a password field.

Glad you've got it working :)

**Comment by Enissay** [comment]
Okay, it was a double issue: the psw length seems to be wrong and additionally, the config backup I have downloaded had a formatting issue which continues given the many tickets I have seen... Anyhow, my issue is solved...
