### ISSUE TITLE
[FEATURE_REQUEST] Add a dropdown list for theme in the UI config editor

### ISSUE THREAD

**Issue by MilesTEG1** [Lissy93/dashy#65]
Hello again 😄 
It would be nice to have a dropdown list for the theme in the UI config editor, like the one for iconesize :
![image](https://user-images.githubusercontent.com/29298312/123505435-5c143f00-d65f-11eb-96c5-7a70a96da614.png)

Because guessing the right font case for the name is tricky 😆
For example, I set manually the theme to `Nord`, but it didn't work, because it should be `nord`.

It may be great to list them in github doc 😊

Thanks again ✋🏻

**Comment by Lissy93** [comment]
Hey, good idea!

I'm just looking into it now, the config uses the schema defined in [`ConfigSchema.json`](https://github.com/Lissy93/dashy/blob/master/src/utils/ConfigSchema.json), but it actually might be a bit harder than it sounds to put the themes in there, as it would mean users couldn't add there own custom theme, but I will see what I can do :)

In the meantime, here's a list of all available theme keys:
 `callisto`, `thebe`, `dracula`, `material`, `material-dark`, `colorful`, `nord`, `nord-frost`, `minimal-dark`, `minimal-light`, `matrix`, `matrix-red`, `hacker-girl`, `raspberry-jam`, `bee`, `tiger`, `material-original`, `material-dark-original`, `vaporware`, `high-contrast-dark`, `high-contrast-light`.  (the themes names are specified in [defaults.js](https://github.com/Lissy93/dashy/blob/master/src/utils/defaults.js))

**Comment by MilesTEG1** [comment]
> I'm just looking into it now, the config uses the schema defined in [`ConfigSchema.json`](https://github.com/Lissy93/dashy/blob/master/src/utils/ConfigSchema.json), but it actually might be a bit harder than it sounds to put the themes in there, as it would mean users couldn't add there own custom theme, but I will see what I can do :)

Maybe set a `custom` entry that use another line like this :
```yaml
appConfig:
  theme: "custom"
  custom_theme: "myCustomTheme"
```
with `custom_theme: "myCustomTheme"` is the only one that can be whatever the user create.
With this, no need to worry about user's own themes 😃 

What do you think about it ?

**Comment by Lissy93** [comment]
Yeah, that's one solution, but it complicates things having two properties both controlling the theme. I guess `customTheme` could always take precedence, but then the user wouldn't be able to switch  to a built-in theme with the main dropdown.

I have made an addition in 369c6f10db7eab3440a935f82dbbc2541e407424, which shows all the built-in themes in the tip, so when you hover over theme property you should see all the built-in options, but you can still type anything in the box. Do you think that will be enough?

![image](https://user-images.githubusercontent.com/1862727/123511894-20d43900-d67c-11eb-8c51-dfbf2fd483e5.png)

**Comment by MilesTEG1** [comment]
> Yeah, that's one solution, but it complicates things having two properties both controlling the theme. I guess `customTheme` could always take precedence, but then the user wouldn't be able to switch to a built-in theme with the main dropdown.
> 
> I have made an addition in [369c6f1](https://github.com/Lissy93/dashy/commit/369c6f10db7eab3440a935f82dbbc2541e407424), which shows all the built-in themes in the tip, so when you hover over theme property you should see all the built-in options, but you can still type anything in the box. Do you think that will be enough?
> 
> ![image](https://user-images.githubusercontent.com/1862727/123511894-20d43900-d67c-11eb-8c51-dfbf2fd483e5.png)

That should be enough :)

If you managed to get the droplist working with another line, as I suggested, maybe with an algorythm like this
```
if theme = custom then
  use custom_theme value instead
else 
  use theme value as normal
endif
```

(I don't know the language used to code...)

**Comment by Lissy93** [comment]
I'll add it to my todo list -  At the moment I'm going to close the issue, but I will update it in the future if a better solution is implemented 😃
Let me know if you need anything else :)
