### ISSUE TITLE
[BUG] Sports Widget doesn’t display Premier League image correctly

### ISSUE THREAD

**Issue by Bod1985** [Lissy93/dashy#654]
### Environment

Self-Hosted (Docker)

### Version

2.0.8

### Describe the problem

In Safari on iOS (iPad and iPhone), the image for Premier League games is the wrong size meaning only the background colour shows. 

The image is definitely loading as it can be long pressed and saved to photos.

Please see the following image:

![IMG_0306](https://user-images.githubusercontent.com/1529155/168440236-6bea8246-77cb-490e-8a93-cc318dbc43cf.jpeg)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hmm, looks like it's going to be this class in [`SportsScores.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/SportsScores.vue):

https://github.com/Lissy93/dashy/blob/e4562495151b4c368fdce0cbf8d1abc2f9a9ef1c/src/components/Widgets/SportsScores.vue#L237-L241

But I do not have any iOS/ Apple devices to test this out (I'm too poor lol), so would anyone else be able to submit a PR for this one?

**Comment by Bod1985** [comment]
> Hmm, looks like it's going to be this class in [`SportsScores.vue`](https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/SportsScores.vue):
> 
> https://github.com/Lissy93/dashy/blob/e4562495151b4c368fdce0cbf8d1abc2f9a9ef1c/src/components/Widgets/SportsScores.vue#L237-L241
> 
> But I do not have any iOS/ Apple devices to test this out (I'm too poor lol), so would anyone else be able to submit a PR for this one?

I will have a go at some point when I’m back at my desk.

I wonder also if it would be possible to have an option to show/hide the image? I quite like the minimalist look with just a score line

**Comment by Lissy93** [comment]
I can easily add an option to hide the image, that's a good idea - I'll do that now...
