### ISSUE TITLE
[FEATURE_REQUEST] drag and drop feature in edit mode

### ISSUE THREAD

**Issue by skaihahaha** [Lissy93/dashy#662]
<h3 dir="auto">Is your feature request related to a problem? If so, please describe.</h3>
<p dir="auto">Is it possible to add drag and drop feature in edit mode?</p>
<h3 dir="auto">Describe the solution you'd like</h3>
<p dir="auto"><a href="https://github.com/SortableJS/Vue.Draggable">https://github.com/SortableJS/Vue.Draggable</a><br>
This library may help.</p>
<h3 dir="auto">Priority</h3>
<p dir="auto">Low (Nice-to-have)</p>
<h3 dir="auto">Is this something you would be keen to implement</h3>
<p dir="auto"><em>No response</em></p>

<blockquote>                    <img src="https://opengraph.githubassets.com/4d9550982c781143816e8fef27bce170323422811d4395c5c6d67b7f1ed8fbab/SortableJS/Vue.Draggable" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/SortableJS/Vue.Draggable">GitHub - SortableJS/Vue.Draggable: Vue drag-and-drop component based on Sortable.js</a>                      </strong>        </div>                    <div>Vue drag-and-drop component based on Sortable.js. Contribute to SortableJS/Vue.Draggable development by creating an account on GitHub.</div>                      </blockquote>

**Comment by Lissy93** [comment]
Duplicate of #561 #378

Yeah, it's on the [roadmap](https://github.com/Lissy93/dashy/discussions/405) :)
Or was this ticket because you would be interested in submitting a PR for it?
