### ISSUE TITLE
[FEATURE_REQUEST] Extending visibility / permissions on items

### ISSUE THREAD

**Issue by robinduerhager** [Lissy93/dashy#664]
### Is your feature request related to a problem? If so, please describe.

Currently, you can only use the `showForUsers` or `hideForUsers` option in the `displayData` section to hide / show specific sections to specific user. However, it could be helpful to also be able to hide specific `items`. E.g.: I want my users to see the login page for our VMWare vCenter, but i don't want them to see each ESXI Host on it's own (i sometimes have to get access to them, so they are stored with the vCenter in one big "VMWare" Section). 😊 

### Describe the solution you'd like

I'd like to have a `hideForUsers`, `showForUsers` and `hideForGuests` option for each item i have in my Dashy Dashboard, so i can manage item visibility individually per item. 😊 

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

Maybe

**Comment by pinarruiz** [comment]
This sounds like a cool feature.
I think it would be beneficial if at the same time this feature was available for `hideForKeycloakUsers` and `showForKeycloakUsers` too, as they are pretty much used for the same thing.

**Comment by pinarruiz** [comment]
I think we can close this issue since #691 got merged.

**Comment by Lissy93** [comment]
Ah yeah. Thanks for building this @pinarruiz :tada: 
Closing..
