### ISSUE TITLE
[FEATURE_REQUEST] Refresh URL when in Multi-Page

### ISSUE THREAD

**Issue by FormBurden** [Lissy93/dashy#670]
### Is your feature request related to a problem? If so, please describe.

Sorry, not sure if Feature Request or Bug.

I started using the Multi-Page feature which is awesome, but I noticed some odd things happening when refreshing the page from your browser when the URL is in a Multi-Page.

When refreshing while the url is in the Multi-Page i.e xxx.xxx.xx.xx:8080/home/widgets, if I refresh I will get a blank white page with: "Cannot GET /home/widgets" while the tab of the page states "Error". So in order to fix I would have to cut everything until just the "8080" part of the url to get back in. Or my Home button, because I have Dashy as my home page. 

Is there any way around this or a fix? so it loads the page exactly, or even just defaults back to the home "8080"?

If it matters I edit my pages using the config instead of the editing method within Dashy. 

### Describe the solution you'd like

Refreshes will have the same page you're on, and/or when you refresh it just goes to the "home" page of Dashy.

### Priority

Medium (Would be very useful)

**Comment by Lissy93** [comment]
Hmm, that does actually sounds like a bug. Lemme look into it and see if I can recreate it....
If you set `appConfig.routingMode` to `hash`, do you still experience the issue? How are you running Dashy, with Docker, you also using a proxy?

**Comment by FormBurden** [comment]
Oh sorry again, I'm running it on Docker-compose. 

And I just updated to latest: 2.0.9 and enabled the routingMode to hash, and I can confirm that it works correctly when I refresh the page when I'm on a Multi-Page. So I'm guessing when routingMode is on "history", such as not putting routingMode into the config it bugs like what I stated before.

**Comment by NSerbin** [comment]
i have the same problem too

**Comment by Lissy93** [comment]
**If the issue is that multi-pages load on click, but not on direct navigation, then:**
Under `appConfig`, set `routingMode` to `hash`. Then rebuild, and refresh the page.

**If the issue is that a new page is never loading, then:**
Check the [browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console), and you'll see an error message explaining what's not working (likely either 404 not found, 401 unauthorized, or CORS).

**Comment by Danie10** [comment]
Thanks @Lissy93 yes the routingMode settings seems to have solved the page reload issue.

**Comment by paxperscientiam** [comment]
> **If the issue is that multi-pages load on click, but not on direct navigation, then:** Under `appConfig`, set `routingMode` to `hash`. Then rebuild, and refresh the page.
> 
> **If the issue is that a new page is never loading, then:** Check the [browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console), and you'll see an error message explaining what's not working (likely either 404 not found, 401 unauthorized, or CORS).

Thank you, setting `appConfig.routingMode` to "hash" did it for me too.
