### ISSUE TITLE
[BUG] Keycloak 18.0, OpenID Connect Logout, redirect_uri is no longer supported

### ISSUE THREAD

**Issue by PlusaN** [Lissy93/dashy#674]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Bare Metal)</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.0.9</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">Keycloak 18.0.0 release notes:</p>
<blockquote>
<p dir="auto"><h3 dir="auto">OpenID Connect Logout</h3>
Previous versions of Keycloak had supported automatic logout of the user and redirecting to the application by opening logout endpoint URL such as <code class="notranslate">http(s)://example-host/auth/realms/my-realm-name/protocol/openid-connect/logout?redirect_uri=encodedRedirectUri</code>. While that implementation was easy to use, it had potentially negative impact on performance and security. The new version has better support for logout based on the OpenID Connect RP-Initiated Logout specification. The parameter <code class="notranslate">redirect_uri</code> is no longer supported; also, in the new version, the user needs to confirm the logout. It is possible to omit the confirmation and do automatic redirect to the application when you include parameter <code class="notranslate">post_logout_redirect_uri</code> together with the parameter <code class="notranslate">id_token_hint</code> with the ID Token used for login.</p>
</blockquote>
<p dir="auto"><a href="https://www.keycloak.org/2022/04/keycloak-1800-released.html" rel="nofollow">https://www.keycloak.org/2022/04/keycloak-1800-released.html</a></p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                                <div>          <strong>                          <a href="https://www.keycloak.org/2022/04/keycloak-1800-released.html">Keycloak 18.0.0 released - Keycloak</a>                      </strong>        </div>                    <div>Keycloak is an open source identity and access management solution</div>                      </blockquote>

**Comment by PlusaN** [comment]
I upgrade keycloak-js to latest version (18.0.0), the problem is no more. But I'm not sure if everything works correctly with the updated package. Need testing :)
`yarn upgrade keycloak-js`

**Comment by Lissy93** [comment]
I forgot to update this ticket, but this was fixed in #663
