### ISSUE TITLE
[SHOWCASE] <Brewhack>

### ISSUE THREAD

**Issue by brpeterso** [Lissy93/dashy#680]
### Title

Brewhack

### Screenshot

![Brewhack](https://user-images.githubusercontent.com/24624605/170798135-2cdec149-e600-45c7-aea2-e5102ceb57b3.png)

### Would you like your name/ username included?

Yes

**Comment by Lissy93** [comment]
You've got a lot of awesome stuff running there!
Thanks for sharing, I'll include it in the the next PR, this weekend :)
