### ISSUE TITLE
[BUG] Copy to Clipboard doesn't work

### ISSUE THREAD

**Issue by wtld** [Lissy93/dashy#681]
### Environment

Self-Hosted (Docker)

### Version

2.0.9

### Describe the problem

Export config to clipboard doesn't work (button "Copy to Clipboard"). Message in the console:

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'writeText')
    at r.copyConfigToClipboard (ExportConfigMenu.vue:83:27)
    at click (Button.vue?df23:1:384)
    at ne (vue.runtime.esm.js:1863:26)
    at HTMLButtonElement.i (vue.runtime.esm.js:2188:14)
    at HTMLButtonElement.Qs.o._wrapper (vue.runtime.esm.js:6961:25)
```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya @wtld 👋 Sorry about that
Are you running the app over HTTPS? Copying to the clipboard requires the app to be running in a secure origin / aka have valid HTTPS cert. This is explained in a bit more detail [here](https://stackoverflow.com/a/71876238/979052).

As a workaround, you could either:
- Highlight the text and copy / <kbd>Ctrl</kbd> + <kbd>C</kbd>
- Or setup SSL - [here's a guide](https://github.com/Lissy93/dashy/blob/master/docs/management.md#ssl-certificates) on doing so

From my end, I will add an error boundary in, to check if clipboard access is available in the users context, and display a more meaningful message if not :)

**Comment by wtld** [comment]
Thank you for the quick reply. I don't use ssl so that's the reason.
