### ISSUE TITLE
Glances widget not loading when using Dashy with Traefik or Nginx

### ISSUE THREAD

**Issue by ViciousWall** [Lissy93/dashy#686]
### Question

Just want to start with saying I really love this dashboard and thank you Lissy93 for all the work you have put in to make this app great.

I recently tried adding Glances widget with my dashboard and for some reason I keep getting an error loading the widget when I run the service using Traefik or Nginx but when I use my internal IP it loads without any issues. I am not sure if I am doing something wrong here but any help on this would be appreciated.

Let me know if you need any screenshots or any other information on this.

Thanks again :)

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Oops, sorry for my bad bod 🤖

That would be a CORS error. If you could share the contents of [the browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console), there should be some additional info there.

Not sure if you've seen it yet, but there's also a section about this under [Troubleshooting → Widget CORS Errors](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#widget-cors-errors), which might help a bit.

But basically, if setting `useProxy: true` doesn't work, then you'll need to set the access control headers for Glances [in your Traefik](https://doc.traefik.io/traefik/middlewares/http/headers/), to accept requests from Dashy.

**Comment by ViciousWall** [comment]
Thank you for your quick response,

I went through the CORS Errors but I had no idea if it actually related to my issue, so apologies that I ended up raising a query for it. Adding the useProxy: true on my config.yml file worked and its now able to display glances widget without issues.

Cheers :)

**Comment by ZanzyTHEbar** [comment]
> Thank you for your quick response,
> 
> I went through the CORS Errors but I had no idea if it actually related to my issue, so apologies that I ended up raising a query for it. Adding the useProxy: true on my config.yml file worked and its now able to display glances widget without issues.
> 
> Cheers :)

may i ask - how did you get tis working with traefik - my dashboard refuses to load. Usign the IP - works fine - but through traefik, no dice.
