### ISSUE TITLE
[QUESTION] Docker mapping all of /app/public question

### ISSUE THREAD

**Issue by cyrus104** [Lissy93/dashy#693]
### Question

I am using docker to map an nfs/smb volume in for my configuration. The issue with this is you can smb map a folder but not a file. I would like to see if there would be an issue with mapping the whole /app/public folder in. I know there are a decent number of files in there that might have issues with restarts or rebuilts?

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by cyrus104** [comment]
What about creating a config folder in side the public app and then adding an if statement looking for the config files and if it falls fall back to the current location?

**Comment by RafaelSchridi** [comment]
Couln't this be solved with a simple symlink? move config to /config and link /config/conf.yaml to /public/conf.yaml

**Comment by joshbuker** [comment]
Hi @Lissy93, just running into this same issue myself and was wondering if there's any update on the `/user-data` mapping?

**Comment by gzl10g** [comment]
I have a swarm cluster with nfs volumes for persistance and have the same problem with the config file.

**Comment by CrazyWolf13** [comment]
Hi
This should now be fixed within the new V3 release of dashy, take a look here https://github.com/Lissy93/dashy/discussions/1537 and here https://github.com/Lissy93/dashy/discussions/1529

Keep in mind V3 has breaking changes, update the volumes and the port accordingly.
