### ISSUE TITLE
[BUG] Minimal view tiles heading text not visible

### ISSUE THREAD

**Issue by Lissy93** [Lissy93/dashy#697]
### Discussed in https://github.com/Lissy93/dashy/discussions/695

<div type='discussions-op-text'>

<sup>Originally posted by **mail02ankit** June  3, 2022</sup>
Hi All,

I started using Dashy recently. It has been really good. Thanks for this nice application.

I found a problem with my installation. Somehow, when I switched to minimal view the text in the heading of tiles is not visible. For the default view it works fine. I have tried switching themes and color schemes, it did not help.

Any help will be appreciated,
Thanks.

![minimal_dashy](https://user-images.githubusercontent.com/19859282/171756946-995e80bb-251a-47c0-997a-b7808e698299.png)

</div>

**Comment by CrazyWolf13** [comment]
This seems resolved for me.
