### ISSUE TITLE
[BUG] Connection not work, if the expiration is set to "Never"

### ISSUE THREAD

**Issue by EVOTk** [Lissy93/dashy#70]
**If applicable to your issue, please include:**
**- A description of the bug, including actual behavior and if applicable, expected behavior**
Connection not work, if the expiration is set to "Never"
If an expiration time is chosen the connection works

If I choose "Never" then "Logging in ..." appears but nothing happens
![2021-06-27 00_26_28-Dashy](https://user-images.githubusercontent.com/45015615/123527428-bead1f80-d6df-11eb-9b76-67197a357e05.png)

**- Info about your system (device, OS, browser and browser version)**
> System Info
Dashy Version: V 1.3.6
Browser: Firefox
Is Mobile? No
OS: Windows

- Any console errors? If the issue happens at runtime, open up the dev tools [F12], and go to the Console tab. If the output is very long, please use [0bin](https://0bin.net/)
https://0bin.net/paste/9xymypXr#oiiiQfiFH2fE5Ipm6RdopVTMWTAqlLd69cf3KmFhdql

**Comment by Lissy93** [comment]
Thanks for raising this, looks like it was an issue when I calculated the timeout, when set the Never the data times out immediately causing an error. I've fixed it in #71 :)
