### ISSUE TITLE
[BUG] memory allocation failure on docker deploy

### ISSUE THREAD

**Issue by ex3me4me** [Lissy93/dashy#707]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.0</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">Trying to deploy docker container, memory allocation failure error and container keep restarting over and over again.<br>
deploying with "latest" tag, tried 2.0.9 - 2.0.6 same outcome.</p>
<p dir="auto">VM Ubuntu 20.04.4 LTS<br>
Ballooning 2GB ram<br>
Docker version 20.10.16, build aa7e414</p>
<p dir="auto">Temporary solution is to turn off ballooning and give the vm full 2GB to alocate, then container deploy with no problems.</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto">yarn run v1.22.15</p>
<p dir="auto">$ npm-run-all --parallel build-watch start</p>
<p dir="auto">$ node server</p>
<p dir="auto">$ vue-cli-service build --watch --mode production</p>
<p dir="auto">Checking config file against schema...</p>
<p dir="auto"><g-emoji class="g-emoji" alias="heavy_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2714.png">✔️</g-emoji> Config file is valid, no issues found</p>
<p dir="auto">SSL Not Enabled: Public key not present</p>
<p dir="auto">██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗</p>
<p dir="auto">██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝</p>
<p dir="auto">██║  ██║███████║███████╗███████║ ╚████╔╝</p>
<p dir="auto">██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝</p>
<p dir="auto">██████╔╝██║  ██║███████║██║  ██║   ██║</p>
<p dir="auto">╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝</p>
<hr>
<p dir="auto">Welcome to Dashy! <g-emoji class="g-emoji" alias="rocket" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f680.png">🚀</g-emoji></p>
<p dir="auto">Your new dashboard is now up and running with Docker</p>
<hr>
<p dir="auto">Using Dashy V-2.1.0. Update Check Complete</p>
<p dir="auto"><g-emoji class="g-emoji" alias="white_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2705.png">✅</g-emoji> Dashy is Up-to-Date</p>
<ul dir="auto">
<li>Building for production...</li>
</ul>
<p dir="auto">WARN  A new version of sass-loader is available. Please upgrade for best experience.</p>
<p dir="auto">&lt;--- Last few GCs ---&gt;</p>
<p dir="auto">[66:0x7fe11678b350]    31234 ms: Scavenge 346.6 (358.3) -&gt; 346.6 (359.3) MB, 4.8 / 0.0 ms  (average mu = 0.283, current mu = 0.164) allocation failure</p>
<p dir="auto">[66:0x7fe11678b350]    31314 ms: Scavenge 347.5 (359.3) -&gt; 347.4 (364.1) MB, 79.4 / 0.0 ms  (average mu = 0.283, current mu = 0.164) allocation failure</p>
<p dir="auto">&lt;--- JS stacktrace ---&gt;</p>
<p dir="auto">FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory</p>
<p dir="auto">error Command failed with signal "SIGABRT".</p>
<p dir="auto">info Visit <a href="https://yarnpkg.com/en/docs/cli/run" rel="nofollow">https://yarnpkg.com/en/docs/cli/run</a> for documentation about this command.</p>
<p dir="auto">ERROR: "build-watch" exited with 1.</p>
<p dir="auto">error Command failed with exit code 1.</p>
<p dir="auto">info Visit <a href="https://yarnpkg.com/en/docs/cli/run" rel="nofollow">https://yarnpkg.com/en/docs/cli/run</a> for documentation about this command.</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy (check the first two digits of the version number)</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://classic.yarnpkg.com/assets/og_image.png" width="48" align="right" />                          <div>          <strong>                          <a href="https://classic.yarnpkg.com/en/docs/cli/run/">Yarn</a>                      </strong>        </div>                    <div>Fast, reliable, and secure dependency management.</div>                      </blockquote>

**Comment by Lissy93** [comment]
Covered in the  [Troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#ineffective-mark-compacts-near-heap-limit-allocation-failed) guide.

Similar to #380, #350, #297, #349, #510 and #511.

If you can, please try and check the docs and past issues before opening a new ticket.
