### ISSUE TITLE
Author and owner 

### ISSUE THREAD

**Issue by dreamingskey** [Lissy93/dashy#709]
### Title

Author christopher paul vincent

### Screenshot

Dreamingskey/christopher paul vincent the author and rights of christopher paul vincent
Dreamings key

### Would you like your name/ username included?

Yes

### Link to your Website/ Profile/ Twitter (optional)

Facebook

### Description (Optional)

The begging of a dream and I maintain all rights of creativity I. This dream and if you had other pla ns I'm sory but you'll have to get  in line like the rest. And remember how to.   All rights reserved to christopher paul vincent

**Comment by Lissy93** [comment]
I'm not sure what mean o.O
Keeping closed, as likely spam.

**Comment by dreamingskey** [comment]
I am author of all startups this is not span this is me I AM CODE AS OF NOW

**Comment by dreamingskey** [comment]
There is a new world and all need to know where ot starts before we can begin

**Comment by dreamingskey** [comment]
Recognition on all programing needs to be made to christopher paul vincent

**Comment by Lissy93** [comment]
I have no idea what you're trying to say. To open a valid ticket, you must provide valid info.
Sorry, but keeping closed as spam.
