### ISSUE TITLE
[BUG] Material-Dark Theme items not expanding to fit Section

### ISSUE THREAD

**Issue by gbrown09** [Lissy93/dashy#715]
### Environment

Self-Hosted (Docker)

### Version

2.1.0

### Describe the problem

Not sure if this is intentional or not but when using the Material-Dark theme the items are not filling the section when using medium or large size.
![image](https://user-images.githubusercontent.com/3360055/172708999-4df15e0b-858b-4240-81bc-3a8a93b72d3d.png)

It seems to work when using small size or any other theme

![image](https://user-images.githubusercontent.com/3360055/172709574-79d4293d-610c-4565-89b2-7509da21e358.png)
![image](https://user-images.githubusercontent.com/3360055/172709695-6bf8739d-1ea0-43b7-8dbd-ebcef41b0363.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
The material and material-dark themes have [some CSS changes](https://github.com/Lissy93/dashy/blob/master/src/styles/color-themes.scss#L567-L696) which would be what has caused this
I guess it probably is a bug, as you'd expect the layout to be consistent across themes

In the meantime, there is also material-original theme, which doesn't have any layout changes or custom animations
Alternatively, just add a lil bit of [custom CSS](https://github.com/Lissy93/dashy/blob/master/docs/theming.md#setting-custom-css-in-the-ui) to get what you want, e.g. `a.item.size-medium { width: auto; }`
