### ISSUE TITLE
[QUESTION] Section Auto Layout - Widgets don't play nice.

### ISSUE THREAD

**Issue by matthewjdegarmo** [Lissy93/dashy#720]
### Question

I don't know if this is an actual issue, or if I did something wrong in my config, but it looks like if you ONLY have sections with `items:` in it, the sections will all stag 'snug' with each other and not have big gaps.
![image](https://user-images.githubusercontent.com/46715299/172879633-e34ad8f7-5218-49b5-be21-3d4d2abe1834.png)

BUT when I add widgets, they don't move up in the empty space like you'd expect. Is this intentional? Here's my example. The 2nd row doesn't start until after the end of the Pi-Hole stats widget on the right. I'd expect these regions to 'overlap' and move up to be directly under the items / sections directly above them.

![image](https://user-images.githubusercontent.com/46715299/172880141-19554118-f2ea-4401-a8ad-4ff1c856b218.png)

Thoughts?

### Category

Theming & Layout

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
You can make a section span multiple / n columns  with `displayData.cols: 2`, or multiple rows with `displayData.rows: 2`
So in your example, you could try something like this:

```yaml
sections:
- name: Pi-Hole Primary Stats
  displayData:
    rows: 2
  widgets:
    ...
```

Let me know if that helps :)

**Comment by anencephalic** [comment]
> You can make a section span multiple / n columns with `displayData.cols: 2`, or multiple rows with `displayData.rows: 2` So in your example, you could try something like this:
> 
> ```yaml
> sections:
> - name: Pi-Hole Primary Stats
>   displayData:
>     rows: 2
>   widgets:
>     ...
> ```
> 
> Let me know if that helps :)

Thank you for sharing, but your response seems incomplete to me.  I tried adding my widget code in that section you pointed out and the file will not rebuild.  It errors out.  

Then again, I am pretty stupid at this level.  Can you share more...?
