### ISSUE TITLE
[FEATURE_REQUEST] Sabnzbd widget

### ISSUE THREAD

**Issue by poke0** [Lissy93/dashy#722]
### Is your feature request related to a problem? If so, please describe.

No problem, but I do miss a feature available in Heimdall.  No urgency for you to reply; take your time.

As an aside, I love the app.  It's a little memory intensive bit it is incredibly flexible and looks to do everything I'm looking for.  Icon handling is great.

### Describe the solution you'd like

1) Display current sizeleft and speed for live queue - This is available in Heimdall
2) Display most recent downloads from history (my example is showing most recent 3) - this would be an extension

I believe this meets your requirements of:
1. Publicly accesable API - Sabnzbd API details are here: (https://sabnzbd.org/wiki/configuration/3.6/api)
2. CORS and HTTPS enabled - Actually I'm not familiar with CORS and I see no mention of it on the API page.  I have HTTPS turned off on my Sabnzbd server but I could easily turn it on.
3. Free to use - I'm hosting it locally so it is free.
4. Allow for use in their TOS - I expect so (Heimdall is using it)
5. Would be useful for others - I expect so

Sizeleft and speed are queried by this commend: `http://[ip:port]/sabnzbd/api?output=xml&apikey=[apikey]&mode=queue` with the following results:
`<queue>
<version>3.6.0</version>
<paused>False</paused>
<pause_int>0</pause_int>
<paused_all>False</paused_all>
<diskspace1>383.36</diskspace1>
<diskspace2>4913.81</diskspace2>
<diskspace1_norm>383.4 G</diskspace1_norm>
<diskspace2_norm>4.8 T</diskspace2_norm>
<diskspacetotal1>476.69</diskspacetotal1>
<diskspacetotal2>14900.06</diskspacetotal2>
<loadavg>0.79 | 0.42 | 0.32 | V=114M R=82M</loadavg>
<speedlimit>50</speedlimit>
<speedlimit_abs>26214400.0</speedlimit_abs>
<have_warnings>0</have_warnings>
<finishaction/>
<quota>0 </quota>
<have_quota>False</have_quota>
<left_quota>0 </left_quota>
<cache_art>0</cache_art>
<cache_size>0 B</cache_size>
<kbpersec>0.00</kbpersec>
**<speed>0 </speed>**
<mbleft>0.00</mbleft>
<mb>0.00</mb>
**<sizeleft>0 B</sizeleft>**
<size>0 B</size>
<noofslots_total>0</noofslots_total>
<noofslots>0</noofslots>
<start>0</start>
<limit>0</limit>
<finish>0</finish>
<status>Idle</status>
<timeleft>0:00:00</timeleft>
<scripts/>
<categories>
<category>Default</category>
<category>tv</category>
<category>movies</category>
<category>software</category>
<category>audio</category>
<category>readarr</category>
</categories>
<slots/>
</queue>`

History is available via this commend: `http://[ip:port]/sabnzbd/api?output=xml&apikey=[apikey]&mode=history&limit=3` with the following results:
`<history>
<total_size>5.7 T</total_size>
<month_size>20.6 G</month_size>
<week_size>13.6 G</week_size>
<day_size>0 </day_size>
<slots>
<slot>
<id>12</id>
<completed>1643546003</completed>
<name>Diners Drive-Ins and Dives S42E01 From Europe to Asia 720p WEBRip x264-KOMPOST</name>
<nzb_name>Diners.Drive-Ins.and.Dives.S42E01.From.Europe.to.Asia.720p.WEBRip.x264-KOMPOST.nzb</nzb_name>
<category>tv</category>
<pp>D</pp>
<script>None</script>
<report/>
<url>Diners.Drive-Ins.and.Dives.S42E01.From.Europe.to.Asia.720p.WEBRip.x264-KOMPOST.nzb</url>
<status>Completed</status>
<nzo_id>SABnzbd_nzo_xsjmambl</nzo_id>
<storage>/Media/Downloads/SABnzbd/tv/Diners Drive-Ins and Dives S42E01 From Europe to Asia 720p WEBRip x264-KOMPOST/Diners.Drive-Ins.and.Dives.S42E01.From.Europe.to.Asia.720p.WEBRip.x264-KOMPOST.mkv</storage>
<path>/incomplete-downloads/Sabnzbs-incomplete-downloads/Diners.Drive-Ins.and.Dives.S42E01.From.Europe.to.Asia.720p.WEBRip.x264-KOMPOST</path>
<script_log/>
<script_line/>
<download_time>39</download_time>
<postproc_time>2</postproc_time>
<stage_log>
<slot>
<name>Source</name>
<actions>
<item>Diners.Drive-Ins.and.Dives.S42E01.From.Europe.to.Asia.720p.WEBRip.x264-KOMPOST.nzb</item>
</actions>
</slot>
<slot>
<name>Download</name>
<actions>
<item>Downloaded in 39 seconds at an average of 12.0 MB/s<br/>Age: 23h</item>
</actions>
</slot>
<slot>
<name>Servers</name>
<actions>
<item>Newsgroupdirect*Usenetexpress=470.5 MB</item>
</actions>
</slot>
<slot>
<name>Repair</name>
<actions>
<item>[f3a59282b6b2e7371b40ef91519b753a] Quick Check OK</item>
</actions>
</slot>
<slot>
<name>Unpack</name>
<actions>
<item>[f3a59282b6b2e7371b40ef91519b753a] Unpacked 1 files/folders in 2 seconds</item>
</actions>
</slot>
</stage_log>
<downloaded>493332395</downloaded>
<completeness/>
<fail_message/>
<url_info/>
<bytes>493332395</bytes>
<meta/>
<series>diners drive-ins and dives/42/1</series>
<md5sum>900ba45a759377097519e9fd11722ef6</md5sum>
<password/>
<action_line/>
<size>470.5 MB</size>
<loaded>False</loaded>
<retry>0</retry>
</slot>
<slot>
<id>8</id>
<completed>1639547751</completed>
<name>Dogs 101 S03E04 720p HDTV x264-CBFM</name>
<nzb_name>Dogs.101.S03E04.720p.HDTV.x264-CBFM.nzb</nzb_name>
<category>tv</category>
<pp>D</pp>
<script>None</script>
<report/>
<url>Dogs.101.S03E04.720p.HDTV.x264-CBFM.nzb</url>
<status>Completed</status>
<nzo_id>SABnzbd_nzo_9hm_9e9y</nzo_id>
<storage>/Media/Downloads/SABnzbd/tv/Dogs 101 S03E04 720p HDTV x264-CBFM</storage>
<path>/incomplete-downloads/Sabnzbs-incomplete-downloads/Dogs.101.S03E04.720p.HDTV.x264-CBFM</path>
<script_log/>
<script_line/>
<download_time>114</download_time>
<postproc_time>21</postproc_time>
<stage_log>
<slot>
<name>Source</name>
<actions>
<item>Dogs.101.S03E04.720p.HDTV.x264-CBFM.nzb</item>
</actions>
</slot>
<slot>
<name>Download</name>
<actions>
<item>Downloaded in 1 min 54 seconds at an average of 11.4 MB/s<br/>Age: 2140d</item>
</actions>
</slot>
<slot>
<name>Servers</name>
<actions>
<item>Newsgroupdirect*Usenetexpress=1.2 GB, Thecubenet*Usenetexpress=3 KB, Vipernews=3 KB, Maximumusenet*Omicron=114.7 MB</item>
</actions>
</slot>
<slot>
<name>Repair</name>
<actions>
<item>[dogs101.0304.720p-cbfm] Quick Check OK</item>
</actions>
</slot>
<slot>
<name>Unpack</name>
<actions>
<item>[dogs101.0304.720p-cbfm] Unpacked 1 files/folders in 21 seconds</item>
</actions>
</slot>
</stage_log>
<downloaded>1368672322</downloaded>
<completeness/>
<fail_message/>
<url_info/>
<bytes>1368672322</bytes>
<meta/>
<series>dogs 101/3/4</series>
<md5sum>57fc20c4efbd669d2384ac6e28d3346e</md5sum>
<password/>
<action_line/>
<size>1.3 GB</size>
<loaded>False</loaded>
<retry>0</retry>
</slot>
<slot>
<id>7</id>
<completed>1639547700</completed>
<name>Dogs 101 S04E04 Grooming Special 1080i HDTV DD5 1 MPEG2-TrollHD</name>
<nzb_name>Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD.nzb</nzb_name>
<category>tv</category>
<pp>D</pp>
<script>None</script>
<report/>
<url>Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD.nzb</url>
<status>Completed</status>
<nzo_id>SABnzbd_nzo_hbw9kocp</nzo_id>
<storage>/Media/Downloads/SABnzbd/tv/Dogs 101 S04E04 Grooming Special 1080i HDTV DD5 1 MPEG2-TrollHD/Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD.ts</storage>
<path>/incomplete-downloads/Sabnzbs-incomplete-downloads/Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD</path>
<script_log/>
<script_line/>
<download_time>403</download_time>
<postproc_time>79</postproc_time>
<stage_log>
<slot>
<name>Source</name>
<actions>
<item>Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD.nzb</item>
</actions>
</slot>
<slot>
<name>Download</name>
<actions>
<item>Downloaded in 6 mins 43 seconds at an average of 11.3 MB/s<br/>Age: 3738d</item>
</actions>
</slot>
<slot>
<name>Servers</name>
<actions>
<item>Newsgroupdirect*Usenetexpress=149 KB, Thecubenet*Usenetexpress=152 KB, Vipernews=152 KB, Maximumusenet*Omicron=4.4 GB</item>
</actions>
</slot>
<slot>
<name>Repair</name>
<actions>
<item>[Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD] Quick Check OK</item>
</actions>
</slot>
<slot>
<name>Unpack</name>
<actions>
<item>[Dogs 101 S04E04 Grooming Special 1080i HDTV DD5.1 MPEG2-TrollHD] Unpacked 1 files/folders in 1 min 19 seconds</item>
</actions>
</slot>
</stage_log>
<downloaded>4769620721</downloaded>
<completeness/>
<fail_message/>
<url_info/>
<bytes>4769620721</bytes>
<meta/>
<series>dogs 101/4/4</series>
<md5sum>b89cf7f92794e65c7bc65487f002a1be</md5sum>
<password/>
<action_line/>
<size>4.4 GB</size>
<loaded>False</loaded>
<retry>0</retry>
</slot>
</slots>
<noofslots>7</noofslots>
<last_history_update>115</last_history_update>
<version>3.6.0</version>
</history>`

XML formatting was stripped as part of the copy/paste bu tI'm sure you get the idea.  I'll attach file to make it easier.
[mode=queue.txt](https://github.com/Lissy93/dashy/files/8883292/mode.queue.txt)
[mode=history.txt](https://github.com/Lissy93/dashy/files/8883293/mode.history.txt)

### Priority

Low (Nice-to-have)

**Comment by poke0** [comment]
I've starred the repository and provided feedback to a couple of issues.  I've also checked that this isn't a duplicate and the documentation doesn't include a Sabnzbd widget already.  All relevant sections have been completed.
I don't see that I can reopen the issue since I didn't close it.  Can you reopen it?

**Comment by Lissy93** [comment]
Sorry about that, bad bot- I've reopened.

Thanks for all the info, I'll look into it and see if i can get it built :)

**Comment by poke0** [comment]
No worries and thank you.  If you are able to build it I would be happy to test.  Sorry I'm not a dev, I'm just a poor sysadmin.  :)

**Comment by Lissy93** [comment]
Hiya @poke0 
A Sabnzbd widget has been built by @alucarddelta and merged in #790 :tada:

**Comment by poke0** [comment]
Thanks so much for this!  I love the layout/look and feel.  I did discover an issue when testing it today.  The widget only refreshes when you manually hit the refresh button.    I never mentioned this in the requirements but I would hope for something tunable with a default of maybe 2-5 minutes when idle, but the ability to increase the polling interval to 20-60 seconds when SABnzbd is active.
My other comment is would it be possible to show more of the filename of the file being downloaded?  At least to take advantage of whatever screen real estate is available would be appreciated.
Thank you again!  Let me know if you want me to open a new issue instead of commenting on this one.

**Comment by Lissy93** [comment]
@poke0 - You need to need to set the update interval yourself. See **[Widgets → Continuous Updates](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#continuous-updates)**
Basically, just add `updateInterval: 2` on that widget.

**Comment by poke0** [comment]
[smacks head]. It works!  Thank you.

**Comment by alucarddelta** [comment]
@poke0 I'm open to change a few things of the widget if you think it could look better.

The filename issue you mention is a limitation of the minimal widget size. I found with my testing that what I have set is the maximum amount of characters that will not break the layout/formatting when the window is at the smallest. At a point dashy then rearranges and resizes itself. I have an idea to resolve this, just it wont be anytime soon :P

**Comment by poke0** [comment]
It isn't that important and probably isn't worth the effort if you have to work around something, but thank you for the offer.  I have to say I've only had it a few hours and I already love it.  I didn't expect anything to be downloaded today but the widget let me know about a large back of files so that was cool.  Thank you!  :)
