### ISSUE TITLE
Setting Language zh-CN unsuccessful

### ISSUE THREAD

**Issue by Kry1702** [Lissy93/dashy#728]
Verions : 2.1.0

Set the language through the panel (zh-CN), save the configuration prompts to write to the disk successfully. The actual config.yaml file has not been tampered with, and the new browser accesses the UI panel again, and the viewing language is "en"

**Comment by Kry1702** [comment]
problem solved

**Comment by hoey94** [comment]
I modified config.yml, but the page did not automatically adjust to Chinese

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/93bc4dfb-b864-4ddf-b2c9-00eb24176699">
