### ISSUE TITLE
[BUG] Cloudflare Continuous Deployment is Broken

### ISSUE THREAD

**Issue by Glitch3dPenguin** [Lissy93/dashy#731]
### Environment

Cloud Service (Static)

### Version

2.1.0

### Describe the problem

It seems that when you attempt to deploy to Cloudflare, the workflow on GitHub never runs.
Cloudflare reports an error and brings up the Github workflow but there is nothing listed there at all. 

### Additional info

After choosing the options "Authorize Workers" and completing the required steps I am left at the page shown in the screenshot.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct
![BrokenWorkers](https://user-images.githubusercontent.com/3271160/173678264-92bbc6ce-b1f4-4f88-8a4d-e14ba4fbaf0d.PNG)
)

**Comment by Glitch3dPenguin** [comment]
Tried to deploy again with personal fork and main. Continuing to fail with no errors.

**Comment by yuanweize** [comment]
> Yeah, looks like it's broken. Will see to it when I get a moment. In the meantime, Netlify deploy works well.

I add BOT_GITHUB_TOKEN to repo secrets and re-run action job deploy_ to_cf_workers, run successful and no error anymore.  But seems not action with CF workers, no new project create... Maybe need to fix docs-link-checker.yml

**Comment by Lissy93** [comment]
I think I need either add an action which keeps the cloudflare branch up-to-date, or include the cloudflare config files in the main branch. I did have it working about a year ago, but didn't think anyone would use it, so kind of forgot about it....

I'll reopen this ticket, and when I finish #799, I'll fix the Cloudflare and Vercel deploys :)

---

In the meantime, deploying to Netlify works great, and I've ported over the server-side status checking to [Netlify functions](https://docs.netlify.com/functions/overview/) ([this code](https://github.com/Lissy93/dashy/tree/master/services/serverless-functions)). Netlify is free, and really fast and reliable.
To deploy, just fork the repo, then login to Netlify and import it, and updating the config file in your GH repo will update the live site (but can't save through the UI editor on Netlify).

**Comment by autumnwalker** [comment]
Is Cloudflare Workers still broken? I'm a new user trying to deploy and keep getting an "error" during deployment with no sort of error log or anything obvious.

**Comment by Glitch3dPenguin** [comment]
> Is Cloudflare Workers still broken? I'm a new user trying to deploy and keep getting an "error" during deployment with no sort of error log or anything obvious.

Yes, it is still broken. I've since moved to Hiemdall dashboard. Might switch back if this gets fixed.

**Comment by yuanweize** [comment]
> Is Cloudflare Workers still broken? I'm a new user trying to deploy and keep getting an "error" during deployment with no sort of error log or anything obvious.

I recommend this[https://github.com/pawelmalak/flame](https://github.com/pawelmalak/flame)

**Comment by kaylak4520** [comment]
@Lissy93 

Not to be that person, buuuuuutttttt:
Will this be fixed?  
If not, probably should remove this deployment option since it's not worked for over a year at this point.

PS: Thank you for making Dashy!!!!!!

**Comment by Glitch3dPenguin** [comment]
> @Lissy93
> 
> Not to be that person, buuuuuutttttt: Will this be fixed? If not, probably should remove this deployment option since it's not worked for over a year at this point.
> 
> PS: Thank you for making Dashy!!!!!!

Cloudflare support has been officially dropped today as of this [merged pull request](https://github.com/Lissy93/dashy/pull/1364#event-10782299717). I would suggest running this on a platform that might support docker or docker-compose. I switched to it and it's been pretty great. Otherwise I also think the [Netlify](https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#netlify) deployment options still works. If you are looking for a cloud option it's a pretty cool platform.
