### ISSUE TITLE
duplicate category

### ISSUE THREAD

**Issue by Kry1702** [Lissy93/dashy#732]
### Is your feature request related to a problem? If so, please describe.

When creating a new Section, add a new item. There are actually multiple identical items. You can specify different item names to distinguish them when you create them, but I personally feel that it is not very friendly.

Example:
There are multiple Harbor Servers in the enterprise,Creating projects can only be distinguished by different names, and it does not feel particularly friendly.

### Describe the solution you'd like

Expect to add subclasses when creating new projects. Display the project name "for example: Harbor" in the newly added project, display the defined name in the subclass, Access the names of different subclasses and jump to different services.

Figure 1 represents the unfriendly effect.
Figure 2 shows the expected effect.

https://www.upload.ee/image/14228847/1.png
https://www.upload.ee/image/14228848/2.png

### Priority

Medium (Would be very useful)

**Comment by Lissy93** [comment]
You can already do this, with [sub-items](https://github.com/Lissy93/dashy/blob/master/docs/pages-and-sections.md#sub-items)

**Comment by Lissy93** [comment]
Closing, as already possible.
