### ISSUE TITLE
[BUG] conf.yml is there in public/ but it is not read...

### ISSUE THREAD

**Issue by Zamana** [Lissy93/dashy#737]
### Environment

Self-Hosted (Bare Metal)

### Version

2.1.0

### Describe the problem

I'm running the non-docker version of Dashy with "npm start". Everything seems to run fine: I'm able to customize the dashboard  with the links to my web apps, and save them to the disk, but if I stop and run the service again, the public/conf.yml seems not to be read. Everything is there, saved, but dashy doesn't read it.

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Am working on this atm
But in the meantime, just run `yarn build`
Or from the UI, go to Config → Rebuild.

**Comment by Lissy93** [comment]
Linked to #799

**Comment by CrazyWolf13** [comment]
Hi
This problems seems to be related to dashy not automatically rebuilding on changes, see #1479 and https://github.com/Lissy93/dashy/issues/1290#issuecomment-1884249018 
A new release has just been published, which should fix this issue, so please upgrade to the latest version.
If this is not the case just respond back to this ticket and I'll reopen this issue.
Thanks and have a nice day.
