### ISSUE TITLE
[SHOWCASE_REQUEST]

### ISSUE THREAD

**Issue by cerealconyogurt** [Lissy93/dashy#74]
Please read the instructions here first:
https://github.com/Lissy93/dashy/blob/master/docs/showcase.md#submitting-your-dashboard

### Complete the Following
- **Title of Dashboard**: NAS Home Dashboard
- **Link to Screenshot**: https://ibb.co/4tgBj8g
- **Would you like your name/ username included**: Yes
- **Link to your Website/ Profile/ Twitter** (optional)
- **Description** (optional)

**Comment by Lissy93** [comment]
Thank you 😊
Added [Here](https://github.com/Lissy93/dashy/blob/master/docs/showcase.md#nas-home-dashboard) 👈

**Comment by juneggg6** [comment]
#74
