### ISSUE TITLE
[BUG] Edit Config not saving changes

### ISSUE THREAD

**Issue by UrekD** [Lissy93/dashy#742]
### Environment

Self-Hosted (Docker)

### Version

2.1.0

### Describe the problem

Updating the config with the "old" editor tree/code doesn't save changes to the config file on disk, just writes the config again with same data. Using the interactive editor it saves it fine. Looking at the POST request send when trying to save, in case of the interactive editor the value passed includes the config with the changes. But when looking at the same POST with the other editor it just passes on the same config as before it was edited.

Tested on my config and also a fresh container. Tried clearing cookies and rebuild, but I'm guessing that doesn't matter much if data doesn't reach the config anyway. Also saving to local doesn't work either in the "old" editor. If you preview the changes it writes changes instantly, I'm guessing it uses the same layout and functions as the interactive editor. Most likely related to #603, opened this as that had no real info.

### Additional info

Interactive edit writes new data to config
![notepad++_27NxJVwWrs](https://user-images.githubusercontent.com/38784343/174650263-69e9cdea-13fd-4ced-afda-d6b9ab92e42d.gif)

"Old" editor writes same/old data to config
![notepad++_mEBJLhS4P1](https://user-images.githubusercontent.com/38784343/174650395-a9b77106-90fd-4fd2-8a7a-1c6718968c08.gif)

Edit using "Old" editor, text in the notepad is the config value found in the save POST request
![notepad++_9IChP4BMOr](https://user-images.githubusercontent.com/38784343/174650535-21250e3c-6c32-46c2-8527-3a95fdbf9e24.png)

Config value passed to the POST request when edited with interactive editor
 ![notepad++_kVjPDpQBbj](https://user-images.githubusercontent.com/38784343/174650641-07fe00e6-1ca8-44fa-8922-50be8071c034.png)

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Glitch3dPenguin** [comment]
I am also having this same issue.

**Comment by Lissy93** [comment]
I am working on a complete re-work of how config is managed to make things faster, and that should also fix this issue.

I think duplicate of #603, but this ticket is much clearer with lots of really good info, so keeping open.

**Comment by chevdor** [comment]
See https://github.com/Lissy93/dashy/discussions/799

**Comment by UrekD** [comment]
See #799

**Comment by UrekD** [comment]
I'll go ahead and close this one you already got it planned in #799, to prevent having to reply it to every 6 weeks and save you having to close it in the future anyway. Thanks for the hard work :)
