### ISSUE TITLE
[BUG] Weather Icons mismatch

### ISSUE THREAD

**Issue by gbrown09** [Lissy93/dashy#747]
### Environment

Self-Hosted (Docker)

### Version

2.1.0

### Describe the problem

Not sure if it's just me cause I'm not seeing any other issues related to this but the icons for the weather widget seem to be off. For example right now I'm seeing this 
![image](https://user-images.githubusercontent.com/3360055/174889950-115ad81c-4d45-4d4d-bf05-b380d2d019cb.png)
When I inspect I see 02d 
![image](https://user-images.githubusercontent.com/3360055/174890167-8d2d8f91-4efd-477e-b752-ec012bdd364a.png)
But on the actual open weather api I see that 02d should be 
![image](https://user-images.githubusercontent.com/3360055/174890256-1967097f-b9a0-4d84-9052-379e45c89d9c.png)

I think there's something off in the weather-icons.scss maybe the contents are mismatched or something. I think maybe the day and night icons are flipped. I'd change it on my end but it will just end up getting overwritten on update

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
>  I'd change it on my end but it will just end up getting overwritten on update

If you know the solution, please do submit a PR! :)

When I get a mo, I'll take a look also...

**Comment by gbrown09** [comment]
Yea this is still relevant

**Comment by cambrian07** [comment]
I have the same problem.
