### ISSUE TITLE
[QUESTION] App Logo and local icons

### ISSUE THREAD

**Issue by markusdd** [Lissy93/dashy#748]
### Question

I do not seem to understand how it works but I just do not manage to choose a local App Logo and same goes for icons.

What is the correct Syntax in the config GUI and how must the path be provided?

I was not able to get a single local icon or the app logo to work if it is not a URL.
The fontawesome icons etc all work great.

So from the docker mount there exists a standard path 'item-icons', below that I would like to place some custom pngs, but no matter how I specify this, I cannot get them to be selected.

Please help.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
I don't think the app icon works the same as item icons. That could probably be updated in the future, but currently it's just a path to an image. Any url should work, or anything in `/public` is accessed at  `/`.

**Comment by markusdd** [comment]
Ok, for the app logo I understand. 
The local icons still give me issues though.
Consider this structure.
![image](https://user-images.githubusercontent.com/25175069/175055067-9c8442ba-0a6b-4e15-b0d6-3a67d1c3a452.png)

Public folder is mounted like so in compose.yml:
![image](https://user-images.githubusercontent.com/25175069/175055360-7870494e-c3c2-480b-a1ce-d7cb14e88a54.png)


The item-icons folder was automatically created by dashy, so I put all my stuff in there.

What is the exact syntax I have to use to get this to load the icons?

**Comment by markusdd** [comment]
hahahaha now it works.

I'm sorry, one can never write docs in a way that the last idiot understands them xD
I never thought this was referring to the YML key, which makes total sense.

The icon displays fine now.

For the fontawesome stuff: Why is it required to use v5? E.g. the letter-icons are missing in this, is there an update planned or any other issues with the newer API?

**Comment by Lissy93** [comment]
Ha ha, well I'm glad you've got it working now :)

**Comment by Lissy93** [comment]
> Why is it required to use v5?

Mostly because V6 has only recently come out, and I've not yet updated to it. But also, in V6 icons are specified in a different way, so updating without thinking about it would break the icons for anyone whose using Font-Awesome.
