### ISSUE TITLE
[QUESTION] Dashy recompiling in Docker container normal?

### ISSUE THREAD

**Issue by TeslaCLT** [Lissy93/dashy#765]
### Question

I just installed Dashy yesterday and have been trying to get my feet wet setting it up. It is up and running, with the expected wait when I brought it up the first time to build the image. However, I am noticing that every time I make a change to the dashboard, whether directly in the config yaml file or via the UI, it recompiles after **every since change**. Add a section header, recompile. Add an item in the section, recompile. Of course, this pegs my CPU at 100% and uses most of my available ram during the recompile. Is this the expected behavior? I see videos on YouTube of people dynamically making changes and I can't imagine how they are doing that if after every button press, you need to wait 5 minutes for a recompile.

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
That should only happen when you **Save Changes**, after you've finished making changes.
It happens, because a pre-compiled dashboard is faster to load.
But a full re-work of the config handling process and data store is underway, which will mean you don't have to rebuild the app.

**Comment by TeslaCLT** [comment]
Sounds great. Even the option to rebuild later would have been great, but avoiding altogether makes that mute. This also won’t be as disruptive once I get things past the initial setup. Thank you!
