### ISSUE TITLE
[QUESTION] Home page displays widget differently than Section page

### ISSUE THREAD

**Issue by Wheels35** [Lissy93/dashy#769]
### Question

So when trying to get a layout on the home page for widgets, I get this on the home page:
![DashyHomePage](https://user-images.githubusercontent.com/26862029/176017389-0b928c25-2440-487d-8e8c-659620f561a3.png)

But when I go into the section page I get the following display:
![DashySectionPage](https://user-images.githubusercontent.com/26862029/176017387-30645fb1-4eb2-4e2c-837e-6692ff549b45.png)

Am I missing something or is there a way to make the home page the same as the section display?

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Wheels35** [comment]
I appreciate the response. It's close but not exactly the same.

This is what it looks like now setting it to flex.
![DashyHomePage-2](https://user-images.githubusercontent.com/26862029/176909017-5bae9574-836d-4c0d-8607-d0fab8e016f2.png)

It seems that on the section page they get evenly spaced whereas on the homepage it does the initial image, or the new one posted above with flex. I do note that the section page is forced to "Horizontal" Layout so it evenly spaces, since it sets the class to 'widget-list wide' vs just 'widget-list' on the auto. It would be nice to be able to set that layout on a per section, that way I can do things like this.

Now admittedly I havent looked into the CSS at all to see if I can force it anyway, I was asking to see if there might be some other way to do it already created.

**Comment by Lissy93** [comment]
Try also adding `justify-content: space-between;`

There's also `justify-content: space-around` if you'd like space on either side. And if you'd like things horizontally centred, then that'd be `align-items: center;`. If you're familiar with the dev tools, you can also play around with any other layouts and styles you might want, then set them under `appConfig.customCss` also.

I will make some improvements to the layout of sections + items, and make it easier to edit without CSS. Am working on better config loading next, but after that will address the layout stuff.

**Comment by Wheels35** [comment]
That definitely solves it for now, before I go breaking down and creating a custom theme. 
One thing to note, since it is all anchored to that left most widget, the time in my case, it slides to the left when the time changes and the width is smaller.

Ive gone to calling the widget name and manually applying a width to them. Ultimately, Id love to be able to add custom classes to pretty much everything, that way I can do completely custom layouts, or even use bootstrap or similar.

One thing I noticed for instance is _clock_ is within _widget-base_ and then I cant use say percentages if i wanted the clock to be 33% always, it will be 33% of the widget base. I understand why this was done, and I know there's a ton being worked on for dashy, so don't take this at all as complaining, because I believe its the best launcher/home dashboard available.

Unrelated, ( and i can make this a separate suggestion) I would also love to have visible names for widgets, which I cant seem to do. For instance having two cpu widgets, but being able to put XYZ CPU and ABC CPU above them

**Comment by Lissy93** [comment]
>  I would also love to have visible names for widgets, which I cant seem to do. For instance having two cpu widgets, but being able to put XYZ CPU and ABC CPU above them

Okay, I've added functionality for applying custom labels on widgets in #779.
Just add a `label` property to any widget, [see docs](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#adding-labels) for more info.

> One thing to note, since it is all anchored to that left most widget, the time in my case, it slides to the left when the time changes and the width is smaller.

And also added a class name to each section, that derives from the section's name so you can target a sec independantly of it's order, that's also in #779.
The class name is just `section_` followed by the sec name, to lower case, with spaces replaced with dashes (so `section_${title.replaceAll(' ', '-').toLowerCase()}`). But you can see that in the dev tools if your unsure.

Maybe in the future I can make this more flexible, so you can apply your own custom classes to any element. Though that would be a long while in the future, as I have a pretty long todo list atm.

> One thing I noticed for instance is clock is within widget-base and then I cant use say percentages if i wanted the clock to be 33% always, it will be 33% of the widget base.

I don't know what this means 🥴
Maybe you mean that it's using flex layout, and space is filled relativity, but you can overide this with `flex: 1`, or set a `min-width` to whatever. Or even use a different layout like relative, or grid layout, but I guess that over-complicates things a bit....

**Comment by Wheels35** [comment]
Wow. Definitely didn't expect the unrelated suggestion get merged into this already, especially with how unimportant it currently is. I had a sort of working solution that worked for me.
Maybe in the future you can visit the class name based on the label name or some regex of it. like _widgetobject.(label)_, and then you can have a _labelDisplay=true_ to acutally show the label and have it hidden by default. Again, it works wonders as it is now, just thinking of ways it could be customized in thelong term. 

Again, greatly appreciate it!!
