### ISSUE TITLE
[BUG] Theme is not correctly saved and reset at each page refresh

### ISSUE THREAD

**Issue by Antiz96** [Lissy93/dashy#774]
### Environment

Self-Hosted (Docker)

### Version

2.1.0

### Describe the problem

Hi,

## Context

I'm using dashy in a docker container on a raspberry Pi 4 (using the latest image).  

Run command : 
```
sudo docker run -d -p 8080:80 -v /opt/dashy/conf.yml:/app/public/conf.yml --name dashy --restart=always lissy93/dashy:latest
```

My conf.yml file is visible [here](https://github.com/Antiz96/Linux-Configuration/blob/main/Rasp-Server/conf.yml)  

## The issue

Since a few days, I have an issue that (*I think*) is happening since the latest update to the docker image (V2.1.0).
*More on that in the additional info field.*

### What is not working

As you can see, I've set the "Adventure" theme is my conf.yml file (line 11). However, when I launch dashy through my web browser, it shows the default theme (even tho the theme is indeed automatically set to "Adventure" by my configuration file):

![Bug_Dashy_1](https://user-images.githubusercontent.com/53110319/176556046-1ecc263b-7f2b-4fa2-ba34-3d61132ea487.png)

Re-selecting the "Adventure" theme manually from the "theme" drop down list makes it appears correctly.
However, refreshing/reloading the page makes Dashy fall back down to the default theme (while still having the "Adventure" theme selected, just like on the above screenshot).

**-!-** It worth mentioning that I initially had this issue with the "Adventure" theme as this is the one I'm using, but I've tried to set other ones in my config file for testing purposes and I had the exact same behavior. According to that, I guess that this issue goes with all themes, not specifically the "Adventure" one. I'll continue to use the "Adventure" theme as an example anyway but it could have been another one **-!-**

### Step to reproduce

Set the "Adventure" theme in the conf.yml file with the following snippet:
```
appConfig:
  theme: Adventure
```
Run the Dashy's latest docker image and mount the configuration file as "/app/public/conf.yml":
```
sudo docker run -d -p 8080:80 -v /opt/dashy/conf.yml:/app/public/conf.yml --name dashy --restart=always lissy93/dashy:latest
```
Check the Dashy's web page.
The "Adventure" theme is indeed selected but the default theme is shown instead. Re-selecting it manually from the drop down menu makes it appears correctly but refreshing/reloading the page makes it fall back to the default theme, even tho "Adventure" is still selected (at least in my case :smile:).

### Expected result

Having the "Adventure" theme correctly shown when launching and reloading/refreshing Dashy's web page without having to manually re-select it.

## Thank you

Thanks a lot for your awesome work ! Dashy's amazing :smile: 

### Additional info

- I said *I think* this issue is happening since the latest docker image (V2.1.0) because I think there's 2 separate parts of this issue:
Indeed, I'm quite sure that I had the bug showing the default theme instead of the one I chose in my config file (even tho it is selected in the drop down menu) **before** the release of the latest docker image (V2.1.0).
However, at that time, I had to re-select my theme manually only one time after a docker run command (so either after the initial launch of Dashy or after an update). I didn't have to redo that until the next docker run command (meaning until the next update).
Having to re-select my theme manually each time the page is refreshed/reload is however an issue introduced since the latest docker image (V2.1.0) for me.

- As I said earlier, I could reproduce this behavior using other themes than "Adventure" in my config file. So it is not related to that particular theme I guess.

- As I said earlier as well, thanks a lot for your awesome work ! :smile:

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hi @Antiz96 
Sorry about that, I can confirm this is a bug, it seems to be caused by #752

Thanks for the detailed report, that's really helpful. 
I'll work on it this afternoon, and update you when fixed :)

/link-dup  #773

**Comment by maks2199** [comment]
Hi! I am using Dashy version 3.0.1, when I switch to minimal or workspace view form default, my chosene theme stays. But, after page refresh theme switches back to default one. This happens only in minimal and workspace view. Thanks in advance!

**Comment by CrazyWolf13** [comment]
Hi @maks2199 

Please look through the open issues first:

Here the related ticket:
https://github.com/Lissy93/dashy/issues/1604
