### ISSUE TITLE
[BUG] "Fatal error in , line 0 unreachable code"

### ISSUE THREAD

**Issue by ZuriPL** [Lissy93/dashy#776]
### Environment

Self-Hosted (Docker)

### Version

N/A

### Describe the problem

Tried installing dashy on a rpi4 using the command in repo's readme, and all I get is this error

```
pi@raspberrypi:~ $ sudo docker run -p 8080:80 lissy93/dashy
Unable to find image 'lissy93/dashy:latest' locally
latest: Pulling from lissy93/dashy
5480d2ca1740: Pull complete
00d662877661: Pull complete
c234d4aeb7df: Pull complete
9a2fd5970489: Pull complete
35900400aefa: Pull complete
45e6ab437750: Pull complete
b40b133afa30: Pull complete
0c813f8feabf: Pull complete
Digest: sha256:a9e8a5a4429cb8be2b963d059736bafbe42bae3a657298f186b761102db1feaa
Status: Downloaded newer image for lissy93/dashy:latest


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe8595ec

```

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Kuchtek** [comment]
Have same issue with latest version with docker image
