### ISSUE TITLE
[SHOWCASE] Dipan's Dash

### ISSUE THREAD

**Issue by dipanghosh** [Lissy93/dashy#777]
<h3 dir="auto">Title</h3>
<p dir="auto">Dipan's Dashboard</p>
<h3 dir="auto">Screenshot</h3>
<p dir="auto"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/5004441/176696796-522e0233-1956-4aa4-b27f-8a376a369870.png"><img src="https://user-images.githubusercontent.com/5004441/176696796-522e0233-1956-4aa4-b27f-8a376a369870.png" alt="screencapture-dash-dipan-de-2022-06-30-16_00_21" style="max-width: 100%;"></a></p>
<h3 dir="auto">Would you like your name/ username included?</h3>
<p dir="auto">Yes</p>
<h3 dir="auto">Link to your Website/ Profile/ Twitter (optional)</h3>
<p dir="auto"><a href="https://dipan.de" rel="nofollow">https://dipan.de</a></p>
<h3 dir="auto">Description (Optional)</h3>
<p dir="auto">With the option of embedding iframes, it becomes possible to combine and conquer. I have set up Dashy to include graphs from grafana, and set them so that they update automatically. I also have uptime monitors from uptime Kuma, panels from homeasistant are also possible to be included.</p>
<p dir="auto">Dashy is awesome!</p>

<blockquote>                                <div>          <strong>                          <a href="https://www.thedesignerd.in/">Web | Dipan Ghosh</a>                      </strong>        </div>                    <div>Personal Website of Dipan Ghosh. Enjoy nature and travel photography especially flower.</div>                      </blockquote>

**Comment by Lissy93** [comment]
That's a work of a work of art, it's beautiful! 
Thanks for sharing :) It will be [added](https://github.com/Lissy93/dashy/blob/REFACTOR/widget-and-docs-improvments/docs/showcase.md) in the next PR (#775).

P.s Lovely photos on your website, you're very talented!

**Comment by dipanghosh** [comment]
Thank you :)

Awesome work on this project.

**Comment by rankokrneta** [comment]
Hi, @dipanghosh 

Will you share config.yml for this state of the art?

**Comment by dipanghosh** [comment]
Hey @rankokrneta ,

Yes, but you should know that this dashboard heavily relies on a tech stack involving InfluxDB and Grafana. The graphs are merely being imported from Grafana.

If you are have grafana set up already, and are interested how to integrate that into Dashy, then I can help.

**Comment by rankokrneta** [comment]
@dipanghosh 
no, still didn't set up, but planning Prometheus(InfluxDB) and Grafana to be my primary monitoring (as I already use this on my work).
Generally, the layout and colors are great, everything on this dash is beautiful!

**Comment by lolgufdHD** [comment]
Hey @dipanghosh,

I love your Dashboard and I'm Currently trying to recreate it. How did you do the Uptime-Kuma widget?

**Comment by dipanghosh** [comment]
@rankokrneta Thanks!! Without the awesome work by @Lissy93, and a whole bunch of other awesome opensource projects have allowed me to create this. Thanks goes to them. If you need any particular help setting it up, just ping me here.

@lolgufdHD Pretty much all the graph widgets on here are using Grafana using iframe, and the uptime kuma widget is also using iframe. Here is the relevant configuration. Let me know if this helps. 

```yaml
  - name: Uptime-Kuma
    widgets:
      - type: iframe
        useProxy: true
        options:
          url: https://<url_to_uptimekuma>
          frameHeight: 500
        id: 0_1071_iframe
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
```

**Comment by lolgufdHD** [comment]
@dipanghosh 
for some reason the iframes are not allowed by my domain which points to uptime kuma as well as Grafana. Do you know whats up with that? In Edge however it does show the widgets but in the window it says that the connection was denied. 

For more Context, a Cloudflare tunnel is pointing to the Grafana and Uptime Kuma app in Truenas. I tried googling said issue, but can't seem to find anything helpful.

**Comment by dipanghosh** [comment]
Oh yes. By default these services does not allow embedding. This is true for Grafana and also for Uptime Kuma. You need to change a setting for that. 

For Grafana, you need to set 

```yaml
 GF_SECURITY_ALLOW_EMBEDDING: true
```
If you are running it as a docker container, just set this pass this as an environment variable. Otherwise, I believe you can edit grafana.ini to achieve the same thing.

and the same applies for Uptime Kuma as well. The relevant setting there is

```yaml
 UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 1
```

Does this make sense to you?

**Comment by lolgufdHD** [comment]
@dipanghosh 
finally got the Grafana embedding to work, how exactly did you set up Grafana? Did you use the panel sharing and then the embed function, or how did you do it?

**Comment by dipanghosh** [comment]
Let me show you the tricks of the trade. It requires quite a bit of trial and error to set up grafana just right. This is actually the secret ingredient 😁

There are two important things what needs to be done in order show grafana graphs in an iframe.

First: You need to tell grafana, that it is okay to be embed into other websites which you have already done.

Second: You need to figure out the URL parameters to set for the embedding to look nice. I will paste the dashy config I am using below, just change the initial part to point it to your server. For the CPU usage, I am using:

```yaml
- name: CPU Usage
widgets:
  - type: iframe
    useProxy: true
    options:
    url: >-
    https://[your_grafana_server]/d/[ID_of_the_dashboard]/new-dashboard?orgId=1&viewPanel=4&kiosk&refresh=5s
    frameHeight: 500
    id: 0_765_iframe
```

Notice the URL. Notice the paramaters passes after the question mark. Those are important. Now, go to grafana and pick a graph. Select share from the dropdown menu.

![2022-09-26_13-18](https://user-images.githubusercontent.com/5004441/237060529-a7e79e3f-1d87-4df5-83d6-dbb4709b746c.png)

Then, copy the URL from there, but replace everything after the question mark like above. This should result in an embedded grafana graph that autoupdates every 5 seconds.

Let me know how this goes.

**Comment by lolgufdHD** [comment]
@dipanghosh 
Thanks for your help in advance, 
but it doesn't work for some reason. Here is my Code:

`  - name: CPU Usage
    widgets:
      - type: iframe
        useProxy: true
        options:
          url: https://my-domain.com/d/rYdddlPWk/truenas-scale?orgId=1&viewPanel=77&kiosk&refresh=5s
          frameHeight: 500

`
I double-checked, but embedding is definitely enabled.
![grafik](https://github.com/Lissy93/dashy/assets/107443931/5d952b2c-5f2d-4cfa-bbbf-9fc48fd8624c)

**Comment by dipanghosh** [comment]
First ensure you are able to visit the URL you are embedding, and that it works correctly. 
If this is working, then check if you are able to embed grafana. Try some other service that allow embedding a webpage (HomeAssistant for instance) or make a simple webpage yourself.

If both of those pass, then you should have no issues.

BTW, have you restarted the grafana service after changing the settings?

**Comment by lolgufdHD** [comment]
Okay, I will try that.

Yes, I did restart Grafana, but I suspect that maybe Cloudflare is blocking the embed.

**Comment by lolgufdHD** [comment]
@dipanghosh 
Okay my uptime Kuma looks diffrent from yours:
![grafik](https://github.com/Lissy93/dashy/assets/107443931/04893ae5-c9ff-4218-a0c8-fbf854f24ac2)

How can I make it look like yours? Did you use the statuspage as an embed?

**Comment by dipanghosh** [comment]
Nope, doing that will create this issue. I created a separate status page, and then used that page to embed. 

![image](https://github.com/Lissy93/dashy/assets/5004441/cd08a5a4-bc71-48e8-aae6-c5560066f80c)

**Comment by lolgufdHD** [comment]
@dipanghosh 
How did you get rid of the "All Systems Operational" box?
When I try to hide the class with CSS, it also hides the monitors.

**Comment by dipanghosh** [comment]
Elementary, dear Watson.

```css
.overall-status {
  display: none;
}
```

Gotta target the right class, not the class that is applied to all the monitor elements as well.

**Comment by lolgufdHD** [comment]
@dipanghosh 

Ahhh thank you

**Comment by fbellati** [comment]
Dear @dipanghosh, 
i'm working to reproduce your beautiful work, but how to:
- hide the "modify status page" and "go to dashboard" buttons?
- hide the title of the Page?
Thnks

**Comment by lolgufdHD** [comment]
![grafik](https://github.com/Lissy93/dashy/assets/107443931/6945879e-4184-4d7b-9f01-35034136071d)

Thats how I did it.

**Comment by dipanghosh** [comment]
Hey @fbellati 

Yes, use CSS. the following CSS hides the title (and logo if you have it).

```css
.mb-4.title-flex{
display: none;
}
```

The two buttons... well you _can_ hide them with css, but that may cause you problems as you will not able to modify the status page anymore (because the buttons will be gone.) You can unhide them by using the DevTools, but depends if you are comfortable with that. 

The alternative here is to log out of Uptime Kuma once you are done with editing and you like the statuspage. Remeber status pages are public, and if you are not logged in, those buttons will no longer show up. 

I hope that helps you out.

**Comment by fbellati** [comment]
Really fast answer! I appreciate the help! @lolgufdHD and @dipanghosh.
- ok with buttons and, ok with logout. It's working.

**Comment by lolgufdHD** [comment]
@fbellati 

Glad to Help :)

**Comment by dipanghosh** [comment]
No worries. I am glad people have such an interest in the Dashboard.

**Comment by vooodooo** [comment]
> Hey @rankokrneta ,
> 
> Yes, but you should know that this dashboard heavily relies on a tech stack involving InfluxDB and Grafana. The graphs are merely being imported from Grafana.
> 
> If you are have grafana set up already, and are interested how to integrate that into Dashy, then I can help.

Awesome theme for dashy <3, Can you share your Config & Style? I already have grafana and Influxdb working. :-)
