### ISSUE TITLE
[QUESTION] How to configure gl-current-cpu widget

### ISSUE THREAD

**Issue by dokho33** [Lissy93/dashy#787]
### Question

Hi !
First sorry for my english, I'm French :)

I'm beginning with dashy and installed it with docker. 
I'm trying to use gl-current-cpu widget but i get an error: "enable to fetch data".
In firefox console i have this: 
`Uncaught (in promise) 
Object { message: "Request failed with status code 404", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }
XHR GET http://192.168.0.240:9595/undefined/api/3/cpu
404 Not Found`

192.168.0.240:9595 is dashy url

Glances run in docker and i can access it by 192.168.0.240:61208

Someone can help me please ?

Regards,

### Category

Widgets

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya @dokho33
Please share the relevant parts of your config, a screenshot of the issue, and the full contents of your browser console. 

The reason you're getting the 404, is because the path includes `/undefined`, which probably means you've got an error in your config. But without more info, it's not possible to know why.
You may find the solution in [Troubleshooting → Widget Errors](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#widget-errors), or by following the examples in the [widget docs](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md).

**Comment by dokho33** [comment]
Hi @Lissy93 

The content of the browser console is:
`⚠️ Warning ⚠️ 
Unable to fetch data 

This is likely not an issue with Dashy, but rather your configuration. If you think it is a bug, please open a ticket on GitHub: https://git.io/JukXk CoolConsole.js:11:10
Stack Trace
AxiosError: Request failed with status code 404 CoolConsole.js:18:12
Uncaught (in promise) 
Object { message: "Request failed with status code 404", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }

XHRGEThttp://192.168.0.240:9595/undefined/api/3/cpu
[HTTP/1.1 404 Not Found 2ms]`


My config is:
`appConfig:
  theme: one-dark
  fontAwesomeKey: XXXXX
  layout: auto
  iconSize: large
  language: fr
pageInfo:
  title: Raph's dashboard
  description: in rock we trust
  navLinks: []
  footerText: test
sections:
  - name: Serveur 2 - Intel Pentium G620 @ 2.60GHz / 8 GiB
    icon: fa-solid fa-server
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: OpenMediaVault
        icon: https://fredddi43.fr/storage/icons/openmediavault.png
        url: http://192.168.0.240
        target: newtab
        id: 0_3504_openmediavault
      - title: Portainer
        icon: https://res.cloudinary.com/canonical/image/fetch/f_auto,q_auto,fl_sanitize,c_fill,w_200,h_200/https://api.charmhub.io/api/v1/media/download/charm_cMu7M9K6a65FsKZvrLZOZwyQradwbs7E_icon_5cef79c2d18f6746
        url: http://192.168.0.240:9000
        target: newtab
        id: 1_3504_portainer
      - title: Yacht
        icon: favicon
        url: http://192.168.0.240:8001
        target: newtab
        id: 2_3504_yacht
  - name: Audio
    icon: fa-solid fa-headphones
    items:
      - title: Airsonic
        description: Streaming audio
        icon: https://airsonic.github.io/favicon-200x200.png
        url: http://192.168.0.240:4040
        target: newtab
        id: 0_498_airsonic
      - title: LMS
        description: Logitech Media Server
        icon: favicon
        url: http://192.168.0.240:9002
        target: newtab
        id: 1_498_lms
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Vidéo
    icon: fa-solid fa-film
    items:
      - title: Jellyfin
        description: Streaming vidéo
        icon: https://framalibre.org/sites/default/files/leslogos/jellyfin_logo.png
        url: http://192.168.0.240:8096
        target: newtab
        id: 0_635_jellyfin
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
- name: cpu
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    widgets:
      - type: gl-current-cpu
        hostname: http://192.168.0.240:61208
        id: 0_328_glcurrentcpu
`

And this is the screenshot of the issue:
![Capture d’écran_2022-07-09_00-37-51](https://user-images.githubusercontent.com/26525217/178078717-e7e1e0bc-9378-4c8b-bd12-3b347b56bd35.png)


Thank you.

**Comment by Lissy93** [comment]
You need to put hostname under options

**Comment by dokho33** [comment]
Pfff i'm dumb ...

It's work :)

Thank you!
