### ISSUE TITLE
[BUG] 401 Error with openweathermap as API version change

### ISSUE THREAD

**Issue by alucarddelta** [Lissy93/dashy#789]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto">Unraid version 6.10.3, Docker version 20.10.14, Firefox 102.0.1</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.1</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">Hey.</p>
<p dir="auto">Setting up the Weather Widget with a new openweathermap user is returning a 401 (unauth) error code being returned form openweathermap .</p>
<p dir="auto">It appears that new accounts from openweathermap have changed the default API version adm the API key that gets generated is the 3.0 type. As per <a href="https://openweathermap.org/api" rel="nofollow">https://openweathermap.org/api</a></p>
<p dir="auto">This means all new openweathermap accounts created will not get the 2.5 API version creds which Dashy appears to be using according to the Sentry output.</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto">Config</p>
<div class="snippet-clipboard-content notranslate position-relative overflow-auto" data-snippet-clipboard-copy-content="      - type: weather
        options: null
        apiKey: XXXXXXX
        city: Brisbane, AU
        units: metric
        hideDetails: false
        id: 1_759_weather"><pre class="notranslate"><code>      - type: weather
        options: null
        apiKey: XXXXXXX
        city: Brisbane, AU
        units: metric
        hideDetails: false
        id: 1_759_weather
</code></pre></div>
<p dir="auto"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/20882097/178093240-8e2c98e7-e3f2-4538-9012-c30a600f0ab6.png"><img src="https://user-images.githubusercontent.com/20882097/178093240-8e2c98e7-e3f2-4538-9012-c30a600f0ab6.png" alt="image" style="max-width: 100%;"></a></p>
<p dir="auto"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/20882097/178093127-3e00d7ce-ae9f-452d-b441-7f586e2d7f58.png"><img src="https://user-images.githubusercontent.com/20882097/178093127-3e00d7ce-ae9f-452d-b441-7f586e2d7f58.png" alt="image" style="max-width: 100%;"></a></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                                <div>          <strong>                          <a href="https://openweathermap.org/api">Weather API - OpenWeatherMap</a>                      </strong>        </div>                    <div>Simple and fast and free weather API from OpenWeatherMap you have access to current weather data, hourly, 5- and 16-day forecasts. Historical weather data for 40 years back for any coordinate. Weather maps, UV Index, air pollution
 and historical data</div>                      </blockquote>

**Comment by alucarddelta** [comment]
O forgot to add the raw output from the API

`{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}`

Also I blanked out the API key in the request... I didn't use "XXXXXXX" :)

**Comment by Lissy93** [comment]
Hiya @alucarddelta 
The API version refers to the schema, and won't have an effect on any credentials. 

Looking at that error message, I see that it includes undefined instead of your actual details.
That's because of an error in your config -  you've set options to null. Instead options should include all the options including your API key and location.

**Comment by alucarddelta** [comment]
Gah, That's what happens when you over look thing and dig into another area that were completely wrong >.<.

Yah that worked out @Lissy93. I don't know where I copied the original weather config from but the `options: null ` is everywhere in my config. Weirdly, it appears that only the weather widget was the only one that had issues with it.

Cheers :)
