### ISSUE TITLE
[QUESTION] Confused about CORS error and configuration.

### ISSUE THREAD

**Issue by aileron565** [Lissy93/dashy#791]
### Question

I'm trying to run the Vulnerbility Widget and I am getting a CORS error. As I don't control the server side and it is already using the proxy, I am not quite sure where to go from here. It is also unclear in the documentation where I would put option 2 for setting the header.

I am using the docker version that is fresh (pulled 2 days ago).
Docker Ver: 20.10.17
Dashy Ver: 2.1.1

Also side note, I haven't been able to console into the container to try to diagnose it there, do you have any suggestions regarding that?

### Category

Configuration

### Please tick the boxes

- [x] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya @aileron565 

Can you share the relevant parts of your config, the output of your browser console, and a screenshot of the issue. Without more info, I wouldn't be able to know what the issue is.

**Comment by Lissy93** [comment]
It's most likely an error in your config...
Try using the following snippet:

```yaml
- name: Vulnerabilities
  widgets:
  - type: cve-vulnerabilities
    useProxy: true
```

I've just verified on a fresh instance, that it is working fine.
<img src="https://user-images.githubusercontent.com/1862727/178150833-df47b7fe-ce23-4aa8-9219-c741f91c51f9.png" width="300" />

**Comment by aileron565** [comment]
Yep, that fixed it. Does this mean it needs to have the useProxy option?
`CORS: 🟠 Proxied`

When reading the documentation, I interpreted it as it is already enabled by default.

**Comment by Lissy93** [comment]
Oh sorry, yeah that means you need to proxy it, if you're not already proxying dashy.
Maybe I should make that clearer...
Glad that's working :)

**Comment by Lissy93** [comment]
> Also side note, I haven't been able to console into the container to try to diagnose it there, do you have any suggestions regarding that?

For client-side issues, you only need to [open the browser console](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console).

But to access the container logs, it should be something like `docker logs [container-id]`.
There's a section in the maintenance docs on which goes into more detail about [accessing docker logs](https://github.com/Lissy93/dashy/blob/master/docs/management.md#logs-and-performance).

:)
