### ISSUE TITLE
[FEATURE_REQUEST] Bing image of the day

### ISSUE THREAD

**Issue by k-rol** [Lissy93/dashy#793]
<h3 dir="auto">Is your feature request related to a problem? If so, please describe.</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Describe the solution you'd like</h3>
<p dir="auto">A widget of the same style as "Astronomy picture of the day" but with Bing images.<br>
To extract the image we need to call:<br>
<code class="notranslate">https://www.bing.com/HPImageArchive.aspx?format=js&amp;idx=0&amp;n=1&amp;mkt=en-US</code><br>
Then cat urlbase + url from the JSON</p>
<p dir="auto">Details at <a href="https://stackoverflow.com/questions/10639914/is-there-a-way-to-get-bings-photo-of-the-day" rel="nofollow">https://stackoverflow.com/questions/10639914/is-there-a-way-to-get-bings-photo-of-the-day</a></p>
<h3 dir="auto">Priority</h3>
<p dir="auto">Low (Nice-to-have)</p>
<h3 dir="auto">Is this something you would be keen to implement</h3>
<p dir="auto">No</p>

<blockquote>                    <img src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v&#x3D;73d79a89bded" width="48" align="right" />                          <div>          <strong>                          <a href="https://stackoverflow.com/questions/10639914/is-there-a-way-to-get-bings-photo-of-the-day">Is there a way to get Bing&#x27;s photo of the day?</a>                      </strong>        </div>                    <div>Is there some way I could get the Bing background image programmatically?

Bing&#x27;s API doesn&#x27;t seem to provide such functionality, perhaps there&#x27;s another way?</div>                      </blockquote>

**Comment by Lissy93** [comment]
Hiya @k-rol 

I'm not sure if there'd be enough interest in this for me to build a dedicated Bing image widget.

But you should be able to do this with the [Image Widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#image), all you'll need is a URL that serves up the raw image.
For reference this is the service I built to do that for APOD, it will likely be very similar: [github.com/lissy93/go-apod](https://github.com/lissy93/go-apod)

Looks like [this project](https://github.com/WangNingkai/BingImageApi) already does what you need, in the form of a GH action. So maybe something like this could work:

```yaml
widgets:
- type: image
  options:
    imagePath: https://cdn.jsdelivr.net/gh/WangNingkai/BingImageApi@latest/images/latest.png
```

Or, you might be able to use the [RSS Widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#rss-feed), with Bing's rss feed. Or build your own simple widget for the [Embeded widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#html-embedded-widget), or build a simple web page, and use it with the [iframe widget](https://github.com/Lissy93/dashy/blob/master/docs/widgets.md#iframe-widget). If none of those options work for you, you can build your own widget very similar to the [APOD widget](https://github.com/Lissy93/dashy/blob/master/src/components/Widgets/Apod.vue) use that.

**Comment by k-rol** [comment]
Hey @Lissy93!
You could have done a mic drop after this. 
I'm amazed that you gave me 5 good solutions.

The first one using the image widget worked straight out.
You also made me realize I didn't know GitHub actions, I've got some learning to do...

thank you very much!

**Comment by Lissy93** [comment]
Ha ha, well I'm glad one of them worked! :)
Oh yeah, GitHub actions is so cool, you can have a lot of fun automating all kinds of stuff!
