### ISSUE TITLE
[FEATURE_REQUEST]  support running dashy on bare nginx server

### ISSUE THREAD

**Issue by augugusto** [Lissy93/dashy#798]
### Is your feature request related to a problem? If so, please describe.

I'm running a raspberry pi with the "dietpi" distro. when I install anything on it, it installs and configures nginx on ports 80 and 443 and it's used for nextcloud, so i can't just run dashy's docker on that port. 

I'll describe the issues I have but this is not a bug report since I'm using an unsupported setup: 
i downloaded the code, built it, uploaded dist to /var/www and it works but editing the config with the ui doesn't save it, editing it with the file is not intuitive ( to me at least ), and i think it causes a bug that doesn't allow me to log in

### Describe the solution you'd like

an official guide on how to set it up on bare nginx server, or at least a mention so I can ask for help / open a ticket for the problems I'm facing

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Closing as no response from OP
