### ISSUE TITLE
[BUG] System slows down after installing the dashy

### ISSUE THREAD

**Issue by writingdeveloper** [Lissy93/dashy#804]
### Environment

Cloud Service (Static)

### System

Oracle Cloud Ubuntu 22.04 E2

### Version

dashy:latest

### Describe the problem

I tried to install it in many ways, but an error occurred during the installation, and I am experiencing a situation where the entire system is broken.

I install dashy with Docker portainer stack with this yml command 

I can access with my ip address but it shows me an error like this.

![2022-07-18 11 18 28](https://user-images.githubusercontent.com/6832586/179437235-6cffc6d6-b7f5-45e0-9358-806463047a42.png)

But real problem is after I saw this error. All system slows down and I cannot access any services. I tried to access with SSH but it shows really slow but it works so command to reboot the system and all system works fine.

After that I want to check the log in portainer and start dashy again, the problem starts again. It seems that it has problem with memory leak something.

![image](https://user-images.githubusercontent.com/6832586/179445694-ebc559af-7551-41c0-b78d-3bc31b42b8de.png)

And there is no error in the log. Here's the logs below.

```
Your new dashboard is now up and running with Docker
*******************************************************************************************


Using Dashy V-2.1.1. Update Check Complete
✅ Dashy is Up-to-Date


-  Building for production...
 WARN  A new version of sass-loader is available. Please upgrade for best experience.
yarn run v1.22.15
$ npm-run-all --parallel build-watch start
$ vue-cli-service build --watch --mode production
$ node server

Checking config file against schema...
✔️ Config file is valid, no issues found

SSL Not Enabled: Public key not present


 ██████╗  █████╗ ███████╗██╗  ██╗██╗   ██╗
 ██╔══██╗██╔══██╗██╔════╝██║  ██║╚██╗ ██╔╝
 ██║  ██║███████║███████╗███████║ ╚████╔╝
 ██║  ██║██╔══██║╚════██║██╔══██║  ╚██╔╝
 ██████╔╝██║  ██║███████║██║  ██║   ██║
 ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝   ╚═╝

*******************************************************************************************
Welcome to Dashy! 🚀
Your new dashboard is now up and running with Docker
*******************************************************************************************


Using Dashy V-2.1.1. Update Check Complete
✅ Dashy is Up-to-Date


```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Going to put this under #799

As duplicate ticket. Last time it was raised I was unable to open an oracle account to start debugging. So nothing else to do but mark the platform as unsupported :(

Although in this instance, I guess the issue is with the unofficial portainer stack.
