### ISSUE TITLE
[QUESTION] difference between admin and normal auth type

### ISSUE THREAD

**Issue by ar3thien** [Lissy93/dashy#805]
### Question

I tested both admin and normal auth types and couldn't see the difference. can you please help me understand the difference between those two types? are those meant to be two different roles?

### Category

Authentication

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
See: **[Docs → Authentication](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md)**
