### ISSUE TITLE
[BUG] Flight Data Widget Error

### ISSUE THREAD

**Issue by servebeer** [Lissy93/dashy#811]
### Environment

Self-Hosted (Docker)

### System

UnRaid 6.10.3

### Version

2.1.1

### Describe the problem

Just started looking at the Flight Data widget. I got an account with AeroDataBox and generated an api key. I verified that the api key works by doing a "Get Airport by code" "Test Endpoint" check on their site. I then configured the widget in Dashy, saved to disk, told it to refresh, and all I get is "Error finding and mounting specified widget". I looked through the troubleshooting section of the documents, and didn't see any mention of this error. Attached is the widget config with the api key redacted
![Screenshot 2022-07-22 084128](https://user-images.githubusercontent.com/8514341/180452171-14ec9e3e-0231-4365-bbea-14240a793ecb.png)
.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by servebeer** [comment]
Please disregard... I restarted the Docker image and it started working, go figure.

**Comment by Lissy93** [comment]
Closing, as nothing to do.
I guess that config not refreshed? If so, this should be fixed when the tasks in #799 are complete :)
