### ISSUE TITLE
[BUG] Multiple-Pages not working

### ISSUE THREAD

**Issue by TheLaskY** [Lissy93/dashy#814]
Hi there!

Actuall i'm building my Dashy environment.
I wanted to split dashy with multiple pages.

As i read the docs, section multiple pages,
the following code: 
`pages:
  - name: Proxmox
    path: './conf-proxmox.yml'`
 Is not working for me, i must add the yml file is in the public folder, as mentionned in the docs

When i build and restart Dashy, i see the proxmox button
![image](https://user-images.githubusercontent.com/38154657/180643423-45a19902-2f65-4189-a7f0-c474aa3a2f8e.png)
It just end up to https://mydashy.fr/home/Proxmox
Problem is i cant see the monitoring...

Thanks for all help and explaining!

**Comment by TheLaskY** [comment]
EDIT: After seeking others tickets, i've seen some things to do:

Hash mode is activated
Console actiavted gave me this output: 
![image](https://user-images.githubusercontent.com/38154657/180643801-2af2c421-83f7-4b12-82b6-35c9ce5a78f2.png)

**Comment by TheLaskY** [comment]
RESOLVED

tips: care to intends, they break everything 🤣 

PS: Dashy's a reeeeeal good tool

**Comment by Lissy93** [comment]
Glad you've got it working :)

The ticket I'm working on atm (#799) should (hopefully) make everything confit-related much easier
