### ISSUE TITLE
[FEATURE_REQUEST] Externally Hosted Config Files and API keys

### ISSUE THREAD

**Issue by mcbrown1010** [Lissy93/dashy#815]
### Is your feature request related to a problem? If so, please describe.

I currently host my conf files externally on my self hosted Gitea and would like to be able to add Widgets to my pages. The issue is that I don't want to have my API keys exposed in plane text.

### Describe the solution you'd like

I'm still pretty new to hosting services and coding so I'm not entirely sure how to implement this. possibly having a secrets file hosted on the web server itself and being able to refer to them in the externally hosted conf files

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Linking up to #799
