### ISSUE TITLE
uptime-kuma integration documentation

### ISSUE THREAD

**Issue by mybuntu-git2** [Lissy93/dashy#818]
### Is your feature request related to a problem? If so, please describe.

there were some notes that uptime-kuma does not have an API, but in practice it does

### Describe the solution you'd like

add to the documentation a section "working with uptime-kuma"  or point to this issue.

basically it is true that the simple uptime-kuma monitor does not work, but in uptime-kuma it is possible to create a status page for each monitor.
this status page can be passed to Dashy and is read correctly.

I think this is useful to report this.
also another possible path could be that a script is created to sync uptime-kuma status pages info into the conf.yml file. this is useful when we start to have quite a lot of services to handle in both.

### Priority

Low (Nice-to-have)

**Comment by Lissy93** [comment]
I don't think there is an integration.

Last time I checked, Uptime Kuma did not have an official API (Re: https://github.com/louislam/uptime-kuma/issues/118).
So the only way to integrate with it was hijaking of it's internal endpoints, which are not documented, subject to frequent change, and sometimes produce unexpected results.

That said, I would be happy to review a PR if you're up for building this.

**Comment by Lissy93** [comment]
Side note, please could you keep the templated title tag (e.g. `[BUG]`), it's used for triaging and organizing tasks.
