### ISSUE TITLE
[BUG] Unable to install docker image

### ISSUE THREAD

**Issue by servebeer** [Lissy93/dashy#822]
### Environment

Self-Hosted (Docker)

### System

Unraid 6.10.3, Edge Version 103.0.1264.49 (Official build) (64-bit)

### Version

latest

### Describe the problem

I had Dashy running fine initially. However, I made so many changes trying to get a "feel" for it, that I messed it up beyond repair. I decided to just delete the docker image and re-install to start over. Now, I can not install Dashy either using the UnRAID Community App or from the cli with the command line. Li have cleared my entire docker environment thinking I might have a conflict:

# Stop all containers
docker stop `docker ps -qa`

# Remove all containers
docker rm `docker ps -qa`

# Remove all images
docker rmi -f `docker images -qa `

# Remove all volumes
docker volume rm $(docker volume ls -qf)

# Remove all networks
docker network rm `docker network ls -q`

# Your installation should now be all fresh and clean.

# The following commands should not output any items:
docker ps -a
docker images -a 
docker volume ls

# The following command show only show the default networks:
docker network ls

But when trying to install via the cli I get this error:

docker run -d -p 8080:80 -v ~/my-conf.yml:/app/public/conf.yml --name Dashy --restart=always lissy93/dashy:latest
Unable to find image 'lissy93/dashy:latest' locally
latest: Pulling from lissy93/dashy
59bf1c3509f3: Pull complete 
b616ac4a64bf: Pull complete 
3b9e1e8ab9ce: Pull complete 
3507ddbf3909: Pull complete 
88ffe1153cc4: Pull complete 
7b23c8336106: Pull complete 
91ae094d5121: Pull complete 
3aa391065cb8: Pull complete 
Digest: sha256:bc59cc6029b52dc93afbf94c37deb867d54edd6cc8e19bb22eecf6e805b88942
Status: Downloaded newer image for lissy93/dashy:latest
ab2d9a73c95c546f24ed38b4e05534ac25f3e641941ea2d1707482810d6bbd9f
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/root/my-conf.yml" to rootfs at "/app/public/conf.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

If I wipe the docker environment again and try to install via the UnRAID Community App, I get this error:

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='dashy' --net='bridge' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e HOST_HOSTNAME="Unraid-1" -e HOST_CONTAINERNAME="dashy" -e 'UID'='99' -e 'GID'='100' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:80]/' -l net.unraid.docker.icon='https://raw.githubusercontent.com/A75G/docker-templates/master/templates/icons/dashy.png' -p '4000:80/tcp' -v '/mnt/user/appdata/dashy/conf.yml':'/app/public/conf.yml':'rw' -v '/mnt/user/appdata/dashy/icons/':'/app/public/item-icons/':'rw' 'lissy93/dashy:latest'
b394fd10478bbbd2321c1d5b5347eca6480729bd43a7feba15fb416a41fe0566
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/mnt/user/appdata/dashy/conf.yml" to rootfs at "/app/public/conf.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

The command failed.

Any help getting this resolved would be greatly appreciated.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Looking at that error message, it says you're trying to mount a directory, instead of a file for your config.
See: [**Troubleshooting → Docker Directory Error**](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#docker-directory)  for more info.

Side note, support for mounted directories will come when #799 is done.

**Comment by servebeer** [comment]
Thanks so much for that pointer! in case it isn't evident ;-) I am new to Docker. I was able to get Dashy installed and running again!

**Comment by Lissy93** [comment]
No problem, glad it's working again :)
