### ISSUE TITLE
[BUG] Error saving any config

### ISSUE THREAD

**Issue by xtraorange** [Lissy93/dashy#826]
### Environment

Self-Hosted (Bare Metal)

### System

Ubuntu Server 22.04 (minimized) / Google Chrome on Windows

### Version

2.1.1

### Describe the problem

When editing config from the main menu and clicking save changes, I get the following error:

> Task Failed
> 
> Unable to backup conf.yml: Error: ENOENT: no such file or directory, copyfile './public/conf.yml' -> './public/conf-1659230401.backup.yml'

Attempting to rebuild application exits with a 'Build operation failed' with a comment:
>Build process exited with 254: Possible Error

### Additional info

For reference, I'm running ubuntu in a VM on proxmox, though I doubt this is related.
I followed the instructions to install dashy via git, pulled in the dependancies via yarn, and ran a yarn build.  Once yarn start was working, I set it up to run on port 80 via pm2 (setting the environment var PORT to 80 and executing server.js) to run it at server boot.

Is server.js not a suitable production server?  Do I need to run it through nginx or something else?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Hiya @xtraorange 
Pls see #799
