### ISSUE TITLE
[BUG] 404 link in the documentation

### ISSUE THREAD

**Issue by ScarUY** [Lissy93/dashy#829]
### Environment

Self-Hosted (Docker)

### System

Debian 11

### Version

2.1.1

### Describe the problem

In "https://github.com/Lissy93/dashy/wiki/configuring#sectionicon-and-sectionitemicon" says: "See [Icon Docs](https://github.com/docs/icons.md) for all available supported icon types" but https://github.com/docs/icons.md returns 404.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
https://github.com/Lissy93/dashy/blob/master/docs/icons.md

**Comment by ScarUY** [comment]
> https://github.com/Lissy93/dashy/blob/master/docs/icons.md
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/343078060/82f850a2-b1af-4e9f-9245-c92700d74856">                                    **                          [dashy/icons.md at master · Lissy93/dashy](https://github.com/Lissy93/dashy)                      **                            🚀 A self-hostable personal dashboard built for you. Includes status-checking, widgets, themes, icon packs, a UI editor and tons more! - dashy/icons.md at master · Lissy93/dashy

Thank you! I had already found the right link, but I'm new to github and I didn't know how to help correcting the link for others, is there a better way? I don't want to bother people if I don't have to.
Thank you again.
