### ISSUE TITLE
[FEATURE_REQUEST] User accounts / single sign on

### ISSUE THREAD

**Issue by deffcolony** [Lissy93/dashy#833]
### Describe the solution you'd like

I would like to see a single sign on feature with security permissions. users can login and see their personal dashy dashboard with the apps they are allowed to see

![Amazing Idea]( https://docs.requarks.io/assets/diagrams/diag-permissions.jpg)

**- User registration**

By default, new users should not be authorized to access anything. They must either be pre-authorized by an administrator or be put into an existing group using the self-registration option.

The latter greatly simplifies the onboarding of new users. The self-registration option can be enabled on a per authentication strategy basis.

**- User Groups**

A user can be part of one or more groups. A group defines what users can see and what they can do.

**- User Roles like: Admin, Moderator, Read, Editor, Guest,**

Permission gives the right to a user to perform a very specific action. For example, the **Read** user role allows the user to view the dashboard, while the permission **Editor** allows the user to upload images and files. These global permissions act as a master switch to allow or deny a specific action on the wiki.

**- LDAP support to sign in with the Windows server active directory account**

LDAP / Active Directory is an enterprise authentication solution. Users can login with their active directory account and get access to dashy that way

**- Two-factor authentication (2FA)**

Two-Factor Authentication (2FA) adds an extra layer of protection to user accounts. It combines something you know (your password) with something you have / are (mobile phone, fingerprint, security key, etc.).

Even if a malicious user obtain your password, they will be unable to login because they don't have the second authentication factor.

**Here are couple of 2FA methods you could implement:**

### OTP (One-Time Passwords)
    TOTP (Authy, Google Authenticator, Microsoft Authenticator) 

### WebAuthn
    Windows Hello
    FIDO2 (Yubikey 5)
    FIDO U2F (Yubikey 4 and earlier, Google Titan Key)
    
**Login screen customization**
An alternate image background that can be set for the login screen. By entering the full path to an image (.jpg / .png / .gif).

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Would you be up for building this? I'm working on some other features and improvements at the moment.

Since this is possible to do already, via KC or using your own auth provider, I'm going to mark as low priority.
