### ISSUE TITLE
[BUG] Multiple context menus

### ISSUE THREAD

**Issue by deffcolony** [Lissy93/dashy#835]
### Environment

Self-Hosted (Docker)

### System

Firefox 103.0.1 (64-bit)

### Version

2.1.1

### Describe the problem

When i right click on different tabs i can open multiple context menus on each app tab (screenshot below) i thought maybe this was suppose to happen but when i click on EDIT the other context menus disappear...  

### Additional info

![bug]( https://i.imgur.com/RbivXnu.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Try left-clicking...?

**Comment by Lissy93** [comment]
But yeah, it is a bug. The closing of the context menu is handled with a custom directive, here: [`directives/ClickOutside.js`](https://github.com/Lissy93/dashy/blob/master/src/directives/ClickOutside.js).
Listening for right-clicks is harder, since users often accidentality right-click on the option they want while using a right-click menu.
