### ISSUE TITLE
[BUG] title ignored in subItems section

### ISSUE THREAD

**Issue by sgolovanov** [Lissy93/dashy#838]
### Environment

Self-Hosted (Docker)

### Version

2.1.2

### Describe the problem

The titles ignored in subItems:
`"items": [
        {
          "title": "VV",
          "target": "newtab",
          "subItems": [
            {
              "url": "https://rr.com/",
              "title": "Site",
              "icon": "1.png"
            },
            {
              "url": "https://drr.com/",
              "title": "Creds",
              "icon": "2.png"
            }
          ],
          "id": "0_448_vv"
        }
      ]
`
Only icons in the items:

<img width="317" alt="bug" src="https://user-images.githubusercontent.com/5835380/184074914-b36a934e-bb36-42c8-98b2-7903758733bc.png">

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Correct, you'll need to set an icon instead, as there's no room for individual titles.

**Comment by sgolovanov** [comment]
Oh, I found the info here - https://github.com/Lissy93/dashy/blob/master/docs/pages-and-sections.md. It will great to have titles here even with 5-6 letters.

**Comment by Lissy93** [comment]
If you hover over the item, then the title should display as a tooltip.

It probably wouldn't be too hard to add the option for textual titles.
Would you be up for implementing? Otherwise I can add it my the todo list.

**Comment by alek-w** [comment]
Vote for this!
@Lissy93 pls add it to your todo list

**Comment by alek-w** [comment]
@Lissy93 pls
