### ISSUE TITLE
[BUG] Dashy Resets to Fresh Install

### ISSUE THREAD

**Issue by BennyDaBee** [Lissy93/dashy#839]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 20.04.3

### Version

2.1.1

### Describe the problem

When I run Dashy using docker run -p 30000:80 lissy93/dashy, and I make changes, then if I have to restart the machine and run dashy with the same command again, It reverts to a clean install of Dashy and all changes are lost. No Errors that I can see in the Console when running. 

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by BennyDaBee** [comment]
Seems to be possibly being addressed in #799

**Comment by UrekD** [comment]
Sound like you are creating a new container each time, is that the exact command you run every machine restart? Use 'docker container ls' to check. If that's the case, try using the second example, which sets a proper name for the container and also mounts the config outside the container:
```
docker run -d \
  -p 4000:80 \
  -v /root/my-local-conf.yml:/app/public/conf.yml \
  --name my-dashboard \
  --restart=always \
  lissy93/dashy:latest
```

**Comment by Lissy93** [comment]
Yeah, both the above comments are correct.

Currently the app rebuilds for changes to take effect, it's not ideal and am working on getting rid of that in #799.

But that shouldn't mean you need to restart the container. Instead to rebuild the app, either exec `yarn build`, or through the UI go to Config → Rebuild. And it may take a minute or two if you're on a low-spec device like a Pi.
