### ISSUE TITLE
[BUG] Truncating of item description

### ISSUE THREAD

**Issue by polhaghverdian** [Lissy93/dashy#842]
### Environment

Self-Hosted (Docker)

### System

Firefox mobile and Firefox dektop

### Version

2.1.1

### Describe the problem

Hi @Lissy93 

Truncating of the item description doesn't work correctly. As you can see in the picture, the third line gets truncated with "..."; however, the text continues on the fourth line.

![dashy](https://user-images.githubusercontent.com/50968806/184424742-4d93324e-6a9c-416d-89d4-cf0f63a66187.png)
.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Ah yeah, that looks like a CSS issue

**Comment by polhaghverdian** [comment]
Yes, this is still relevant.

**Comment by polhaghverdian** [comment]
Yes, this is still relevant.

**Comment by polhaghverdian** [comment]
Yes, this is still relevant.

**Comment by Lissy93** [comment]
Hey,
Sorry for the late reply. I'm just looking into this, but am struggling to re-create the issue.

![image](https://github.com/Lissy93/dashy/assets/1862727/13c7bb03-f753-476b-9830-c21e6d35c274)


You're using Firefox, right? And was there any other relevant config stuff that you updated to see the ellipse?

**Comment by CrazyWolf13** [comment]
Can Reproduce:
![image](https://github.com/Lissy93/dashy/assets/96661824/f4ccef0a-1c08-4df7-82a4-a4479933cfd4)
on [https://live.dashy.to/](https://live.dashy.to/)

With these settings.
![image](https://github.com/Lissy93/dashy/assets/96661824/e4fcade1-42bf-48c7-a1ed-bbbb5c08953c)

**Comment by CrazyWolf13** [comment]
I think this can be closed, for me it's working now, thanks lissy!
