### ISSUE TITLE
🚚 Dashboard Icons has moved to another home!

### ISSUE THREAD

**Issue by walkxcode** [Lissy93/dashy#849]
<p dir="auto">Heya Lissy!</p>
<p dir="auto">walkxhub/dashboard-icons has moved to another home: <a href="https://github.com/walkxcode/Dashboard-Icons">https://github.com/walkxcode/Dashboard-Icons</a><br>
So for newly added icons the URLs will need to be changed in the code... No worries though, old icons will still work, so no rush!</p>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/525443495/f7dec1f5-3f74-47ae-9723-f9ae3f52cdbb" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/walkxcode/Dashboard-Icons">GitHub - walkxcode/Dashboard-Icons: ❤️ The best icons for your personal dashboard.</a>                      </strong>        </div>                    <div>❤️ The best icons for your personal dashboard. Contribute to walkxcode/Dashboard-Icons development by creating an account on GitHub.</div>                      </blockquote>

**Comment by Lissy93** [comment]
Again? 😆 

Thanks for letting me know :)
I'll get this updated this weekend. 

Unless anyone else would like to submit a PR, is an easy one, just update [this url](https://github.com/Lissy93/dashy/blob/master/src/utils/defaults.js#L215) in defaults.js

https://github.com/Lissy93/dashy/blob/ba1fd77509a20d055fcb1c939b67f39a69ce35d2/src/utils/defaults.js#L215


P.s. Thanks @walkxcode for maintaining that repo, it's now become the defacto home for self-hosted icons, so nice work!
