### ISSUE TITLE
[QUESTION] Keycloak valid redirect_url

### ISSUE THREAD

**Issue by vfricou** [Lissy93/dashy#852]
### Question

Hello,

I use Keycloak v19, and when I configure Client, I only set such as documented :
- Valid redirect url : https://dashy.domain.tld
- Web origins : https://dashy.domain.tld

But I take a keycloak error `Invalid parameter: redirect_uri`

I’ve try to set `Valid redirect url` to `https://dashy.domain.tld*` or `https://dashy.domain.tld/`, authentication correctly work, but it’s impossible to logout from dashy with error `Invalid parameter: redirect_url`

Which link is correct to setup Keycloak ? I’ve search into docs and issues and I’ve not found any answers.

Thanks for your product in any cases. 

### Category

Authentication

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Where's the error happening, KC side or Dashy side? Is this in the browser console?
The redirect URL of `https://dashy.domain.tld` should be correct. But maybe there's a bug on Dashy's side.I'll look into it when I get a moment.


In the meantim, not sure if it's any help, but have you seen [Troubleshooting --> Keycloak Redirect](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#keycloak-redirect-error)?
And some similar issues: #479, #409, #507, #491, #341, #520

**Comment by vfricou** [comment]
Thanks for reply,

I’ve try to setup CORS without success. 
I’ve read too all of similar issues, but any correction possible found in it.

**Comment by zell-mbc** [comment]
Hi @vfricou, I ran into the same issue at my end. Not a big deal for me but if you happen to find a solution I'd appreciate if you could update the thread here.

Thanks

**Comment by juliannoble** [comment]
Apparently redirect_uri has been deprecated in keycloak since version 18
This can be worked around on the keycloak side using:
bin/kc.[sh|bat] --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start

I tried this on keycloak 19.0.1 and it works

However - this switch is intended to be removed in some future keycloak version, so at some point a client fix will be needed.
see https://www.keycloak.org/2022/04/keycloak-1800-released

**Comment by zell-mbc** [comment]
That worked for me as well, thanks for sharing @juliannoble

**Comment by kutekroma** [comment]
After the authorization window, enter the login and password. Next, the infinite cycle begins. Where can I see detailed logs?
