### ISSUE TITLE
[BUG] 404 on Chrome, but not Firefox or Edge

### ISSUE THREAD

**Issue by MayhemBill** [Lissy93/dashy#854]
### Environment

Self-Hosted (Docker)

### System

Chrome 104.0.5112.102

### Version

Dashy V-2.1.1

### Describe the problem

When loading dashy I get this error in browser console:
`Refused to apply style from 'https://dash.myhm.space/css/chunk-vendors.d8067ad8.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`
which is then followed by a bunch of 404's for several other chunk-vendors file

this issue only occurs on Chrome, as I can load the site no problem on Firefox and Edged
attached are the logs from dashy
[_my-dashboard_logs.txt](https://github.com/Lissy93/dashy/files/9377496/_my-dashboard_logs.txt)
s

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Try clearing the cache

**Comment by MayhemBill** [comment]
I have tried clearing cache already, as well as rebuilding the container for Dashy

**Comment by MayhemBill** [comment]
after a few hours it just randomly started working again, so idk what happened.
