### ISSUE TITLE
[SHOWCASE_REQUEST] Shadowking001

### ISSUE THREAD

**Issue by shadowking001** [Lissy93/dashy#86]
### Complete the Following

- Shadowking's Dashy
- ![shadowking_dashboard](https://user-images.githubusercontent.com/43928955/125409835-99493280-e3bc-11eb-8932-a6269cee4ba2.png)
- **Would you like your name/ username included**: Yes
- **Homelab & VPS dashboard** (optional)

**Comment by Lissy93** [comment]
Nice dashboard - thanks for sharing it 😎
It's been added in 9c5ce6b3f8ca01c6225eda8e2ebaefee27ae527b of PR #91, which will be merged soon
