### ISSUE TITLE
[QUESTION] <How do i actually make a widget?>

### ISSUE THREAD

**Issue by AdmiralAtomic** [Lissy93/dashy#889]
### Question

Unsure if i am just being blind but i cant find anywhere to actually make a widget using the UI. It says there are some premade ones, but i cant seem to find how to put those onto the dashboard from within the UI editor. Am i missing something?

### Category

Configuration

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Dictynna-PHA** [comment]
I think [#796](https://github.com/Lissy93/dashy/discussions/796) is what your looking for, although as mentioned in the thread it's potentially easier to edit the yaml directly.
