### ISSUE TITLE
[QUESTION] - How do I edit the config inside the container ?  

### ISSUE THREAD

**Issue by johntdyer** [Lissy93/dashy#89]
I would love to mount a host folder so I can edit and persist my config however there doesnt seem to be a way to do this currently...  Am I missing something ?

**Comment by johntdyer** [comment]
meh, RTFM... closing :)

**Comment by Lissy93** [comment]
Glad you got it sorted :) 
I should maybe have made the docs a little clearer, I'm working on improving them.


I will leave this here, in case anyone else is looking for the same thing in the future:
In your Docker run command, you can use the [`-v`](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only) flag to mound a volume, either a file or directory. For example, to pass in a YAML config file from your host system, you can use:
```bash
docker run -d -p 8080:80  -v /root/my-local-conf.yml:/app/public/conf.yml lissy93/dashy:latest
```
For full options, see Dashy's [Deploying with Docker Docs](https://github.com/Lissy93/dashy/blob/master/docs/deployment.md#deploy-with-docker)

**Comment by dbzx6r** [comment]
How can this be done after? I could not get it working with that line due to an error, and a tutorial I found online said it can be removed and it will automatically create it. However, I'm trying to add widgets and unfortunately it can't be done via the UI
