### ISSUE TITLE
[BUG] Changes saved to local storage not loading properly

### ISSUE THREAD

**Issue by Lowizer** [Lissy93/dashy#893]
### Environment

Self-Hosted (Docker)

### System

Firefox 103.0.2, Vivaldi 5.4.2753.47, Docker 20.10.17

### Version

2.1.1

### Describe the problem

**The problem**

When creating a new section or item inside the interactive editor and saving to local storage, the section / item disappears after reloading.

**Steps to reproduce**

- Open Dashy v.2.1.1 inside any browser
- Activate the interactive editor
- Create a new item in any section
- Save the changes to local storage only
- Reload the page

**Actual Result**

`confSections` seems to be reset to the remote config.

**Expected Result**

Changes saved to local storage should already be loaded on page load.

### Additional info

- When inspecting the local storage inside the browser, `confSections` gets updated accordingly after saving the changes made inside the interactive editor.
- After reloading with the created sections / items missing, when activating the interactive editor again and clicking the `Cancel Edit`-Button, the items reappear.
- All `InfoHandler`-calls are properly output into the console (e.g. `New item added` or `Config has succesfully been saved in browser storage`)
- No warnings or errors are output into the console.
- The behaviour can also be reproduced in the [Demo3](https://dev.dashy.to), but not in the other two demos with Dashy v.1.9.2.
- I've taken a peek at the source, but couldn't find the problem. Both initially on page load, als well as clicking the `Cancel Edit`-Button seem to dispatch the action `INITIALIZE_CONFIG`, so my guess would be that there's something wrong with either the `Vuex.Store`, since the `ConfigAccumulator` also uses its config-states?
- The `appConfig` gets saved propely though. Changing the theme or layout survives reloading the page.
- Is there a probability, that this will also get fixed with #799 ?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by chevdor** [comment]
All the 👀  are turning toward #799, this is where those issues are being fixed.
