### ISSUE TITLE
[BUG] Dashboard does not start

### ISSUE THREAD

**Issue by AmadeusGraves** [Lissy93/dashy#898]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto">Docker version 20.10.18</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.1</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">I can't start the Dashy container of the latest version (2.1.1), it loads Dashy but at the end the dashboard doesn't appear, it hangs. I pass the log.</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto">today at 13:50:58-  Building for production...<br>
today at 13:50:58 WARN  A new version of sass-loader is available. Please upgrade for best experience.<br>
today at 13:51:03node:internal/errors:464<br>
today at 13:51:03    ErrorCaptureStackTrace(err);<br>
today at 13:51:03    ^<br>
today at 13:51:03<br>
today at 13:51:03Error: getaddrinfo EAI_AGAIN Dashy<br>
today at 13:51:03    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {<br>
today at 13:51:03  errno: -3001,<br>
today at 13:51:03  code: 'EAI_AGAIN',<br>
today at 13:51:03  syscall: 'getaddrinfo',<br>
today at 13:51:03  hostname: 'Dashy'<br>
today at 13:51:03}<br>
today at 13:51:03error Command failed with exit code 1.<br>
today at 13:51:03info Visit <a href="https://yarnpkg.com/en/docs/cli/run" rel="nofollow">https://yarnpkg.com/en/docs/cli/run</a> for documentation about this command.<br>
today at 13:51:03ERROR: "start" exited with 1.<br>
today at 13:51:03error Command failed with exit code 1.</p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445"><img src="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445" alt="important" data-canonical-src="https://img.shields.io/badge/Important!-F6094E" style="max-width: 100%;"></a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://classic.yarnpkg.com/assets/og_image.png" width="48" align="right" />                          <div>          <strong>                          <a href="https://classic.yarnpkg.com/en/docs/cli/run/">Yarn</a>                      </strong>        </div>                    <div>Fast, reliable, and secure dependency management.</div>                      </blockquote>

**Comment by sur1v** [comment]
Probably related with #877, please test with master branch Dockerfile to build the image

**Comment by AmadeusGraves** [comment]
Ok, I'll give it a try. Thanks

**Comment by alexdelprete** [comment]
> Probably related with #877, please test with master branch Dockerfile to build the image

My beautiful Dashy doesn't start anymore...but I'm not able to edit the dockerfile, just waiting for a new release of the container...I hope that will fix it.
