### ISSUE TITLE
[BUG] Config should have it own folder

### ISSUE THREAD

**Issue by chevdor** [Lissy93/dashy#902]
### Environment

Self-Hosted (Docker)

### System

n/a

### Version

master

### Describe the problem

Currently the config is a `conf.yml` file in `/app/public/.
That works fine for a single file config when using containers (docker, k8s, ..)

If however  you have a config in multiple files, you will need to mount the entire `/app/public` folder for your container to see all config files and this will shadow the rest of the files under `/app/public`.

Ideally the config folder should be configurable or set to a **subfolder** somewhere. That could be `/app/config` by default for instance. This would allow mapping `/app/config` while not affecting the content of `/app/public` (also the config should probably not be public).

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by getuslocal** [comment]
Im having an issue with this as well. I bind the local to the hosted path but it forces me to put config.yml in the actual path (which makes no sense).  I would expect to see /app/config/ and that is where the yml file is read from that way I can attach it to a volume etc.  When you do /app/public/config.yml it actually creates a folder called config.yml with no config file in it, and when I added one it still didn't read or recognize it.

**Comment by Lissy93** [comment]
Have already implemented this as part of #799 - but am just waiting until the rest of the ticket is completed before it will be merged (for version 2.1.2)
