### ISSUE TITLE
Authentik IDP Integration

### ISSUE THREAD

**Issue by hooray4me** [Lissy93/dashy#906]
### Question

I am trying to tie in my IDP for use with Dashy. The documentation was sparse on setting up other auth methods (OAuth2/OpenID/SAML) . Is there any other guidance on this? I am using Authentik and have many options for provider setups. Any help/insight would be appreciated.

### Category

Authentication

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by barrelltitor** [comment]
I'd also like to know if this is possible. I wanted to try switching over to Dashy, but without having any sort of control over who can see what it's not feasible

**Comment by Lissy93** [comment]
See: [Authentication](https://github.com/Lissy93/dashy/blob/master/docs/authentication.md)

You can either set this up via Keycloak, or you can use Dashy with any web server configured with your own auth provider, like you would with any other app.

As to weather it's officially supported, no - afraid not, as there are so many auth provider, that it's so far not been feasible to add native support for all of them. You would have to either configure it yourself, or use an [alternative dash](https://github.com/Lissy93/dashy/#alternatives-)

Hope that helps :)

**Comment by hooray4me** [comment]
What about oauth2/openID or SAML support? Any one of those would open up an option for almost all auth providers.

**Comment by Lissy93** [comment]
Yup, you can use both OpenID or SAML via Keycloak :)

**Comment by Lissy93** [comment]
Btw, ticket was only closed because it's a duplicate of #385 and #823 (I should have mentioned the reason, sorry)
