### ISSUE TITLE
[BUG] Very high CPU usage every time I make any change

### ISSUE THREAD

**Issue by erohtar** [Lissy93/dashy#908]
### Environment

Self-Hosted (Docker)

### System

Raspbian Bullseye

### Version

2.1.1

### Describe the problem

This is often how my CPU looks like with Dashy:
![image](https://user-images.githubusercontent.com/5120628/190662068-251b2cbf-43a7-4dd3-8b55-18acaa2c6dcf.png)

The temperature also shoots up about 8-10C. It remains so for around half a minute and then goes back down to expected levels:
![image](https://user-images.githubusercontent.com/5120628/190662666-a07a29b2-2224-42a0-a956-e9f563b1764b.png)

### Additional info

From my testing I've found it happens each time I commit any config change to disk.
Browser console doesn't tell me anything:
![image](https://user-images.githubusercontent.com/5120628/190663287-e5435d20-7307-4e95-a819-e45619a9efb4.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by erohtar** [comment]
Found one more issue - during that wait time when the CPU is showing high usage after me pressing 'Save changes to disk' button, if I refresh the Dashy page, the changes are NOT written to disk, even though Dashy showed the green changes saved notification immediately after I press the button.

**Comment by chevdor** [comment]
See #799

**Comment by erohtar** [comment]
> See #799

"Remove the need for a rebuild when config updated" this part?

**Comment by chevdor** [comment]
Yes, the problems are:
- when the container starts, it builds the whole thing. It takes a while and is very hungry on memory. We are talking >1GB which is humongous for such an app. During that time, Dashy tells you it is ready, but it is not and won't respond.
- when you change the config, it will trigger a rebuild (go to step above)

So the changes from #799 will really bring some fresh air to the issues you mention.

**Comment by erohtar** [comment]
That makes sense, but wow.. Dashy seems rather mature at this point, and this wasn't tackled early on?
