### ISSUE TITLE
Empty blank page

### ISSUE THREAD

**Issue by famaia** [Lissy93/dashy#909]
I keep getting a blank page.

![image](https://user-images.githubusercontent.com/736407/190814184-8e76db07-1bf0-4738-a2a6-e2be0afdb555.png)

Randomly, if i remove the docker and do a sudo docker-compose up -d it loads but gets broken again shortly after without any change.

Any ideias?

**Comment by Lissy93** [comment]
Hiya,
Can you share the output of the browser console ([here's how](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#how-to-open-browser-console) if you're unsure), also include the relevant parts of your config, and steps to reproduce the issue, including confirming it's still present in Incognito.

**Comment by famaia** [comment]
Hi, thanks.

![image](https://user-images.githubusercontent.com/736407/190929342-83ca9eb4-bb9d-4788-880f-e2cbf67313a2.png)

The problem also exists in Incognito mode.

What part of the config you wish me to place here?

**Comment by Lissy93** [comment]
That's weird, I've not seen that issue before, I'll look into it...
In the meantime, setting `routingMode: hash` under `appConfig` should fix it.
Are you missing the top-level `appConfig` section in your config by any chance?

Usually just the relevant parts, or the whole thing - but with personal info redacted, is really helpful. But I think in this case it's because there is no appConfig block in your config file.

**Comment by famaia** [comment]
@Lissy93 thank you. It started working with the appConfig section.

I don't understand how did that section got deleted but I think it was by the app (some web change I made) and not manually by me.

I got to a previous version of the appConfig section from one of the generated backup files and it now works.

I you need some kind of debug from my part to try to figure how this happened just shoot me a message.


Anyway, thank you for your time,
Francisco

**Comment by Lissy93** [comment]
If it's happened through the UI, that wouldn't be good at all - loosing part of the users config would be a pretty big bug. 

Can't think how this could have happened, but I've made note to add some test cases within #799 to ensure there's no such issue with the new version. If this did happen via the UI config editor, then my sincere apologies. 

Keeping a backup of the config file (like you did) will protect against any loss of data, and also means you can easily convert it into any other dashboards format, if needed.

**Comment by famaia** [comment]
Hey,

I can't say for sure that it was caused by some UI bug, I just don't remember removing a section of the config I put there myself  (I had a authentication block on there, for example) for no reason. It's software... time will tell. :-)

Anyway, thank you for your time on this issue,
Francisco
