### ISSUE TITLE
AxiosError: Network Error

### ISSUE THREAD

**Issue by Bunsenbrenner14** [Lissy93/dashy#910]
Hey ive setup my dashy dashboard today. But when i tried to save config this error appears:
`AxiosError: Network Error`
How can i fix this issue

**Comment by Lissy93** [comment]
Hi, please can you follow the issue template. There's not enough info here to diagnose the error, but take a look at the [Troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md) page for common issues and solutions.
