### ISSUE TITLE
[FEATURE_REQUEST] Wake Up Server Icon when a Server is Down

### ISSUE THREAD

**Issue by HenkVanHoek** [Lissy93/dashy#920]
### Describe the solution you'd like

When a server is down, it would be nice to send a magic packet to wake up the server.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Hi @HenkVanHoek 

Thanks for your idea. But I think that strays a little bit outside what a dashboard app should be used for, so I'm going to mark as out of scope.

Instead, there are dedicated services which can do just this. But you could just write your own simple script to ping your server at pre-defined intervals, and trigger a wake on lan request if it's not responding.

If you'd like to still use Dashy for this, then you can write a widget to implement this functionality.
