### ISSUE TITLE
[FEATURE_REQUEST] ENV var with URL instead of mounting a conf.yaml file

### ISSUE THREAD

**Issue by TechDufus** [Lissy93/dashy#921]
### Is your feature request related to a problem? If so, please describe.

If you are wanting to deploy this app on hardware that you don't own, it would be awesome to be able to specify a URL that dashy could cURL the conf from an online public source instead of needing to mount the conf file to a local path.

### Describe the solution you'd like

Instead of mounting a conf file with docker, setting an ENV variable with the URL would have dashy pull that yaml file and place it in its correct location.

I realize that we could just build a custom dashy image with the custom conf therein, but this is a special use case.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
This is actually already included in #799

**Comment by matthewjdegarmo** [comment]
> This is actually already included in #799

Please forgive me for being dense... but I can't tell how #799 shows me how to use this feature.
