### ISSUE TITLE
[FEATURE_REQUEST] Ability to define a default icon

### ISSUE THREAD

**Issue by chevdor** [Lissy93/dashy#925]
### Is your feature request related to a problem? If so, please describe.

Currently it is **mandatory** to provide a valid icon. Omitting the icon will render in a poor way:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/738724/192996622-cc1c859f-199f-4a7a-a2ea-114e680f2807.png">

The issue is that finding the right icons are not trivial as there is no way to search for icons (without leaving the page) and icons are not previewed.

When I add bookmarks to Dashy, I usually want to get it done quickly and I don't care much about the icon. I usually do a second pass when I have time to embellish with bewtiful icons :) I would love if the dashboard could look decent already after pass 1.

### Describe the solution you'd like

I think it would be a fair solution to have Dashy pick a default such as `fas fa-bookmark` (or anything else) and let the user override this default.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Hiya @chevdor - Apologies for the delay in getting back to you on this, been a busy few weeks this slipped me by.

And for the default icon, that would definitely be possible to implement, pretty easily - it's a good idea too, so thanks for suggesting :)

Probably just a case of creating a property, like `appConfig.defaultIcon`, which will apply to any item that doesn't have an icon already set. I've got 10 mins  spare, so I'll submit a PR now :)

**Comment by Lissy93** [comment]
> The issue is that finding the right icons are not trivial as there is no way to search for icons (without leaving the page) and icons are not previewed.

Yeah, that's true. There's an open ticket for it in  #749

**Comment by Lissy93** [comment]
I've submitted your feature request in PR #966 - I'll merge it shortly.
Hope that helps :)
