### ISSUE TITLE
[FEATURE_REQUEST] Hiding widget UI options

### ISSUE THREAD

**Issue by RynoM** [Lissy93/dashy#927]
### Is your feature request related to a problem? If so, please describe.

Dashy dashboards look can look awesome! But when going for a clean and minimalistic dashboard setup, the Widget UI options (full-page and refresh buttons) feel a bit like extra clutter to me (specially when you have a very opaque theme and a nice background image). I couldn't find any way to do something about this currently. Maybe it's just me, but i'd like the extra 'cleanliness' :).

### Describe the solution you'd like

I'd love to be able to either hide those buttons (since I realistically never use them) or have them hidden until hovered over the specific widget or something similar.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement

No

**Comment by Lissy93** [comment]
Heya @RynoM 

That's a good idea :) It should be fairly easy to add this as a feature, so I'll add it to my (quite long) todo list.

But in the meantime you can also do this with a lil bit of CSS. Here's an example:

```css
.widget-base .action-btn { display: none; }
```

(you can add this either under `appConfig.customCss` or through the UI via Config Menu --> Custom CSS)

**Comment by RynoM** [comment]
Ah right, thanks for pointing me in that direction!
