### ISSUE TITLE
[Security] Security Issue 

### ISSUE THREAD

**Issue by MrFey** [Lissy93/dashy#928]
### Environment

Self-Hosted (Docker)

### Describe the problem

First of all I'd like to say thank you for developing Dashy, this tool is very useful.

I send you multiples emails about security vulnerability (SSRF) in a certain Dashy endpoint and never get and answer, maybe I have the wrong email ?

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by skornel02** [comment]
I think backend security is not currently in scope for the development. There is an open issue #668 on this topic, which has been open for quite a while now.
