### ISSUE TITLE
[BUG] Updating Icons

### ISSUE THREAD

**Issue by obsidiangroup** [Lissy93/dashy#930]
### Environment

Self-Hosted (Docker)

### System

Docker swarm, 20.10.18, Ubuntu

### Version

2.1.1

### Describe the problem

When adding a new item and setting the icon to an incorrect entry, and saving, i.e set the Icon to: hl-resilio.  You will be shown a Menu item with an icon.  Go back to the same entry, edit, correct the icon path, save.  Icon does not update.  Even deleting the icon field and re-adding it does not work.  You have to refresh the entire page in order for the icon to update.  

Whenever a change is made, once the config is saved the change should take effect, you should not have to reload the page.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by UrekD** [comment]
This along many other things should be addressed in the upcoming #799
