### ISSUE TITLE
[Resolved][BUG] Dashboard is not changed with multi pages 

### ISSUE THREAD

**Issue by isaaccs** [Lissy93/dashy#931]
### Environment

Self-Hosted (Docker)

### System

Unraid 6.11.0

### Version

 2.1.1

### Describe the problem

I want to use the Multi-Page.

In my `conf.yml`

I have the following code 
```
pages:
  - name: My home page
    path: 'conf.yml'
  - name: Crypto dashboard
    path: 'crypto.yml'
```

When I click on crypto dashboard, I have exactly the same dashboard than my home page.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by coalwater** [comment]
Hey @isaaccs, I was able to fix my issue, and [it was related to the `yarn` command I used](https://github.com/Lissy93/dashy/issues/929#issuecomment-1270736774).
Could you maybe share your docker run command that you used, just to make sure it's not the same as my issue.

**Comment by coalwater** [comment]
Hey @isaaccs glad to hear that, I think you can close this issue, I've created a new one to understand why this behavior is happening.

**Comment by OrionPaxNL** [comment]
Is this solved, i still have these issues...

**Comment by technodivergent** [comment]
I have the same issue using the latest docker container. The content from conf.yml is displayed when navigating to the new page. Permissions are the same as conf.yml
