### ISSUE TITLE
[BUG] Unable to use certain HomeLab Dashboard icons

### ISSUE THREAD

**Issue by ulysserevient** [Lissy93/dashy#937]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.1</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">Hi,<br>
I'm triyng to use certain Homelab Dashboard icons that doesn't want to appear, like hl-d-link : <a href="https://github.com/walkxcode/Dashboard-Icons/blob/main/png/d-link.png">https://github.com/walkxcode/Dashboard-Icons/blob/main/png/d-link.png</a><br>
Is there a problem with icon with an hyphen in name, like d-link ?<br>
Thx</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445"><img src="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445" alt="important" data-canonical-src="https://img.shields.io/badge/Important!-F6094E" style="max-width: 100%;"></a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/525443495/f7dec1f5-3f74-47ae-9723-f9ae3f52cdbb" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/walkxcode/Dashboard-Icons">Dashboard-Icons/d-link.png at main · walkxcode/Dashboard-Icons</a>                      </strong>        </div>                    <div>❤️ The best icons for your personal dashboard. Contribute to walkxcode/Dashboard-Icons development by creating an account on GitHub.</div>                      </blockquote>

**Comment by ulysserevient** [comment]
I think, i've the same problem with FontAwesome or Material Design Icons
Is there a problem with hyphen in name ?
Thx

**Comment by Lissy93** [comment]
I think this is caused by a misconfiguration. Try setting the icon to `hd-d-link`


```
sections:
- name: Home Lab Icons Example
  items:
  - title: D-Link Example
    icon: hl-d-link
```

will display:

![image](https://github.com/Lissy93/dashy/assets/1862727/879333fc-0a78-4118-bbfa-1129f7300875)

(I must admit, this isn't the best icon - raise an issue or PR with https://github.com/walkxcode/dashboard-icons to get a square icon added for this service)
