### ISSUE TITLE
[BUG] Unable to use Material Design icons

### ISSUE THREAD

**Issue by ulysserevient** [Lissy93/dashy#938]
### Environment

Self-Hosted (Docker)

### Version

2.1.1

### Describe the problem

Hi,
I'm trying to use Material design icons, like mdi-wifi but my Dashy doesn't want to show them !
Is there something to configure before sue them ?
Thx.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by changbowen** [comment]
For anyone arrives here in the future, I had to change `enableMaterialDesignIcons` to `true` under `appConfig` for mdi-xxxx to work.
