### ISSUE TITLE
[BUG] It looks like something's gone wrong

### ISSUE THREAD

**Issue by DJB1966** [Lissy93/dashy#941]
### Environment

Self-Hosted (Docker)

### System

Docker and all browsers

### Version

V-2.1.1

### Describe the problem

Browser give It "looks like something's gone wrong error" in all browsers windows 10
![image](https://user-images.githubusercontent.com/83762543/194958235-1dbbb7fe-da6f-407c-8a9f-b5d4fde45c9a.png)
![image](https://user-images.githubusercontent.com/83762543/194958300-d805ddff-191f-4d85-a7f4-200fe1a14fe0.png)
![image](https://user-images.githubusercontent.com/83762543/194958787-0bb93fdd-8670-4ada-ae9b-42a4b4d16a1b.png)

### Additional info

[Dashy-2022-10-10T22-00-54.log.gz](https://github.com/Lissy93/dashy/files/9749489/Dashy-2022-10-10T22-00-54.log.gz)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Are you running from a sub-path, e.g. `https://[my-host].local/dashy/`?
If so, try running from a URL root, e.g. `https://dashy.[my-host].local/`.

**Comment by DJB1966** [comment]
Thanks that did the trick working now made a local DNS using pihole `https://dashy.[my-host].local`
