### ISSUE TITLE
[QUESTION] Can I use actual domain not second level domain to fetch favicon?

### ISSUE THREAD

**Issue by SuperMarioBean** [Lissy93/dashy#953]
### Question

hi, I found dashy's favicon api always use sencod-level domain to fetch a favicon, just like google.com for google. Is there any method to use the actual domain to fetch a favicon，no matter it domain level，just like docs.google.com for google Doc

### Category

Using Icons

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [X] You've checked that this [question hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by SuperMarioBean** [comment]
anyone help me？

**Comment by Lissy93** [comment]
Yeah, this was fixed by dkyeremeh in #926
