### ISSUE TITLE
[BUG] Keycloak 18 not working

### ISSUE THREAD

**Issue by djessich** [Lissy93/dashy#954]
### Environment

Self-Hosted (Docker)

### System

Kubernetes with containerd (v1.22)

### Version

2.1.1

### Describe the problem

With Keycloak enabled, I get the following error:
https://sso.example.com/realms/default/protocol/openid-connect/3p-cookies/step1.html 404 Not Found

I think the problem is, that currently used keycloak-js is set to 16.1.1 in package.json. The used server version is 18.0.2 (new Quarkus distribution). I think Dashy and Keycloak is incompatible due to old dependencies of Dashy.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Smith-fms** [comment]
still there

**Comment by zell-mbc** [comment]
I have Dashy working with Keycloak v19.0
Somehow you seem to have some sample configuration left over? I mean this domain  `sso.example.com` can't be right?

> https://sso.example.com/realms/default/protocol/openid-connect/3p-cookies/step1.html 404 Not Found

**Comment by zell-mbc** [comment]
Hapy to, my setup is rather simple…

Here's dashy:
![image](https://user-images.githubusercontent.com/29018767/206793783-3cb78be4-79ff-4e65-a10a-2f0f5fa9c0ac.png)

And Keycloak
![image](https://user-images.githubusercontent.com/29018767/206794319-eb43781b-9c78-42c3-86a0-a6fdf8a80930.png)

**Comment by djessich** [comment]
Thank you, its now working perfectly with Keycloak 19.
