### ISSUE TITLE
[BUG] gh-trending is down, hence so is the GitHub trending widget

### ISSUE THREAD

**Issue by Antiz96** [Lissy93/dashy#965]
### Environment

Self-Hosted (Docker)

### System

Firefox 106, Arch-Linux, Docker version 20.10.21

### Version

2.1.1

### Describe the problem

The Github trending widget is not working since a few days.
It looks like the application it relies on is down:

https://gh-trending-repos.herokuapp.com/repo 
![image](https://user-images.githubusercontent.com/53110319/187756080-2d7a92c7-03a0-4856-82ed-0e17c04226f0.png)

### Additional info

![image](https://user-images.githubusercontent.com/53110319/187756742-6dc6c5d7-b117-4521-8ee0-12979ed9d158.png)

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Yeah, you're right :( 

My API (here: https://github.com/Lissy93/gh-trending-no-cors) that fetched and calculated trending repos is hosted on Heroku, but Heroku has recently [scrapped](https://techcrunch.com/2022/08/25/heroku-announces-plans-to-eliminate-free-plans-blaming-fraud-and-abuse/) all their free plans, and bumped up the pricing. Causing the project to go offline. 

Does anyone know of any decent and free/ affordable Heroku alternatives?
Otherwise, I've got a few DO droplets, so should be able to host it there.

**Comment by Antiz96** [comment]
> Yeah, you're right :(
> My API (here: https://github.com/Lissy93/gh-trending-no-cors) that fetched and calculated trending repos is hosted on Heroku, but Heroku has recently [scrapped](https://techcrunch.com/2022/08/25/heroku-announces-plans-to-eliminate-free-plans-blaming-fraud-and-abuse/) all their free plans, and bumped up the pricing. Causing the project to go offline.

Oh... that's unfortunate. :disappointed:

> Does anyone know of any decent and free/ affordable Heroku alternatives? [...]

Not that I can think of right now unfortunately... I'll come back with suggestions if I can find some!

**Comment by Antiz96** [comment]
I see that the API came back to life! 
Have you found the Heroku alternative you were looking for? :)

**Comment by Antiz96** [comment]
> Does anyone know of any decent and free/ affordable Heroku alternatives? Otherwise, I've got a few DO droplets, so should be able to host it there.
> 
@Lissy93 It might be a bit anticipated as it looks like they're currently building things up but it might worth taking a lot at Radix[https://radixproject.org/], which seems to be some sort iof [FOSSHost](https://fosshost.net/) successor.
https://masto.ai/@radix/109539351216183977
