### ISSUE TITLE
[BUG] Using 66% of a CPU when idle

### ISSUE THREAD

**Issue by ohmantics** [Lissy93/dashy#969]
### Environment

Self-Hosted (Docker)

### System

Ubuntu 22.0.4

### Version

2.1.1

### Describe the problem

With no browser windows taking to dashy, the "node server" process is using 66% of a CPU core at minimum. Presumably this is background processing such as the docker healthcheck. There's no rebuild running. It's not going to zero at any point. With any browser window open, it goes up to 125% and stays there or above. However, this all seems very excessive for what's logically happening.

This was a straight-forward docker install using Portainer on a Raspberry Pi 4 running Ubuntu 22.04. This is enough CPU use to trigger the cooling fan on this box, hence why I've noticed it.

### Additional info

partial output of pstree -a -p:
```
  ├─containerd-shim,654085 -namespace moby -id fcfa6e2acda69da0fbd4ca458e75243f3b7b4563f64322e231e6566505c71980 -address /run/containerd/containerd.sock
  │   ├─tini,654108 -- yarn build-and-start
  │   │   └─node,654156 /opt/yarn-v1.22.15/bin/yarn.js build-and-start
  │   │       ├─node,654179 /app/node_modules/.bin/npm-run-all --parallel build-watch start
  │   │       │   ├─node,654190 /opt/yarn-v1.22.15/bin/yarn.js run build-watch
  │   │       │   │   ├─node,654212 /app/node_modules/.bin/vue-cli-service build --watch --mode production
  │   │       │   │   │   ├─{node},654214
  │   │       │   │   │   ├─{node},654215
  │   │       │   │   │   ├─{node},654216
  │   │       │   │   │   ├─{node},654217
  │   │       │   │   │   ├─{node},654218
  │   │       │   │   │   ├─{node},654224
  │   │       │   │   │   ├─{node},654232
  │   │       │   │   │   ├─{node},654233
  │   │       │   │   │   ├─{node},654234
  │   │       │   │   │   └─{node},654235
  │   │       │   │   ├─{node},654192
  │   │       │   │   ├─{node},654193
  │   │       │   │   ├─{node},654194
  │   │       │   │   ├─{node},654195
  │   │       │   │   ├─{node},654196
  │   │       │   │   ├─{node},654202
  │   │       │   │   ├─{node},654204
  │   │       │   │   ├─{node},654205
  │   │       │   │   ├─{node},654206
  │   │       │   │   └─{node},654207
  │   │       │   ├─node,654191 /opt/yarn-v1.22.15/bin/yarn.js run start
  │   │       │   │   ├─node,654213 server
  │   │       │   │   │   ├─{node},654219
  │   │       │   │   │   ├─{node},654220
  │   │       │   │   │   ├─{node},654221
  │   │       │   │   │   ├─{node},654222
  │   │       │   │   │   ├─{node},654223
  │   │       │   │   │   ├─{node},654225
  │   │       │   │   │   ├─{node},654226
  │   │       │   │   │   ├─{node},654227
  │   │       │   │   │   ├─{node},654228
  │   │       │   │   │   └─{node},654229
  │   │       │   │   ├─{node},654197
  │   │       │   │   ├─{node},654198
  │   │       │   │   ├─{node},654199
  │   │       │   │   ├─{node},654200
  │   │       │   │   ├─{node},654201
  │   │       │   │   ├─{node},654203
  │   │       │   │   ├─{node},654208
  │   │       │   │   ├─{node},654209
  │   │       │   │   ├─{node},654210
  │   │       │   │   └─{node},654211
  │   │       │   ├─{node},654180
  │   │       │   ├─{node},654181
  │   │       │   ├─{node},654182
  │   │       │   ├─{node},654183
  │   │       │   ├─{node},654184
  │   │       │   ├─{node},654185
  │   │       │   ├─{node},654186
  │   │       │   ├─{node},654187
  │   │       │   ├─{node},654188
  │   │       │   └─{node},654189
  │   │       ├─{node},654167
  │   │       ├─{node},654168
  │   │       ├─{node},654169
  │   │       ├─{node},654170
  │   │       ├─{node},654171
  │   │       ├─{node},654172
  │   │       ├─{node},654175
  │   │       ├─{node},654176
  │   │       ├─{node},654177
  │   │       └─{node},654178
  │   ├─{containerd-shim},654086
  │   ├─{containerd-shim},654087
  │   ├─{containerd-shim},654088
  │   ├─{containerd-shim},654089
  │   ├─{containerd-shim},654090
  │   ├─{containerd-shim},654091
  │   ├─{containerd-shim},654092
  │   ├─{containerd-shim},654093
  │   ├─{containerd-shim},654094
  │   ├─{containerd-shim},654375
  │   └─{containerd-shim},657704

```

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by JohnnieDK** [comment]
I had the same problem, so I built a new docker image from master, and that sort of seems to have fixed it.
However, I also noticed that when I had the status check enabled, it would interfere with my pi-alert container (Note that pi-alert is VERY buggy). And both would consume a lot of cpu.

**Comment by ohmantics** [comment]
AFAIK, nothing has changed. Sounds like Lissy93 is swamped.

**Comment by bdovaz** [comment]
No stale

**Comment by ohmantics** [comment]
Still relevant. @Lissy93, any chance you'll be able to look at this? If not, perhaps you have some hints as to how you'd diagnose it?

**Comment by Lissy93** [comment]
Hey,
Really sorry for the delay in replying, (I have so many unread GH notifications at the moment, that it's hard to spot the important ones! 😬)

This definitely doesn't sound good at all, weirdly I'm running a very similar setup (Pi 4, default Docker, etc) and no issues.
Looking at those logs, I'm wondering if it's something gone wrong with the healthcheck. If you disable that, do you still see issues?

**Comment by adamantike** [comment]
@ohmantics, do you have an example config file to reproduce this issue? Also, does it still happen if you change the container command to run `yarn start` instead?

@Lissy93, is there any reason for the ARM-based Docker images to have `yarn build-and-serve` as default CMD, while the Docker image for x86 is just `yarn start`?

**Comment by bdovaz** [comment]
No stale

**Comment by bdovaz** [comment]
It is still relevant, no stale

**Comment by anderconsu** [comment]
Same issue with docker compose, Dashy v2.1.1 on Debian 11 in a raspberry pi4. I was searching what was using 100% of CPU constantly until I stopped the stack. It does't go down when Dashy isn't accessed.

**Comment by anderconsu** [comment]
> Same issue with docker compose, Dashy v2.1.1 on Debian 11 in a raspberry pi4. I was searching what was using 100% of CPU constantly until I stopped the stack. It does't go down when Dashy isn't accessed.

Turning off Enable status check in page settings and restarting the container fixed it. I think I'm going to use uptime kuma for now

**Comment by ohmantics** [comment]
Still relevant.

**Comment by bdovaz** [comment]
Still relevant

**Comment by CrazyWolf13** [comment]
I also run Dashy with **many** other things on my Rpi 3B+ with 1GB RAM and Dashy is consuming very few MB and barely any CPU even when starting up.

Can you confirm if you are running x64 or x32 ?

**Comment by ohmantics** [comment]
Auto-closing bots are a project management smell.

**Comment by CrazyWolf13** [comment]
> Auto-closing bots are a project management smell.

I haven't gotten any confirmation that it is still relevant, so the bot did everything correct.

**Comment by bdovaz** [comment]
Still relevant

**Comment by CrazyWolf13** [comment]
Then please answer the question I asked above.

Instead of ranting on the bot!

**Comment by bdovaz** [comment]
In my case x64

**Comment by CrazyWolf13** [comment]
> In my case x64

Hi 
Could you test this with the :latest tag by repulling and rebuilding the app?

Keep in mind V3 has breaking changes:
https://github.com/Lissy93/dashy/releases/tag/3.0.0

**Comment by ohmantics** [comment]
Not seeing the original issue now. It did take several re-pulls for the build to complete without errors; not sure why since it says "possible error, check logs" and there are no logs to see.

**Comment by CrazyWolf13** [comment]
> Not seeing the original issue now. It did take several re-pulls for the build to complete without errors; not sure why since it says "possible error, check logs" and there are no logs to see.

Awesome!

Then I think we can close this.

If you have changed the bind mounts and the port those errors shouldn't appear, yeah.

Did you wait about 3 minutes longer and refreshed the page, after the error appears?
The first build takes a bit longer and on a raspberry pi it takes even longer, so it may exceed the expected time and then the "possible error" popps up.
