### ISSUE TITLE
[BUG] HomeLab icons using wrong repository

### ISSUE THREAD

**Issue by alvarodev-lc** [Lissy93/dashy#972]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto">Ubuntu 20.04 LTS</p>
<h3 dir="auto">Version</h3>
<p dir="auto">Latest</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">The icon documentation says the icons are taken from <a href="https://github.com/walkxcode/Dashboard-Icons">https://github.com/walkxcode/Dashboard-Icons</a> but the icons are actually getting fetched from <a href="https://github.com/walkxhub/dashboard-icons">https://github.com/walkxhub/dashboard-icons</a>, which is the previous legacy repository, not maintained anymore.</p>
<p dir="auto">I'd like it to use the correct repo, with updated images and support.</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445"><img src="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445" alt="important" data-canonical-src="https://img.shields.io/badge/Important!-F6094E" style="max-width: 100%;"></a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://repository-images.githubusercontent.com/525443495/f7dec1f5-3f74-47ae-9723-f9ae3f52cdbb" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/walkxcode/Dashboard-Icons">GitHub - walkxcode/Dashboard-Icons: ❤️ The best icons for your personal dashboard.</a>                      </strong>        </div>                    <div>❤️ The best icons for your personal dashboard. Contribute to walkxcode/Dashboard-Icons development by creating an account on GitHub.</div>                      </blockquote><blockquote>                    <img src="https://repository-images.githubusercontent.com/405627037/a9020ecc-ad4e-4eb5-a68a-820d809e0d6e" width="48" align="right" />                          <div>          <strong>                          <a href="https://github.com/walkxhub/dashboard-icons">GitHub - walkxhub/dashboard-icons: 🚚 Dashboard Icons has moved to another home!</a>                      </strong>        </div>                    <div>🚚 Dashboard Icons has moved to another home! Contribute to walkxhub/dashboard-icons development by creating an account on GitHub.</div>                      </blockquote>

**Comment by alvarodev-lc** [comment]
Giving it a second looks, seems like the docker image was last updated 3 months ago. This issue has been fixed, but the docker build/push github action is failing. Seems like an Azure Container Registry credential issue, you are getting a 403 forbidden error (I guess you are aware). 
Here is the link for the first time the build action failed. (https://github.com/Lissy93/dashy/actions/runs/2871372507)

Thank to @p41bl4F for helping to notice this

**Comment by Jekotia** [comment]
I was using an older image, and came here due to experiencing this same issue. I can confirm that after pulling the latest image, this issue is fixed.

**Comment by alvarodev-lc** [comment]
Thanks @Jekotia for confirming, closing the issue.

**Comment by alvarodev-lc** [comment]
Thanks @Jekotia for confirming, closing the issue.
