### ISSUE TITLE
[BUG] Rename conf.yml to config.yml 

### ISSUE THREAD

**Issue by Ramzh** [Lissy93/dashy#978]
<h3 dir="auto">Environment</h3>
<p dir="auto">Self-Hosted (Docker)</p>
<h3 dir="auto">System</h3>
<p dir="auto">Firefox 107</p>
<h3 dir="auto">Version</h3>
<p dir="auto">2.1.1</p>
<h3 dir="auto">Describe the problem</h3>
<p dir="auto">If followed the guide using the YAML file, and using the template conf.yml found in the public folder of the repo, code-server will report the following error:</p>
<p dir="auto"><code class="notranslate">Property sections is not allowed</code><br>
<code class="notranslate">Property pageInfo is not allowed</code><br>
<code class="notranslate">Property appConfig is not allowed</code></p>
<p dir="auto">This is due to conf.yml being some sort of keyword in code-server/YAML and expecting certain structure: <a href="https://stackoverflow.com/questions/69493762/visual-studio-code-showing-error-property-stages-is-not-allowed-property-param" rel="nofollow">https://stackoverflow.com/questions/69493762/visual-studio-code-showing-error-property-stages-is-not-allowed-property-param</a></p>
<p dir="auto">Changing the filename to config.yml or something else will make it code-server detect it correctly</p>
<h3 dir="auto">Additional info</h3>
<p dir="auto"><em>No response</em></p>
<h3 dir="auto">Please tick the boxes</h3>
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You have explained the issue clearly, and included all relevant info</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You are using a <a href="https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions">supported</a> version of Dashy</li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked that this <a href="https://github.com/Lissy93/dashy/issues?q=is%3Aissue">issue hasn't already been raised</a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You've checked the <a href="https://github.com/Lissy93/dashy/tree/master/docs#readme">docs</a> and <a href="https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting">troubleshooting</a> guide <a target="_blank" rel="noopener noreferrer nofollow" href="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445"><img src="https://camo.githubusercontent.com/4dc60d0234fddf1d6e2f5f9306cde840c6325ef0762e8e73f6e9a0ead0b5989e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f496d706f7274616e74212d463630393445" alt="important" data-canonical-src="https://img.shields.io/badge/Important!-F6094E" style="max-width: 100%;"></a></li>
<li class="task-list-item"><input type="checkbox" id="" disabled="" class="task-list-item-checkbox" checked=""> You agree to the <a href="https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct">code of conduct</a></li>
</ul>

<blockquote>                    <img src="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v&#x3D;73d79a89bded" width="48" align="right" />                          <div>          <strong>                          <a href="https://stackoverflow.com/questions/69493762/visual-studio-code-showing-error-property-stages-is-not-allowed-property-param">Visual Studio Code showing error: Property Stages is not allowed, Property parameters is not allowed</a>                      </strong>        </div>                    <div>I created reusable templates from Azure DevOps yaml pipeline. The build.yaml you see below is one such template.
When I push code, the pipeline successfully runs on Azure DevOps without complaining. </div>                      </blockquote>

**Comment by Stinky-c** [comment]
I ran into this issue while using the yaml plugin from redhat
try adding `"yaml.schemaStore.enable": false` to a vscode workspace config if you happen to be using it

**Comment by Ramzh** [comment]
> I ran into this issue while using the yaml plugin from redhat try adding `"yaml.schemaStore.enable": false` to a vscode workspace config if you happen to be using it

I fixed the issue just by renaming the conf file. to config Think would be better to have it config by default to avoid such thing in the future (not a bug per se of Dashy but more like enhancement of the guide)

**Comment by Ramzh** [comment]
It seems like using config.yml does not work, kinda as if Dashy was hardcoded to read from a specific path and filename... :(

**Comment by Lissy93** [comment]
Closing as dup
For dev updates relating to renaming config, please see #799
