### ISSUE TITLE
[TEST] - Translator Bot

### ISSUE THREAD

**Issue by Lissy93** [Lissy93/dashy#98]
世界您好

如果这是英文的，那么机器人正在工作。。。

**Comment by Lissy93** [comment]
Yayy 😎
Thanks @liss-bot - I'm glad you're alive, welcome to the word 🌈🌏

**Comment by Lissy93** [comment]
Tout est stupide

**Comment by Lissy93** [comment]
Tout est Stupide

**Comment by Lissy93** [comment]
আমি তো এখনও কাজ করছি

আপনার প্রতি 5 মিনিটে আমাকে পরীক্ষা করার দরকার নেই, আমার আরও ভাল কাজ করার আছে...

**Comment by worldworm** [comment]
What if I mix it up a little?
Funktioniert das dann auch noch?
За съжаление не знам испански
Ups, to nebyla španělština
XD Awesome

**Comment by Lissy93** [comment]
thisisatriggerword

**Comment by Lissy93** [comment]
Testing the removal of Awaiting User Reponse label

**Comment by Lissy93** [comment]
Testing the removal of Awaiting User Reponse label

**Comment by Lissy93** [comment]
Testing removal of Awaiting maintainr response

**Comment by Lissy93** [comment]
Testing removal of Awaiting maintainr response

**Comment by Lissy93** [comment]
Testing removal of Awaiting maintainer response

**Comment by Lissy93** [comment]
Testing removal of Awaiting maintainer response, third time lucky?

**Comment by Lissy93** [comment]
Testing removal of Awaiting maintainer response, third time lucky?

**Comment by Lissy93** [comment]
Test that [this](https://google.com) embeded URL is not unfurled, but this one is: https://github.com/Lissy93/dashy and this one https://duckduckgo.com are, because they was pasted raw.

**Comment by Lissy93** [comment]
Test link unfurl: https://github.com/Lissy93/dashy
