### ISSUE TITLE
hideSettings config option not working?

### ISSUE THREAD

**Issue by zell-mbc** [Lissy93/dashy#983]
Either I missunderstood how hideSettings works  or there is something strange going on.
I set it to true (1) but the settings menu still shows (2)?
Is there maybe another setting which overrules?

![image](https://user-images.githubusercontent.com/29018767/203582925-b7e60834-2c09-4a4b-8d9e-b1b6084827ad.png)

**Comment by Maxiksan** [comment]
?? No response, why ?
