### ISSUE TITLE
latest version brought back 404 on mobile Home Screen and authentication is not functioning

### ISSUE THREAD

**Issue by fate8383** [Lissy93/dashy#988]
### Environment

Self-Hosted (Docker)

### System

safari latest stable, linux rpi latest stable, docker latest stable

### Version

Dashy version 2.1.1

### Describe the problem

#628 like previous I raised this issue, and it was resolved with changing routing mode to HASH, but latest version again broke it, either history nor hash mode fixes it. Also noticed authentication is broken, no matter what browser I tried with cleared cache it goes right to the dashboard without any login.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by psychowood** [comment]
I believe this is related to manifest.json having ["start_url": "./index.html"](https://github.com/Lissy93/dashy/blob/92d12915de04555d7fbb0d9031f741b6212ff6a9/public/manifest.json#L6).

In my configuration (docker, macvlan network, caddy as reverse proxy), browsing directly to /index.html gives the very same error with a redirect to /404.

Again, I'm not sure if this is a workaround  just for my conf, but changing start_url to "./" fixes the problem.

**Comment by wolflarson** [comment]
Your comment about authentication being broken also applies to my issue https://github.com/Lissy93/dashy/issues/1019

Perhaps one is a duplicate. Downgrading to 2.1.0 fixed my auth issue for now.

**Comment by Dacred** [comment]
Changing **"start_url"** to **"./"** in /public/manifest.json and running `yarn build` fixes this issue(and https://github.com/Lissy93/dashy/issues/1019) for me as well.
Just restarting didn't work for me.

**Comment by kieraneglin** [comment]
#1026 Resolves this
