### ISSUE TITLE
[BUG] updateInterval (and refresh-icon) not working on widgets of type "image"

### ISSUE THREAD

**Issue by svenniuwe** [Lissy93/dashy#992]
### Environment

Self-Hosted (Bare Metal)

### System

latest Chrome, Ubuntu 22.04.1 LTS

### Version

2.1.1

### Describe the problem

I want some webcam-images be updated automatically:

`
    widgets:
      - type: image
        updateInterval: 300
        options:
          imagePath: https://www.gasthaus-haldenhof.de/MOBOTIX/webcam-1.jpg
      - type: image
        updateInterval: 60
        options:
          imagePath: http://pfaenderbahn.it-wms.com/big_panorama1.jpg
      - type: image
        updateInterval: 60
        options:
          imagePath: https://bachtel.it-wms.com/panorama1_raw.jpg   
`

But it does not work. The get refreshed on load and that's it. 
When I click on the refresh icon - nothing happens either.

What could be wrong?

Thank you for any hint!

Bye
Sven

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by svenniuwe** [comment]
`      - type: embed
        updateInterval: 300      
        options:
          html: '<img width="100%" height="auto" src="https://www.gasthaus-haldenhof.de/MOBOTIX/webcam-1.jpg" />'  `

As I discovered that I could render it with the "embed" widget, too, I've tried this way shown above.

Does not update either.

Thank you!

**Comment by Lissy93** [comment]
Hey Sven,
Sorry for the late reply. It looks like the way the re-fetch works, is by re-triggering the fetch request, [here](https://github.com/Lissy93/dashy/blob/master/src/mixins/WidgetMixin.js#L68). Since the image, and iframe work as standard embeded content, instead of using any XHR requests, they're not being refreshed.

**Comment by Lissy93** [comment]
I'll work on this tomorrow evening :)

**Comment by svenniuwe** [comment]
> I'll work on this tomorrow evening :)

WOW! Really appreciate that. I thought this must be a problem in my installation "only"!!

**Comment by Lissy93** [comment]
Heya @svenniuwe, sorry for the delay
..This is now implemented in #1008, which I will merge shortly :)

Won't require any changes to your config, just update the latest version, and both the `updateInterval` option, as well as the "Refresh" button should now work on Image widgets.

**Comment by svenniuwe** [comment]
@Lissy93 Short question - two months later: Was this already released? How can I update to get this? Thank you!!
