### ISSUE TITLE
[BUG] Layout & Item Size butttons do not have any effect

### ISSUE THREAD

**Issue by tlatsas** [Lissy93/dashy#996]
### Environment

Self-Hosted (Docker)

### System

dashy:latest, Firefox 107.x, Safari 16.1

### Version

2.1.1

### Describe the problem

Layout & Item Size butttons are not working. However, if I click them and then select a new theme from the drop-down, then the selected Layout/Item size takes effect.

Tested on multiple browsers, also tested on latest dashy from git (head).

### Additional info

https://user-images.githubusercontent.com/372440/205496773-4cc1d04a-3d25-4f5a-96e5-704f6298f516.mov

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy
- [X] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide ![important](https://img.shields.io/badge/Important!-F6094E)
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by isaac-varg** [comment]
I also am experiencing this bug after a fresh install.  I am adding my system information here in hopes it helps isolate the issue.

**Environment**: Self-Hosted (Docker in local Unraid Server) 
**System**: Vivaldi 5.6 browser, dashy:latest
**Version**: Dashy 2.1.1
**Issue**: Layout and Size buttons not changing UI when clicked. This is after several fresh installs via Unraid apps (docker installer).
